-- Auto-generated by tools/generate_dc_collection_cdbc.py. Do not edit.
local DC = DCCollection
DC.COLLECTION_STATIC_MANIFEST = {
    version = 1,
    types = {
        mounts = {
            collectionType = 1,
            serverType = "mount",
            serverSource = "table+index",
            definitionCount = 1526,
            expectedCount = 1522,
            indexAvailable = true,
            authoritative = true,
            requestSkip = true,
            missingCount = 0,
            missingIds = {
            },
        },
        pets = {
            collectionType = 2,
            serverType = "pet",
            serverSource = "table",
            definitionCount = 1197,
            expectedCount = 1196,
            indexAvailable = true,
            authoritative = true,
            requestSkip = true,
            missingCount = 0,
            missingIds = {
            },
        },
        heirlooms = {
            collectionType = 4,
            serverType = "heirloom",
            serverSource = "table",
            definitionCount = 392,
            expectedCount = 392,
            indexAvailable = false,
            authoritative = true,
            requestSkip = true,
            missingCount = 0,
            missingIds = {
            },
        },
        titles = {
            collectionType = 5,
            serverType = "title",
            serverSource = "dbc",
            definitionCount = 205,
            expectedCount = 205,
            indexAvailable = false,
            authoritative = true,
            requestSkip = true,
            missingCount = 0,
            missingIds = {
            },
        },
        transmog = {
            collectionType = 6,
            serverType = "transmog",
            serverSource = "item_template",
            definitionCount = 59082,
            expectedCount = 59082,
            indexAvailable = false,
            authoritative = true,
            requestSkip = true,
            missingCount = 0,
            missingIds = {
            },
        },
        itemsets = {
            collectionType = 7,
            serverType = "itemset",
            serverSource = "runtime",
            definitionCount = 0,
            expectedCount = 0,
            indexAvailable = false,
            authoritative = false,
            requestSkip = false,
            missingCount = 0,
            missingIds = {
            },
        },
    },
    shop = {
        rowCount = 23,
        enabledRowCount = 23,
        resolvedRowCount = 23,
        authoritative = true,
        missingPreview = {
        },
    },
    dataRevisions = {
        collectionCategories = 1684590543,
        collectionSources = 39978998,
        collectionShop = 96056661,
        collectionSets = 786799120,
    },
}
DC.COLLECTION_STATIC_MANIFEST_VERSION = 1
