-- Auto-generated by tools/generate_dc_collection_cdbc.py. Do not edit.
local DC = DCCollection
DC.COLLECTION_STATIC_MANIFEST = {
    version = 1,
    types = {
        mounts = {
            collectionType = 1,
            serverType = "mount",
            serverSource = "table+index",
            definitionCount = 615,
            expectedCount = 613,
            indexAvailable = true,
            authoritative = true,
            requestSkip = true,
            missingCount = 0,
            missingIds = {
            },
        },
        pets = {
            collectionType = 2,
            serverType = "pet",
            serverSource = "table",
            definitionCount = 224,
            expectedCount = 212,
            indexAvailable = true,
            authoritative = true,
            requestSkip = true,
            missingCount = 0,
            missingIds = {
            },
        },
        heirlooms = {
            collectionType = 4,
            serverType = "heirloom",
            serverSource = "table",
            definitionCount = 352,
            expectedCount = 352,
            indexAvailable = false,
            authoritative = true,
            requestSkip = true,
            missingCount = 0,
            missingIds = {
            },
        },
        titles = {
            collectionType = 5,
            serverType = "title",
            serverSource = "dbc",
            definitionCount = 204,
            expectedCount = 204,
            indexAvailable = false,
            authoritative = true,
            requestSkip = true,
            missingCount = 0,
            missingIds = {
            },
        },
        transmog = {
            collectionType = 6,
            serverType = "transmog",
            serverSource = "item_template",
            definitionCount = 55483,
            expectedCount = 55483,
            indexAvailable = false,
            authoritative = true,
            requestSkip = true,
            missingCount = 0,
            missingIds = {
            },
        },
        itemsets = {
            collectionType = 7,
            serverType = "itemset",
            serverSource = "runtime",
            definitionCount = 0,
            expectedCount = 0,
            indexAvailable = false,
            authoritative = false,
            requestSkip = false,
            missingCount = 0,
            missingIds = {
            },
        },
    },
    shop = {
        rowCount = 23,
        enabledRowCount = 23,
        resolvedRowCount = 23,
        authoritative = true,
        missingPreview = {
        },
    },
}
DC.COLLECTION_STATIC_MANIFEST_VERSION = 1
