-- Generated by _tools/dc-talents/sync_retail.py from retail 11.2.7 (64632): API documentation Enum/Constants,
-- Helix/GlobalStrings.lua, Helix/GlobalColors.lua and SoundKitConstants, limited to what the addon references.
-- Do not edit by hand; rerun the script. Everything lands in the private environment, never in _G.
local _, ns = ...
setfenv(1, ns.env)

Enum = Enum or {}
Enum.FrameTutorialAccount = Enum.FrameTutorialAccount or { HudRevampBagChanges = 1, PerksProgramActivitiesIntro = 2, EditModeManager = 3, TransmogSetsTab = 4, MountCollectionDragonriding = 5, LFGList = 6, HeirloomJournalLevel = 7, TimerunnersAdvantage = 8, AccountWideReputation = 9, TransferableCurrencies = 10, BindToAccountUntilEquip = 11, CompletedQuestsFilter = 12, CompletedQuestsFilterSeen = 13, ConcentrationCurrency = 14, MapLegendOpened = 15, NpcCraftingOrders = 16, NpcCraftingOrderCreateButton = 17, NpcCraftingOrderTabNew = 18, LocalStoriesFilterSeen = 19, EventSchedulerTabSeen = 20, AssistedCombatRotationDragSpell = 21, AssistedCombatRotationActionButton = 22, HousingDecorCleanup = 23, HousingDecorPlace = 24, HousingDecorClippingGrid = 25, HousingDecorCustomization = 26, HousingDecorLayout = 27, HousingHouseFinderMap = 28, HousingHouseFinderVisitHouse = 29, HousingItemAcquisition = 30, HousingNewPip = 31, PerksProgramActivitiesOpen = 32, EnconterJournalTutorialsTabSeen = 33, HousingMarketTab = 34, HousingTeleportButton = 35, RPETalentStarterBuild = 36, HousingInvalidCollision = 37 }
Enum.LFGRole = Enum.LFGRole or { Tank = 0, Healer = 1, Damage = 2 }
Enum.LoadConfigResult = Enum.LoadConfigResult or { Error = 0, NoChangesNecessary = 1, LoadInProgress = 2, Ready = 3 }
Enum.SpellBookItemType = Enum.SpellBookItemType or { None = 0, Spell = 1, FutureSpell = 2, PetAction = 3, Flyout = 4 }
Enum.TraitConditionType = Enum.TraitConditionType or { Available = 0, Visible = 1, Granted = 2, Increased = 3, DisplayError = 4, RanksAllowed = 5 }
Enum.TraitConfigType = Enum.TraitConfigType or { Invalid = 0, Combat = 1, Profession = 2, Generic = 3 }
Enum.TraitCurrencyType = Enum.TraitCurrencyType or { Gold = 0, CurrencyTypesBased = 1, TraitSourced = 2, TraitSourcedPlayerDataElement = 3 }
Enum.TraitDefinitionSubType = Enum.TraitDefinitionSubType or { DragonflightRed = 0, DragonflightBlue = 1, DragonflightGreen = 2, DragonflightBronze = 3, DragonflightBlack = 4 }
Enum.TraitEdgeType = Enum.TraitEdgeType or { VisualOnly = 0, DeprecatedRankConnection = 1, SufficientForAvailability = 2, RequiredForAvailability = 3, MutuallyExclusive = 4, DeprecatedSelectionOption = 5 }
Enum.TraitEdgeVisualStyle = Enum.TraitEdgeVisualStyle or { None = 0, Straight = 1 }
Enum.TraitNodeEntryType = Enum.TraitNodeEntryType or { SpendHex = 0, SpendSquare = 1, SpendCircle = 2, SpendSmallCircle = 3, DeprecatedSelect = 4, DragAndDrop = 5, SpendDiamond = 6, ProfPath = 7, ProfPerk = 8, ProfPathUnlock = 9, RedButton = 10, ArmorSet = 11, SpendInfinite = 12 }
Enum.TraitNodeFlag = Enum.TraitNodeFlag or { ShowMultipleIcons = 1, NeverPurchasable = 2, TestPositionLocked = 4, TestGridPositioned = 8, ActiveAtFirstRank = 16, ShowExpandedSelection = 32, HideMaxRank = 64, HighestChosenRank = 128 }
Enum.TraitNodeType = Enum.TraitNodeType or { Single = 0, Tiered = 1, Selection = 2, SubTreeSelection = 3 }
Enum.LFGRoleMeta = Enum.LFGRoleMeta or { MinValue = 0, MaxValue = 2, NumValues = 3 }

Constants = Constants or {}
Constants.LFG_ROLEConstants = Constants.LFG_ROLEConstants or { LFG_ROLE_NO_ROLE = -1, LFG_ROLE_ANY = Enum.LFGRoleMeta.NumValues }
Constants.TraitConsts = Constants.TraitConsts or { MAX_COMBAT_TRAIT_CONFIGS = 40, COMMIT_COMBAT_TRAIT_CONFIG_CHANGES_SPELL_ID = 384255, INSPECT_TRAIT_CONFIG_ID = -1, STARTER_BUILD_TRAIT_CONFIG_ID = -2, VIEW_TRAIT_CONFIG_ID = -3 }

SOUNDKIT = SOUNDKIT or {}
SOUNDKIT.IG_CHARACTER_INFO_TAB = 841
SOUNDKIT.IG_MAINMENU_OPTION_CHECKBOX_ON = 856
SOUNDKIT.UI_CLASS_TALENT_APPLY_CHANGES = 207767
SOUNDKIT.UI_CLASS_TALENT_APPLY_COMPLETE = 212391
SOUNDKIT.UI_CLASS_TALENT_CLOSE_WINDOW = 207758
SOUNDKIT.UI_CLASS_TALENT_NODE_REFUND = 207762
SOUNDKIT.UI_CLASS_TALENT_NODE_SPEND = 207765
SOUNDKIT.UI_CLASS_TALENT_NODE_SPEND_MAJOR = 207763
SOUNDKIT.UI_CLASS_TALENT_OPEN_WINDOW = 207757
SOUNDKIT.UI_CLASS_TALENT_SPEC_ACTIVATE = 207761
SOUNDKIT.UI_CLASS_TALENT_TAB = 207760

-- Retail global strings used by the port that the 3.3.5 client lacks (or words differently),
-- visible inside our environment only. Strings stock 3.3.5 has with the same enUS text are left
-- out, so lookups fall through to the client's own, localized, copy.
ERR_LEARN_PASSIVE_S = "You have learned a new passive effect: %s."
ERR_TALENT_FAILED_COMMIT_IN_PROGRESS = "You can't change talents while a talent change is already processing"
ERR_TALENT_FAILED_INSPECTING = "You can't change an inspected player's talents"
ERR_TALENT_FAILED_INVALID_CONFIG = "Failed to find the specified loadout for your current specialization"
ERR_TALENT_FAILED_INVALID_CONFIG_INDEX = "Loadout index is outside the bounds of available loadouts for your current specialization"
ERR_TALENT_FAILED_INVALID_CONFIG_NAME = "Invalid loadout name"
ERR_TALENT_FAILED_INVALID_SPEC = "Failed to find the specified specialization for your class"
ERR_TALENT_FAILED_INVALID_SPEC_INDEX = "Specialization index is outside the bounds of available specializations for your class"
ERR_TALENT_FAILED_INVALID_SPEC_NAME = "Invalid specialization name"
ERR_TALENT_FAILED_NO_DATA = "Class talent data has not yet been loaded"
GENERIC_TRAIT_FRAME_EDGE_REQUIREMENTS_BUTTON_TOOLTIP = "Requires all preceding talents"
GENERIC_TRAIT_FRAME_INTERNAL_ERROR = "Internal error. Try again later."
HUD_CLASS_TALENTS_EDIT_LOADOUT_DIALOG_EDIT_BOX_LABEL = "Name"
HUD_CLASS_TALENTS_EDIT_LOADOUT_DIALOG_TITLE = "Loadout Settings"
HUD_CLASS_TALENTS_EDIT_LOADOUT_SHARED_ACTION_BARS_TEXT = "Use Shared Action Bars"
HUD_CLASS_TALENTS_EDIT_LOADOUT_USES_SHARED_ACTION_BARS_TOOLTIP = "By default, each loadout has its own saved set of action bars.\n\nAll loadouts that have this option enabled will share the same action bars."
HUD_CLASS_TALENTS_IMPORT_DIALOG_EDIT_BOX_LABEL = "Import Text"
HUD_CLASS_TALENTS_IMPORT_DIALOG_NAME_LABEL = "New Loadout Name"
HUD_CLASS_TALENTS_IMPORT_DIALOG_TITLE = "Import Loadout"
HUD_CLASS_TALENTS_IMPORT_ERROR_IMPORT_STRING_AND_NAME = "Enter valid loadout code"
HUD_CLASS_TALENTS_IMPORT_INSTRUCTIONS = "Paste loadout code here"
HUD_CLASS_TALENTS_IMPORT_LOADOUT_ACCEPT_BUTTON = "Import"
HUD_CLASS_TALENTS_NEW_LOADOUT_DIALOG_EDIT_BOX_LABEL = "Name"
HUD_CLASS_TALENTS_NEW_LOADOUT_DIALOG_TITLE = "New Loadout"
LOADOUT_ERROR_BAD_STRING = "Error: Invalid loadout code"
LOADOUT_ERROR_IMPORT_FAILED = "Failed to import loadout"
LOADOUT_ERROR_SERIALIZATION_VERSION_MISMATCH = "Error: The loadout you are trying to import was saved from an old version"
LOADOUT_ERROR_TREE_CHANGED = "Error: The loadout you are trying to import is out of date"
LOADOUT_ERROR_WRONG_SPEC = "Error: The loadout you are trying to import is for a different specialization"
NPEV2_TALENTS_STARTER_BUILD = "Can't decide what to choose? Try the |cFF00FFFFStarter Build|r preset."
RELOADUI = "Reload UI"
SAMPLE_ABILITIES = "Sample Abilities"
SPECIALIZATION = "Specialization"
SPEC_ACTIVE = "Active"
SPEC_FRAME_PRIMARY_STAT = "Primary Stat: %s"
SPEC_FRAME_PRIMARY_STAT_AGILITY = "Agility"
SPEC_FRAME_PRIMARY_STAT_INTELLECT = "Intellect"
SPEC_FRAME_PRIMARY_STAT_STRENGTH = "Strength"
TALENT = "Talent"
TALENTS_INSPECT_FORMAT = "Talents - %s"
TALENTS_LINK_FORMAT = "Linked Talents (%s %s)"
TALENT_BUILD_CHAT_LINK_TEXT = "Talents: %s %s"
TALENT_BUTTON_TOOLTIP_CLEAR_REPURCHASE_INSTRUCTIONS = "Right click to clear all history nodes"
TALENT_BUTTON_TOOLTIP_COST_ENTRY_FORMAT = "%d %s"
TALENT_BUTTON_TOOLTIP_COST_ENTRY_SEPARATOR = " "
TALENT_BUTTON_TOOLTIP_COST_FORMAT = "Cost: %s"
TALENT_BUTTON_TOOLTIP_NEXT_RANK = "Next Rank:"
TALENT_BUTTON_TOOLTIP_NOT_ON_ACTION_BAR = "You haven't added this to your action bars"
TALENT_BUTTON_TOOLTIP_ON_DISABLED_ACTIONBAR = "You've added this to an action bar that is hidden or disabled"
TALENT_BUTTON_TOOLTIP_ON_INACTIVE_BONUSBAR = "You've added this to your action bar, but on a different stance"
TALENT_BUTTON_TOOLTIP_PURCHASE_INSTRUCTIONS = "Click to learn"
TALENT_BUTTON_TOOLTIP_QUICK_ASSIGN_INSTRUCTIONS = "Ctrl-Click to Quick Assign"
TALENT_BUTTON_TOOLTIP_RANK_FORMAT = "Rank %s/%s"
TALENT_BUTTON_TOOLTIP_RANK_NO_MAX_FORMAT = "Rank %s"
TALENT_BUTTON_TOOLTIP_REFUND_INSTRUCTIONS = "Right click to unlearn"
TALENT_BUTTON_TOOLTIP_REFUND_INVALID_CONDITIONS_ERROR = "Spend more points to restore this talent or right click to unlearn it"
TALENT_BUTTON_TOOLTIP_REFUND_INVALID_LINKS_ERROR = "No active links. Reconnect or unlearn this talent."
TALENT_BUTTON_TOOLTIP_REPLACED_BY_FORMAT = "Replaced by %s"
TALENT_BUTTON_TOOLTIP_REPURCHASE_INSTRUCTIONS = "Shift click to learn all connected history nodes"
TALENT_BUTTON_TOOLTIP_SELECTION_CHOICE_ERROR = "Select another choice"
TALENT_BUTTON_TOOLTIP_SELECTION_COST_ERROR = "You can't afford this choice"
TALENT_BUTTON_TOOLTIP_SELECTION_CURRENT_INSTRUCTIONS = "This is already learned"
TALENT_BUTTON_TOOLTIP_SELECTION_ERROR = "This node isn't active"
TALENT_FRAME_APPLY_BUTTON_TEXT = "Apply Changes"
TALENT_FRAME_CONFIG_OPERATION_TOO_FAST = "Talent operation still in progress, try again later."
TALENT_FRAME_CONFIRM_CLOSE = "You will lose any pending changes if you continue."
TALENT_FRAME_CONFIRM_LEAVE_DEFAULT_LOADOUT = "You will permanently lose your current talent build unless you save it as a loadout first.|n|nAre you sure you want to continue?"
TALENT_FRAME_CONFIRM_STARTER_DEVIATION = "Choosing this talent will remove you from the Starter Build guided experience."
TALENT_FRAME_CURRENCY_DISPLAY_FORMAT_NAME_ONLY = "%s"
TALENT_FRAME_DISCARD_CHANGES_BUTTON_TOOLTIP = "Undo Pending Changes"
TALENT_FRAME_DROP_DOWN_DEFAULT = "Default Loadout"
TALENT_FRAME_DROP_DOWN_EXPORT = "Share"
TALENT_FRAME_DROP_DOWN_EXPORT_CHAT_LINK = "Post in Chat"
TALENT_FRAME_DROP_DOWN_EXPORT_CLIPBOARD = "Copy to Clipboard |cnNORMAL_FONT_COLOR:(to share online)|r"
TALENT_FRAME_DROP_DOWN_IMPORT = "Import"
TALENT_FRAME_DROP_DOWN_NEW_LOADOUT = "New Loadout"
TALENT_FRAME_DROP_DOWN_STARTER_BUILD = "Starter Build"
TALENT_FRAME_DROP_DOWN_STARTER_BUILD_TOOLTIP = "A preset talent build that's suitable for most content"
TALENT_FRAME_DROP_DOWN_TOOLTIP_EDIT = "Loadout Settings"
TALENT_FRAME_EXPORT_LOADOUT_DISABLED_TOOLTIP = "You must spend all available talent points to share this loadout"
TALENT_FRAME_EXPORT_TEXT = "Loadout code copied to clipboard."
TALENT_FRAME_GATE_TOOLTIP_FORMAT = "Spend %d more |4point:points; to unlock this row"
TALENT_FRAME_INCREASED_RANKS_TEXT = "(+%d |4Rank:Ranks; from %s)"
TALENT_FRAME_INSPECT_COPY_BUTTON_TEXT = "Copy Loadout Code"
TALENT_FRAME_NEW_LOADOUT_DISABLED_TOOLTIP = "You've reached the maximum number of loadouts. Delete a loadout from any of your specializations to free up a slot."
TALENT_FRAME_REFUND_INVALID_ERROR = "You must fix all errors. Unlearn talents to free up points and use them elsewhere to create a valid build."
TALENT_FRAME_RESET_BUTTON_DROPDOWN_ALL = "All"
TALENT_FRAME_RESET_BUTTON_DROPDOWN_LEFT = "Left Tree"
TALENT_FRAME_RESET_BUTTON_DROPDOWN_RIGHT = "Right Tree"
TALENT_FRAME_RESET_BUTTON_DROPDOWN_TITLE = "Reset Talents"
TALENT_FRAME_SEARCH_NOT_ON_ACTIONBAR = "Missing from action bar"
TALENT_FRAME_SEARCH_PREVIEW_OVERFLOW_FORMAT = "And %s more"
TALENT_FRAME_SEARCH_TOOLTIP_EXACT_MATCH = "Exact search match"
TALENT_FRAME_SEARCH_TOOLTIP_MATCH = "Search match"
TALENT_FRAME_SEARCH_TOOLTIP_NOT_ON_ACTIONBAR = "Not on action bar"
TALENT_FRAME_SEARCH_TOOLTIP_ON_DISABLED_ACTIONBAR = "On a disabled action bar"
TALENT_FRAME_SEARCH_TOOLTIP_ON_INACTIVE_BONUSBAR = "On an action bar belonging to a different stance"
TALENT_FRAME_SEARCH_TOOLTIP_RELATED_MATCH = "Related to the talent you searched for"
TALENT_FRAME_TAB_LABEL_SPEC = "Specialization"
TALENT_FRAME_TAB_LABEL_SPELLBOOK = "Spellbook"
TALENT_FRAME_TAB_LABEL_TALENTS = "Talents"
TALENT_SPEC_ACTIVATE = "Activate"
TUTORIAL_HERO_TALENT_NONE_SPENT = "Don't worry, you'll learn all these talents by level 80."

-- Retail named colours (Helix/GlobalColors.lua) used by the port. The vendored Color.lua turns
-- them into ColorMixins through C_UIColor.GetColors (Core/RetailAPI.lua) when it loads.
ns.RetailColorDefinitions = {
    { "BLUE_FONT_COLOR", "|cff00bff3", 0.000, 0.749, 0.953, 1.000 },
    { "BRIGHTBLUE_FONT_COLOR", "|cff66bbff", 0.400, 0.733, 1.000, 1.000 },
    { "DIM_RED_FONT_COLOR", "|cffcc1919", 0.800, 0.098, 0.098, 1.000 },
    { "DISABLED_FONT_COLOR", "|cff808080", 0.502, 0.502, 0.502, 1.000 },
    { "DRAGONFLIGHT_BLACK_COLOR", "|c00969696", 0.588, 0.588, 0.588, 0.000 },
    { "DRAGONFLIGHT_BLUE_COLOR", "|c003b9de3", 0.231, 0.616, 0.890, 0.000 },
    { "DRAGONFLIGHT_BRONZE_COLOR", "|c00b3920f", 0.702, 0.573, 0.059, 0.000 },
    { "DRAGONFLIGHT_GREEN_COLOR", "|c002dae5a", 0.176, 0.682, 0.353, 0.000 },
    { "DRAGONFLIGHT_RED_COLOR", "|c00ff6161", 1.000, 0.380, 0.380, 0.000 },
    { "ERROR_COLOR", "|cffff2020", 1.000, 0.125, 0.125, 1.000 },
    { "GRAY_FONT_COLOR", "|cff808080", 0.502, 0.502, 0.502, 1.000 },
    { "GREEN_FONT_COLOR", "|cff19ff19", 0.098, 1.000, 0.098, 1.000 },
    { "HIGHLIGHT_FONT_COLOR", "|cffffffff", 1.000, 1.000, 1.000, 1.000 },
    { "LIGHTBLUE_FONT_COLOR", "|cff87abff", 0.529, 0.671, 1.000, 1.000 },
    { "LIGHTGRAY_FONT_COLOR", "|cff999999", 0.600, 0.600, 0.600, 1.000 },
    { "NORMAL_FONT_COLOR", "|cffffd200", 1.000, 0.824, 0.000, 1.000 },
    { "ORANGE_FONT_COLOR", "|cffff8040", 1.000, 0.502, 0.251, 1.000 },
    { "PANEL_BACKGROUND_COLOR", "|ccc1f1e21", 0.122, 0.118, 0.129, 0.800 },
    { "RED_FONT_COLOR", "|cffff2020", 1.000, 0.125, 0.125, 1.000 },
    { "SPELL_LINK_COLOR", "|cff71d5ff", 0.443, 0.835, 1.000, 1.000 },
    { "WHITE_FONT_COLOR", "|cffffffff", 1.000, 1.000, 1.000, 1.000 },
    { "YELLOW_FONT_COLOR", "|cffffff00", 1.000, 1.000, 0.000, 1.000 },
}
