-- ---------------------------------------------------------------------------
-- 117  Hyjal round-14 -- the last 3 map-750 vehicles (Vehicle.dbc 701/825/1606)
-- ---------------------------------------------------------------------------
-- Round 1/2 of the vehicle audit (66_, 82_) fixed the "non-existing VehicleId
-- ... WILL cause the client to freeze" boot errors by downporting the rows it
-- had -- but for three creatures it took the other route and simply ZEROED
-- creature_template.VehicleId, which silences the error at the cost of the
-- content:  the NPC is then not a vehicle at all and cannot be ridden.
--     3640719  Aviana's Guardian      VehicleId 701   -- quest 25523 "Flight in
--                                                        the Firelands" / the
--                                                        Aviana flying quests
--     3641459  Player Float Vehicle   VehicleId 825   -- "Aessina's Miracle"
--                                                        (npc_aessina_miracle_vehicle)
--     3652556  Druid Combat Circle    VehicleId 1606
-- This downports the real rows (Vehicle 701/825/1606 + VehicleSeat 7643/7897/
-- 7898/9840/9859) from the Cata 4.3.4 client's locale-enUS.MPQ and restores
-- the VehicleIds.  Generated by HyjalCata/tools/gen_hyjal_vehicle_downport.py,
-- whose field decode self-validates against seat 7683 as already shipped by
-- 82_ before it emits anything.
-- The matching CLIENT rows go into Custom/CSV DBC/Vehicle.csv + VehicleSeat.csv
-- (emitted next to this file) and need a DBC recompile + patch repack.
-- ---------------------------------------------------------------------------

DELETE FROM `vehicleseat_dbc` WHERE `ID` IN (7643,7897,7898,9840,9859);

INSERT INTO `vehicleseat_dbc` (`ID`, `Flags`, `AttachmentID`, `AttachmentOffsetX`, `AttachmentOffsetY`, `AttachmentOffsetZ`, `EnterPreDelay`, `EnterSpeed`, `EnterGravity`, `EnterMinDuration`, `EnterMaxDuration`, `EnterMinArcHeight`, `EnterMaxArcHeight`, `EnterAnimStart`, `EnterAnimLoop`, `RideAnimStart`, `RideAnimLoop`, `RideUpperAnimStart`, `RideUpperAnimLoop`, `ExitPreDelay`, `ExitSpeed`, `ExitGravity`, `ExitMinDuration`, `ExitMaxDuration`, `ExitMinArcHeight`, `ExitMaxArcHeight`, `ExitAnimStart`, `ExitAnimLoop`, `ExitAnimEnd`, `PassengerYaw`, `PassengerPitch`, `PassengerRoll`, `PassengerAttachmentID`, `VehicleEnterAnim`, `VehicleExitAnim`, `VehicleRideAnimLoop`, `VehicleEnterAnimBone`, `VehicleExitAnimBone`, `VehicleRideAnimLoopBone`, `VehicleEnterAnimDelay`, `VehicleExitAnimDelay`, `VehicleAbilityDisplay`, `EnterUISoundID`, `ExitUISoundID`, `UiSkin`, `FlagsB`, `CameraEnteringDelay`, `CameraEnteringDuration`, `CameraExitingDelay`, `CameraExitingDuration`, `CameraOffsetX`, `CameraOffsetY`, `CameraOffsetZ`, `CameraPosChaseRate`, `CameraFacingChaseRate`, `CameraEnteringZoom`, `CameraSeatZoomMin`, `CameraSeatZoomMax`) VALUES
(7643, -502233073, 21, 0, 0, 0, 0, 7, 19.290001, 0, 0, 1, 4, 37, 38, -1, 478, 89, 478, 0, 7, 19.290001, 0, 0, 1, 3, 37, 38, 39, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, 0, 0, 1, 0, 0, 0, 11280, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0),
(7897, 1074823177, 2, 0, 0, 0, 0, 7, 19.290001, 0, 1, 0, 4, 37, 38, -1, -1, -1, -1, 0, 7, 19.290001, 0, 1, 0, 4, 37, 38, 39, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, 0, 0, 1, 0, 0, 0, -2147472384, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0),
(7898, 33587209, 2, 5, 0, -7.5, 0, 7, 19.290001, 0, 0, 1, 4, 37, 38, -1, -1, -1, -1, 0, 7, 19.290001, 0, 0, 1, 4, 37, 38, 39, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, 0, 0, 1, 0, 0, 0, 33554432, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(9840, 33587209, 14, 0, 0, 0, 0, 7, 19.290001, 0, 0, 1, 4, 37, 38, -1, 102, 128, 123, 0, 7, 19.290001, 0, 0, 1, 4, 37, 38, 39, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, 0, 0, 1, 0, 0, 0, 33554432, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
(9859, 33587209, 15, 0, 0, 0, 0, 7, 19.290001, 0, 0, 1, 4, 37, 38, -1, 102, 128, 123, 0, 7, 19.290001, 0, 0, 1, 4, 37, 38, 39, 0, 0, 0, -1, -1, -1, -1, -1, -1, -1, 0, 0, 1, 0, 0, 0, 33554432, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

DELETE FROM `vehicle_dbc` WHERE `ID` IN (701,825,1606);

INSERT INTO `vehicle_dbc` (`ID`, `Flags`, `TurnSpeed`, `PitchSpeed`, `PitchMin`, `PitchMax`, `SeatID_1`, `SeatID_2`, `SeatID_3`, `SeatID_4`, `SeatID_5`, `SeatID_6`, `SeatID_7`, `SeatID_8`, `MouseLookOffsetPitch`, `CameraFadeDistScalarMin`, `CameraFadeDistScalarMax`, `CameraPitchOffset`, `FacingLimitRight`, `FacingLimitLeft`, `MsslTrgtTurnLingering`, `MsslTrgtPitchLingering`, `MsslTrgtMouseLingering`, `MsslTrgtEndOpacity`, `MsslTrgtArcSpeed`, `MsslTrgtArcRepeat`, `MsslTrgtArcWidth`, `MsslTrgtImpactRadius_1`, `MsslTrgtImpactRadius_2`, `MsslTrgtArcTexture`, `MsslTrgtImpactTexture`, `MsslTrgtImpactModel_1`, `MsslTrgtImpactModel_2`, `CameraYawOffset`, `UilocomotionType`, `MsslTrgtImpactTexRadius`, `VehicleUIIndicatorID`, `PowerDisplayID_1`, `PowerDisplayID_2`, `PowerDisplayID_3`) VALUES
(701, 1342357514, 3.141593, 3.141593, 0, 0, 7643, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1.5, 0, 0, 0, 1.5, 1.5, 1, 0.75, 0.5, 0.5, 1.6, 5, 0.5, NULL, NULL, 'INTERFACE\\Vehicles\\Vehicle_Target_02.mdx', 'Interface\\Vehicles\\Vehicle_Target_02.mdx', 0, 1, 1, 0, 0, 0, 0),
(825, 1074266112, 1.047, 1.047, 0, 0, 7897, 7898, 0, 0, 0, 0, 0, 0, 0, 1, 1.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0),
(1606, 1073877031, 3.141593, 3.141593, 0, 0, 9840, 9859, 0, 0, 0, 0, 0, 0, 0.785398, 1, 1.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);

-- restore the VehicleIds that round 1/2 zeroed
UPDATE `creature_template` SET `VehicleId` = 701  WHERE `entry` = 3640719 AND `VehicleId` = 0;
UPDATE `creature_template` SET `VehicleId` = 825  WHERE `entry` = 3641459 AND `VehicleId` = 0;
UPDATE `creature_template` SET `VehicleId` = 1606 WHERE `entry` = 3652556 AND `VehicleId` = 0;
