-- ---------------------------------------------------------------------------
-- 135  Hyjal round-17 -- the two spells 132_'s new templates brought in
-- ---------------------------------------------------------------------------
-- Applying MoltenFront/apply_all.sql brought map 861 live (1,118 creatures) and
-- with it a second wave of spell references that resolve in NEITHER the built
-- client Spell.dbc NOR acore_world.spell_dbc -- plus the spells called from the
-- timed action lists that 122_ finally imports.  Without these rows SmartAIMgr
-- skips the whole row at load, which is why so many Molten Front entries also
-- report "has SmartAI enabled but no SmartAI entries": every one of their rows
-- was being thrown away.
--
-- Three sources, in order of fidelity:
--   * 39 straight downports from the real Cata 4.3.4 client (Spell.dbc +
--     SpellEffect.dbc, wow-update-base-15601.MPQ).
--   * 7 effect-only orphans -- Blizzard dropped the Spell.dbc row in 4.3.4 but
--     left the SpellEffect rows, so the header is synthesised from those
--     (98503-98505 the Furnace rappelling ropes, 101173/77/79/82 the Molten
--     Front invoker dummies).
--   * 8 Project Neltharion CUSTOM 15xxxx ids, which exist in no Blizzard build
--     at all -- flattened out of nelt_world's normalised spell_dbc +
--     spelleffect_dbc (keyed by EffectSpellId, not Id), same technique as 47_.
--
-- SUMMON / TRANSFORM / KILL_CREDIT EffectMiscValue is remapped from the Cata
-- entry to the DC +3,600,000 clone (52988->3652988 Turtle Punter, 52804,
-- 52950, 53163, 53234, 53354, 52705, 52990).  126_ imports those creature
-- templates and is a HARD PREREQUISITE for this file.
--
-- Generated by HyjalCata/tools/gen_hyjal_spell_downport_r15.py.  Matching
-- CLIENT rows are emitted alongside as hyjal_r15_spells.csv for Spell.csv.
-- ---------------------------------------------------------------------------

DELETE FROM `spell_dbc` WHERE `ID` IN (76232,76233);

INSERT INTO `spell_dbc` VALUES
('76232','0','0','0','67108864','16388','0','0','0','0','16384','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','5','0','0','0','0','0','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','6','6','2','0','0','0','0','0','0','2000','0','0','0','0','0','6','1','6','0','0','0','0','0','0','87','23','0','0','500','0','0','0','0','0','0','0','0','0','0','126','0','0','0','0','0','0','76366','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Storm''s Fury','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','2','0','0','1','1','1','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0'),
('76233','0','0','0','67108864','16388','0','0','0','0','16384','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','5','0','0','0','0','0','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','6','6','2','0','0','0','0','0','0','2000','0','0','0','0','0','6','1','6','0','0','0','0','0','0','87','23','0','0','1000','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','77805','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Earth''s Rage','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','2','0','0','1','1','1','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0');
