-- ---------------------------------------------------------------------------
-- 140  Hyjal round-18 -- the 20 missing Molten Front quest / loot items
-- ---------------------------------------------------------------------------
--     Quest 29287 has `RequiredItemId1` = 69836 but item with entry 69836 does
--     not exist, quest can't be done.
--     Table 'gameobject_loot_template' Entry 208630 Item 69836: item entry not
--     listed in `item_template` - skipped
--
-- Round 15 deferred these because nelt_world's ItemSparse holds only 6 of the
-- 20 (it is a partial table, ~54k of Cata's ~68k items).  Two other sources
-- between them cover all 20:
--   * the Cata client Item.db2 (build 15595) -> class / subclass / material /
--     displayid / inventorytype / sheath.  Its WDB2 header is 48 bytes with NO
--     index table when minid == maxid == 0, which is the case here; getting
--     that wrong shifts every record.
--   * the retail ItemSparse extract -> names and descriptions, so the strings
--     are authentic rather than invented.
--
-- Unblocks the Molten Front chain that needed them: Egg-stinction, Embergris,
-- Steal Magmolias, Fandral's Methods, The Flame Spider Queen, Living Obsidium,
-- Peaked Interest, Starting Young, The Bigger They Are, Aggressive Growth, The
-- Mysterious Seed, Planting Season, A Bitter Pill, How Hot, Singed Wings, Bye
-- Bye Burdy -- plus the Cinderweb Egg Sac / Fire Hawk Egg loot 124_ imported.
--
-- DISPLAY IDs: 11 of the 20 Cata display ids already exist in the fork's
-- ItemDisplayInfo and are kept.  The other 9 (the Cata-new 98xxx icons) do not,
-- and an unknown display makes the core log "does not have a correct display id
-- (N), must be 0" -- so those are set to 0.  The items function; they show no
-- icon until those ItemDisplayInfo rows + their BLPs are downported.
--
-- 18 of the 20 are class 12 (Quest, bind-on-pickup); 52976 is class 7 (Trade
-- Goods) and 56236 class 15 (Miscellaneous), both left unbound.
-- Generated by HyjalCata/tools/gen_mf_quest_items.py.
-- ---------------------------------------------------------------------------

DELETE FROM `item_template` WHERE `entry` IN (52976,56236,69214,69675,69722,69725,69749,69759,69806,69807,69808,69809,69810,69811,69812,69832,69836,69837,69845,69860);

INSERT INTO `item_template` (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `Flags`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `maxcount`, `stackable`, `ContainerSlots`, `bonding`, `description`, `startquest`, `Material`, `sheath`, `BagFamily`, `ScriptName`, `VerifiedBuild`) VALUES
(52976, 7, 6, 'Savage Leather', 0, 1, 0, 1, 0, 0, 0, -1, -1, 25, 0, 0, 1000, 0, 0, '', 0, 8, 0, 136, '', 0),
(56236, 15, 0, 'Cloudy Brille', 0, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 4, 0, 0, '', 0),
(69214, 12, 0, 'Cinderweb Egg', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 20, 0, 1, 'Tiny spiders incubate within the squishy, gel-like sac.', 0, 7, 0, 0, '', 0),
(69675, 12, 0, 'Dried Acorn', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, 'A small, dried seed.', 0, 2, 0, 0, '', 0),
(69722, 12, 0, 'Embergris', 18716, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 20, 0, 1, 'This molten substance is hot to the touch.', 0, 4, 0, 0, '', 0),
(69725, 12, 0, 'Magmolia', 75401, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 20, 0, 1, 'This glowing flower is hot to the touch.', 0, 7, 0, 0, '', 0),
(69749, 12, 0, 'Smothervine Seeds', 77114, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, 'The seeds pulsate with a strange glow, ready to burst, given the right environment.', 0, 0, 0, 0, '', 0),
(69759, 12, 0, 'The Bitter Pill', 38994, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(69806, 12, 0, 'Tholo''s Thermometer', 20892, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(69807, 12, 0, 'Obsidium Meteorite', 36189, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 20, 0, 1, 'This shiny, hardened substance was forged in unimaginable heat. It glows with an unearthly radiance.', 0, 4, 0, 0, '', 0),
(69808, 12, 0, 'Flame Venom', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 20, 0, 1, 'Poison is bad enough when it''s NOT boiling hot.', 0, 4, 0, 0, '', 0),
(69809, 12, 0, 'Searing Web Fluid', 36601, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 20, 0, 1, 'The substance is unbelievably viscous.', 0, 4, 0, 0, '', 0),
(69810, 12, 0, 'Flame Druid Staff', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, 'To the untrained eye, this would be indistinguishable from any druid''s staff.', 0, 4, 0, 0, '', 0),
(69811, 12, 0, 'Flame Druid Spellbook', 67550, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, 'Within lie the details of the flame druids'' strange spells.', 0, 4, 0, 0, '', 0),
(69812, 12, 0, 'Flame Druid Reagent Pouch', 4584, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, 'Contains some burned seeds, ash, and... what appears to be marshmallows.', 0, 4, 0, 0, '', 0),
(69832, 12, 0, 'Burd Sticker', 23315, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, 'Gud fer flipjabbing pesky burds.', 0, 4, 0, 0, '', 0),
(69836, 12, 0, 'Fire Hawk Egg', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 1, 'Pulsing with an intense heat...', 0, 4, 0, 0, '', 0),
(69837, 12, 0, 'Arthorn''s Injury Kit', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, 'Splints, bandages, burn salves, smelling salts... anything you will need to get an injured Druid of the Talon back on his feet.', 0, 0, 0, 0, '', 0),
(69845, 12, 0, 'Fire Hawk Hatchling', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 10, 20, 0, 1, 'Surprisingly docile.', 0, 4, 0, 0, '', 0),
(69860, 12, 0, 'Living Obsidium Chip', 18519, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 20, 0, 1, 'The dark, jagged stone shimmers and moves as if it were alive.', 0, 4, 0, 0, '', 0);
