-- ---------------------------------------------------------------------------
-- 151  Hyjal round-23 -- Zen'Vorka's 13 missing stock items
-- ---------------------------------------------------------------------------
-- Zen'Vorka (3652822, map 861) is the Molten Front token vendor -- he is what
-- the "Mark of the World Tree" currency is FOR.  He carries the vendor npcflag
-- but has zero npc_vendor rows, so his window opens empty and the whole Mark
-- sink is dead content.  nelt_world has all 17 of his rows; 13 of the items do
-- not exist here, so 152_ cannot import the vendor list until these exist --
-- otherwise the empty window is merely traded for 13 "item entry not listed in
-- `item_template` - skipped" errors.
--
-- Sources are the pair rounds 19/21 used: the Cata client Item.db2 (build
-- 15595) for class / subclass / material / display / inventorytype / sheath,
-- and the retail ItemSparse extract for names and descriptions, so the strings
-- are authentic rather than invented.
--
-- DISPLAY IDs: any Cata display the fork's ItemDisplayInfo lacks is written as
-- 0 -- an unknown display makes the core log "does not have a correct display
-- id (N), must be 0".  The items work; they show no icon until those rows and
-- their BLPs are downported.
--
-- Generated by HyjalCata/tools/gen_zenvorka_items.py.  Apply BEFORE 152_.
-- ---------------------------------------------------------------------------

DELETE FROM `item_template` WHERE `entry` IN (70145,70146,70147,70148,70149,70150,70151,70152,70153,70154,71087,71088,71631);

INSERT INTO `item_template` (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `Flags`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `maxcount`, `stackable`, `ContainerSlots`, `bonding`, `description`, `startquest`, `Material`, `sheath`, `BagFamily`, `ScriptName`, `VerifiedBuild`) VALUES
(70145, 12, 0, 'Darnassus Writ of Commendation', 0, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(70146, 12, 0, 'Exodar Writ of Commendation', 0, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(70147, 12, 0, 'Gnomeregan Writ of Commendation', 0, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(70148, 12, 0, 'Ironforge Writ of Commendation', 58580, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(70149, 12, 0, 'Orgrimmar Writ of Commendation', 0, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(70150, 12, 0, 'Sen''jin Writ of Commendation', 0, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(70151, 12, 0, 'Silvermoon Writ of Commendation', 0, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(70152, 12, 0, 'Stormwind Writ of Commendation', 0, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(70153, 12, 0, 'Thunder Bluff Writ of Commendation', 0, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(70154, 12, 0, 'Undercity Writ of Commendation', 0, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(71087, 12, 0, 'Gilneas Writ of Commendation', 0, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(71088, 12, 0, 'Bilgewater Writ of Commendation', 0, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 250, 0, 1, '', 0, 7, 0, 0, '', 0),
(71631, 15, 0, 'Zen''Vorka''s Cache', 31783, 2, 0, 1, 0, 0, 0, -1, -1, 32, 0, 0, 1, 0, 0, '', 0, 4, 0, 0, '', 0);
