-- ---------------------------------------------------------------------------
-- 166  Hyjal round-34 -- clone the border-zone NPCs and objects
-- ---------------------------------------------------------------------------
-- 157_/161_/164_ imported stock creatures and gameobjects onto map 750 using
-- their RAW entry ids.  The data is correct, but it means the map-750 copy and
-- the real Winterspring / Moonglade / Felwood / Darkshore / Azshara / Ashenvale
-- copy are the SAME records -- editing one edits the other.
--
-- This clones them into private ranges so map 750 can be modified freely:
--     creature entry / loot / gossip   raw + 3,700,000
--     gameobject entry / loot          raw + 3,900,000
-- Both ranges were verified empty first.  smart_scripts is the exception and
-- needed a third namespace: 3,7xx,xxx already holds 148 source_type 9 rows
-- belonging to STOCK Icecrown Citadel (AzerothCore numbers action lists
-- entry*100, so ICC's 37000-37999 land there).  Cloned action lists go to
-- raw_list + 370,000,000 instead; 168_ restores what the earlier revision of
-- this file deleted from that band.
--
-- SHARED ON PURPOSE: npc_text / broadcast_text (a global string pool -- gossip
-- text shared, gossip structure not), item_template, and ScriptName values so
-- the same C++ still drives the cloned NPCs.
--
-- QUESTS ARE NOT CLONED HERE -- separate pass, because ~200 quests need
-- PrevQuestID / NextQuestID / ExclusiveGroup remapping and mixing it in would
-- make both halves harder to verify.  Until then the clones offer no quests;
-- the raw NPCs they came from still do.
--
-- Column lists below are read from information_schema, not assumed: this fork's
-- creature_template has no `scale` and no `trainer_class`, and adds speed_swim,
-- speed_flight, detection_range and CreatureImmunitiesId.  A bare
-- INSERT ... SELECT would shift every column past the first difference.
--
-- Generated by HyjalCata/tools/gen_border_zone_clone.py.  Idempotent.
-- ---------------------------------------------------------------------------

-- --- materialise the source set -- see the note in the generator -------------
DROP TABLE IF EXISTS `_dc_clone_src`;
CREATE TABLE `_dc_clone_src` (`id` INT UNSIGNED NOT NULL PRIMARY KEY) ENGINE=InnoDB;
INSERT INTO `_dc_clone_src` (`id`)
SELECT DISTINCT c.`id` FROM `creature` c
WHERE c.`guid` BETWEEN 15600000 AND 15899999 AND c.`id` < 3700000
UNION SELECT DISTINCT c.`id` - 3700000 FROM `creature` c
WHERE c.`guid` BETWEEN 15600000 AND 15899999 AND c.`id` BETWEEN 3700000 AND 3799999
  AND EXISTS (SELECT 1 FROM `creature_template` t WHERE t.`entry` = c.`id` - 3700000)
UNION SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999
  AND `entry` IN (SELECT `id` FROM `creature` WHERE `guid` BETWEEN 15600000 AND 15899999);

DROP TABLE IF EXISTS `_dc_clone_srcg`;
CREATE TABLE `_dc_clone_srcg` (`id` INT UNSIGNED NOT NULL PRIMARY KEY) ENGINE=InnoDB;
INSERT INTO `_dc_clone_srcg` (`id`)
SELECT DISTINCT g.`id` FROM `gameobject` g
WHERE g.`guid` BETWEEN 15600000 AND 15899999 AND g.`id` < 3900000
UNION SELECT DISTINCT g.`id` - 3900000 FROM `gameobject` g
WHERE g.`guid` BETWEEN 15600000 AND 15899999 AND g.`id` BETWEEN 3900000 AND 4399999
  AND EXISTS (SELECT 1 FROM `gameobject_template` t WHERE t.`entry` = g.`id` - 3900000)
UNION SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` BETWEEN 3900000 AND 4399999
  AND `entry` IN (SELECT `id` FROM `gameobject` WHERE `guid` BETWEEN 15600000 AND 15899999);

-- The timed action lists the cloned creatures call.  Materialised here, while
-- the source set is still raw, so the smart_scripts block can DELETE exactly
-- the ids it is about to write instead of guessing at a range.  Nested lists
-- (a source_type 9 row calling another list) are deliberately not followed --
-- the clone keeps calling the shared original, same as it keeps ScriptName.
DROP TABLE IF EXISTS `_dc_clone_al`;
CREATE TABLE `_dc_clone_al` (`id` INT UNSIGNED NOT NULL PRIMARY KEY) ENGINE=InnoDB;
INSERT INTO `_dc_clone_al` (`id`)
SELECT DISTINCT `action_param1` FROM `smart_scripts`
WHERE `source_type` = 0 AND `action_type` = 80 AND `action_param1` <> 0
  AND `entryorguid` IN (SELECT `id` FROM `_dc_clone_src`);

-- --- creature_template -------------------------------------------------------
DELETE FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999;
INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_flight`, `detection_range`, `rank`, `dmgschool`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `CreatureImmunitiesId`, `flags_extra`, `ScriptName`, `VerifiedBuild`)
SELECT `entry` + 3700000, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `speed_walk`, `speed_run`, `speed_swim`, `speed_flight`, `detection_range`, `rank`, `dmgschool`, `DamageModifier`, `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`, `dynamicflags`, `family`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `CreatureImmunitiesId`, `flags_extra`, `ScriptName`, `VerifiedBuild`
FROM `creature_template` WHERE `entry` IN (SELECT `id` FROM `_dc_clone_src`);

UPDATE `creature_template` SET `KillCredit1` = `KillCredit1` + 3700000
WHERE `entry` BETWEEN 3700000 AND 3799999 AND `KillCredit1` <> 0 AND `KillCredit1` IN (SELECT `id` FROM `_dc_clone_src`);
UPDATE `creature_template` SET `KillCredit2` = `KillCredit2` + 3700000
WHERE `entry` BETWEEN 3700000 AND 3799999 AND `KillCredit2` <> 0 AND `KillCredit2` IN (SELECT `id` FROM `_dc_clone_src`);
UPDATE `creature_template` SET `lootid` = `lootid` + 3700000 WHERE `entry` BETWEEN 3700000 AND 3799999 AND `lootid` <> 0;
UPDATE `creature_template` SET `pickpocketloot` = `pickpocketloot` + 3700000 WHERE `entry` BETWEEN 3700000 AND 3799999 AND `pickpocketloot` <> 0;
UPDATE `creature_template` SET `skinloot` = `skinloot` + 3700000 WHERE `entry` BETWEEN 3700000 AND 3799999 AND `skinloot` <> 0;
UPDATE `creature_template` SET `gossip_menu_id` = `gossip_menu_id` + 3700000 WHERE `entry` BETWEEN 3700000 AND 3799999 AND `gossip_menu_id` <> 0;
-- difficulty_entry_* would dangle at templates that were not cloned
UPDATE `creature_template` SET `difficulty_entry_1` = 0, `difficulty_entry_2` = 0, `difficulty_entry_3` = 0
WHERE `entry` BETWEEN 3700000 AND 3799999;

-- --- creature_template_model / addon / equip ---------------------------------
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 3700000 AND 3799999;
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`)
SELECT `CreatureID` + 3700000, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`
FROM `creature_template_model` WHERE `CreatureID` IN (SELECT `id` FROM `_dc_clone_src`);

DELETE FROM `creature_template_addon` WHERE `entry` BETWEEN 3700000 AND 3799999;
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `visibilityDistanceType`, `auras`)
SELECT `entry` + 3700000, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `visibilityDistanceType`, `auras`
FROM `creature_template_addon` WHERE `entry` IN (SELECT `id` FROM `_dc_clone_src`);

DELETE FROM `creature_equip_template` WHERE `CreatureID` BETWEEN 3700000 AND 3799999;
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`, `VerifiedBuild`)
SELECT `CreatureID` + 3700000, `ID`, `ItemID1`, `ItemID2`, `ItemID3`, `VerifiedBuild`
FROM `creature_equip_template` WHERE `CreatureID` IN (SELECT `id` FROM `_dc_clone_src`);

-- --- loot tables -- Reference rows keep their raw target:
--     reference_loot_template is a shared pool, not per-creature data 
DELETE FROM `creature_loot_template` WHERE `Entry` BETWEEN 3700000 AND 3799999;
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`)
SELECT `Entry` + 3700000, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`
FROM `creature_loot_template` WHERE `Entry` IN (SELECT DISTINCT `lootid` FROM `creature_template` WHERE `entry` IN (SELECT `id` FROM `_dc_clone_src`) AND `lootid` <> 0);

DELETE FROM `pickpocketing_loot_template` WHERE `Entry` BETWEEN 3700000 AND 3799999;
INSERT INTO `pickpocketing_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`)
SELECT `Entry` + 3700000, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`
FROM `pickpocketing_loot_template` WHERE `Entry` IN (SELECT DISTINCT `pickpocketloot` FROM `creature_template` WHERE `entry` IN (SELECT `id` FROM `_dc_clone_src`) AND `pickpocketloot` <> 0);

DELETE FROM `skinning_loot_template` WHERE `Entry` BETWEEN 3700000 AND 3799999;
INSERT INTO `skinning_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`)
SELECT `Entry` + 3700000, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`
FROM `skinning_loot_template` WHERE `Entry` IN (SELECT DISTINCT `skinloot` FROM `creature_template` WHERE `entry` IN (SELECT `id` FROM `_dc_clone_src`) AND `skinloot` <> 0);

-- --- vendor / trainer / gossip / text / reputation ---------------------------
DELETE FROM `npc_vendor` WHERE `entry` BETWEEN 3700000 AND 3799999;
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`)
SELECT `entry` + 3700000, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`
FROM `npc_vendor` WHERE `entry` IN (SELECT `id` FROM `_dc_clone_src`);

DELETE FROM `creature_default_trainer` WHERE `CreatureId` BETWEEN 3700000 AND 3799999;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`)
SELECT `CreatureId` + 3700000, `TrainerId`
FROM `creature_default_trainer` WHERE `CreatureId` IN (SELECT `id` FROM `_dc_clone_src`);

DELETE FROM `gossip_menu` WHERE `MenuID` BETWEEN 3700000 AND 3799999;
INSERT INTO `gossip_menu` (`MenuID`, `TextID`)
SELECT `MenuID` + 3700000, `TextID`
FROM `gossip_menu` WHERE `MenuID` IN (SELECT DISTINCT `gossip_menu_id` FROM `creature_template` WHERE `entry` IN (SELECT `id` FROM `_dc_clone_src`) AND `gossip_menu_id` <> 0);

DELETE FROM `gossip_menu_option` WHERE `MenuID` BETWEEN 3700000 AND 3799999;
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`)
SELECT `MenuID` + 3700000, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `ActionMenuID` + IF(`ActionMenuID` <> 0, 3700000, 0), `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`
FROM `gossip_menu_option` WHERE `MenuID` IN (SELECT DISTINCT `gossip_menu_id` FROM `creature_template` WHERE `entry` IN (SELECT `id` FROM `_dc_clone_src`) AND `gossip_menu_id` <> 0);

DELETE FROM `creature_text` WHERE `CreatureID` BETWEEN 3700000 AND 3799999;
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`)
SELECT `CreatureID` + 3700000, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`
FROM `creature_text` WHERE `CreatureID` IN (SELECT `id` FROM `_dc_clone_src`);

-- quest_greeting.ID is a CREATURE entry when type = 0, not a quest id.  167_ got
-- this wrong -- it matched IDs against creature_queststarter.quest and wrote them
-- at +100,000, producing five rows keyed to creatures that do not exist.  It
-- belongs on the creature side, at the creature offset; 169_ clears the bad rows.
DELETE FROM `quest_greeting` WHERE `type` = 0 AND `ID` BETWEEN 3700000 AND 3799999;
INSERT INTO `quest_greeting` (`ID`, `type`, `GreetEmoteType`, `GreetEmoteDelay`, `Greeting`, `VerifiedBuild`)
SELECT `ID` + 3700000, `type`, `GreetEmoteType`, `GreetEmoteDelay`, `Greeting`, `VerifiedBuild`
FROM `quest_greeting` WHERE `type` = 0 AND `ID` IN (SELECT `id` FROM `_dc_clone_src`);

DELETE FROM `creature_onkill_reputation` WHERE `creature_id` BETWEEN 3700000 AND 3799999;
INSERT INTO `creature_onkill_reputation` (`creature_id`, `RewOnKillRepFaction1`, `RewOnKillRepFaction2`, `MaxStanding1`, `IsTeamAward1`, `RewOnKillRepValue1`, `MaxStanding2`, `IsTeamAward2`, `RewOnKillRepValue2`, `TeamDependent`)
SELECT `creature_id` + 3700000, `RewOnKillRepFaction1`, `RewOnKillRepFaction2`, `MaxStanding1`, `IsTeamAward1`, `RewOnKillRepValue1`, `MaxStanding2`, `IsTeamAward2`, `RewOnKillRepValue2`, `TeamDependent`
FROM `creature_onkill_reputation` WHERE `creature_id` IN (SELECT `id` FROM `_dc_clone_src`);

-- --- smart_scripts -- creature rows plus the action lists they call ----------
-- The source_type 0 band is safe to clear wholesale: entryorguid there is a
-- creature entry, and nothing but these clones lives at 3,7xx,xxx.
--
-- source_type 9 is NOT.  AzerothCore numbers timed action lists
-- `creature_entry * 100`, so stock entries 37000-37999 -- Highlord Darion
-- Mograine, Blood-Queen Lana'thel, The Lich King and the rest of Icecrown
-- Citadel -- own 148 rows sitting squarely in 3,700,000-3,799,999.  An earlier
-- revision of this file deleted that band and destroyed all ten of those lists;
-- 168_ puts them back.  The clones therefore live at raw_list + 370,000,000,
-- which keeps the entry*100 convention intact (a clone at entry 3,7xx,xxx wants
-- list 370,xxx,xxx) and lands in a band verified completely empty.  The DELETE
-- targets the exact ids about to be written rather than a range, via the
-- scratch table -- a range guard is what caused the damage in the first place.
DELETE FROM `smart_scripts` WHERE `source_type` = 0 AND `entryorguid` BETWEEN 3700000 AND 3799999;
DELETE FROM `smart_scripts` WHERE `source_type` = 9
  AND `entryorguid` IN (SELECT `id` + 370000000 FROM `_dc_clone_al`);

INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`)
SELECT `entryorguid` + 3700000, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`
FROM `smart_scripts` WHERE `source_type` = 0 AND `entryorguid` IN (SELECT `id` FROM `_dc_clone_src`);

INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`)
SELECT `entryorguid` + 370000000, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`
FROM `smart_scripts` WHERE `source_type` = 9 AND `entryorguid` IN (SELECT `id` FROM `_dc_clone_al`);

-- Repoint the action-list call, and any summon / kill-credit / target naming a
-- creature we also cloned.  References OUTSIDE the cloned set stay raw on
-- purpose: they point at world content that was not copied.
UPDATE `smart_scripts` SET `action_param1` = `action_param1` + 370000000
WHERE `source_type` = 0 AND `entryorguid` BETWEEN 3700000 AND 3799999
  AND `action_type` = 80 AND `action_param1` IN (SELECT `id` FROM `_dc_clone_al`);
-- Both bands, because the cloned rows no longer share one: creature rows are at
-- 3,7xx,xxx and their action lists at 370,xxx,xxx.  Matching only the first
-- would leave every summon and target inside a cloned action list pointing at
-- the raw NPC -- the exact leak this file exists to close.
UPDATE `smart_scripts` SET `action_param1` = `action_param1` + 3700000
WHERE ((`source_type` = 0 AND `entryorguid` BETWEEN 3700000 AND 3799999)
    OR (`source_type` = 9 AND `entryorguid` BETWEEN 370000000 AND 379999999))
  AND `action_type` IN (12,33) AND `action_param1` IN (SELECT `id` FROM `_dc_clone_src`);
UPDATE `smart_scripts` SET `target_param1` = `target_param1` + 3700000
WHERE ((`source_type` = 0 AND `entryorguid` BETWEEN 3700000 AND 3799999)
    OR (`source_type` = 9 AND `entryorguid` BETWEEN 370000000 AND 379999999))
  AND `target_type` IN (9,11,19) AND `target_param1` IN (SELECT `id` FROM `_dc_clone_src`);

-- --- gameobject_template + addon + loot --------------------------------------
DELETE FROM `gameobject_template` WHERE `entry` IN (SELECT `id` + 3900000 FROM `_dc_clone_srcg`);
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `AIName`, `ScriptName`, `VerifiedBuild`)
SELECT `entry` + 3900000, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `AIName`, `ScriptName`, `VerifiedBuild`
FROM `gameobject_template` WHERE `entry` IN (SELECT `id` FROM `_dc_clone_srcg`);

DELETE FROM `gameobject_template_addon` WHERE `entry` IN (SELECT `id` + 3900000 FROM `_dc_clone_srcg`);
INSERT INTO `gameobject_template_addon` (`entry`, `faction`, `flags`, `mingold`, `maxgold`, `artkit0`, `artkit1`, `artkit2`, `artkit3`)
SELECT `entry` + 3900000, `faction`, `flags`, `mingold`, `maxgold`, `artkit0`, `artkit1`, `artkit2`, `artkit3`
FROM `gameobject_template_addon` WHERE `entry` IN (SELECT `id` FROM `_dc_clone_srcg`);

-- type 3 (CHEST) holds its loot id in Data1
DELETE FROM `gameobject_loot_template` WHERE `Entry` IN (
  SELECT DISTINCT `Data1` + 3900000 FROM `gameobject_template`
  WHERE `entry` IN (SELECT `id` FROM `_dc_clone_srcg`) AND `type` = 3 AND `Data1` <> 0);
INSERT INTO `gameobject_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`)
SELECT `Entry` + 3900000, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`
FROM `gameobject_loot_template` WHERE `Entry` IN (SELECT DISTINCT `Data1` FROM `gameobject_template` WHERE `entry` IN (SELECT `id` FROM `_dc_clone_srcg`) AND `type` = 3 AND `Data1` <> 0);

UPDATE `gameobject_template` SET `Data1` = `Data1` + 3900000
WHERE `entry` IN (SELECT `id` + 3900000 FROM `_dc_clone_srcg`) AND `type` = 3 AND `Data1` <> 0;

-- SmartGameobjectAI carries across with the template, so the scripts have to as
-- well -- 20 cloned objects had the AIName and no rows, which the core reports
-- as "has SmartGameobjectAI enabled but no SmartAI entries in the database".
DELETE FROM `smart_scripts` WHERE `source_type` = 1 AND `entryorguid` IN (SELECT `id` + 3900000 FROM `_dc_clone_srcg`);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`)
SELECT `entryorguid` + 3900000, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param5`, `event_param6`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_param4`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`
FROM `smart_scripts` WHERE `source_type` = 1 AND `entryorguid` IN (SELECT `id` FROM `_dc_clone_srcg`);
UPDATE `smart_scripts` SET `action_param1` = `action_param1` + 3700000
WHERE `source_type` = 1 AND `entryorguid` IN (SELECT `id` + 3900000 FROM `_dc_clone_srcg`)
  AND `action_type` IN (12,33) AND `action_param1` IN (SELECT `id` FROM `_dc_clone_src`);
UPDATE `smart_scripts` SET `target_param1` = `target_param1` + 3700000
WHERE `source_type` = 1 AND `entryorguid` IN (SELECT `id` + 3900000 FROM `_dc_clone_srcg`)
  AND `target_type` IN (9,11,19) AND `target_param1` IN (SELECT `id` FROM `_dc_clone_src`);

-- --- finally: point the imported spawns at the clones ------------------------
-- Done LAST on purpose.  Every block above selects its source rows via
-- `WHERE ... IN (SELECT id FROM creature WHERE guid BETWEEN 15600000 AND
-- 15899999)`, so the spawn rows must still hold the RAW ids while they run.
-- Flipping them earlier makes every later block select nothing -- the file
-- would report success while cloning almost nothing.
UPDATE `creature` SET `id` = `id` + 3700000
WHERE `guid` BETWEEN 15600000 AND 15899999 AND `id` < 3700000
  AND EXISTS (SELECT 1 FROM `creature_template` t WHERE t.`entry` = `creature`.`id` + 3700000);

UPDATE `gameobject` SET `id` = `id` + 3900000
WHERE `guid` BETWEEN 15600000 AND 15899999 AND `id` < 3900000
  AND EXISTS (SELECT 1 FROM `gameobject_template` t WHERE t.`entry` = `gameobject`.`id` + 3900000);

-- --- drop the scratch tables -------------------------------------------------
DROP TABLE IF EXISTS `_dc_clone_src`;
DROP TABLE IF EXISTS `_dc_clone_srcg`;
DROP TABLE IF EXISTS `_dc_clone_al`;

