-- ---------------------------------------------------------------------------
-- 167  Hyjal round-35 -- clone the border-zone quests
-- ---------------------------------------------------------------------------
-- Finishes what 166_ started.  166_ gave map 750 private copies of the stock
-- NPCs and objects (creature +3,700,000 / gameobject +3,900,000) but left the
-- quests shared, so the cloned NPCs offered nothing.  This clones the quests
-- too, at raw + 100,000.
--
--     194 quests, raw ids 28..13,075  ->  100,028..113,075
--
-- The window 100,000-199,999 was verified completely empty first: 175 quests
-- exist above 100,000, but every one is beyond 199,999 (up to 920,101).
--
-- CHAIN REMAPPING is the part that needs care.  PrevQuestID, NextQuestID,
-- ExclusiveGroup and BreadcrumbForQuestId each hold a quest id, and each is
-- rewritten ONLY when it points at a quest that is also in the cloned set:
--   * inside the set  -> +100,000, so the chain stays intact inside map 750
--   * outside the set -> LEFT RAW, because it points at a real prerequisite the
--     player earns elsewhere.  Blanking those would orphan chains; offsetting
--     them blindly would point at quests that do not exist.
--
-- ExclusiveGroup is the subtle one: it is a GROUP id (conventionally equal to
-- one member's quest id) whose SIGN carries meaning -- negative means "only one
-- of this group may be taken", positive means "all of them".  It is therefore
-- remapped by MAGNITUDE with the sign preserved.  Getting the sign wrong
-- inverts the rule for every quest in the group.
--
-- SOURCE SET is derived from the CLONED templates (entry - offset), not from
-- the spawn rows: 166_ already repointed those, so the raw ids are gone from
-- `creature`/`gameobject` and reading them would clone zero quests while
-- appearing to succeed.
--
-- quest_poi is rewritten to MapID 750 / WorldMapAreaId 1216 so the markers land
-- on the DC map.  The raw quests keep their own POI untouched.
--
-- Generated by HyjalCata/tools/gen_border_zone_quests.py.  Idempotent.
-- ---------------------------------------------------------------------------

-- --- quest_template ----------------------------------------------------------
DELETE FROM `quest_template` WHERE `ID` BETWEEN 100000 AND 199999;

-- SELECT * is safe here and preferable: quest_template has ~90 columns that
-- differ between forks, and only `ID` needs changing.  Every other clone block
-- in 166_/167_ uses an explicit list because it rewrites interior columns.
CREATE TEMPORARY TABLE `_qt_clone` AS SELECT * FROM `quest_template` WHERE `ID` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));
UPDATE `_qt_clone` SET `ID` = `ID` + 100000;
INSERT INTO `quest_template` SELECT * FROM `_qt_clone`;
DROP TEMPORARY TABLE `_qt_clone`;

-- Mail templates are ONE quest per template, first registration wins -- a clone
-- keeping the id either loses its own mail (cosmetic) or, when it registers
-- first, strips the mail reward from the STOCK quest (quest 5128 lost its
-- Everlook letter this way).  Clones reward without the follow-up mail.  The
-- mail fields live in quest_template_addon on this fork, and the column is
-- `RewardMailTemplateID` -- capital ID, unlike the worldserver's log message.
UPDATE `quest_template_addon` SET `RewardMailTemplateID` = 0, `RewardMailDelay` = 0
WHERE `ID` BETWEEN 100000 AND 199999 AND `RewardMailTemplateID` <> 0;

-- objectives that name a creature or object we cloned should point at the clone
UPDATE `quest_template` SET `RequiredNpcOrGo1` = `RequiredNpcOrGo1` + 3700000
WHERE `ID` BETWEEN 100000 AND 199999 AND `RequiredNpcOrGo1` > 0 AND `RequiredNpcOrGo1` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999);
UPDATE `quest_template` SET `RequiredNpcOrGo2` = `RequiredNpcOrGo2` + 3700000
WHERE `ID` BETWEEN 100000 AND 199999 AND `RequiredNpcOrGo2` > 0 AND `RequiredNpcOrGo2` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999);
UPDATE `quest_template` SET `RequiredNpcOrGo3` = `RequiredNpcOrGo3` + 3700000
WHERE `ID` BETWEEN 100000 AND 199999 AND `RequiredNpcOrGo3` > 0 AND `RequiredNpcOrGo3` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999);
UPDATE `quest_template` SET `RequiredNpcOrGo4` = `RequiredNpcOrGo4` + 3700000
WHERE `ID` BETWEEN 100000 AND 199999 AND `RequiredNpcOrGo4` > 0 AND `RequiredNpcOrGo4` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999);
-- a NEGATIVE RequiredNpcOrGo is a gameobject id, stored negated
UPDATE `quest_template` SET `RequiredNpcOrGo1` = `RequiredNpcOrGo1` - 3900000
WHERE `ID` BETWEEN 100000 AND 199999 AND `RequiredNpcOrGo1` < 0 AND -`RequiredNpcOrGo1` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000);
UPDATE `quest_template` SET `RequiredNpcOrGo2` = `RequiredNpcOrGo2` - 3900000
WHERE `ID` BETWEEN 100000 AND 199999 AND `RequiredNpcOrGo2` < 0 AND -`RequiredNpcOrGo2` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000);
UPDATE `quest_template` SET `RequiredNpcOrGo3` = `RequiredNpcOrGo3` - 3900000
WHERE `ID` BETWEEN 100000 AND 199999 AND `RequiredNpcOrGo3` < 0 AND -`RequiredNpcOrGo3` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000);
UPDATE `quest_template` SET `RequiredNpcOrGo4` = `RequiredNpcOrGo4` - 3900000
WHERE `ID` BETWEEN 100000 AND 199999 AND `RequiredNpcOrGo4` < 0 AND -`RequiredNpcOrGo4` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000);

-- --- quest_template_addon + chain remap --------------------------------------
DELETE FROM `quest_template_addon` WHERE `ID` BETWEEN 100000 AND 199999;
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`)
SELECT `ID` + 100000, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `BreadcrumbForQuestId`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`
FROM `quest_template_addon` WHERE `ID` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

-- Only rewrite a link when its target is also cloned; otherwise it names a real
-- prerequisite from elsewhere in the world and must stay raw.
UPDATE `quest_template_addon` SET `PrevQuestID` = `PrevQuestID` + 100000
WHERE `ID` BETWEEN 100000 AND 199999 AND `PrevQuestID` > 0 AND `PrevQuestID` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));
UPDATE `quest_template_addon` SET `PrevQuestID` = `PrevQuestID` - 100000
WHERE `ID` BETWEEN 100000 AND 199999 AND `PrevQuestID` < 0 AND -`PrevQuestID` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));
UPDATE `quest_template_addon` SET `NextQuestID` = `NextQuestID` + 100000
WHERE `ID` BETWEEN 100000 AND 199999 AND `NextQuestID` > 0 AND `NextQuestID` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));
UPDATE `quest_template_addon` SET `BreadcrumbForQuestId` = `BreadcrumbForQuestId` + 100000
WHERE `ID` BETWEEN 100000 AND 199999 AND `BreadcrumbForQuestId` > 0 AND `BreadcrumbForQuestId` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

-- ExclusiveGroup: remap by MAGNITUDE, keep the SIGN.  Negative = "only one of
-- the group", positive = "all of them" -- flipping it would invert the rule.
UPDATE `quest_template_addon` SET `ExclusiveGroup` = `ExclusiveGroup` + 100000
WHERE `ID` BETWEEN 100000 AND 199999 AND `ExclusiveGroup` > 0 AND `ExclusiveGroup` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));
UPDATE `quest_template_addon` SET `ExclusiveGroup` = `ExclusiveGroup` - 100000
WHERE `ID` BETWEEN 100000 AND 199999 AND `ExclusiveGroup` < 0 AND -`ExclusiveGroup` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

-- --- quest text / emote tables -----------------------------------------------
DELETE FROM `quest_details` WHERE `ID` BETWEEN 100000 AND 199999;
INSERT INTO `quest_details` (`ID`, `Emote1`, `Emote2`, `Emote3`, `Emote4`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `EmoteDelay4`, `VerifiedBuild`)
SELECT `ID` + 100000, `Emote1`, `Emote2`, `Emote3`, `Emote4`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `EmoteDelay4`, `VerifiedBuild`
FROM `quest_details` WHERE `ID` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

DELETE FROM `quest_offer_reward` WHERE `ID` BETWEEN 100000 AND 199999;
INSERT INTO `quest_offer_reward` (`ID`, `Emote1`, `Emote2`, `Emote3`, `Emote4`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `EmoteDelay4`, `RewardText`, `VerifiedBuild`)
SELECT `ID` + 100000, `Emote1`, `Emote2`, `Emote3`, `Emote4`, `EmoteDelay1`, `EmoteDelay2`, `EmoteDelay3`, `EmoteDelay4`, `RewardText`, `VerifiedBuild`
FROM `quest_offer_reward` WHERE `ID` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

DELETE FROM `quest_request_items` WHERE `ID` BETWEEN 100000 AND 199999;
INSERT INTO `quest_request_items` (`ID`, `EmoteOnComplete`, `EmoteOnIncomplete`, `CompletionText`, `VerifiedBuild`)
SELECT `ID` + 100000, `EmoteOnComplete`, `EmoteOnIncomplete`, `CompletionText`, `VerifiedBuild`
FROM `quest_request_items` WHERE `ID` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

-- --- questgiver links -- both sides remapped ---------------------------------
DELETE FROM `creature_queststarter` WHERE `quest` BETWEEN 100000 AND 199999;
INSERT INTO `creature_queststarter` (`id`,`quest`)
SELECT `id` + 3700000, `quest` + 100000 FROM `creature_queststarter`
WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999) AND `quest` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

DELETE FROM `creature_questender` WHERE `quest` BETWEEN 100000 AND 199999;
INSERT INTO `creature_questender` (`id`,`quest`)
SELECT `id` + 3700000, `quest` + 100000 FROM `creature_questender`
WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999) AND `quest` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

DELETE FROM `gameobject_queststarter` WHERE `quest` BETWEEN 100000 AND 199999;
INSERT INTO `gameobject_queststarter` (`id`,`quest`)
SELECT `id` + 3900000, `quest` + 100000 FROM `gameobject_queststarter`
WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000) AND `quest` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

DELETE FROM `gameobject_questender` WHERE `quest` BETWEEN 100000 AND 199999;
INSERT INTO `gameobject_questender` (`id`,`quest`)
SELECT `id` + 3900000, `quest` + 100000 FROM `gameobject_questender`
WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000) AND `quest` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

-- --- quest POI -- retargeted at map 750 / WorldMapArea 1216 ------------------
DELETE FROM `quest_poi_points` WHERE `QuestID` BETWEEN 100000 AND 199999;
DELETE FROM `quest_poi` WHERE `QuestID` BETWEEN 100000 AND 199999;

INSERT INTO `quest_poi`
  (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`)
SELECT `QuestID` + 100000, `id`, `ObjectiveIndex`, 750, 1216, `Floor`, `Priority`, `Flags`, 0
FROM `quest_poi` WHERE `QuestID` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`)
SELECT `QuestID` + 100000, `Idx1`, `Idx2`, `X`, `Y`, 0
FROM `quest_poi_points` WHERE `QuestID` IN (SELECT DISTINCT `quest` FROM `creature_queststarter` WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `creature_questender`   WHERE `id` IN (SELECT `entry` - 3700000 FROM `creature_template` WHERE `entry` BETWEEN 3700000 AND 3799999)
  UNION SELECT DISTINCT `quest` FROM `gameobject_queststarter` WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000)
  UNION SELECT DISTINCT `quest` FROM `gameobject_questender`   WHERE `id` IN (SELECT `entry` - 3900000 FROM `gameobject_template` WHERE `entry` >= 3900000));

-- --- verification -- all of these should return zero rows --------------------
-- 1. a cloned quest whose Prev/Next points at a quest that does not exist
--    SELECT a.ID, a.PrevQuestID, a.NextQuestID FROM quest_template_addon a
--    WHERE a.ID BETWEEN 100000 AND 199999
--      AND ((a.PrevQuestID > 0 AND NOT EXISTS (SELECT 1 FROM quest_template q WHERE q.ID = a.PrevQuestID))
--        OR (a.NextQuestID > 0 AND NOT EXISTS (SELECT 1 FROM quest_template q WHERE q.ID = a.NextQuestID)));
--
-- 2. a cloned quest with no giver and no ender
--    SELECT q.ID FROM quest_template q WHERE q.ID BETWEEN 100000 AND 199999
--      AND NOT EXISTS (SELECT 1 FROM creature_queststarter s WHERE s.quest = q.ID)
--      AND NOT EXISTS (SELECT 1 FROM creature_questender e WHERE e.quest = q.ID)
--      AND NOT EXISTS (SELECT 1 FROM gameobject_queststarter s WHERE s.quest = q.ID)
--      AND NOT EXISTS (SELECT 1 FROM gameobject_questender e WHERE e.quest = q.ID);
--
-- 3. an ExclusiveGroup whose sign flipped (magnitude moved but sign did not)
--    SELECT ID, ExclusiveGroup FROM quest_template_addon
--    WHERE ID BETWEEN 100000 AND 199999 AND ExclusiveGroup <> 0
--      AND SIGN(ExclusiveGroup) <> (SELECT SIGN(o.ExclusiveGroup) FROM quest_template_addon o
--                                   WHERE o.ID = quest_template_addon.ID - 100000);

