-- ---------------------------------------------------------------------------
-- 243  Map 750 -- zone-themed leveling sets (400708-400782)
-- ---------------------------------------------------------------------------
-- The 400xxx ladder is Hyjal-branded, which reads wrong dropping in Darkshore
-- or Winterspring. Five 15-piece THEMED sets fix that -- one per leveling
-- zone, stat-cloned from the zone's band-appropriate ladder tier (so power,
-- ItemLevel, Quality and the 238_-retuned RequiredLevel carry over verbatim)
-- with zone-flavored names and Cata/newer display ids from the downported
-- appearance corpus:
--
--   400708-400722  Tidewatcher's          Darkshore 4929     (tier-1 stats)
--   400723-400737  Bilgewater Profiteer's Azshara 4930       (tier-1 stats)
--   400738-400752  Ashenvale Skirmisher's Ashenvale 4931     (tier-2 stats)
--   400753-400767  Emerald Warden's       Felwood 4927       (tier-3 stats)
--   400768-400782  Frostsaber Stalker's   Winterspring 4926  (tier-3 stats)
--
-- Ladder ItemLevels (300/332/372) land every piece inside the item-upgrade
-- system's tier-4 window (300-411) -> token-upgradeable out of the box (see
-- 244_). 237_ wires these into the per-zone drop references; Hyjal itself
-- keeps the original epic ladder (already Hyjal-themed).
--
-- Slot note: the ladder tiers are NOT slot-parallel -- tier 1 = wrist/waist/
-- hands, tier 2 = feet/shoulder/legs, tier 3 = wrist/hands/waist. Each set
-- clones its own tier's layout, so slot coverage varies by zone on purpose;
-- the re-banded native Cata drops (236_) fill the remaining slots.
--
-- Generated by Custom/Documentation/scripts/gen_map750_themed_sets.py from
-- data/zone_themed_sets.csv -- edit the CSV and re-run, never this file.
-- Run AFTER 238_ (RequiredLevel retune must be baked in before cloning).
-- Idempotent (DELETE + re-clone).
-- ---------------------------------------------------------------------------

DELETE FROM `item_template` WHERE `entry` BETWEEN 400708 AND 400782;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400041;
UPDATE `tmp_dc750_item` SET `entry` = 400708, `name` = 'Tidewatcher''s Bindings',
    `displayid` = 169563, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400042;
UPDATE `tmp_dc750_item` SET `entry` = 400709, `name` = 'Tidewatcher''s Cuffs',
    `displayid` = 656061, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400043;
UPDATE `tmp_dc750_item` SET `entry` = 400710, `name` = 'Tidewatcher''s Wristguards',
    `displayid` = 179086, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400044;
UPDATE `tmp_dc750_item` SET `entry` = 400711, `name` = 'Tidewatcher''s Bracers',
    `displayid` = 111180, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400045;
UPDATE `tmp_dc750_item` SET `entry` = 400712, `name` = 'Tidewatcher''s Vambraces',
    `displayid` = 180205, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400046;
UPDATE `tmp_dc750_item` SET `entry` = 400713, `name` = 'Tidewatcher''s Cord',
    `displayid` = 667889, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400047;
UPDATE `tmp_dc750_item` SET `entry` = 400714, `name` = 'Tidewatcher''s Sash',
    `displayid` = 676560, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400048;
UPDATE `tmp_dc750_item` SET `entry` = 400715, `name` = 'Tidewatcher''s Belt',
    `displayid` = 175868, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400049;
UPDATE `tmp_dc750_item` SET `entry` = 400716, `name` = 'Tidewatcher''s Girdle',
    `displayid` = 145029, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400050;
UPDATE `tmp_dc750_item` SET `entry` = 400717, `name` = 'Tidewatcher''s Greatbelt',
    `displayid` = 668707, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400051;
UPDATE `tmp_dc750_item` SET `entry` = 400718, `name` = 'Tidewatcher''s Gloves',
    `displayid` = 169564, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400052;
UPDATE `tmp_dc750_item` SET `entry` = 400719, `name` = 'Tidewatcher''s Handwraps',
    `displayid` = 656060, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400053;
UPDATE `tmp_dc750_item` SET `entry` = 400720, `name` = 'Tidewatcher''s Grips',
    `displayid` = 109537, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400054;
UPDATE `tmp_dc750_item` SET `entry` = 400721, `name` = 'Tidewatcher''s Gauntlets',
    `displayid` = 180658, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400055;
UPDATE `tmp_dc750_item` SET `entry` = 400722, `name` = 'Tidewatcher''s Crushers',
    `displayid` = 166387, `description` = 'Tidewatcher''s regalia, issued to the coast wardens of Lor''danel.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400041;
UPDATE `tmp_dc750_item` SET `entry` = 400723, `name` = 'Bilgewater Profiteer''s Bindings',
    `displayid` = 124540, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400042;
UPDATE `tmp_dc750_item` SET `entry` = 400724, `name` = 'Bilgewater Profiteer''s Cuffs',
    `displayid` = 194620, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400043;
UPDATE `tmp_dc750_item` SET `entry` = 400725, `name` = 'Bilgewater Profiteer''s Wristguards',
    `displayid` = 59741, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400044;
UPDATE `tmp_dc750_item` SET `entry` = 400726, `name` = 'Bilgewater Profiteer''s Bracers',
    `displayid` = 75065, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400045;
UPDATE `tmp_dc750_item` SET `entry` = 400727, `name` = 'Bilgewater Profiteer''s Vambraces',
    `displayid` = 713961, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400046;
UPDATE `tmp_dc750_item` SET `entry` = 400728, `name` = 'Bilgewater Profiteer''s Cord',
    `displayid` = 5838, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400047;
UPDATE `tmp_dc750_item` SET `entry` = 400729, `name` = 'Bilgewater Profiteer''s Sash',
    `displayid` = 737869, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400048;
UPDATE `tmp_dc750_item` SET `entry` = 400730, `name` = 'Bilgewater Profiteer''s Belt',
    `displayid` = 138590, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400049;
UPDATE `tmp_dc750_item` SET `entry` = 400731, `name` = 'Bilgewater Profiteer''s Girdle',
    `displayid` = 696032, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400050;
UPDATE `tmp_dc750_item` SET `entry` = 400732, `name` = 'Bilgewater Profiteer''s Greatbelt',
    `displayid` = 686108, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400051;
UPDATE `tmp_dc750_item` SET `entry` = 400733, `name` = 'Bilgewater Profiteer''s Gloves',
    `displayid` = 124542, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400052;
UPDATE `tmp_dc750_item` SET `entry` = 400734, `name` = 'Bilgewater Profiteer''s Handwraps',
    `displayid` = 733346, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400053;
UPDATE `tmp_dc750_item` SET `entry` = 400735, `name` = 'Bilgewater Profiteer''s Grips',
    `displayid` = 184207, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400054;
UPDATE `tmp_dc750_item` SET `entry` = 400736, `name` = 'Bilgewater Profiteer''s Gauntlets',
    `displayid` = 87531, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400055;
UPDATE `tmp_dc750_item` SET `entry` = 400737, `name` = 'Bilgewater Profiteer''s Crushers',
    `displayid` = 75438, `description` = 'Bilgewater Cartel field kit. The cartel deducts losses from your pay.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400056;
UPDATE `tmp_dc750_item` SET `entry` = 400738, `name` = 'Ashenvale Skirmisher''s Slippers',
    `displayid` = 164872, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400057;
UPDATE `tmp_dc750_item` SET `entry` = 400739, `name` = 'Ashenvale Skirmisher''s Treads',
    `displayid` = 677927, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400058;
UPDATE `tmp_dc750_item` SET `entry` = 400740, `name` = 'Ashenvale Skirmisher''s Footpads',
    `displayid` = 176244, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400059;
UPDATE `tmp_dc750_item` SET `entry` = 400741, `name` = 'Ashenvale Skirmisher''s Sabatons',
    `displayid` = 667627, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400060;
UPDATE `tmp_dc750_item` SET `entry` = 400742, `name` = 'Ashenvale Skirmisher''s Warboots',
    `displayid` = 182028, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400061;
UPDATE `tmp_dc750_item` SET `entry` = 400743, `name` = 'Ashenvale Skirmisher''s Mantle',
    `displayid` = 171168, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400062;
UPDATE `tmp_dc750_item` SET `entry` = 400744, `name` = 'Ashenvale Skirmisher''s Amice',
    `displayid` = 673375, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400063;
UPDATE `tmp_dc750_item` SET `entry` = 400745, `name` = 'Ashenvale Skirmisher''s Spaulders',
    `displayid` = 168894, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400064;
UPDATE `tmp_dc750_item` SET `entry` = 400746, `name` = 'Ashenvale Skirmisher''s Pauldrons',
    `displayid` = 666854, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400065;
UPDATE `tmp_dc750_item` SET `entry` = 400747, `name` = 'Ashenvale Skirmisher''s Shoulderguards',
    `displayid` = 181987, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400066;
UPDATE `tmp_dc750_item` SET `entry` = 400748, `name` = 'Ashenvale Skirmisher''s Leggings',
    `displayid` = 164874, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400067;
UPDATE `tmp_dc750_item` SET `entry` = 400749, `name` = 'Ashenvale Skirmisher''s Trousers',
    `displayid` = 679061, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400068;
UPDATE `tmp_dc750_item` SET `entry` = 400750, `name` = 'Ashenvale Skirmisher''s Legguards',
    `displayid` = 729572, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400069;
UPDATE `tmp_dc750_item` SET `entry` = 400751, `name` = 'Ashenvale Skirmisher''s Legplates',
    `displayid` = 193228, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400070;
UPDATE `tmp_dc750_item` SET `entry` = 400752, `name` = 'Ashenvale Skirmisher''s Greaves',
    `displayid` = 669008, `description` = 'Skirmisher''s gear from the contested groves of Ashenvale.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400083;
UPDATE `tmp_dc750_item` SET `entry` = 400753, `name` = 'Emerald Warden''s Bindings',
    `displayid` = 162731, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400084;
UPDATE `tmp_dc750_item` SET `entry` = 400754, `name` = 'Emerald Warden''s Cuffs',
    `displayid` = 661622, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400085;
UPDATE `tmp_dc750_item` SET `entry` = 400755, `name` = 'Emerald Warden''s Wristguards',
    `displayid` = 181098, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400086;
UPDATE `tmp_dc750_item` SET `entry` = 400756, `name` = 'Emerald Warden''s Bracers',
    `displayid` = 162189, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400087;
UPDATE `tmp_dc750_item` SET `entry` = 400757, `name` = 'Emerald Warden''s Vambraces',
    `displayid` = 140191, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400088;
UPDATE `tmp_dc750_item` SET `entry` = 400758, `name` = 'Emerald Warden''s Gloves',
    `displayid` = 159489, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400089;
UPDATE `tmp_dc750_item` SET `entry` = 400759, `name` = 'Emerald Warden''s Handwraps',
    `displayid` = 661623, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400090;
UPDATE `tmp_dc750_item` SET `entry` = 400760, `name` = 'Emerald Warden''s Grips',
    `displayid` = 688454, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400091;
UPDATE `tmp_dc750_item` SET `entry` = 400761, `name` = 'Emerald Warden''s Gauntlets',
    `displayid` = 103558, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400092;
UPDATE `tmp_dc750_item` SET `entry` = 400762, `name` = 'Emerald Warden''s Crushers',
    `displayid` = 672511, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400093;
UPDATE `tmp_dc750_item` SET `entry` = 400763, `name` = 'Emerald Warden''s Cord',
    `displayid` = 661619, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400094;
UPDATE `tmp_dc750_item` SET `entry` = 400764, `name` = 'Emerald Warden''s Sash',
    `displayid` = 130756, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400095;
UPDATE `tmp_dc750_item` SET `entry` = 400765, `name` = 'Emerald Warden''s Belt',
    `displayid` = 688499, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400096;
UPDATE `tmp_dc750_item` SET `entry` = 400766, `name` = 'Emerald Warden''s Girdle',
    `displayid` = 714332, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400097;
UPDATE `tmp_dc750_item` SET `entry` = 400767, `name` = 'Emerald Warden''s Greatbelt',
    `displayid` = 140419, `description` = 'Warden''s vestments, sap-stained from the fight for Felwood.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400083;
UPDATE `tmp_dc750_item` SET `entry` = 400768, `name` = 'Frostsaber Stalker''s Bindings',
    `displayid` = 151200, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400084;
UPDATE `tmp_dc750_item` SET `entry` = 400769, `name` = 'Frostsaber Stalker''s Cuffs',
    `displayid` = 120066, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400085;
UPDATE `tmp_dc750_item` SET `entry` = 400770, `name` = 'Frostsaber Stalker''s Wristguards',
    `displayid` = 659279, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400086;
UPDATE `tmp_dc750_item` SET `entry` = 400771, `name` = 'Frostsaber Stalker''s Bracers',
    `displayid` = 659640, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400087;
UPDATE `tmp_dc750_item` SET `entry` = 400772, `name` = 'Frostsaber Stalker''s Vambraces',
    `displayid` = 181702, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400088;
UPDATE `tmp_dc750_item` SET `entry` = 400773, `name` = 'Frostsaber Stalker''s Gloves',
    `displayid` = 97536, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400089;
UPDATE `tmp_dc750_item` SET `entry` = 400774, `name` = 'Frostsaber Stalker''s Handwraps',
    `displayid` = 182996, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400090;
UPDATE `tmp_dc750_item` SET `entry` = 400775, `name` = 'Frostsaber Stalker''s Grips',
    `displayid` = 144654, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400091;
UPDATE `tmp_dc750_item` SET `entry` = 400776, `name` = 'Frostsaber Stalker''s Gauntlets',
    `displayid` = 172441, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400092;
UPDATE `tmp_dc750_item` SET `entry` = 400777, `name` = 'Frostsaber Stalker''s Crushers',
    `displayid` = 659641, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400093;
UPDATE `tmp_dc750_item` SET `entry` = 400778, `name` = 'Frostsaber Stalker''s Cord',
    `displayid` = 669185, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400094;
UPDATE `tmp_dc750_item` SET `entry` = 400779, `name` = 'Frostsaber Stalker''s Sash',
    `displayid` = 144296, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400095;
UPDATE `tmp_dc750_item` SET `entry` = 400780, `name` = 'Frostsaber Stalker''s Belt',
    `displayid` = 48282, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400096;
UPDATE `tmp_dc750_item` SET `entry` = 400781, `name` = 'Frostsaber Stalker''s Girdle',
    `displayid` = 661281, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;
CREATE TEMPORARY TABLE `tmp_dc750_item` AS
SELECT * FROM `item_template` WHERE `entry` = 400097;
UPDATE `tmp_dc750_item` SET `entry` = 400782, `name` = 'Frostsaber Stalker''s Greatbelt',
    `displayid` = 181705, `description` = 'Stalker''s furs, cured against Winterspring''s endless frost.';
INSERT INTO `item_template` SELECT * FROM `tmp_dc750_item`;

DROP TEMPORARY TABLE IF EXISTS `tmp_dc750_item`;

-- ---------------------------------------------------------------------------
-- Trailer -- verification (expect 75 rows, displayid > 0, ilvl 300/332/372)
-- ---------------------------------------------------------------------------
-- SELECT COUNT(*), MIN(ItemLevel), MAX(ItemLevel) FROM item_template
-- WHERE entry BETWEEN 400708 AND 400782;
-- SELECT entry, name, displayid, RequiredLevel FROM item_template
-- WHERE entry BETWEEN 400708 AND 400782 ORDER BY entry;
