-- ---------------------------------------------------------------------------
-- 259  Map 750 -- 17 quest objectives left pointing at un-cloned raw Cata ids
-- ---------------------------------------------------------------------------
-- 17 quests on map 750 name a RequiredNpcOrGo that exists nowhere on our side,
-- so every one logs "quest can't be done" and is genuinely uncompletable. The
-- cause is the same guarded-remap gap that MoltenFront/03_ hit: the +3,600,000
-- sweep only rewrites an objective when the clone already exists, and silently
-- leaves it raw when it does not.
--
-- Quest 14383 "The Terrible Tinkers of the Ruined Reaches" is the proof, not an
-- inference: objectives 2 and 3 are already 3636385 / 3636384 while objective 1
-- is still raw 36407. Quest 24430 shows the same split (3636890 offset, 36906
-- raw). The sweep ran; it just skipped what it could not resolve.
--
-- Affected quests, by zone --
--   Azshara (16)     14226 Trouble Under Foot .............. 35628
--                    14310 Segmentation Fault: Core Dumped . 36096
--                    14377 Befriending Giants ............... 36333
--                    14383 The Terrible Tinkers ............. 36407
--                    14385 Azsharite Experiment One ......... 36420
--                    14388 Azsharite Experiment Two ......... 36438
--                    14484 Head of the Snake ................ 36822
--                    14485 Ticker Required .................. 36843 (clone EXISTS)
--                    24430 Blacken the Skies ................ 36906
--                    26337 Beating the Market ............... 42798
--                    26374 Ready the Ground Troops .......... 42893
--   Ashenvale (331)  13628 Got Wood? ....................... 33374
--                    13886 Vortex ........................... 34333
--                    13935 Defend the Tree! ................. 32856
--                    13947 Blastranaar! ..................... 34494, 34492
--                    13980 They're Out There! ............... 34603
--   Stonetalon (406) 25622 Burn, Baby, Burn! ............... 40957
--
-- BAND. +3,600,000, which is the Cata band on this map -- confirmed by the two
-- already-offset objectives above and by 3636843 Runestone Bunny, which is live
-- with 8 spawns. All 17 target ids were checked free before writing.
--
-- 9 of the 17 are 0-spawn quest-credit markers in source too (34333, 35628,
-- 36096, 36333, 36420, 36438, 36906, 42798, 42893). That is normal for this
-- content -- credit is granted by script, nothing is ever placed -- so they are
-- template-only here as well and that is the finished state, not a gap.
--
-- SPAWNS ARE NOT PLACED BY THIS FILE, deliberately. The remaining 8 do have
-- source spawns (34494 Astranaar Sentinel x23, 34603 Ashenvale Assassin x17,
-- 40957 Warsong Stockpile x13, 32856 Warsong Invader x10, 34492 Astranaar
-- Thrower x4, 33374 Brutusk x1, 36407 Bingham Gadgetspring x1, 36822 Lord
-- Kassarus x1 -- 70 in all). Placing them needs a guid allocation and the
-- position discipline map 750 requires, which is its own round; this file fixes
-- the logged reference errors and stops there. Note it plainly: after this the
-- objectives resolve and the boot log goes quiet, but those 8 quests still have
-- nothing to kill until the spawn round runs.
--
-- MISSING CLIENT DISPLAYS -- record for that spawn round, do not "fix" here.
-- 7 of the 14 distinct displays are absent from the deployed
-- CreatureDisplayInfo.dbc (28,592 records): 28478 (32856), 28595 (33374), 29294
-- (34603), 29849 (36096), 30106 (36407), 30338 (36822), 32209 (40957). Six of
-- those belong to the spawn-bearing set, so they must be extracted before those
-- 70 spawns are placed or the NPCs render as nothing. This is the recurring
-- per-import display gap, not a new one. 29849 is the exception: 36096 is a
-- 0-spawn credit marker that is never rendered, so it is left as-is rather than
-- substituted.

-- ---- 1. spells 3636822 Lord Kassarus casts (PREREQUISITE for section 3) ----
-- SmartAIMgr discards any row whose spell is unknown, so without these the
-- clone would import with AIName='SmartAI' and immediately lose its cast row.
-- 69481 is pulled in by trigger closure over 69463. Its TRANS_DOOR effect names
-- gameobject 200301, cloned in section 2. Generated by
-- tools/gen_hyjal_spell_downport_r27.py -- re-run it rather than hand-editing.

DELETE FROM `spell_dbc` WHERE `ID` IN (69463,69481);

INSERT INTO `spell_dbc` VALUES
('69463','0','0','0','539033600','136','4','262144','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','14','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','134','20','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','32','0','0','0','0','0','0','0','0','0','0','0','0','0','0','53','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','69481','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Impaling Spine','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0'),
('69481','0','0','0','539033600','136','4','262144','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','9','0','0','0','0','0','134','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','2','144','76','5','0','0','0','0','0','47','90','0','0','0','0','87','87','87','16','16','0','8','8','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','90','3800301','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Impaling Spine Impact','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','2','0','0','1','1','1','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0');

-- ---- 2. the gameobject 69481 places --------------------------------------
-- "Impaling Spine", type 10 (goober). Display 7362 confirmed present in the
-- deployed GameObjectDisplayInfo.dbc. nelt names its Data columns in lower case
-- and carries faction/flags/questItem1-6 that this fork does not have, so the
-- column list is written out explicitly and those source-only columns dropped.
SET @OFF := 3600000;

DELETE FROM acore_world.`gameobject_template` WHERE `entry` = 3800301;

INSERT INTO acore_world.`gameobject_template`
(`entry`,`type`,`displayId`,`name`,`IconName`,`castBarCaption`,`unk1`,`size`,`Data0`,`Data1`,`Data2`,`Data3`,`Data4`,`Data5`,`Data6`,`Data7`,`Data8`,`Data9`,`Data10`,`Data11`,`Data12`,`Data13`,`Data14`,`Data15`,`Data16`,`Data17`,`Data18`,`Data19`,`Data20`,`Data21`,`Data22`,`Data23`,`AIName`,`ScriptName`,`VerifiedBuild`)
SELECT entry+@OFF, type, displayId, name, IconName, castBarCaption, unk1, size, data0, data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12, data13, data14, data15, data16, data17, data18, data19, data20, data21, data22, data23, '', '', 0
FROM nelt_world.gameobject_template WHERE entry = 200301;

-- ---- 3. the 17 objective creature templates --------------------------------
-- Source is nelt_world with MoltenFront/16_'s column mapping verbatim.
-- lootid/pickpocketloot/skinloot are forced to 0: only 34603 and 36407 carry
-- one in source (34603 / 36407) and neither table exists on our side, so
-- copying them would trade one boot-log error for another.
DELETE FROM acore_world.`creature_template` WHERE `entry` IN (3632856,3633374,3634333,3634492,3634494,3634603,3635628,3636096,3636333,3636407,3636420,3636438,3636822,3636906,3640957,3642798,3642893);

INSERT INTO acore_world.`creature_template`
(`entry`,`KillCredit1`,`KillCredit2`,`name`,`subname`,`IconName`,`gossip_menu_id`,`minlevel`,`maxlevel`,`exp`,`faction`,`npcflag`,`speed_walk`,`speed_run`,`speed_swim`,`speed_flight`,`rank`,`dmgschool`,`DamageModifier`,`BaseAttackTime`,`RangeAttackTime`,`BaseVariance`,`RangeVariance`,`unit_class`,`unit_flags`,`unit_flags2`,`dynamicflags`,`family`,`type`,`type_flags`,`lootid`,`pickpocketloot`,`skinloot`,`PetSpellDataId`,`VehicleId`,`mingold`,`maxgold`,`AIName`,`MovementType`,`HoverHeight`,`HealthModifier`,`ManaModifier`,`ArmorModifier`,`RacialLeader`,`movementId`,`RegenHealth`,`flags_extra`,`ScriptName`,`VerifiedBuild`)
SELECT entry+@OFF, IF(KillCredit1>0,KillCredit1+@OFF,0), IF(KillCredit2>0,KillCredit2+@OFF,0), name, subname, IconName, gossip_menu_id, minlevel, maxlevel, LEAST(exp,2), faction_A, npcflag, speed_walk, speed_run, speed_swim, speed_fly, `rank`, dmgschool, dmg_multiplier, baseattacktime, rangeattacktime, 1, 1, unit_class, unit_flags, unit_flags2, dynamicflags, family, type, type_flags, 0, 0, 0, PetSpellDataId, VehicleId, mingold, maxgold,
       AIName,
       MovementType, HoverHeight, Health_mod, Mana_mod, Armor_mod, RacialLeader, movementId, RegenHealth, flags_extra, '', 0
FROM nelt_world.creature_template
WHERE entry IN (32856,33374,34333,34492,34494,34603,35628,36096,36333,36407,36420,36438,36822,36906,40957,42798,42893);

DELETE FROM acore_world.`creature_template_model` WHERE `CreatureID` IN (3632856,3633374,3634333,3634492,3634494,3634603,3635628,3636096,3636333,3636407,3636420,3636438,3636822,3636906,3640957,3642798,3642893);

INSERT INTO acore_world.`creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
SELECT entry+@OFF, idx, mid, scale, 1, 0 FROM (
  SELECT entry, 0 idx, modelid1 mid, scale FROM nelt_world.creature_template WHERE entry IN (32856,33374,34333,34492,34494,34603,35628,36096,36333,36407,36420,36438,36822,36906,40957,42798,42893) AND modelid1>0
  UNION ALL SELECT entry, 1, modelid2, scale FROM nelt_world.creature_template WHERE entry IN (32856,33374,34333,34492,34494,34603,35628,36096,36333,36407,36420,36438,36822,36906,40957,42798,42893) AND modelid2>0
  UNION ALL SELECT entry, 2, modelid3, scale FROM nelt_world.creature_template WHERE entry IN (32856,33374,34333,34492,34494,34603,35628,36096,36333,36407,36420,36438,36822,36906,40957,42798,42893) AND modelid3>0
  UNION ALL SELECT entry, 3, modelid4, scale FROM nelt_world.creature_template WHERE entry IN (32856,33374,34333,34492,34494,34603,35628,36096,36333,36407,36420,36438,36822,36906,40957,42798,42893) AND modelid4>0
) m;

-- ---- 4. SmartAI rows for the three clones that claim AIName='SmartAI' ------
-- 34603 Ashenvale Assassin (16 rows), 36407 Bingham Gadgetspring (2), 36822
-- Lord Kassarus (3). The other fourteen carry AIName='' in source, so they owe
-- nothing. Importing the templates without these rows would manufacture three
-- fresh "has SmartAI enabled but no SmartAI entries" lines.
--
-- TWO REWRITES, both load-bearing:
--
--   * SMART_EVENT_RANGE (9). This fork's layout is
--     (min, max, repeatMin, repeatMax, rangeMin, rangeMax) and SmartScript.cpp
--     reads the distance from rangeMin/rangeMax -- event_param5/param6.
--     Upstream, and therefore nelt_world, puts the distance in param1/param2,
--     and nelt's smart_scripts table has no param5/param6 columns at all. A
--     verbatim copy leaves rangeMin = rangeMax = 0, so IsInRange(victim, 0, 0)
--     makes the row fire only on contact. All four of 34603's event-9 rows are
--     shifted: 5-30, 30-80, 0-10, 11-25 yards. This is the same fork divergence
--     that left 226 rows firing at contact in an earlier import.
--     Note what the shift does and does NOT touch: param3/param4 are repeatMin/
--     repeatMax on BOTH sides and are copied through unchanged, because
--     SMART_EVENT_RANGE's handler feeds them to ProcessTimedAction -- zeroing
--     them would make the row re-fire every tick. Params 1/2 are the fork-only
--     initial timer that InitTimer reads, seeded from the repeat window so the
--     first fire is paced like the rest. Events 67 and 74 share this exact
--     layout and are covered by the same CASE; every other event type in this
--     import matches upstream and is copied verbatim.
--   * action 33 KILLED_MONSTER param1 36822 -> 3636822, or killing Lord
--     Kassarus grants credit for a creature that does not exist. Params are
--     never touched by the +3,600,000 clone scheme; each import has to sweep
--     them by hand.
DELETE FROM acore_world.`smart_scripts` WHERE `source_type` = 0 AND `entryorguid` IN (3634603,3636407,3636822);

INSERT INTO acore_world.`smart_scripts`
(`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`event_param6`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`)
SELECT entryorguid+@OFF, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags,
       CASE WHEN event_type IN (9,67,74) THEN event_param3 ELSE event_param1 END,
       CASE WHEN event_type IN (9,67,74) THEN event_param4 ELSE event_param2 END,
       event_param3,
       event_param4,
       CASE WHEN event_type IN (9,67,74) THEN event_param1 ELSE 0 END,
       CASE WHEN event_type IN (9,67,74) THEN event_param2 ELSE 0 END,
       action_type,
       CASE WHEN action_type = 33 AND action_param1 = 36822 THEN 3636822 ELSE action_param1 END,
       action_param2, action_param3, action_param4, action_param5, action_param6,
       target_type, target_param1, target_param2, target_param3, target_param4,
       target_x, target_y, target_z, target_o,
       CONCAT('map750 objective clone - src ', entryorguid, '.', id)
FROM nelt_world.smart_scripts
WHERE source_type = 0 AND entryorguid IN (34603,36407,36822);

-- ---- 5. repoint the 18 objectives at the clones -----------------------------
-- Guarded on the clone existing, so re-running after a partial apply is safe
-- and nothing can be pointed at a template that is not there. 36843 is in the
-- list because its clone 3636843 has been live all along -- only quest 14485's
-- objective was left raw.
UPDATE acore_world.`quest_template` q
SET q.`RequiredNpcOrGo1` = q.`RequiredNpcOrGo1` + @OFF
WHERE q.`ID` IN (14226,14310,14377,14383,14385,14388,14484,14485,26337,26374,13628,13886,13935,13947,13980,25622)
  AND q.`RequiredNpcOrGo1` > 0
  AND EXISTS (SELECT 1 FROM acore_world.`creature_template` t WHERE t.`entry` = q.`RequiredNpcOrGo1` + @OFF)
  AND NOT EXISTS (SELECT 1 FROM acore_world.`creature_template` t WHERE t.`entry` = q.`RequiredNpcOrGo1`);

UPDATE acore_world.`quest_template` q
SET q.`RequiredNpcOrGo2` = q.`RequiredNpcOrGo2` + @OFF
WHERE q.`ID` IN (13947,24430)
  AND q.`RequiredNpcOrGo2` > 0
  AND EXISTS (SELECT 1 FROM acore_world.`creature_template` t WHERE t.`entry` = q.`RequiredNpcOrGo2` + @OFF)
  AND NOT EXISTS (SELECT 1 FROM acore_world.`creature_template` t WHERE t.`entry` = q.`RequiredNpcOrGo2`);

-- Verify after apply -- both must return 0 rows:
--   SELECT ID, RequiredNpcOrGo1, RequiredNpcOrGo2 FROM quest_template
--    WHERE ID IN (14226,14310,14377,14383,14385,14388,14484,14485,24430,26337,
--                 26374,13628,13886,13935,13947,13980,25622)
--      AND ((RequiredNpcOrGo1>0 AND NOT EXISTS (SELECT 1 FROM creature_template t
--             WHERE t.entry=RequiredNpcOrGo1))
--        OR (RequiredNpcOrGo2>0 AND NOT EXISTS (SELECT 1 FROM creature_template t
--             WHERE t.entry=RequiredNpcOrGo2)));
--   SELECT entry FROM creature_template WHERE entry IN (3634603,3636407,3636822)
--     AND AIName='SmartAI' AND NOT EXISTS (SELECT 1 FROM smart_scripts s
--       WHERE s.entryorguid=creature_template.entry AND s.source_type=0);
