-- ---------------------------------------------------------------------------
-- 260  Map 750 -- 38 missing items and the 16 loot tables 236 containers use
-- ---------------------------------------------------------------------------
-- Two symptoms, one gap. Every Cata quest container placed on map 750 --
-- Thorned Bloodcup x59, Iron Ingot x42, Smoked Meat x37, Iron Stockpile x28,
-- Chillwind Eggs x19, Ancient Debris Pile x17, Briaroot Brew x13, Serviceable
-- Arrow x13 and nine one-offs, 236 spawns across 17 templates -- names a
-- gameobject_loot_template that does not exist, so opening one yields nothing:
--
--     Table 'gameobject_loot_template' Entry 27108 does not exist but it is
--     used by Gameobject 3794997
--
-- and 16 quests report the same items missing from the other direction:
--
--     Quest 14201 has `RequiredItemId1` = 48525 but item with entry 48525 does
--     not exist, quest can't be done.
--
-- These are the Cata quest chains of Azshara, Ashenvale, Darkshore, Felwood and
-- Stonetalon. It is the same root cause the Darkshore and Felwood layers hit --
-- creatures, gameobjects and models imported, the item layer not -- and the
-- same fix shape as 189_ and 192_: pull the items from the real Cata client,
-- then the loot rows they unblock.
--
-- Section 1 also covers 22 items that are quest-side only and never sat in a
-- container (Bear's Paw Bundle, Troll Charm, Heart of Arkkoroc, Darla's
-- Grapple, ...), which is why 38 items serve 16 loot tables.
--
-- ITEM SOURCE. Cata client Item.db2 build 15601 for class / subclass /
-- material / displayid / inventorytype / sheath, retail ItemSparse for names
-- and descriptions so the strings are authentic rather than invented. All 38
-- resolved in both. Generated by tools/gen_map750_quest_items_r28.py.
--
-- DISPLAY IDs. 26 of the 38 Cata display ids already exist in the fork's
-- ItemDisplayInfo and are kept as-is. The other 12 (57681, 57951, 58373, 58437,
-- 59596, 60710, 61036, 67690, 68294, 72360, 73507, 75179) do not, and an
-- unknown display makes the core log "does not have a correct display id (N),
-- must be 0" -- so those are written as 0 rather than trading one boot-log
-- error for another. Those 12 items work; they just show no icon until the
-- ItemDisplayInfo rows and their BLPs are downported.
--
-- LOOT IDs STAY RAW. The 17 gameobject templates already point at the un-offset
-- Cata lootids (27108, 27446, 36131, ...) and that is this downport's
-- convention, not a bug -- so the tables are created at those raw ids and no
-- gameobject_template row is touched. cata_world's IsCurrency column has no
-- equivalent here and is 0 on all 16 rows anyway, so it is simply dropped.

-- ---- 1. the 38 items --------------------------------------------------------

DELETE FROM `item_template` WHERE `entry` IN (44868,44886,44887,44888,44967,45004,45025,45571,45572,45573,45678,46091,46310,46315,46365,46366,46387,46388,46543,46702,48128,48525,48921,49094,49365,49367,49629,49642,55152,56577,63513,63515,65890,65899,65900,65901,65902,68645);

INSERT INTO `item_template` (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `Flags`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `maxcount`, `stackable`, `ContainerSlots`, `bonding`, `description`, `startquest`, `Material`, `sheath`, `BagFamily`, `ScriptName`, `VerifiedBuild`) VALUES
(44868, 12, 0, 'Frenzied Cyclone Bracers', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 1, '', 0, 1, 0, 0, '', 0),
(44886, 12, 0, 'Fleetfoot''s Tailfeathers', 46608, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(44887, 12, 0, 'Blessed Herb Bundle', 57686, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(44888, 12, 0, 'Bear''s Paw Bundle', 18087, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(44967, 12, 0, 'Bottle of Wildfire', 15788, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 1, 0, 0, '', 0),
(45004, 12, 0, 'Serviceable Arrow', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 10, 0, 1, '', 0, 2, 0, 0, '', 0),
(45025, 12, 0, 'Bag of Bathran''s Hair', 34798, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'Already the leaves in the bag appear to be wilting. You should quickly get them to Orendil at Maestra''s Post.', 0, 4, 0, 0, '', 0),
(45571, 12, 0, 'Untainted Spirit', 8620, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 10, 0, 1, '', 0, 4, 0, 0, '', 0),
(45572, 12, 0, 'Power of Nature', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(45573, 12, 0, 'The Forest Heart', 58375, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'The corruption seems to be spreading to you. Better get it to Gnarl quickly!', 0, 4, 0, 0, '', 0),
(45678, 12, 0, 'Blood-Soaked Axe', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 10, 0, 1, '', 0, 0, 0, 0, '', 0),
(46091, 12, 0, 'Splintertree Post Report', 58367, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 0, 0, 0, '', 0),
(46310, 12, 0, 'Troll Charm', 27471, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, 'A subtle aura permeates the wood of this carving. It gives you a feeling of unease.', 0, 4, 0, 0, '', 0),
(46315, 12, 0, 'Thorned Bloodcup', 50453, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 10, 0, 1, '', 0, 0, 0, 0, '', 0),
(46365, 12, 0, 'Mystlash Hydra Blubber', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 10, 0, 1, '', 0, 0, 0, 0, '', 0),
(46366, 12, 0, 'Mystlash Hydra Oil', 37813, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 10, 0, 1, 'Used to fuel the Zoram''gar Lighthouse.', 0, 4, 0, 0, '', 0),
(46387, 12, 0, 'Ancient Slotted Device', 46851, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, 'Caked with eons of mud, the inner workings of this artifact are an enigma.', 0, 4, 0, 0, '', 0),
(46388, 12, 0, 'Buried Artifact Detector', 70849, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, 'A heavy, corroded battery wired sloppily to a large metal dish.', 0, 4, 0, 0, '', 0),
(46543, 12, 0, 'Laughing Sister''s Corpse', 19540, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 10, 10, 0, 1, 'They''re surprisingly light.', 0, 4, 0, 0, '', 0),
(46702, 0, 0, 'Ancient Device Fragment', 8925, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 5, 5, 0, 0, 'Crusted with eons of debris and recently fractured.', 0, 4, 0, 0, '', 0),
(48128, 12, 0, 'Mountainfoot Iron', 54472, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 1, 'Certified 88-percent impurity free.', 0, 4, 0, 0, '', 0),
(48525, 12, 0, 'Recovered Artifacts', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 1, 'Mud-crusted trinkets that have been buried for thousands of years.', 0, 4, 0, 0, '', 0),
(48921, 12, 0, 'Sarcen Stone', 32920, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'Perfectly smooth but for hundreds of tiny runes, somehow unblemished despite its age.', 0, 0, 0, 0, '', 0),
(49094, 12, 0, 'Keystone Shard', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 1, 'Perfectly smooth and icy cold to the touch.', 0, 4, 0, 0, '', 0),
(49365, 0, 5, 'Briaroot Brew', 50880, 1, 0, 1, 0, 0, 0, -1, -1, 3, 1, 0, 20, 0, 0, 'A pungent beverage with spicy overtones.', 0, 3, 0, 65536, '', 0),
(49367, 12, 0, 'Blackmaw Meeting Agenda', 7744, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 1, 1, 0, 1, 'The negotiations appear to be planned down to the minute, including a dinner menu.', 0, 0, 0, 0, '', 0),
(49629, 12, 0, 'Gob Squad Flare', 62821, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(49642, 12, 0, 'Heart of Arkkoroc', 54249, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, 'It''s just about as heavy as it looks.', 0, 4, 0, 0, '', 0),
(55152, 12, 0, 'Warsong Flame Thrower', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(56577, 12, 0, 'Crate of Spare Parts', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(63513, 12, 0, 'Darla''s Grapple', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(63515, 12, 0, 'Irontree Oilcan', 55088, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 20, 0, 1, 'Fill ''er up!', 0, 4, 0, 0, '', 0),
(65890, 12, 0, 'Chillwind Egg', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 50, 0, 1, 'It''s hard, like a rock.  Is this even an egg?', 0, 4, 0, 0, '', 0),
(65899, 12, 0, 'Essence of the Claw-Totem', 37222, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, 'The powder roils and sifts itself under its own power.', 0, 4, 0, 0, '', 0),
(65900, 12, 0, 'Essence of the Life-Totem', 33538, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, 'Light and fine, like powdered silk.', 0, 4, 0, 0, '', 0),
(65901, 12, 0, 'Essence of the Moon-Totem', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, 'It glows with an ephemeral energy.', 0, 4, 0, 0, '', 0),
(65902, 12, 0, 'Owlbeast Dreamcatcher', 21207, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, 'Dusty from ages of disuse.', 0, 4, 0, 0, '', 0),
(68645, 12, 0, 'Smoked Meat', 67991, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 10, 0, 1, '', 0, 4, 0, 0, '', 0);

-- ---- 2. the 16 container loot tables ----------------------------------------
-- One row each, copied unchanged from cata_world: Chance 100 with QuestRequired
-- 1 on 15 of the 16 (49365 "Briaroot Brew" is the one open drop). MinCount /
-- MaxCount are preserved -- 27445 Iron Stockpile gives 1-5 and 36131 Chillwind
-- Eggs 2-8, so flattening them to 1 would quietly change the quest pacing.
DELETE FROM acore_world.`gameobject_loot_template` WHERE `Entry` IN (26865,26872,27108,27445,27446,27447,27506,27554,27638,27645,36131,36132,36133,36134,36135,39381);

INSERT INTO acore_world.`gameobject_loot_template`
(`Entry`,`Item`,`Reference`,`Chance`,`QuestRequired`,`LootMode`,`GroupId`,`MinCount`,`MaxCount`,`Comment`)
SELECT Entry, Item, Reference, Chance, QuestRequired, LootMode, GroupId, MinCount, MaxCount,
       CONCAT('map750 Cata container - ', Entry)
FROM cata_world.gameobject_loot_template
WHERE Entry IN (26865,26872,27108,27445,27446,27447,27506,27554,27638,27645,36131,36132,36133,36134,36135,39381);

-- Verify after apply -- both must return 0 rows:
--   SELECT gt.entry, gt.name, gt.Data1 FROM gameobject_template gt
--     JOIN gameobject g ON g.id = gt.entry AND g.map = 750
--    WHERE gt.type = 3 AND gt.Data1 > 0
--      AND NOT EXISTS (SELECT 1 FROM gameobject_loot_template l
--                       WHERE l.Entry = gt.Data1);
--   SELECT Entry, Item FROM gameobject_loot_template WHERE Entry IN (26865,26872,27108,27445,27446,27447,27506,27554,27638,27645,36131,36132,36133,36134,36135,39381)
--     AND NOT EXISTS (SELECT 1 FROM item_template i WHERE i.entry = Item);
