-- ---------------------------------------------------------------------------
-- 262  Map 750 -- the 7 creature and 13 item displays 259_/260_ referenced
-- ---------------------------------------------------------------------------
-- 259_ cloned 17 Cata quest-objective creatures and 260_ created 38 quest items.
-- Between them they named 7 CreatureDisplayInfo ids and 13 ItemDisplayInfo ids
-- absent from this client, so the NPCs would render as nothing and 12 of the
-- items would carry displayid 0. Both headers said "record for the spawn round,
-- do not fix here" -- this is that round, and it turned out to be cheap.
--
-- EVERY UNDERLYING ASSET ALREADY SHIPS WITH THIS CLIENT. Checked, not assumed:
--
--   * 6 of the 7 creature displays reuse a CreatureModelData row we already
--     have. Cata model ids 51 / 56 / 182 / 1914 / 2555 are the same ids here --
--     our CSV just stores the path with the WotLK `.mdx` extension, which is
--     why a naive `.m2` path match reports them as absent. Only model 3394
--     (OrcCrate09) is new, and its .m2 is in common-2.MPQ.
--   * NagaLordMale.m2, KodoBeastPvPT2.m2, the two PVPKotoBeast textures and the
--     shoulder component LShoulder_Robe_B_04.m2 all resolve in
--     common / common-2 / expansion.
--   * All 12 item icons resolve too. Worth remembering WHERE: interface art on
--     this install lives in the enGB LOCALE archives (locale-enGB.MPQ and
--     patch-enGB.MPQ), NOT in the root ones. Searching only common/patch-N
--     reports every icon as missing -- including stock ones like INV_Sword_04 --
--     which is exactly the false negative that nearly sent this round off to
--     extract BLPs it already had.
--
-- So no model bake and no BLP extraction were needed: the whole fix is DBC rows.
-- The four client DBCs are ALREADY COMPILED AND DEPLOYED (patch-4 +
-- enGB/patch-enGB-3, both verified byte-identical, 0 ids lost against the
-- previous build). This file is the SERVER half.
--
-- Generated by tools/gen_map750_missing_displays_r29.py + its companion; the
-- overlay rows below are read back out of Custom/CSV DBC/*.csv so the SQL and
-- the compiled DBCs cannot drift apart.

-- ---- 1. creature_model_info -- gates whether the spawns LOAD ---------------
-- Without a row here the core rejects the spawn outright, which is a different
-- failure from the display being absent client-side (that only stops it
-- RENDERING). Both layers are needed; this is the third of the three.
-- Values come from nelt_world except where noted inline.
DELETE FROM acore_world.`creature_model_info` WHERE `DisplayID` IN (28478,28595,29294,29849,30106,30338,32209);

INSERT INTO acore_world.`creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`) VALUES
(28478,0.4092,1.65,0,0),  -- nelt
(28595,0.51,2.25,2,0),  -- nelt
(29294,0.306,1.5,1,0),  -- nelt row is 0/0; canonical NightElfFemale value, identical on displays 56/1543/1681/1700/1705
(29849,0.306,1.5,1,0),  -- nelt
(30106,0.3519,1.725,0,0),  -- nelt
(30338,1.05,5.25,0,0),  -- nelt row is 0/0; taken from display 35382, the other NagaLordMale at the same 3.5 scale
(32209,0.54,1.0,2,0);  -- nelt

-- ---- 2. the DBC overlay tables --------------------------------------------
-- These are the source the binary DBCs get rebuilt FROM, not a runtime merge --
-- the worldserver reads its own data/dbc, so keeping them in step matters for
-- the next rebuild, not for this boot.
--
-- 🔴 THE COLUMN NAMES ARE NOT THE CSV HEADERS. This block was generated from
-- Custom/CSV DBC/*.csv on the first pass and `creaturedisplayinfoextra_dbc`
-- failed with "Unknown column 'NPCItemDisplay_1'": the CSV says
-- NPCItemDisplay_1..11 with an underscore, the TABLE says NPCItemDisplay1..11
-- without one. The other three overlay tables happen to match their CSV headers
-- exactly, which is what made the mismatch easy to miss.
--
-- It failed SILENTLY in the worst way: mysql continues past the error, so the
-- DELETE above it had already run and every statement after it applied
-- normally. Nothing in the apply output stands out and the round looks clean.
-- Always verify overlay INSERTs landed by COUNTing the ids afterwards, and
-- always read the real schema (information_schema.COLUMNS) before generating a
-- column list from a CSV.

DELETE FROM acore_world.`creaturedisplayinfo_dbc` WHERE `ID` IN (28478,28595,29294,29849,30106,30338,32209);

INSERT INTO acore_world.`creaturedisplayinfo_dbc`
(`ID`,`ModelID`,`SoundID`,`ExtendedDisplayInfoID`,`CreatureModelScale`,`CreatureModelAlpha`,`TextureVariation_1`,`TextureVariation_2`,`TextureVariation_3`,`PortraitTextureName`,`BloodLevel`,`BloodID`,`NPCSoundID`,`ParticleColorID`,`CreatureGeosetData`,`ObjectEffectPackageID`) VALUES
(28478,51,0,18884,1.1,255,'','','','',1,0,60,0,0,0),
(28595,1914,0,0,1.5,255,'PVPKotoBeastSkinBlack','PVPKotoBeastEyeGlowViolet','','',1,0,0,0,0,0),
(29294,56,0,19371,1,255,'','','','',1,0,52,0,0,0),
(29849,56,0,19747,1,255,'','','','',1,0,53,0,0,0),
(30106,182,0,19950,1,255,'','','','',1,0,43,0,0,0),
(30338,2555,2457,0,3.5,255,'','','','',-1,0,0,0,0,0),
(32209,3394,0,0,1,255,'','','','inv_crate_04',0,0,0,0,0,0);

DELETE FROM acore_world.`creaturedisplayinfoextra_dbc` WHERE `ID` IN (18884,19371,19747,19950);

INSERT INTO acore_world.`creaturedisplayinfoextra_dbc`
(`ID`,`DisplayRaceID`,`DisplaySexID`,`SkinID`,`FaceID`,`HairStyleID`,`HairColorID`,`FacialHairID`,`NPCItemDisplay1`,`NPCItemDisplay2`,`NPCItemDisplay3`,`NPCItemDisplay4`,`NPCItemDisplay5`,`NPCItemDisplay6`,`NPCItemDisplay7`,`NPCItemDisplay8`,`NPCItemDisplay9`,`NPCItemDisplay10`,`NPCItemDisplay11`,`Flags`,`BakeName`) VALUES
(18884,2,0,6,6,4,0,6,0,12525,10962,12920,22816,9195,9196,0,9197,0,0,0,'CreatureDisplayExtra-18884.blp'),
(19371,4,1,5,7,2,6,1,5677,32016,4596,12165,12053,6865,18153,3767,11241,0,0,0,'CreatureDisplayExtra-19371.blp'),
(19747,4,1,9,0,5,6,7,0,60762,0,44557,4300,33385,15621,0,0,0,0,0,'CreatureDisplayExtra-19747.blp'),
(19950,7,0,2,5,4,1,5,0,0,57506,25131,0,28995,10295,7082,5860,0,0,0,'CreatureDisplayExtra-19950.blp');

DELETE FROM acore_world.`creaturemodeldata_dbc` WHERE `ID` IN (3394);

INSERT INTO acore_world.`creaturemodeldata_dbc`
(`ID`,`Flags`,`ModelName`,`SizeClass`,`ModelScale`,`BloodID`,`FootprintTextureID`,`FootprintTextureLength`,`FootprintTextureWidth`,`FootprintParticleScale`,`FoleyMaterialID`,`FootstepShakeSize`,`DeathThudShakeSize`,`SoundID`,`CollisionWidth`,`CollisionHeight`,`MountHeight`,`GeoBoxMinX`,`GeoBoxMinY`,`GeoBoxMinZ`,`GeoBoxMaxX`,`GeoBoxMaxY`,`GeoBoxMaxZ`,`WorldEffectScale`,`AttachedEffectScale`,`MissileCollisionRadius`,`MissileCollisionPush`,`MissileCollisionRaise`) VALUES
(3394,12288,'WORLD\\GENERIC\\ORC\\PASSIVE DOODADS\\BARRELSANDCRATES\\ORCCRATE09.mdx',0,1,3,4,18,12,1,0,0,0,0,1.7951,1.71,0,0,0,0,0,0,0,1,1,0,0,0);

DELETE FROM acore_world.`itemdisplayinfo_dbc` WHERE `ID` IN (57681,57951,58373,58437,59596,60710,60762,61036,67690,68294,72360,73507,75179);

INSERT INTO acore_world.`itemdisplayinfo_dbc`
(`ID`,`ModelName_1`,`ModelName_2`,`ModelTexture_1`,`ModelTexture_2`,`InventoryIcon_1`,`InventoryIcon_2`,`GeosetGroup_1`,`GeosetGroup_2`,`GeosetGroup_3`,`Flags`,`SpellVisualID`,`GroupSoundIndex`,`HelmetGeosetVis_1`,`HelmetGeosetVis_2`,`Texture_1`,`Texture_2`,`Texture_3`,`Texture_4`,`Texture_5`,`Texture_6`,`Texture_7`,`Texture_8`,`ItemVisual`,`ParticleColorID`) VALUES
(57681,'','','','','INV_Bracer_25A','',0,0,0,0,0,8,0,0,'','','','','','','','',0,0),
(57951,'','','','','INV_Ammo_Arrow_04','',0,0,0,0,0,12,0,0,'','','','','','','','',0,0),
(58373,'','','','','Spell_Nature_WispSplodeGreen','',0,0,0,0,0,24,0,0,'','','','','','','','',0,0),
(58437,'','','','','INV_Axe_11','',0,0,0,0,0,16,0,0,'','','','','','','','',0,0),
(59596,'','','','','INV_Misc_Food_125_FishChunk','',0,0,0,0,0,23,0,0,'','','','','','','','',0,0),
(60710,'','','','','INV_Misc_Gear_05','',0,0,0,0,0,10,0,0,'','','','','','','','',0,0),
(60762,'LShoulder_Robe_B_04.mdx','RShoulder_Robe_B_04.mdx','shoulder_robe_b_03purple','shoulder_robe_b_03purple','','',0,0,0,0,0,0,0,0,'','','','','','','','',0,0),
(61036,'','','','','inv_misc_apexis_shard','',0,0,0,0,0,21,0,0,'','','','','','','','',0,0),
(67690,'','','','','inv_gizmo_gnomishflameturret','',0,0,0,0,0,9,0,0,'','','','','','','','',0,0),
(68294,'','','','','inv_crate_09','',0,0,0,0,0,9,0,0,'','','','','','','','',0,0),
(72360,'','','','','inv_egg_09','',0,0,0,0,0,12,0,0,'','','','','','','','',0,0),
(73507,'','','','','inv_misc_hook_01','',0,0,0,0,0,7,0,0,'','','','','','','','',0,0),
(75179,'','','','','inv_enchant_dustvision','',0,0,0,0,0,22,0,0,'','','','','','','','',0,0);

-- ---- 3. give 260_'s twelve display-less items their icons ------------------
-- 260_ wrote displayid 0 for these because an unknown display makes the core
-- log "does not have a correct display id (N), must be 0". Now that the
-- ItemDisplayInfo rows exist the real values can go in. Guarded on the display
-- actually being present so this is safe to re-run and cannot re-introduce the
-- error it was avoiding.
UPDATE acore_world.`item_template` SET `displayid` = 57681 WHERE `entry` = 44868 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 57681);
UPDATE acore_world.`item_template` SET `displayid` = 57951 WHERE `entry` = 45004 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 57951);
UPDATE acore_world.`item_template` SET `displayid` = 58373 WHERE `entry` = 45572 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 58373);
UPDATE acore_world.`item_template` SET `displayid` = 58437 WHERE `entry` = 45678 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 58437);
UPDATE acore_world.`item_template` SET `displayid` = 59596 WHERE `entry` = 46365 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 59596);
UPDATE acore_world.`item_template` SET `displayid` = 60710 WHERE `entry` = 48525 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 60710);
UPDATE acore_world.`item_template` SET `displayid` = 61036 WHERE `entry` = 49094 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 61036);
UPDATE acore_world.`item_template` SET `displayid` = 67690 WHERE `entry` = 55152 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 67690);
UPDATE acore_world.`item_template` SET `displayid` = 68294 WHERE `entry` = 56577 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 68294);
UPDATE acore_world.`item_template` SET `displayid` = 73507 WHERE `entry` = 63513 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 73507);
UPDATE acore_world.`item_template` SET `displayid` = 72360 WHERE `entry` = 65890 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 72360);
UPDATE acore_world.`item_template` SET `displayid` = 75179 WHERE `entry` = 65901 AND `displayid` = 0
  AND EXISTS (SELECT 1 FROM acore_world.`itemdisplayinfo_dbc` d WHERE d.`ID` = 75179);

-- Verify after apply -- all must return 0 rows:
--   SELECT DisplayID FROM creature_model_info WHERE DisplayID IN (28478,28595,29294,29849,30106,30338,32209)
--     AND (BoundingRadius = 0 OR CombatReach = 0);
--   SELECT entry, displayid FROM item_template WHERE entry IN (44868,45004,45572,45678,46365,48525,49094,55152,56577,63513,65890,65901) AND displayid = 0;
--   and no "has no model ... defined in table `creature_template_model`" or
--   "does not have a correct display id" lines for any of these on next boot.
