-- ---------------------------------------------------------------------------
-- 265  The 32 items creature_loot_template references and item_template lacks
-- ---------------------------------------------------------------------------
--     Table 'creature_loot_template' Entry 33193 Item 78343: item entry not
--     listed in `item_template` - skipped
--
-- 145 loot rows across 96 loot tables are dropped at load for want of 32 item
-- rows. This is NOT map-750-scoped like the rest of round 25: the affected
-- tables sit on stock WotLK creatures (33193, 34350, 35095...), on their +3.6M
-- Cata clones, and on Castle Nathria. It is the "11,580 loot rows reference
-- non-existent items" class that earlier rounds deferred -- now measured
-- properly, it is far smaller than that note suggested.
--
-- 🔴 HOW THAT NUMBER SHRANK, because the same mistake is easy to repeat. A
-- naive "loot rows whose Item is not in item_template" query returns ~19,000
-- rows / 95 items. Almost all of it is noise: `LootStoreItem::IsValid`
-- (LootMgr.cpp:347) only validates the item **when `Reference` is 0** --
--
--     if (!reference)                      // item entry, maybe grouped
--     {   ItemTemplate const* proto = sObjectMgr->GetItemTemplate(itemid); ...
--
-- and DC's own World Loot ladder stores a slot index (1, 2, 3, ... 24) in
-- `Item` alongside a real `Reference`, e.g.
--
--     Entry 3, Item 1, Reference 1000124, GroupId 5, "Flesh Eater - World Loot
--     Level 24"
--
-- Those ~19,000 rows are correct and the core never looks at their Item. Filter
-- on `Reference = 0` and the true set is 145 rows / 32 items, which matches the
-- boot log exactly. Always reproduce a log class with a query that returns the
-- SAME count before acting on it.
--
-- SOURCES. 30 of the 32 come from the Cata client Item.db2 (build 15595) for
-- class / subclass / material / displayid / inventorytype / sheath, with names
-- and descriptions from the retail ItemSparse extract so the strings are
-- authentic. The two Shadowlands ids -- 176871 "Fortified Antennae" and 179311
-- "Synvir Lockbox", which drop from live Castle Nathria creatures (Nathrian
-- Siphoner x13, Anima Crazed Worker x8, Nathrian Gargon Rider x4 and four
-- rares) -- have no Cata row, so their class/subclass/material/inventorytype
-- come from the retail Item.db2 export instead. Both are class 15 subclass 0,
-- plain junk. Generated by tools/gen_loot_items_r31.py.
--
-- DISPLAY IDs. 20 of the 32 Cata display ids exist in the fork's
-- ItemDisplayInfo and are kept. The other 12 do not, and an unknown display
-- makes the core log "does not have a correct display id (N), must be 0" -- so
-- those are written as 0 rather than trading one boot-log error for another.
-- The two Shadowlands items are also 0: a modern IconFileDataID has no 3.3.5
-- ItemDisplayInfo equivalent. Those items work; they show no icon until the
-- ItemDisplayInfo rows and their BLPs are downported.

DELETE FROM `item_template` WHERE `entry` IN (47038,47039,47819,47831,49359,49364,49366,49624,49765,50438,54631,54632,54633,54831,55974,55983,56034,56046,56150,56151,56237,56968,58949,60743,62328,62340,62341,62514,67229,78343,176871,179311);

INSERT INTO `item_template` (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `Flags`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `maxcount`, `stackable`, `ContainerSlots`, `bonding`, `description`, `startquest`, `Material`, `sheath`, `BagFamily`, `ScriptName`, `VerifiedBuild`) VALUES
(47038, 12, 0, 'Slab of Venison', 47467, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 20, 0, 1, 'Lean and gamey.', 0, 4, 0, 0, '', 0),
(47039, 12, 0, 'Scout''s Orders', 0, 1, 0, 1, 0, 0, 0, -1, -1, 5, 5, 1, 1, 0, 1, 'Found sewn into a secret pocket.', 14127, 4, 0, 0, '', 0),
(47819, 12, 0, 'Crystal Pendant', 19763, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'Rainbows of light seem to dance off of the flawless crystal.', 0, 4, 0, 0, '', 0),
(47831, 15, 0, 'Shattered Crystal Pendant', 0, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, 'Crushed in the fury of combat.', 0, 4, 0, 0, '', 0),
(49359, 12, 0, 'Attuned Runestone', 38758, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 1, '', 0, 0, 0, 0, '', 0),
(49364, 12, 0, 'Blackmaw Intelligence', 18010, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, 'An outline of a pending agreement between the Blackmaw and the night elves.', 0, 0, 0, 0, '', 0),
(49366, 12, 0, 'Ambassador''s Robes', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'Bloodstained but serviceable.', 0, 7, 0, 0, '', 0),
(49624, 15, 0, 'Tiny Scaly Tail', 20915, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 4, 0, 0, '', 0),
(49765, 12, 0, 'Basalt Rockling', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(50438, 15, 0, 'Damaged Naga Hide', 0, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, 'Maybe you shouldn''t have hit this naga so hard?', 0, 4, 0, 0, '', 0),
(54631, 15, 0, 'Broken Jaws', 45394, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 2, 0, 0, '', 0),
(54632, 15, 0, 'Torn Flipper', 3124, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 8, 0, 0, '', 0),
(54633, 15, 0, 'Shattered Jaws', 21368, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 2, 0, 0, '', 0),
(54831, 15, 0, 'Shiny Pebble', 4719, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 2, 0, 0, '', 0),
(55974, 15, 0, 'Inert Elemental Particle', 0, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 4, 0, 0, '', 0),
(55983, 15, 0, 'Inert Elemental Scintilla', 40304, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 4, 0, 0, '', 0),
(56034, 15, 0, 'Tinted Rock', 4721, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 2, 0, 0, '', 0),
(56046, 15, 0, 'Shattered Rock Fragments', 4714, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 2, 0, 0, '', 0),
(56150, 15, 0, 'Glue Material', 0, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 7, 0, 0, '', 0),
(56151, 15, 0, 'Broken Hoof Piece', 18072, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 2, 0, 0, '', 0),
(56237, 15, 0, 'Keeled Scale', 21363, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 4, 0, 0, '', 0),
(56968, 15, 0, 'Bug Juice', 2637, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 4, 1, 0, '', 0),
(58949, 12, 0, 'Stag Eye', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 1, 'The eye still flinches occasionaly.', 0, 4, 0, 32768, '', 0),
(60743, 15, 0, 'Diseased Beast Guts', 55263, 0, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 20, 0, 0, '', 0, 4, 0, 0, '', 0),
(62328, 15, 0, 'Shed Fur', 18093, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 8, 0, 0, '', 0),
(62340, 15, 0, 'Flaky Basilisk Scale', 4433, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 4, 0, 0, '', 0),
(62341, 15, 0, 'Gluey Basilisk Tear', 0, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 1, 0, 0, '', 0),
(62514, 15, 0, 'Cracked Pincer', 0, 0, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 0, '', 0, 3, 0, 0, '', 0),
(67229, 7, 8, 'Stag Flank', 25466, 1, 0, 1, 0, 0, 0, -1, -1, 10, 0, 0, 1000, 0, 0, '', 0, 4, 0, 65536, '', 0),
(78343, 9, 8, 'Formula: Enchant Gloves - Herbalism', 7798, 2, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 0, 'Teaches you how to perform the Herbalism enchantment.', 0, 0, 0, 64, '', 0),
(176871, 15, 0, 'Fortified Antennae', 0, 0, 0, 1, 0, 0, 0, -1, -1, 120, 1, 0, 200, 0, 0, '', 0, 0, 0, 0, '', 0),
(179311, 15, 0, 'Synvir Lockbox', 0, 2, 0, 1, 0, 0, 0, -1, -1, 50, 50, 0, 1, 0, 0, '', 0, 1, 0, 0, '', 0);

-- Verify after apply -- must return 0 rows:
--   SELECT l.Entry, l.Item FROM creature_loot_template l
--    WHERE l.Reference = 0 AND l.Item > 0
--      AND NOT EXISTS (SELECT 1 FROM item_template i WHERE i.entry = l.Item);
--   ... and the same shape against gameobject_loot_template, item_loot_template
--   and reference_loot_template, all of which are already at 0.
--
-- NOT TOUCHED, needs a decision rather than a guess: the 327
--   "Table 'creature_loot_template' Entry N isn't creature entry and not
--    referenced from loot, and thus useless"
-- lines in the same log block. 220 of the 327 are provably import duplication --
-- the raw Cata id whose +3.6M clone table exists AND is the one a creature
-- actually points at -- so the raw copy is unreachable dead weight:
--
--   SELECT DISTINCT l.Entry FROM creature_loot_template l
--    WHERE NOT EXISTS (SELECT 1 FROM creature_template ct
--            WHERE ct.lootid = l.Entry OR ct.pickpocketloot = l.Entry
--               OR ct.skinloot = l.Entry)
--      AND NOT EXISTS (SELECT 1 FROM creature_loot_template r
--            WHERE r.Reference = l.Entry)
--      AND EXISTS (SELECT 1 FROM creature_template c2
--            WHERE c2.lootid = l.Entry + 3600000);
--
-- Deleting those 220 would cut two thirds of that noise and cannot change
-- behaviour. It is still 220 tables of data removal for a cosmetic gain, and
-- the remaining 107 need judging one at a time, so nothing is deleted here.
