-- ---------------------------------------------------------------------------
-- 267  quest_template -- backfill every item, creature and object it references
-- ---------------------------------------------------------------------------
-- Closes the whole "Loading Quests..." error block: 54 items, 37 creatures and
-- one gameobject that quest_template names and the world does not have.
--
-- 🔴 READ THIS BEFORE ASSUMING IT FIXED GAMEPLAY. It did not, and that was the
-- explicit call when this was scoped. All 62 affected quests are UNREACHABLE:
-- every one has zero spawned questgivers and 61 of the 62 have no
-- `creature_queststarter` row at all. This file silences ~113 boot-log lines and
-- makes the quests structurally complete so they work the day a questgiver layer
-- lands -- it does not make a single quest playable today.
--
-- The reason is bigger than these 62. Of 10,946 quest_template rows only 8,362
-- have a creature questgiver, 472 a gameobject one and 373 an item -- roughly
-- 2,100 are orphaned. Per zone (quests / with-giver): Felwood 230/163, Ashenvale
-- 207/130, Azshara 158/84, Hyjal 618 = 144/109, Stranglethorn 128/100,
-- Stonetalon 68/47, Vashj'ir 5/0. The Cata quest layer was imported as templates
-- across many zones without its relation layer -- the same root cause the
-- Darkshore and Felwood rounds fixed, at a much larger scale and well outside
-- map 750. That import is the real fix and is deliberately NOT attempted here.
--
-- Before downporting anything for a quest error, check reachability first:
--   SELECT (SELECT COUNT(*) FROM creature_queststarter r JOIN creature c
--             ON c.id = r.id WHERE r.quest = q.ID) AS spawned_givers
--     FROM quest_template q WHERE q.ID = <id>;
-- Zero means the quest is inert and the "fix" is cosmetic. That check is what
-- kept round 25's 17 objective repairs meaningful -- they were scoped to quests
-- whose giver is actually spawned on map 750.

-- ---- 1. the 54 items -------------------------------------------------------
-- All 54 resolve in the Cata client Item.db2 (build 15595) for class / subclass
-- / material / displayid / inventorytype / sheath, with names from the retail
-- ItemSparse extract. Generated by tools/gen_quest_items_r33.py.
-- Where the Cata display id is absent from our ItemDisplayInfo the row is
-- written with displayid 0, because an unknown display makes the core log
-- "does not have a correct display id (N), must be 0" -- swapping one boot-log
-- line for another is not progress.

DELETE FROM `item_template` WHERE `entry` IN (45476,45477,45545,45710,46094,46128,46147,46389,46715,46720,46721,46739,46741,46774,46777,46781,47040,47050,48104,48665,48780,48835,49204,49350,49368,49685,52581,52582,53057,53408,53415,53424,53444,55174,56263,56469,56473,56575,56707,56709,56710,57477,57489,60214,60215,60638,60644,61049,63387,67272,68638,68644,68646,69986);

INSERT INTO `item_template` (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `Flags`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `maxcount`, `stackable`, `ContainerSlots`, `bonding`, `description`, `startquest`, `Material`, `sheath`, `BagFamily`, `ScriptName`, `VerifiedBuild`) VALUES
(45476, 12, 0, 'Seeker''s Fel Spear', 51452, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'The fel energies seething off of the spear''s tip make your stomach turn.', 0, 4, 0, 0, '', 0),
(45477, 12, 0, 'Gorgannon''s Flaming Blade', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'Not likely to play nicely with the other items in your bags.', 0, 4, 0, 0, '', 0),
(45545, 12, 0, 'Gnarl''s Bough', 41542, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(45710, 12, 0, 'Secret Signal Powder', 1168, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(46094, 12, 0, 'Bucket of Water', 22198, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(46128, 12, 0, 'Troll Charm', 27471, 1, 0, 1, 0, 0, 0, -1, -1, 1, 7, 1, 1, 0, 1, 'A subtle aura permeates the wood of this carving. It gives you a feeling of unease.', 13868, 4, 0, 0, '', 0),
(46147, 12, 0, 'Kaldorei Assassin''s Head', 19540, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 0, 0, 0, '', 0),
(46389, 12, 0, 'Elune''s Tear', 12310, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(46715, 12, 0, 'Sanctified Moonstones', 46253, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'The brilliance of Elune''s grace shines through.', 0, 4, 0, 0, '', 0),
(46720, 12, 0, 'Shael''dryn''s Playing Possum Technique', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(46721, 12, 0, 'Dartol''s Rod', 7143, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'The assembled rod somehow feels both light and heavy within your hand.', 0, 4, 0, 0, '', 0),
(46739, 12, 0, 'Dartol''s Rod', 7143, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 0, 0, 0, '', 0),
(46741, 12, 0, 'Furbolg Ear', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 20, 0, 1, '', 0, 0, 0, 0, '', 0),
(46774, 12, 0, 'Heart of Kaliva', 5287, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'It yet beats with foul demonic magic!', 0, 4, 0, 0, '', 0),
(46777, 12, 0, 'Bloodtooth Banner', 6748, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 0, 0, 0, '', 0),
(46781, 12, 0, 'Dartol''s Rod', 7143, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 0, 0, 0, '', 0),
(47040, 12, 0, 'Scout''s Orders', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(47050, 12, 0, 'Azshara Lumber', 929, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 6, 0, 1, '', 0, 1, 0, 0, '', 0),
(48104, 12, 0, 'The Refleshifier', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'A re-purposed laser drill, warm to the touch and humming.', 0, 0, 0, 0, '', 0),
(48665, 12, 0, 'Surveyor''s Beacon', 44269, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(48780, 12, 0, 'Ectosplatter Sample', 2637, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 0, 1, 0, 1, 'Greasy to the touch, with a strange phosphorescent glow.', 0, 4, 0, 0, '', 0),
(48835, 12, 0, 'Kalytha''s Ring', 23629, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, 'Allows you to interact with the spirit of Kalytha.', 0, 0, 0, 0, '', 0),
(49204, 12, 0, 'Secret Rocket Plans', 56319, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 1, 1, 0, 1, 'An incomprehensible pile of dense schematics.', 0, 4, 0, 0, '', 0),
(49350, 12, 0, 'Blessed Flaregun', 39435, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(49368, 12, 0, 'Ambassador Disguise', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 0, 0, 0, '', 0),
(49685, 12, 0, 'Flag of Territorial Claim', 31257, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(52581, 12, 0, 'SI:7 Emblem', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 1, 1, 0, 1, 'There''s blood on this patch that was torn from an SI:7 officer''s uniform.', 0, 8, 0, 0, '', 0),
(52582, 12, 0, 'Sealed Package', 39459, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 1, 1, 0, 1, 'It''s sealed up pretty tight, but something metallic rattles around inside.', 0, 8, 0, 0, '', 0),
(53057, 4, 0, 'Faded Wizard Hat', 62272, 1, 0, 1, 0, 0, 1, -1, -1, 10, 1, 0, 1, 0, 0, 'In memory of lost dreams of being an apprentice.', 0, 7, 0, 0, '', 0),
(53408, 4, 0, 'Detonation Ring', 39127, 2, 0, 1, 0, 0, 11, -1, -1, 12, 0, 0, 1, 0, 0, '', 0, 3, 0, 0, '', 0),
(53415, 4, 1, 'Heart Wrapper', 0, 3, 0, 1, 0, 0, 16, -1, -1, 10, 0, 0, 1, 0, 0, '', 0, 7, 0, 0, '', 0),
(53424, 4, 0, 'Kroum''s Signet', 9842, 2, 0, 1, 0, 0, 11, -1, -1, 12, 0, 0, 1, 0, 0, '', 0, 3, 0, 0, '', 0),
(53444, 4, 0, 'Sniper''s Band', 224, 2, 0, 1, 0, 0, 11, -1, -1, 12, 0, 0, 1, 0, 0, '', 0, 3, 0, 0, '', 0),
(55174, 12, 0, 'Azure Iron Ore', 38648, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 10, 0, 1, '', 0, 4, 0, 0, '', 0),
(56263, 12, 0, 'Land Mine Wrench', 31515, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(56469, 12, 0, 'Alliance Attack Plans', 0, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(56473, 12, 0, 'Krom''gar Flame Thrower', 67690, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(56575, 12, 0, 'Spare Part', 20627, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 10, 0, 1, '', 0, 4, 0, 0, '', 0),
(56707, 4, 0, 'Band of Perseverance', 28830, 2, 0, 1, 0, 0, 11, -1, -1, 16, 0, 0, 1, 0, 0, '', 0, 3, 0, 0, '', 0),
(56709, 4, 0, 'Garrosh''s Pardon', 224, 3, 0, 1, 0, 0, 11, -1, -1, 14, 0, 0, 1, 0, 0, '', 0, 3, 0, 0, '', 0),
(56710, 4, 1, 'Unbountied Cloak', 0, 3, 0, 1, 0, 0, 16, -1, -1, 14, 0, 0, 1, 0, 0, '', 0, 7, 0, 0, '', 0),
(57477, 4, 0, 'Overlord''s Favor', 52417, 2, 0, 1, 0, 0, 2, -1, -1, 17, 0, 0, 1, 0, 0, '', 0, 4, 0, 0, '', 0),
(57489, 4, 0, 'Bombgutz Band', 38541, 2, 0, 1, 0, 0, 11, -1, -1, 17, 0, 0, 1, 0, 0, '', 0, 3, 0, 0, '', 0),
(60214, 12, 0, 'Kurzen Compound Prison Records', 56320, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, 'A short list of political prisoners within the compound.', 0, 4, 0, 0, '', 0),
(60215, 12, 0, 'Kurzen Compound Officers'' Dossier', 56320, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, 'A list of Kurzen officials.', 0, 4, 0, 0, '', 0),
(60638, 12, 0, 'Durak''s Head', 1310, 1, 0, 1, 0, 0, 0, -1, -1, 1, 0, 1, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(60644, 4, 0, 'Gorka''s Band', 224, 2, 0, 1, 0, 0, 11, -1, -1, 13, 0, 0, 1, 0, 0, '', 0, 3, 0, 0, '', 0),
(61049, 4, 0, 'Ring of Forgotten Causes', 54488, 2, 0, 1, 0, 0, 11, -1, -1, 16, 0, 0, 1, 0, 0, '', 0, 3, 0, 0, '', 0),
(63387, 12, 0, 'Whisperwind Moonwell Water', 1249, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(67272, 0, 5, 'Shy-Rotam Steak', 0, 1, 0, 1, 0, 0, 0, -1, -1, 20, 20, 0, 20, 0, 0, 'Hope you aren''t Shy.', 0, 4, 0, 65536, '', 0),
(68638, 12, 0, 'Frostsaber Cub', 23606, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 10, 0, 1, '', 0, 4, 0, 0, '', 0),
(68644, 12, 0, 'Winterspring Cub Whisker', 36984, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 20, 0, 1, '', 0, 4, 0, 0, '', 0),
(68646, 12, 0, 'Winterspring Cub', 23606, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 1, '', 0, 4, 0, 0, '', 0),
(69986, 15, 0, 'Cub''s First Toy', 41380, 1, 0, 1, 0, 0, 0, -1, -1, 1, 1, 0, 1, 0, 0, '', 0, 4, 0, 0, '', 0);

-- ---- 2. the 22 creature displays those 37 templates need -------------------
-- Checked BEFORE importing the creatures rather than after. Bringing in 37
-- templates with their creature_template_model rows would otherwise have added
-- 22 "lists non-existing CreatureDisplayID id (N), this can crash the client"
-- lines -- trading a cosmetic class for a worse one. That is exactly the
-- mistake 259_ made and 264_ had to repair; sweep every modelid of an import
-- against the deployed DBC first.
--
-- All 22 were cheap: every model behind them (49, 50, 51, 53, 55, 56, 182, 831,
-- 1391, 2923) already exists in our CreatureModelData, so it is DBC rows only --
-- no model bake, no BLP extraction. Already compiled and deployed to patch-4 and
-- enGB/patch-enGB-3 (0 ids lost); this is the server half.
--
-- 18 Extra rows back 19 references: 19653 is shared by displays 29656 and 29657.
-- A generator that does not dedupe writes it twice and the next compile silently
-- drops one -- guard for that whenever Extra rows are emitted per-display.

DELETE FROM acore_world.`creaturedisplayinfo_dbc` WHERE `ID` IN (29187,29191,29192,29193,29656,29657,29671,29672,31477,31484,33014,33015,33178,33179,33283,33543,33545,33546,33554,33555,33556,33557);

INSERT INTO acore_world.`creaturedisplayinfo_dbc`
(`ID`,`ModelID`,`SoundID`,`ExtendedDisplayInfoID`,`CreatureModelScale`,`CreatureModelAlpha`,`TextureVariation_1`,`TextureVariation_2`,`TextureVariation_3`,`PortraitTextureName`,`BloodLevel`,`BloodID`,`NPCSoundID`,`ParticleColorID`,`CreatureGeosetData`,`ObjectEffectPackageID`) VALUES
(29187,51,0,19258,1.4,255,'','','','',1,0,62,0,0,0),
(29191,51,0,19260,1,255,'','','','',1,0,62,0,0,0),
(29192,51,0,19261,1,255,'','','','',1,0,62,0,0,0),
(29193,51,0,19262,1,255,'','','','',1,0,62,0,0,0),
(29656,55,0,19653,1,255,'','','','',1,0,59,0,0,0),
(29657,55,0,19653,1,255,'','','','',1,0,53,0,0,0),
(29671,55,0,19668,1,255,'','','','',1,0,59,0,0,0),
(29672,56,0,19654,1,255,'','','','',1,0,53,0,0,0),
(31477,831,3173,19671,3,255,'','','','',1,0,390,0,0,0),
(31484,2923,0,0,1.25,255,'GoblinShredderMountSkin1_01','GoblinShredderMountSkin1_02','','',2,0,0,0,0,0),
(33014,831,0,21884,1,255,'','','','',0,0,362,0,0,0),
(33015,831,0,21885,1,255,'','','','',0,0,362,0,0,0),
(33178,1391,0,0,0.65,255,'EggCreature04','','','',-1,0,0,0,0,0),
(33179,1391,0,0,0.65,255,'EggCreature01','','','',0,0,0,0,0,0),
(33283,51,0,22071,1,255,'','','','',0,0,62,0,0,0),
(33543,182,0,22258,1,255,'','','','',1,0,44,0,0,0),
(33545,50,0,22259,1,255,'','','','',1,0,46,0,0,0),
(33546,53,0,22261,1,255,'','','','',1,0,36,0,0,0),
(33554,49,0,22271,1.2,255,'','','','',1,0,0,0,0,0),
(33555,49,0,22269,1.2,255,'','','','',1,0,0,0,0,0),
(33556,49,0,22268,1.2,255,'','','','',1,0,0,0,0,0),
(33557,50,0,22270,1,255,'','','','',1,0,0,0,0,0);

DELETE FROM acore_world.`creaturedisplayinfoextra_dbc` WHERE `ID` IN (19258,19260,19261,19262,19653,19668,19654,19671,21884,21885,22071,22258,22259,22261,22271,22269,22268,22270);

INSERT INTO acore_world.`creaturedisplayinfoextra_dbc`
(`ID`,`DisplayRaceID`,`DisplaySexID`,`SkinID`,`FaceID`,`HairStyleID`,`HairColorID`,`FacialHairID`,`NPCItemDisplay1`,`NPCItemDisplay2`,`NPCItemDisplay3`,`NPCItemDisplay4`,`NPCItemDisplay5`,`NPCItemDisplay6`,`NPCItemDisplay7`,`NPCItemDisplay8`,`NPCItemDisplay9`,`NPCItemDisplay10`,`NPCItemDisplay11`,`Flags`,`BakeName`) VALUES
(19258,2,0,12,1,0,0,1,11976,0,47074,0,42004,42802,42803,0,0,0,0,0,'CreatureDisplayExtra-19258.blp'),
(19260,2,0,6,1,8,0,10,43891,0,59689,39185,29256,29254,29258,8197,29260,58390,0,0,'CreatureDisplayExtra-19260.blp'),
(19261,2,0,5,1,9,8,2,43891,0,59689,39185,29256,29254,29258,8197,29260,58390,0,0,'CreatureDisplayExtra-19261.blp'),
(19262,2,0,3,3,7,8,1,43891,0,59689,39185,29256,29254,29258,8197,29260,58390,0,0,'CreatureDisplayExtra-19262.blp'),
(19653,4,0,0,2,5,5,4,0,0,60364,0,4852,18043,16988,8423,0,0,0,0,'CreatureDisplayExtra-19653.blp'),
(19668,4,0,0,0,0,2,0,0,59863,60365,22677,14853,7193,5470,18331,0,0,0,0,'CreatureDisplayExtra-19668.blp'),
(19654,4,1,2,4,2,5,0,0,59863,60365,22677,14853,7193,5470,18331,0,0,0,0,'CreatureDisplayExtra-19654.blp'),
(19671,9,0,4,4,5,1,0,62495,36640,60412,60413,60341,59823,25459,0,60414,0,0,0,'CreatureDisplayExtra-19671.blp'),
(21884,9,0,4,3,11,0,8,8421,0,69289,0,14853,4469,16734,0,9050,0,0,0,'CreatureDisplayExtra-21884.blp'),
(21885,9,0,6,0,2,5,13,8421,0,57506,0,4852,9049,6648,66531,9791,0,0,0,'CreatureDisplayExtra-21885.blp'),
(22071,2,0,1,8,10,4,9,0,0,0,69948,12131,69882,3261,0,0,63161,0,0,'CreatureDisplayExtra-22071.blp'),
(22258,7,0,2,4,6,6,7,17967,0,70531,5864,6049,11568,17721,0,0,0,0,0,'CreatureDisplayExtra-22258.blp'),
(22259,1,1,2,1,8,6,1,0,10169,35566,35566,5725,35567,35455,0,0,0,0,0,'CreatureDisplayExtra-22259.blp'),
(22261,3,0,16,0,11,8,8,0,0,61065,10116,7662,6300,16186,0,10947,0,0,0,'CreatureDisplayExtra-22261.blp'),
(22271,1,0,0,2,8,5,4,70541,0,60090,8136,8137,5297,5451,0,12249,0,0,0,'CreatureDisplayExtra-22271.blp'),
(22269,1,0,5,10,16,9,8,0,0,0,37140,70537,70538,0,0,0,0,0,0,'CreatureDisplayExtra-22269.blp'),
(22268,1,0,3,8,12,0,8,0,0,7223,10018,11014,7225,7255,0,10090,0,0,0,'CreatureDisplayExtra-22268.blp'),
(22270,1,1,5,11,20,4,0,3868,0,70539,7609,0,70540,7943,0,12269,0,0,0,'CreatureDisplayExtra-22270.blp');

-- creature_model_info gates whether a spawn LOADS, which is a different failure
-- from the client display being absent. These 37 are template-only so nothing
-- loads today, but the rows belong with the displays rather than in whatever
-- round eventually places them. Values come from nelt_world.
DELETE FROM acore_world.`creature_model_info` WHERE `DisplayID` IN (29187,29191,29192,29193,29656,29657,29671,29672,31477,31484,33014,33015,33178,33179,33283,33543,33545,33546,33554,33555,33556,33557);

INSERT INTO acore_world.`creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`)
SELECT n.modelid, IF(n.bounding_radius > 0, n.bounding_radius, 0.306),
       IF(n.combat_reach > 0, n.combat_reach, 1.5), n.gender, 0
FROM nelt_world.creature_model_info n
WHERE n.modelid IN (29187,29191,29192,29193,29656,29657,29671,29672,31477,31484,33014,33015,33178,33179,33283,33543,33545,33546,33554,33555,33556,33557);

-- ---- 3. the 37 objective creatures + 1 object ------------------------------
-- Created at their RAW ids, deliberately: these quests already name the raw id,
-- the ids are free, and they are the canonical Blizzard entries. No +3,600,000
-- offset and therefore no quest_template UPDATE -- unlike 259_, where the
-- objectives pointed at raw ids whose CLONES were the live creatures on map 750.
--
-- Template-only, no spawns. 0-spawn objective markers are normal for this
-- content (kill-credit proxies and script-summoned targets), and placing them
-- would be meaningless while no questgiver offers the quests.
--
-- AIName is forced to '' on ALL 37. Ten of them carry AIName='SmartAI' in nelt
-- WITH real smart_scripts rows, and copying the flag without the rows would
-- manufacture ten "has SmartAI enabled but no SmartAI entries" lines -- the
-- exact trap 258_ fell into and 264_ had to repair. Importing those rows instead
-- is not worth it here: it drags in their spells and needs the full param sweep,
-- all to animate creatures that are never spawned and belong to quests nobody
-- can accept. If the questgiver layer ever lands, port the AI then, together
-- with the spawns.
SET @Z := 0;

DELETE FROM acore_world.`creature_template` WHERE `entry` IN (33507,33709,33965,33969,34007,34176,34333,34341,34353,35149,35177,35375,35487,35488,35489,35593,36534,36625,39582,39592,40942,41936,42016,42017,42620,42674,42675,42977,43243,43910,43911,43912,43913,43919,43920,43921,52041);

INSERT INTO acore_world.`creature_template`
(`entry`,`KillCredit1`,`KillCredit2`,`name`,`subname`,`IconName`,`gossip_menu_id`,`minlevel`,`maxlevel`,`exp`,`faction`,`npcflag`,`speed_walk`,`speed_run`,`speed_swim`,`speed_flight`,`rank`,`dmgschool`,`DamageModifier`,`BaseAttackTime`,`RangeAttackTime`,`BaseVariance`,`RangeVariance`,`unit_class`,`unit_flags`,`unit_flags2`,`dynamicflags`,`family`,`type`,`type_flags`,`lootid`,`pickpocketloot`,`skinloot`,`PetSpellDataId`,`VehicleId`,`mingold`,`maxgold`,`AIName`,`MovementType`,`HoverHeight`,`HealthModifier`,`ManaModifier`,`ArmorModifier`,`RacialLeader`,`movementId`,`RegenHealth`,`flags_extra`,`ScriptName`,`VerifiedBuild`)
SELECT entry, IF(KillCredit1>0,KillCredit1,0), IF(KillCredit2>0,KillCredit2,0), name, subname, IconName, gossip_menu_id, minlevel, maxlevel, LEAST(exp,2), faction_A, npcflag, speed_walk, speed_run, speed_swim, speed_fly, `rank`, dmgschool, dmg_multiplier, baseattacktime, rangeattacktime, 1, 1, unit_class, unit_flags, unit_flags2, dynamicflags, family, type, type_flags, 0, 0, 0, PetSpellDataId, VehicleId, mingold, maxgold,
       '',
       MovementType, HoverHeight, Health_mod, Mana_mod, Armor_mod, RacialLeader, movementId, RegenHealth, flags_extra, '', 0
FROM nelt_world.creature_template
WHERE entry IN (33507,33709,33965,33969,34007,34176,34333,34341,34353,35149,35177,35375,35487,35488,35489,35593,36534,36625,39582,39592,40942,41936,42016,42017,42620,42674,42675,42977,43243,43910,43911,43912,43913,43919,43920,43921,52041);

DELETE FROM acore_world.`creature_template_model` WHERE `CreatureID` IN (33507,33709,33965,33969,34007,34176,34333,34341,34353,35149,35177,35375,35487,35488,35489,35593,36534,36625,39582,39592,40942,41936,42016,42017,42620,42674,42675,42977,43243,43910,43911,43912,43913,43919,43920,43921,52041);

INSERT INTO acore_world.`creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
SELECT entry, idx, mid, scale, 1, 0 FROM (
  SELECT entry, 0 idx, modelid1 mid, scale FROM nelt_world.creature_template WHERE entry IN (33507,33709,33965,33969,34007,34176,34333,34341,34353,35149,35177,35375,35487,35488,35489,35593,36534,36625,39582,39592,40942,41936,42016,42017,42620,42674,42675,42977,43243,43910,43911,43912,43913,43919,43920,43921,52041) AND modelid1>0
  UNION ALL SELECT entry, 1, modelid2, scale FROM nelt_world.creature_template WHERE entry IN (33507,33709,33965,33969,34007,34176,34333,34341,34353,35149,35177,35375,35487,35488,35489,35593,36534,36625,39582,39592,40942,41936,42016,42017,42620,42674,42675,42977,43243,43910,43911,43912,43913,43919,43920,43921,52041) AND modelid2>0
  UNION ALL SELECT entry, 2, modelid3, scale FROM nelt_world.creature_template WHERE entry IN (33507,33709,33965,33969,34007,34176,34333,34341,34353,35149,35177,35375,35487,35488,35489,35593,36534,36625,39582,39592,40942,41936,42016,42017,42620,42674,42675,42977,43243,43910,43911,43912,43913,43919,43920,43921,52041) AND modelid3>0
  UNION ALL SELECT entry, 3, modelid4, scale FROM nelt_world.creature_template WHERE entry IN (33507,33709,33965,33969,34007,34176,34333,34341,34353,35149,35177,35375,35487,35488,35489,35593,36534,36625,39582,39592,40942,41936,42016,42017,42620,42674,42675,42977,43243,43910,43911,43912,43913,43919,43920,43921,52041) AND modelid4>0
) m;

-- 194612 "Ritual Gem", type 10, display 5811 -- confirmed present in the
-- deployed GameObjectDisplayInfo.dbc. nelt names its Data columns lower case and
-- carries faction/flags/questItem1-6 this fork does not have, so the column list
-- is written out and those source-only columns dropped.
DELETE FROM acore_world.`gameobject_template` WHERE `entry` = 194612;

INSERT INTO acore_world.`gameobject_template`
(`entry`,`type`,`displayId`,`name`,`IconName`,`castBarCaption`,`unk1`,`size`,`Data0`,`Data1`,`Data2`,`Data3`,`Data4`,`Data5`,`Data6`,`Data7`,`Data8`,`Data9`,`Data10`,`Data11`,`Data12`,`Data13`,`Data14`,`Data15`,`Data16`,`Data17`,`Data18`,`Data19`,`Data20`,`Data21`,`Data22`,`Data23`,`AIName`,`ScriptName`,`VerifiedBuild`)
SELECT entry, type, displayId, name, IconName, castBarCaption, unk1, size, data0, data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12, data13, data14, data15, data16, data17, data18, data19, data20, data21, data22, data23, '', '', 0
FROM nelt_world.gameobject_template WHERE entry = 194612;

-- Verify after apply -- all must return 0 rows:
--   * every quest item field resolves:
--       SELECT ID FROM quest_template WHERE
--         (StartItem>0 AND NOT EXISTS(SELECT 1 FROM item_template i WHERE i.entry=StartItem))
--         OR (RewardChoiceItemID1>0 AND NOT EXISTS(SELECT 1 FROM item_template i WHERE i.entry=RewardChoiceItemID1))
--         ... (all 21 item columns);
--   * SELECT COUNT(*) FROM creature_template WHERE entry IN (33507,33709,33965,33969,34007,34176,34333,34341,34353,35149,35177,35375,35487,35488,35489,35593,36534,36625,39582,39592,40942,41936,42016,42017,42620,42674,42675,42977,43243,43910,43911,43912,43913,43919,43920,43921,52041);  -> 37
--   * SELECT COUNT(*) FROM gameobject_template WHERE entry = 194612;    -> 1
--   * no NEW "lists non-existing CreatureDisplayID" line -- that is the one to
--     watch, it is the class this file could most easily have introduced.
--   * SELECT ct.entry FROM creature_template ct WHERE ct.entry IN (33507,33709,33965,33969,34007,34176,34333,34341,34353,35149,35177,35375,35487,35488,35489,35593,36534,36625,39582,39592,40942,41936,42016,42017,42620,42674,42675,42977,43243,43910,43911,43912,43913,43919,43920,43921,52041)
--       AND ct.AIName <> '';                                             -> 0
--     (all 37 are imported with AIName blank -- see section 3.)
--
-- STILL EXPECTED AFTER THIS, not regressions: the ~30 "RewardSpell does not
-- exist" lines. Those are Cata spells on inert quests and the reward is cosmetic
-- -- the quest completes regardless -- so they are not worth a downport round on
-- their own. And the PrevQuestId / RewardNextQuest chain warnings, which point at
-- quests that were never imported at all; they resolve with the questgiver layer
-- or not at all.
