-- ---------------------------------------------------------------------------
-- 297  Baron Ashbury's vehicle -- the one crash-class line in the log
-- ---------------------------------------------------------------------------
--     Creature (Entry: 5046962) has a non-existing VehicleId (1422).
--     This *WILL* cause the client to freeze!
--
-- Two templates carry VehicleId 1422 -- **5046962 Baron Ashbury** (1 spawn, map
-- 825 Shadowfang Keep) and 5049708 "Baron Ashbury (1)", his difficulty-1 twin.
-- The core is not exaggerating: handing the client a vehicle id it cannot
-- resolve hangs it, and this one is live.
--
-- 🔴 THE OVERLAY TRAP CAUGHT ME FIRST, SO THE NUMBER IN THE OBVIOUS QUERY IS
-- MEANINGLESS. Asking "which creature_template rows have a VehicleId missing
-- from `vehicle_dbc`" returns **459**. That is nonsense: `vehicle_dbc` is an
-- OVERLAY holding only 90 CUSTOM rows (DBCStores.cpp:379 loads Vehicle.dbc and
-- then supplements it from that table), so almost all 459 resolve fine in the
-- real DBC. Same shape as the `spell_dbc` trap. The authoritative check is
-- `read_server_dbc` against the live Vehicle.dbc -- 508 records, and 1422 is
-- genuinely absent. Exactly one id is really missing, not 459.
--
-- DOWNPORTED RATHER THAN ZEROED. The cheap fix is `VehicleId = 0`, which stops
-- the freeze and silently deletes the boss mechanic -- and 117_'s header records
-- that rounds 66_/82_ did precisely that to three map-750 creatures and it had
-- to be undone later. So the real rows come across instead:
--     Vehicle.dbc      1422  -- layouts are IDENTICAL between the two clients
--                              (40 fields / 160 bytes), so it copies verbatim
--     VehicleSeat.dbc  9362  -- **NOT** verbatim: Cata is 66 fields / 264 bytes
--                              against our 58 / 232, so the trailing 8 Cata-only
--                              fields are dropped and the rest re-mapped
--
-- Generated by `tools/gen_shadowfang_vehicle_r39.py` (WANT_VEHICLES = [1422] on
-- top of `gen_hyjal_vehicle_downport.py`). That generator **self-validates**:
-- it re-decodes seat 7683 and asserts it matches the hand-verified row 82_
-- already shipped before emitting anything, so a wrong field-classification
-- assumption trips an assert instead of shipping garbage. It printed
-- "layout self-check OK" for this run.
--
-- CLIENT HALF IS ALREADY DONE AND VERIFIED (this file is only the server half):
--   Custom/CSV DBC/Vehicle.csv      508 -> 509 rows
--   Custom/CSV DBC/VehicleSeat.csv  904 -> 905 rows
--   recompiled, strict-superset checked (0 ids lost, exactly 1 gained each),
--   and written into patch-4 AND enGB/patch-enGB-3 -- both re-extracted
--   afterwards and confirmed to carry 1422 / 9362. Also synced to the three
--   WarcraftXL checkouts and to Server/data/dbc. Backups: *.pre-r39veh.bak.
--   **The live server's data/dbc copy still needs pushing.**
--
-- 🔴 AND A WARNING FOR THE NEXT DEPLOY: writing those archives with a bash loop
-- re-created the `DBFilesClient$t.dbc` junk entry this project has hit before --
-- `"...=DBFilesClient\$t.dbc"` inside double quotes does not produce what you
-- expect. Four junk entries went into the two archives before I noticed. They
-- were removed with `mpq_stormlib_remove.py` and both archives re-verified.
-- **Drive mpq_stormlib_patch.py with `--set-file` manifests, never a shell
-- loop** -- a manifest has no quoting layer to get wrong.
--
-- Apply against acore_world, then restart worldserver. Idempotent.
--
-- NOTE both templates already carry VehicleId 1422, so there is no
-- creature_template UPDATE here -- the ids were never zeroed. Once these rows
-- exist the ids simply resolve.

DELETE FROM `vehicleseat_dbc` WHERE `ID` IN (9362);

INSERT INTO `vehicleseat_dbc` (`ID`, `Flags`, `AttachmentID`, `AttachmentOffsetX`, `AttachmentOffsetY`, `AttachmentOffsetZ`, `EnterPreDelay`, `EnterSpeed`, `EnterGravity`, `EnterMinDuration`, `EnterMaxDuration`, `EnterMinArcHeight`, `EnterMaxArcHeight`, `EnterAnimStart`, `EnterAnimLoop`, `RideAnimStart`, `RideAnimLoop`, `RideUpperAnimStart`, `RideUpperAnimLoop`, `ExitPreDelay`, `ExitSpeed`, `ExitGravity`, `ExitMinDuration`, `ExitMaxDuration`, `ExitMinArcHeight`, `ExitMaxArcHeight`, `ExitAnimStart`, `ExitAnimLoop`, `ExitAnimEnd`, `PassengerYaw`, `PassengerPitch`, `PassengerRoll`, `PassengerAttachmentID`, `VehicleEnterAnim`, `VehicleExitAnim`, `VehicleRideAnimLoop`, `VehicleEnterAnimBone`, `VehicleExitAnimBone`, `VehicleRideAnimLoopBone`, `VehicleEnterAnimDelay`, `VehicleExitAnimDelay`, `VehicleAbilityDisplay`, `EnterUISoundID`, `ExitUISoundID`, `UiSkin`, `FlagsB`, `CameraEnteringDelay`, `CameraEnteringDuration`, `CameraExitingDelay`, `CameraExitingDuration`, `CameraOffsetX`, `CameraOffsetY`, `CameraOffsetZ`, `CameraPosChaseRate`, `CameraFacingChaseRate`, `CameraEnteringZoom`, `CameraSeatZoomMin`, `CameraSeatZoomMax`) VALUES
(9362, 33587215, 1, 0, 0, 0, 0, 7, 19.290001, 0, 0, 1, 4, 37, 38, -1, 102, 128, 123, 0, 7, 19.290001, 0, 0, 1, 4, 37, 38, 39, 0, 0, 0, 34, -1, -1, -1, -1, -1, -1, 0, 0, 1, 0, 0, 0, 33554432, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

DELETE FROM `vehicle_dbc` WHERE `ID` IN (1422);

INSERT INTO `vehicle_dbc` (`ID`, `Flags`, `TurnSpeed`, `PitchSpeed`, `PitchMin`, `PitchMax`, `SeatID_1`, `SeatID_2`, `SeatID_3`, `SeatID_4`, `SeatID_5`, `SeatID_6`, `SeatID_7`, `SeatID_8`, `MouseLookOffsetPitch`, `CameraFadeDistScalarMin`, `CameraFadeDistScalarMax`, `CameraPitchOffset`, `FacingLimitRight`, `FacingLimitLeft`, `MsslTrgtTurnLingering`, `MsslTrgtPitchLingering`, `MsslTrgtMouseLingering`, `MsslTrgtEndOpacity`, `MsslTrgtArcSpeed`, `MsslTrgtArcRepeat`, `MsslTrgtArcWidth`, `MsslTrgtImpactRadius_1`, `MsslTrgtImpactRadius_2`, `MsslTrgtArcTexture`, `MsslTrgtImpactTexture`, `MsslTrgtImpactModel_1`, `MsslTrgtImpactModel_2`, `CameraYawOffset`, `UilocomotionType`, `MsslTrgtImpactTexRadius`, `VehicleUIIndicatorID`, `PowerDisplayID_1`, `PowerDisplayID_2`, `PowerDisplayID_3`) VALUES
(1422, 1073877031, 3.142, 3.142, 0, 0, 9362, 0, 0, 0, 0, 0, 0, 0, 0.785398, 1, 1.5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, NULL, NULL, NULL, 0, 0, 0, 0, 0, 0, 0);

-- ---------------------------------------------------------------------------
-- Verify after apply
-- ---------------------------------------------------------------------------
--   SELECT COUNT(*) FROM vehicle_dbc     WHERE ID = 1422;                  -> 1
--   SELECT COUNT(*) FROM vehicleseat_dbc WHERE ID = 9362;                  -> 1
--   SELECT SeatID_1 FROM vehicle_dbc WHERE ID = 1422;                   -> 9362
--
--   Next boot: both "non-existing VehicleId (1422) ... WILL cause the client to
--   freeze" lines gone. That is the whole crash-class content of this log.
--
--   THE CHECK THAT ACTUALLY MATTERS is in-game, and the log cannot tell you:
--   pull Baron Ashbury on map 825 with a client that has the refreshed patch-4 /
--   patch-enGB-3 and confirm the client does not hang when his vehicle mechanic
--   fires. A quiet boot log only proves the server resolved the id.
--
-- REVERT
--   DELETE FROM vehicle_dbc     WHERE ID = 1422;
--   DELETE FROM vehicleseat_dbc WHERE ID = 9362;
--   -- and if you want the freeze risk gone WITHOUT the mechanic, the fallback
--   -- rounds 66_/82_ used is: UPDATE creature_template SET VehicleId = 0
--   --   WHERE entry IN (5046962, 5049708);
