-- ---------------------------------------------------------------------------
-- 298  Plaguelands + Shadowfang leftovers -- locks, GO spells, difficulty, wander
-- ---------------------------------------------------------------------------
-- Errors.log is 56 lines. This clears 13 of them across four small classes, all
-- from the map 751 / 825 imports.
--
--   1  2 GO spells (server half; the DBC half is already deployed)
--   2  7 difficulty variants carrying a ScriptName
--   3  2 spawns with wander_distance but MovementType 0
--   4  2 Lock.dbc ids -- DBC-only, no SQL, recorded here
--
-- 🔴 THE LOCK ERROR NAMES THE WRONG FIELD, AND TAKING IT LITERALLY WOULD BREAK
-- WORKING DATA.
--     Gameobject (Entry: 4601557 GoType: 10) have data0=24985 but lock
--       (Id: 24985) not found.
--     Gameobject (Entry: 4601628 GoType: 3)  have data0=4601628 but lock
--       (Id: 4601628) not found.
-- Both say "data0" and then print a value that is actually **Data1**:
--   4601557 "Lillith's Dinner Table" (GOOBER) Data0=1856  Data1=24985
--   4601628 "Grave Moss"             (CHEST)  Data0=1945  Data1=4601628
-- and for those two types Data1 is the questId and the lootId -- both correct.
-- 4601628's Data1 is simply the lootid == entry convention from 232_.
-- Settled it against Lock.dbc rather than the message: **1856 and 1945 are both
-- absent** (405 records), while 1691 -- the lock on the neighbouring Book of
-- Lost Souls -- is present and produces no error. So the real defect is Data0 in
-- both cases and the printed value is a red herring.
-- (ObjectMgr.cpp:7852/7885 do pass chest.lockId / goober.lockId with N=0, and
-- both are raw.data[0] per GameObjectData.h -- so the running binary and this
-- source tree disagree here. Trust the DBC lookup, not the label.)
--
-- FIXED IN THE DBC, NOT IN SQL. Locks 1856 and 1945 both exist in the Cata 4.3.4
-- client and Lock.dbc is **33 fields / 132 bytes on both sides**, so they copy
-- verbatim. Generated by tools/gen_plaguelands_locks_r40.py:
--     Lock 1856  slot1 ITEM  = 3080 "Candle of Beckoning"  (verified present)
--     Lock 1945  slot1 SKILL = 2     Herbalism -- correct for a herb node
-- Lock.csv 405 -> 407, recompiled (0 ids lost, exactly 2 gained), deployed to
-- patch-4 + enGB-3 + the three WXL checkouts + Server/data/dbc.
-- Nothing for this file to do -- the GO templates already point at the right ids.

-- ---------------------------------------------------------------------------
-- 1) 2 gameobject spellcaster spells
-- ---------------------------------------------------------------------------
--     Gameobject (Entry: 4805165 GoType: 22) have data0=83837 but Spell
--       (Entry 83837) not exist.
--   4805165 "Sea Dog Crate"        (11 spawns, map 751) -> 83837 Pick Up Orc Crate
--   4805417 "7th Legion Telescope" (1 spawn,   map 751) -> 84936 Summon Gilneas Camera
-- Both screen CLEAN (effect 140; no stealth/invisibility/phase aura; effect id
-- well under the 165 crash bound) and neither uses TARGET_DEST_DB, so unlike the
-- 95303/95305 pair deferred in 296_ these need no spell_target_position row.
--
-- 🔴 THE CLIENT HALF NEARLY DESTROYED 13 SPELLS. Rebuilding Spell.dbc from
-- Custom/CSV DBC/Spell.csv with csv2wdbc produced 54,109 records against the
-- deployed 54,120 -- **13 ids exist in the DBC that are NOT in the CSV**, so a
-- straight recompile would have silently deleted them (91310, 91311, 96890,
-- 96891, 96927, 96977, 96993, 97139 and five more). The CSV is not the source of
-- truth for this table. Used spell-dbc-append.py instead, which adds rows to the
-- existing DBC: 54,120 -> 54,122, **0 ids lost**. Deployed to patch-4 + enGB-3 +
-- checkouts + Server/data/dbc.
-- **Never rebuild the 234-field fork Spell.dbc from CSV -- always append.**

DELETE FROM acore_world.`spell_dbc` WHERE `ID` IN (83837,84936);

INSERT INTO acore_world.`spell_dbc` VALUES
('83837','0','0','0','696254464','1056','273170437','1245696','8388736','393224','4608','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','3','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','140','0','0','0','0','0','0','0','0','0','0','0','0','0','0','25','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','83838','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Pick Up Orc Crate','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0'),
('84936','0','0','0','696254848','1056','273170437','269681152','8388736','393224','4608','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','13','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','140','0','0','0','0','0','0','0','0','0','0','0','0','0','0','25','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','84882','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Summon Gilneas Camera','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0');

-- ---------------------------------------------------------------------------
-- 2) 7 difficulty variants that carry a ScriptName
-- ---------------------------------------------------------------------------
--     Creature (Entry: 5003887) lists difficulty 1 mode entry 5049709 with
--     `ScriptName` filled in. `ScriptName` of difficulty 0 mode creature is
--     always used instead.
--
-- Same class as 283_, and provably a no-op: every one of the seven variants
-- carries the **identical** ScriptName to its parent, so the core preferring the
-- parent's changes nothing.
--     5003887 Baron Silverlaine    -> 5049709  boss_baron_silverlaine
--     5004278 Commander Springvale -> 5049710  boss_commander_springvale
--     5046962 Baron Ashbury        -> 5049708  boss_baron_ashbury
--     5046963 Lord Walden          -> 5049711  boss_lord_walden
--     5046964 Lord Godfrey         -> 5049712  boss_lord_godfrey
--     5050613 Wailing Guardsman    -> 5050614  npc_wailing_guardsman
--     5050615 Tormented Officer    -> 5050616  npc_tormented_officer
-- Guarded on the parent still holding the SAME name, so this cannot strip a
-- variant that was deliberately given different behaviour.
UPDATE acore_world.`creature_template` v
JOIN acore_world.`creature_template` p
  ON (p.`difficulty_entry_1` = v.`entry` OR p.`difficulty_entry_2` = v.`entry`
      OR p.`difficulty_entry_3` = v.`entry`)
SET v.`ScriptName` = ''
WHERE v.`ScriptName` <> ''
  AND p.`ScriptName` = v.`ScriptName`;

-- ---------------------------------------------------------------------------
-- 3) 2 spawns with a wander distance they cannot use
-- ---------------------------------------------------------------------------
--     Table `creature` have creature (SpawnId: 16714534 Entry: 4139080) with
--     `MovementType`=0 (idle) have `wander_distance`<>0, set to 0.
--
-- Both on map 751, both wander_distance 10 with MovementType 0 (idle). The core
-- zeroes it at load, so this only makes the DB agree with what runs.
-- Deliberately NOT the other reading: setting MovementType to 1 would start two
-- NPCs wandering that the import placed as stationary -- a content change dressed
-- up as a log fix.
UPDATE acore_world.`creature` SET `wander_distance` = 0
 WHERE `MovementType` = 0 AND `wander_distance` <> 0;

-- ---------------------------------------------------------------------------
-- Verify after apply
-- ---------------------------------------------------------------------------
--  1  SELECT COUNT(*) FROM spell_dbc WHERE ID IN (83837, 84936);            -> 2
--  2  SELECT COUNT(*) FROM creature_template v
--       JOIN creature_template p ON (p.difficulty_entry_1=v.entry
--         OR p.difficulty_entry_2=v.entry OR p.difficulty_entry_3=v.entry)
--      WHERE v.ScriptName <> '';                                            -> 0
--     -- the PARENTS must keep theirs:
--     SELECT COUNT(*) FROM creature_template
--      WHERE entry IN (5003887,5004278,5046962,5046963,5046964,5050613,5050615)
--        AND ScriptName <> '';                                              -> 7
--  3  SELECT COUNT(*) FROM creature WHERE MovementType=0 AND wander_distance<>0;
--                                                                           -> 0
--  4  Locks are DBC-side: once the live data/dbc has the refreshed Lock.dbc the
--     two "but lock (Id: ...) not found" lines go. In-game, Grave Moss on 751
--     should be herbable and Lillith's Dinner Table should want a Candle of
--     Beckoning.
--
--  Next boot: 13 of the 56 lines gone (2 lock + 2 GO spell + 7 difficulty +
--  2 wander).
--
-- ---------------------------------------------------------------------------
-- Still open in this log, unchanged
-- ---------------------------------------------------------------------------
-- * 8 dangling loot ids -- blocked on the 5 Cata quest items (60741, 60953,
--   60871-3) and 69988, per 296_'s footer. One item downport clears all of them.
-- * GO 5400038 "Book of Lost Souls" displayId 9901 "not loaded" -- 1 spawn on
--   825, 2 templates share the id. Cata HAS display 9901 but
--   GameObjectDisplayInfo is **21 fields there against our 19**, so it needs a
--   field remap like VehicleSeat did, plus the model must exist in the client.
--   Left for a display round rather than guessed at.
-- * SmartAI spells 95303/95305 -- deferred in 296_: each needs a
--   spell_target_position row and cata has a destination for only one.
-- * 8 unassigned scripts, 6 spell-script effect mismatches, 2 upstream waypoint
--   gaps, the stock loot-chance lines, the pickpocket/skinning/reference
--   orphans, and OutdoorPvP type 8 -- all previously triaged as not-DB-fixes.
