-- ---------------------------------------------------------------------------
-- 324  Clean up the four loot references 322_ left without a consumer
-- ---------------------------------------------------------------------------
-- Post-apply check of the worldserver boot log after 319_/321_/322_/323_ found
-- four new "isn't reference id and not referenced from loot, and thus useless"
-- warnings, and nothing else. The loot works -- these are startup noise, not
-- failures -- but they are noise those files introduced, so they get cleaned.
--
--   752080   492 rows   the band-80 rare pool 322_ builds
--   751081   110 rows   band clone of stock ref 34003
--   751082    15 rows   band clone of stock ref 34008
--   751083     5 rows   band clone of stock ref 34010
--
-- 🔴 752080 CAN NEVER BE USED. 322_ builds one rare pool per band, but a rare
-- draws from the band ABOVE its own, and the lowest-level rank >= 2 creature on
-- the continent is level 90 -- which promotes to band 88. Nothing promotes TO
-- band 80, so its pool is dead by construction, not by accident. Verified: the
-- only references actually attached are 752088, 752096, 752104 and 752113.
-- 322_ is corrected at source as well, so a fresh apply never creates it.
--
-- 751081/751082/751083 were orphaned BY 322_: they were reachable only from the
-- rank-3 boss whose band-floor gear rows 322_ strips. Their items still exist
-- and are still reachable through the 752xxx pools, so nothing becomes
-- unlootable -- only the now-unreferenced reference rows go.
--
-- ROLLBACK: 751081-751083 are regenerated by re-running 313_; 752080 by
-- re-running the ORIGINAL 322_ (the pre-correction version). Neither holds
-- state -- both are derived tables.
--
-- Apply against acore_world, after 322_. Idempotent.
-- ---------------------------------------------------------------------------

USE `acore_world`;

-- The band-80 rare pool: built, never attachable.
DELETE FROM `reference_loot_template` WHERE `Entry` = 752080;

-- Orphaned when 322_ stripped the rank-3 boss's band-floor gear.
DELETE FROM `reference_loot_template` WHERE `Entry` IN (751081, 751082, 751083);

-- ---------------------------------------------------------------------------
-- Trailer -- verification
-- ---------------------------------------------------------------------------
-- All four gone (expect 0):
-- SELECT COUNT(*) FROM reference_loot_template
-- WHERE Entry IN (751081, 751082, 751083, 752080);
--
-- No DC reference left without a consumer (expect 0):
-- SELECT rlt.Entry, COUNT(*) rows_ FROM reference_loot_template rlt
-- WHERE rlt.Entry BETWEEN 750000 AND 752999
--   AND NOT EXISTS (SELECT 1 FROM creature_loot_template c WHERE c.Reference = rlt.Entry)
--   AND NOT EXISTS (SELECT 1 FROM reference_loot_template r2 WHERE r2.Reference = rlt.Entry)
--   AND NOT EXISTS (SELECT 1 FROM gameobject_loot_template g WHERE g.Reference = rlt.Entry)
-- GROUP BY rlt.Entry;
--
-- The four live rare pools still intact (expect 1196 / 110 / 637 / 101):
-- SELECT Entry, COUNT(*) FROM reference_loot_template
-- WHERE Entry BETWEEN 752080 AND 752113 GROUP BY Entry ORDER BY Entry;
--
-- After the next restart, Errors.log should carry none of the four warnings.
-- ---------------------------------------------------------------------------
