-- ---------------------------------------------------------------------------
-- 10  Faction bases: Jaina's Encampment (Alliance) + Thrall's Vanguard (Horde)
-- ---------------------------------------------------------------------------
-- Map 750 has NO Alliance or Horde presence -- every NPC on it is neutral
-- (Guardians of Hyjal 2252 / 2233, or 35). Zero faction-12 and zero faction-29
-- creatures, so neither side has a base, an innkeeper to bind at, or a
-- quartermaster of its own.
--
-- The rosters already exist as `creature_template` rows WITH complete vendor
-- stock (288 npc_vendor lines across 16 vendors, 0 missing items, 0 missing
-- ItemExtendedCost rows). They were authored for the superseded map 1410 and
-- never placed. This file re-homes them; nothing is re-authored.
--
-- PLACEMENT (revised after in-game testing -- the first pass floated):
--   * Centres come from a verified `.gps` reading where **GroundZ == FloorZ**.
--     Where those two differ there is a VMAP object above the terrain and
--     anything placed there stands on the object or clips into it.
--   * Rings are deliberately tight. The Grove of Aessina shelf is flat to
--     within ~0.6 yd out to ~13 yd but climbs to 1210.8 by 20 yd westward, so
--     the original 18 yd ring ran half the town onto a slope.
--
-- Generated by Custom/Documentation/scripts/gen_hyjal_camps.py -- edit the CAMPS
-- table there and re-run rather than hand-editing this file.
--
-- GUID block 9020000-9020499 (verified empty). Idempotent.
-- ---------------------------------------------------------------------------

-- 1. Retire the map-1410 placements (that map is superseded).
DELETE FROM `creature` WHERE `id` BETWEEN 830000 AND 830999 AND `map` = 1410;

-- 2. Place the camps on map 750.
DELETE FROM `creature` WHERE `guid` BETWEEN 9020000 AND 9020499;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`,
    `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`,
    `wander_distance`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`,
    `unit_flags`, `dynamicflags`, `ScriptName`, `VerifiedBuild`, `CreateObject`, `Comment`) VALUES
(9020000, 830023, 750, 4923, 4923, 1, 1, 0, 4456.500, -2077.470, 1206.250, 3.142, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Innkeeper Cerelina'),
(9020001, 830024, 750, 4923, 4923, 1, 1, 0, 4454.758, -2070.970, 1206.250, 3.665, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Emberwood Sap Quartermaster'),
(9020002, 830135, 750, 4923, 4923, 1, 1, 0, 4450.000, -2066.212, 1206.250, 4.189, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Banker'),
(9020003, 830136, 750, 4923, 4923, 1, 1, 0, 4443.500, -2064.470, 1206.250, 4.712, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Auctioneer'),
(9020004, 830137, 750, 4923, 4923, 1, 1, 0, 4437.000, -2066.212, 1206.250, 5.236, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Provisioner'),
(9020005, 830138, 750, 4923, 4923, 1, 1, 0, 4432.242, -2070.970, 1206.250, 5.760, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Trader'),
(9020006, 830139, 750, 4923, 4923, 1, 1, 0, 4430.500, -2077.470, 1206.250, 0.000, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Cook'),
(9020007, 830140, 750, 4923, 4923, 1, 1, 0, 4432.242, -2083.970, 1206.250, 0.524, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Alchemist'),
(9020008, 830141, 750, 4923, 4923, 1, 1, 0, 4437.000, -2088.728, 1206.250, 1.047, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Weaponsmith'),
(9020009, 830142, 750, 4923, 4923, 1, 1, 0, 4443.500, -2090.470, 1206.250, 1.571, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Armorer'),
(9020010, 830143, 750, 4923, 4923, 1, 1, 0, 4450.000, -2088.728, 1206.250, 2.094, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Stable Master'),
(9020011, 830144, 750, 4923, 4923, 1, 1, 0, 4454.758, -2083.970, 1206.250, 2.618, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Tabard Vendor'),
(9020012, 830021, 750, 4923, 4923, 1, 1, 0, 4457.356, -2069.470, 1206.250, 0.524, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Guard'),
(9020013, 830021, 750, 4923, 4923, 1, 1, 0, 4443.500, -2061.470, 1206.250, 1.571, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Guard'),
(9020014, 830021, 750, 4923, 4923, 1, 1, 0, 4429.644, -2069.470, 1206.250, 2.618, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Encampment Guard'),
(9020015, 830161, 750, 4923, 4923, 1, 1, 0, 4429.644, -2085.470, 1206.250, 3.665, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Hyjal Frontier Soldier'),
(9020016, 830161, 750, 4923, 4923, 1, 1, 0, 4443.500, -2093.470, 1206.250, 4.712, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Hyjal Frontier Soldier'),
(9020017, 830161, 750, 4923, 4923, 1, 1, 0, 4457.356, -2085.470, 1206.250, 5.760, 300, 0, 0, 0, 0, 0, 0, 0, 0, '', NULL, 0, 'Jaina''s Encampment - Hyjal Frontier Soldier');

-- PENDING, not emitted (no verified GroundZ == FloorZ coordinate yet):
--   Thrall's Vanguard -- guids 9020030+, PENDING verified ground coordinate
