-- Plaguelands (DCPlaguelands, map 751)
-- dc_entry = 3,600,000 + original (isolated, tunable). Source cata_world(TDB434)->acore_world. Cross-DB INSERT...SELECT.
SET @OFF := 3600000;

-- GameObjects cloned to dc_entry = original+@OFF too (consistent with creatures, isolated/tunable).
INSERT IGNORE INTO acore_world.gameobject_template (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `AIName`, `ScriptName`, `VerifiedBuild`)
SELECT `entry`+@OFF, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `AIName`, `ScriptName`, `VerifiedBuild` FROM cata_world.gameobject_template WHERE entry IN (SELECT DISTINCT g.id FROM cata_world.gameobject g WHERE (g.map=0 AND g.zoneId IN (139,28))) AND entry NOT IN (SELECT entry FROM acore_world.gameobject_template WHERE entry < @OFF);
INSERT IGNORE INTO acore_world.gameobject_template (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `AIName`, `ScriptName`, `VerifiedBuild`)
SELECT `entry`+@OFF, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `Data2`, `Data3`, `Data4`, `Data5`, `Data6`, `Data7`, `Data8`, `Data9`, `Data10`, `Data11`, `Data12`, `Data13`, `Data14`, `Data15`, `Data16`, `Data17`, `Data18`, `Data19`, `Data20`, `Data21`, `Data22`, `Data23`, `AIName`, `ScriptName`, `VerifiedBuild` FROM acore_world.gameobject_template WHERE entry IN (SELECT DISTINCT g.id FROM cata_world.gameobject g WHERE (g.map=0 AND g.zoneId IN (139,28))) AND entry < @OFF;
INSERT IGNORE INTO acore_world.gameobject_template_addon (`entry`, `faction`, `flags`, `mingold`, `maxgold`, `artkit0`, `artkit1`, `artkit2`, `artkit3`)
SELECT `entry`+@OFF, `faction`, `flags`, `mingold`, `maxgold`, `artkit0`, `artkit1`, `artkit2`, `artkit3` FROM cata_world.gameobject_template_addon WHERE entry IN (SELECT DISTINCT g.id FROM cata_world.gameobject g WHERE (g.map=0 AND g.zoneId IN (139,28))) AND entry NOT IN (SELECT entry FROM acore_world.gameobject_template WHERE entry < @OFF);
INSERT IGNORE INTO acore_world.gameobject_template_addon (`entry`, `faction`, `flags`, `mingold`, `maxgold`, `artkit0`, `artkit1`, `artkit2`, `artkit3`)
SELECT `entry`+@OFF, `faction`, `flags`, `mingold`, `maxgold`, `artkit0`, `artkit1`, `artkit2`, `artkit3` FROM acore_world.gameobject_template_addon WHERE entry IN (SELECT DISTINCT g.id FROM cata_world.gameobject g WHERE (g.map=0 AND g.zoneId IN (139,28))) AND entry IN (SELECT entry FROM acore_world.gameobject_template WHERE entry < @OFF) AND entry < @OFF;
