-- 102_wander_restore.sql -- map 751 extension, DB step 40.
--
-- GENERATED by Custom/Documentation/scripts/gen_summon_and_wander_repairs.py.
--
-- "Silverpine Forest spawns seem pretty static, no wandering waypoints mostly".
--
-- MEASURED, NOT ASSUMED, AND THE FIRST ANSWER WAS THAT NOTHING IS WRONG:
-- Silverpine on 751 has 591 wandering spawns out of 4,026, and `cata_world` has
-- EXACTLY the same 591 -- so the import copied its source faithfully.
--
-- What gave it away was the neighbour: Tirisfal on the same map runs 48%
-- wandering against Silverpine's 15%. cata_world is a KNOWN MovementType-stripped
-- source, so the source itself is the defect. Cross-checking every static 751
-- spawn against nelt_world by creature ENTRY finds 3,068 spawns -- 1,502 of them
-- in Silverpine -- whose entry demonstrably wanders in nelt but is pinned here.
--
-- CONSERVATIVE BY CONSTRUCTION. A spawn is touched only when ALL hold:
--   * currently MovementType 0 AND wander_distance 0
--   * its base entry wanders in nelt_world with spawndist > 0
--   * it is NOT in a creature_formation -- moving one member breaks the group
--   * it has no waypoint path of its own (creature_addon.path_id) and no
--     SmartAI waypoint script, so nothing scripted is overridden
-- wander_distance takes nelt's median spawndist for that entry, clamped 3..15 so
-- one odd source value cannot send a mob wandering across the zone.

UPDATE `creature` c
JOIN (
    SELECT n.`id` AS id,
           LEAST(15, GREATEST(3, ROUND(AVG(n.`spawndist`)))) AS dist
    FROM `nelt_world`.`creature` n
    WHERE n.`MovementType` = 1 AND n.`spawndist` > 0
    GROUP BY n.`id`
) w ON w.`id` = (CASE WHEN c.`id` >= 4100000 THEN c.`id` - 4100000 WHEN c.`id` >= 3600000 THEN c.`id` - 3600000 ELSE c.`id` END)
SET c.`MovementType` = 1, c.`wander_distance` = w.`dist`
WHERE c.`map` = 751
  AND c.`MovementType` = 0 AND c.`wander_distance` = 0
  AND NOT EXISTS (SELECT 1 FROM `creature_formations` f WHERE f.`memberGUID` = c.`guid`)
  AND NOT EXISTS (SELECT 1 FROM `creature_addon` a WHERE a.`guid` = c.`guid` AND a.`path_id` > 0)
  AND NOT EXISTS (SELECT 1 FROM `smart_scripts` s WHERE s.`source_type` = 0
                    AND s.`entryorguid` = c.`id` AND s.`action_type` IN (53, 54));

-- ---------------------------------------------------------------------------
-- Verification
-- ---------------------------------------------------------------------------
SELECT 'map-751 spawns now wandering' AS what, COUNT(*) AS n
  FROM `creature` WHERE `map` = 751 AND `MovementType` = 1
UNION ALL SELECT '  ...in Silverpine', COUNT(*) FROM `creature`
  WHERE `map` = 751 AND `MovementType` = 1
    AND `position_y` BETWEEN -750 AND 3450 AND `position_x` BETWEEN -1133 AND 1667
UNION ALL SELECT 'formation members accidentally set wandering (want 0)', COUNT(*)
  FROM `creature` c JOIN `creature_formations` f ON f.`memberGUID` = c.`guid`
  WHERE c.`map` = 751 AND c.`MovementType` = 1
UNION ALL SELECT 'waypoint spawns accidentally set wandering (want 0)', COUNT(*)
  FROM `creature` c JOIN `creature_addon` a ON a.`guid` = c.`guid` AND a.`path_id` > 0
  WHERE c.`map` = 751 AND c.`MovementType` = 1;
