-- 109_boot_log_cleanup.sql -- creature display / faction / gossip boot errors, DB step 48.
--
-- GENERATED by Custom/Documentation/scripts/gen_109_boot_log_cleanup.py.
--
-- Three unrelated things out of one boot log, plus one that is NOT a defect.
--
-- ===========================================================================
-- 0. THE ~50 'deprecated flags_extra' LINES ARE NOT AN ERROR -- IGNORE THEM
-- ===========================================================================
--   "has deprecated flags_extra bit IMMUNITY_KNOCKBACK (0x40000000) set. This will
--    be migrated to the `creature_immunities` table in a future update."
--
--   That is the core announcing its OWN future migration. Nothing is broken, the
--   immunities still apply, and hand-migrating them now would fight the upgrade that is
--   coming. They are also almost all stock/Cata entries (51456-51461, 49973-49987, ...)
--   rather than map-751 content. Deliberately not touched.
--
-- ===========================================================================
-- 1. TWO MAP-751 NPCs THAT CANNOT BE TALKED TO -- the only gameplay bug in this log
-- ===========================================================================
--   "has assigned gossip menu N, but npcflag does not include UNIT_NPC_FLAG_GOSSIP (1)"
--   Both are spawned on map 751 and both have a real gossip menu, so today a player
--   walks up to them and gets no conversation at all.
--
--     4102239  Drull           menu 262    npcflag 0 -> 1
--     4136517  Aleric Hawkins  menu 10813  npcflag 2 -> 3   (keeps QUESTGIVER)
--
--   OR-ing the bit rather than assigning it, so Aleric keeps his questgiver flag.

UPDATE `creature_template` SET `npcflag` = `npcflag` | 1
WHERE `entry` IN (4102239, 4136517) AND (`npcflag` & 1) = 0;

-- ===========================================================================
-- 2. TWO NON-EXISTING FACTION TEMPLATES
-- ===========================================================================
--     39038  Lilian Voss                              faction 2237
--     42597  Revantusk Troll Drums Buff Credit Bunny  faction 2273
--
--   Cata faction templates that were never downported. NEITHER CREATURE IS SPAWNED
--   (0 rows in `creature`), so this is log noise rather than a live problem -- but an
--   unresolvable faction makes a creature hostile to everything if it is ever summoned,
--   so both are pointed at sane existing templates:
--     2237 -> 1665   Lilian Voss is a Forsaken questline NPC (friendly undead)
--     2273 ->   35   a credit bunny should be friendly to everyone

UPDATE `creature_template` SET `faction` = 1665 WHERE `entry` = 39038 AND `faction` = 2237;
UPDATE `creature_template` SET `faction` = 35   WHERE `entry` = 42597 AND `faction` = 2273;

-- ===========================================================================
-- 3. 29 CREATURES WITH A DISPLAY ID THE CLIENT DOES NOT HAVE
-- ===========================================================================
--   "lists non-existing CreatureDisplayID id (NNNNN), this can crash the client."
--
--   THIS IS THE FOLLOW-UP 100_ PREDICTED. When 100_ imported the 66 spell-summoned
--   creatures it explicitly did not claim display coverage; this is that pass.
--
--   Every one of the 29 has ZERO spawns -- they exist only as the target of a summon
--   effect (verified: 28 of them appear in Spell.dbc EffectMiscValue_1/2), so the crash
--   risk is real but only fires if the summoning spell is ever cast. They are guild-perk
--   props, companion pets and event visuals.
--
--   REPOINTED, NOT DOWNPORTED. 27 of the 29 display ids are absent from our own
--   CreatureDisplayInfo.dbc as well, so a proper fix means downporting 27 models plus
--   their CreatureModelData and the client M2s -- for content that is not obtainable
--   here. Repointing at an existing analogue removes the crash risk now and is trivially
--   reversible if the models are ever downported.
--
--   EVERY SUBSTITUTE WAS VERIFIED AGAINST THE BINARY CreatureDisplayInfo.dbc, not the
--   `creaturedisplayinfo_dbc` table. That table is a sparse overlay and checking against
--   it reports almost every valid display as missing -- the same trap as `spell_dbc` in
--   108_, hit twice in one session.
--
-- entry     name                             bad -> new
--   39145   Mud                               31327 -> 358    Ooze
--   39160   Jeweled Serpent                   36878 -> 169    serpent / whelp
--   42895   Tornado                           31882 -> 20211  Tornado
--   43719   Unpowered Golem                   33492 -> 367    Bile Golem
--   47944   Dark Phoenix Hatchling            37136 -> 169    hatchling
--   48115   Guild Battle Standard             36162 -> 14541  Alliance Battle Standard
--   48242   Armadillo Pup                     36220 -> 1072   Brown Prairie Dog, a small critter pet
--   48633   Guild Battle Standard             36214 -> 14541  Alliance Battle Standard
--   48634   Guild Battle Standard             36215 -> 14541  Alliance Battle Standard
--   48636   Guild Battle Standard             36216 -> 14542  Horde Battle Standard
--   48637   Guild Battle Standard             36217 -> 14542  Horde Battle Standard
--   48638   Guild Battle Standard             36218 -> 14542  Horde Battle Standard
--   48846   Goblin Pocket-Nuke                36302 -> 31484  Footbomb Uniform, a bomb prop
--   49176   Brazie the Botanist               36612 -> 36575  the OTHER Brazie the Botanist (4149687) -- same name, real display
--   49405   Blackwing Descent Transform       36457 -> 11686  invisible -- a transform helper, never actually seen
--   49426   Deathguard Darnell                36497 -> 1588   Deathguard Oliver
--   49586   Guild Page                        37200 -> 328    Footman
--   49587   Guild Herald                      37198 -> 5187   Argent Tournament Herald
--   49588   Guild Page                        37199 -> 328    Footman
--   49590   Guild Herald                      37196 -> 5187   Argent Tournament Herald
--   50380   Risen Dead j                      36775 -> 36774  Risen Dead (50374) -- the non-j twin, adjacent display id
--   51090   Singing Sunflower                 37154 -> 28178  Kat Sunflower
--   53475   Cauterizing Flame                 38375 -> 11686  invisible -- a pure spell effect
--   53590   Moat Monster                      30165 -> 525    Water Elemental
--   53883   Moonwell                          38538 -> 11686  invisible -- a moonwell is normally a gameobject
--   54027   Lil' Tarecgosa                    38614 -> 169    whelp
--   57220   Tentacle of the Old Ones          33547 -> 15788  Claw Tentacle
--   58077   Tentacle of the Old Ones          33547 -> 15788  Claw Tentacle
--   58078   Tentacle of the Old Ones          33547 -> 15788  Claw Tentacle

UPDATE `creature_template_model` SET `CreatureDisplayID` = 358
WHERE `CreatureID` = 39145 AND `CreatureDisplayID` = 31327;   -- Mud
UPDATE `creature_template_model` SET `CreatureDisplayID` = 169
WHERE `CreatureID` = 39160 AND `CreatureDisplayID` = 36878;   -- Jeweled Serpent
UPDATE `creature_template_model` SET `CreatureDisplayID` = 20211
WHERE `CreatureID` = 42895 AND `CreatureDisplayID` = 31882;   -- Tornado
UPDATE `creature_template_model` SET `CreatureDisplayID` = 367
WHERE `CreatureID` = 43719 AND `CreatureDisplayID` = 33492;   -- Unpowered Golem
UPDATE `creature_template_model` SET `CreatureDisplayID` = 169
WHERE `CreatureID` = 47944 AND `CreatureDisplayID` = 37136;   -- Dark Phoenix Hatchling
UPDATE `creature_template_model` SET `CreatureDisplayID` = 14541
WHERE `CreatureID` = 48115 AND `CreatureDisplayID` = 36162;   -- Guild Battle Standard
UPDATE `creature_template_model` SET `CreatureDisplayID` = 1072
WHERE `CreatureID` = 48242 AND `CreatureDisplayID` = 36220;   -- Armadillo Pup
UPDATE `creature_template_model` SET `CreatureDisplayID` = 14541
WHERE `CreatureID` = 48633 AND `CreatureDisplayID` = 36214;   -- Guild Battle Standard
UPDATE `creature_template_model` SET `CreatureDisplayID` = 14541
WHERE `CreatureID` = 48634 AND `CreatureDisplayID` = 36215;   -- Guild Battle Standard
UPDATE `creature_template_model` SET `CreatureDisplayID` = 14542
WHERE `CreatureID` = 48636 AND `CreatureDisplayID` = 36216;   -- Guild Battle Standard
UPDATE `creature_template_model` SET `CreatureDisplayID` = 14542
WHERE `CreatureID` = 48637 AND `CreatureDisplayID` = 36217;   -- Guild Battle Standard
UPDATE `creature_template_model` SET `CreatureDisplayID` = 14542
WHERE `CreatureID` = 48638 AND `CreatureDisplayID` = 36218;   -- Guild Battle Standard
UPDATE `creature_template_model` SET `CreatureDisplayID` = 31484
WHERE `CreatureID` = 48846 AND `CreatureDisplayID` = 36302;   -- Goblin Pocket-Nuke
UPDATE `creature_template_model` SET `CreatureDisplayID` = 36575
WHERE `CreatureID` = 49176 AND `CreatureDisplayID` = 36612;   -- Brazie the Botanist
UPDATE `creature_template_model` SET `CreatureDisplayID` = 11686
WHERE `CreatureID` = 49405 AND `CreatureDisplayID` = 36457;   -- Blackwing Descent Transform
UPDATE `creature_template_model` SET `CreatureDisplayID` = 1588
WHERE `CreatureID` = 49426 AND `CreatureDisplayID` = 36497;   -- Deathguard Darnell
UPDATE `creature_template_model` SET `CreatureDisplayID` = 328
WHERE `CreatureID` = 49586 AND `CreatureDisplayID` = 37200;   -- Guild Page
UPDATE `creature_template_model` SET `CreatureDisplayID` = 5187
WHERE `CreatureID` = 49587 AND `CreatureDisplayID` = 37198;   -- Guild Herald
UPDATE `creature_template_model` SET `CreatureDisplayID` = 328
WHERE `CreatureID` = 49588 AND `CreatureDisplayID` = 37199;   -- Guild Page
UPDATE `creature_template_model` SET `CreatureDisplayID` = 5187
WHERE `CreatureID` = 49590 AND `CreatureDisplayID` = 37196;   -- Guild Herald
UPDATE `creature_template_model` SET `CreatureDisplayID` = 36774
WHERE `CreatureID` = 50380 AND `CreatureDisplayID` = 36775;   -- Risen Dead j
UPDATE `creature_template_model` SET `CreatureDisplayID` = 28178
WHERE `CreatureID` = 51090 AND `CreatureDisplayID` = 37154;   -- Singing Sunflower
UPDATE `creature_template_model` SET `CreatureDisplayID` = 11686
WHERE `CreatureID` = 53475 AND `CreatureDisplayID` = 38375;   -- Cauterizing Flame
UPDATE `creature_template_model` SET `CreatureDisplayID` = 525
WHERE `CreatureID` = 53590 AND `CreatureDisplayID` = 30165;   -- Moat Monster
UPDATE `creature_template_model` SET `CreatureDisplayID` = 11686
WHERE `CreatureID` = 53883 AND `CreatureDisplayID` = 38538;   -- Moonwell
UPDATE `creature_template_model` SET `CreatureDisplayID` = 169
WHERE `CreatureID` = 54027 AND `CreatureDisplayID` = 38614;   -- Lil' Tarecgosa
UPDATE `creature_template_model` SET `CreatureDisplayID` = 15788
WHERE `CreatureID` = 57220 AND `CreatureDisplayID` = 33547;   -- Tentacle of the Old Ones
UPDATE `creature_template_model` SET `CreatureDisplayID` = 15788
WHERE `CreatureID` = 58077 AND `CreatureDisplayID` = 33547;   -- Tentacle of the Old Ones
UPDATE `creature_template_model` SET `CreatureDisplayID` = 15788
WHERE `CreatureID` = 58078 AND `CreatureDisplayID` = 33547;   -- Tentacle of the Old Ones

-- ---------------------------------------------------------------------------
-- Verification
-- ---------------------------------------------------------------------------
SELECT 'the 2 gossip NPCs now flagged (want 2)' AS what, COUNT(*) AS n
  FROM `creature_template` WHERE `entry` IN (4102239, 4136517) AND (`npcflag` & 1)
UNION ALL SELECT '  ...4136517 kept its QUESTGIVER bit (want 1)', COUNT(*)
  FROM `creature_template` WHERE `entry` = 4136517 AND (`npcflag` & 2)
UNION ALL SELECT 'creatures still on faction 2237 / 2273 (want 0)', COUNT(*)
  FROM `creature_template` WHERE `faction` IN (2237, 2273)
UNION ALL SELECT 'model rows still on a dead display (want 0)', COUNT(*)
  FROM `creature_template_model` WHERE `CreatureDisplayID` IN (30165,31327,31882,33492,33547,36162,36214,36215,36216,36217,36218,36220,36302,36457,36497,36612,36775,36878,37136,37154,37196,37198,37199,37200,38375,38538,38614)
UNION ALL SELECT 'the 29 still have a model row (want 29)', COUNT(DISTINCT `CreatureID`)
  FROM `creature_template_model` WHERE `CreatureID` IN (39145,39160,42895,43719,47944,48115,48242,48633,48634,48636,48637,48638,48846,49176,49405,49426,49586,49587,49588,49590,50380,51090,53475,53590,53883,54027,57220,58077,58078);
