-- 97_gameobject_displays.sql -- map 751 Lordaeron extension, DB step 36.
--
-- GENERATED by Custom/Documentation/scripts/gen_map751_go_displays.py.
--
-- The 18 GameObjectDisplayInfo rows map 751's gameobjects reference and 3.3.5
-- does not have. Symptom:
--   Gameobject (GUID: ... Entry 4808816 GoType: 3) has an invalid displayId
--   (10615), not loaded.
-- 146 spawns over 49 gameobject entries never load. NOTHING on any other map
-- uses these 18 displays, so this cannot disturb existing content.
--
-- LAYOUT: ours is Cata's FIRST 19 FIELDS. Cata's table is 21 fields / 84 bytes,
-- ours 19 / 76; the extra two are Cata additions and are dropped. Verified over
-- 150 ids present in both clients: fields 0-11 and 18 agree 100%, and only the
-- GeoBox floats (12-17) differ, on ~10% of rows -- Blizzard recalculating bounds,
-- not a misalignment. A layout error would fail ~100% on specific fields.
--
-- No model work: all 18 referenced models, including the Cata-only expansion03
-- worgen and deepholm doodads, are ALREADY in the live client from earlier
-- downport passes (every live archive probed for each path, .mdx and .m2).
--
-- THE OVERLAY ALONE IS NOT ENOUGH. The server reads its binary
-- data/dbc/GameObjectDisplayInfo.dbc to decide whether a spawn loads -- proven
-- for CreatureDisplayInfo in 2026-08-02. The rebuilt DBC ships alongside this
-- file and must reach data/dbc; the client patches only gate RENDERING.

DELETE FROM `gameobjectdisplayinfo_dbc` WHERE `ID` IN (9140,9141,9146,9342,9374,9375,9376,9539,9667,9883,9943,10014,10216,10237,10238,10241,10414,10615);

INSERT INTO `gameobjectdisplayinfo_dbc`
  (`ID`, `ModelName`, `Sound_1`, `Sound_2`, `Sound_3`, `Sound_4`, `Sound_5`, `Sound_6`, `Sound_7`, `Sound_8`, `Sound_9`, `Sound_10`, `GeoBoxMinX`, `GeoBoxMinY`, `GeoBoxMinZ`, `GeoBoxMaxX`, `GeoBoxMaxY`, `GeoBoxMaxZ`, `ObjectEffectPackageID`)
VALUES
(9140, 'world\\expansion03\\doodads\\worgen\\items\\worgen_cauldron_01.MDX', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.74873, -1.095016, -0.272449, 0.853095, 1.143835, 4.185697, 0),
(9141, 'world\\expansion03\\doodads\\worgen\\items\\worgen_forge_01.MDX', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2.676028, -1.521746, -0.115871, 2.162074, 6.410564, 5.43818, 0),
(9146, 'world\\expansion03\\doodads\\worgen\\items\\worgen_telescope.MDX', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -6.878117, -2.044235, -0.023808, 6.678966, 2.111002, 16.682484, 0),
(9342, 'world\\expansion03\\doodads\\worgen\\items\\worgen_cage_01.mdx', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
(9374, 'WORLD\\EXPANSION03\\DOODADS\\WORGEN\\ITEMS\\WORGEN_BENCH_01.MDX', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
(9375, 'WORLD\\EXPANSION03\\DOODADS\\WORGEN\\ITEMS\\WORGEN_ROCKINGCHAIR.MDX', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.716626, -0.542601, -0.012142, 0.624506, 0.455437, 1.393887, 0),
(9376, 'WORLD\\EXPANSION03\\DOODADS\\WORGEN\\ITEMS\\WORGEN_BENCH_02.MDX', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.881517, -1.764367, -0.070359, 0.647808, 1.848027, 1.058282, 0),
(9539, 'world\\kalimdor\\tanaris\\passivedoodads\\goblin\\go_dynamite_bundle.mdx', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
(9667, 'world\\expansion03\\doodads\\worgen\\items\\worgen_cage_01_active.mdx', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
(9883, 'world\\expansion02\\doodads\\generic\\vrykul\\quest\\vr_plants_04_q.mdx', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
(9943, 'world\\generic\\goblin\\passivedoodads\\lostisles\\spool\\goblin_spool_02.mdx', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
(10014, 'WORLD\\EXPANSION03\\DOODADS\\GENERIC\\HORDE_TASKBOARD_PILLARS.MDX', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1.073026, -3.658705, -0.02324, 1.073189, 3.658705, 5.455123, 0),
(10216, 'world\\generic\\human\\passive doodads\\armor\\armorhelmgreenflat.mdx', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
(10237, 'world\\generic\\undead\\passive doodads\\undeadtoolstable\\undead_tools_table.mdx', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
(10238, 'WORLD\\AZEROTH\\DUSKWOOD\\PASSIVEDOODADS\\TOMBS\\TOMBSTONE08.MDX', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
(10241, 'world\\expansion03\\doodads\\generic\\horde_taskboard.mdx', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
(10414, 'world\\generic\\passivedoodads\\lights\\generaltorch02.mdx', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0),
(10615, 'world\\expansion03\\doodads\\deepholm\\mushrooms\\deepholm_mushrooms09.mdx', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0);

-- ---------------------------------------------------------------------------
-- Verification
-- ---------------------------------------------------------------------------
SELECT 'display rows added (want 18)' AS what, COUNT(*) AS n
  FROM `gameobjectdisplayinfo_dbc` WHERE `ID` IN (9140,9141,9146,9342,9374,9375,9376,9539,9667,9883,9943,10014,10216,10237,10238,10241,10414,10615)
UNION ALL SELECT 'map-751 GO spawns they unblock (want 146)', COUNT(*)
  FROM `gameobject` g JOIN `gameobject_template` t ON t.`entry` = g.`id`
  WHERE g.`map` = 751 AND t.`displayId` IN (9140,9141,9146,9342,9374,9375,9376,9539,9667,9883,9943,10014,10216,10237,10238,10241,10414,10615)
UNION ALL SELECT '  ...distinct GO entries (want 49)', COUNT(DISTINCT t.`entry`)
  FROM `gameobject` g JOIN `gameobject_template` t ON t.`entry` = g.`id`
  WHERE g.`map` = 751 AND t.`displayId` IN (9140,9141,9146,9342,9374,9375,9376,9539,9667,9883,9943,10014,10216,10237,10238,10241,10414,10615);

-- must be empty: a map-751 gameobject still pointing at a display that is in
-- neither the overlay nor the shipped DBC
SELECT 'PROBLEM: GO display still missing' AS problem, t.`entry`, t.`displayId`, COUNT(*) AS spawns
FROM `gameobject` g JOIN `gameobject_template` t ON t.`entry` = g.`id`
WHERE g.`map` = 751 AND t.`displayId` > 0
  AND t.`displayId` NOT IN (9140,9141,9146,9342,9374,9375,9376,9539,9667,9883,9943,10014,10216,10237,10238,10241,10414,10615)
  AND NOT EXISTS (SELECT 1 FROM `gameobjectdisplayinfo_dbc` d WHERE d.`ID` = t.`displayId`)
GROUP BY t.`entry`, t.`displayId`;
