-- ---------------------------------------------------------------------------
-- Azshara Crater (map 37) -- map markers for the quests fixed on 2026-09-11
-- ---------------------------------------------------------------------------
-- Same shape as 2026_07_14_01_dc_azshara_crater_quest_pois_areas.sql: each
-- objective is a rectangle around its source creatures' live spawns (+/- 40 yd),
-- the turn-in is a small rectangle at the ender (+/- 20 yd), WorldMapAreaId 613.
-- Collection quests used to mark the quest giver as the objective; they now mark
-- the creatures that drop the item (2026_09_11_03 / 2026_09_11_04), and 300407
-- marks the Cooking vendors.
--
-- Every INSERT is guarded on a live spawn existing, so running this BEFORE the
-- Felmusk satyrs are spawned leaves 300300/300301 with only a turn-in marker.
-- Re-run it after spawning -- it deletes and rebuilds only these ten quests.
-- POI ids are fixed per quest (objectives first, turn-in last), so a skipped
-- objective leaves a gap instead of renumbering the others.
--
-- Apply, then restart (quest POIs have no .reload command).
-- ---------------------------------------------------------------------------

DELETE FROM `quest_poi` WHERE `QuestID` IN (300107, 300207, 300300, 300301, 300307, 300407, 300507, 300706, 300804, 300805);
DELETE FROM `quest_poi_points` WHERE `QuestID` IN (300107, 300207, 300300, 300301, 300307, 300407, 300507, 300706, 300804, 300805);

-- Quest 300107 (Hides Against the Cold: Mangy Wolf)
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300107,0,0,37,613,0,0,3,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (525)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300107,0,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-40 ELSE a.mxx+40 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-40 ELSE a.mxy+40 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (525)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300107,1,-1,37,613,0,0,1,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (300002)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300107,1,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-20 ELSE a.mxx+20 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-20 ELSE a.mxy+20 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (300002)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;

-- Quest 300207 (Dust of the Fallen: Dreadbone Skeleton)
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300207,0,0,37,613,0,0,3,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (16303)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300207,0,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-40 ELSE a.mxx+40 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-40 ELSE a.mxy+40 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (16303)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300207,1,-1,37,613,0,0,1,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (300010)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300207,1,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-20 ELSE a.mxx+20 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-20 ELSE a.mxy+20 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (300010)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;

-- Quest 300300 (A Test of Steel: Felmusk Satyr / Felmusk Rogue (hand-spawned))
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300300,0,0,37,613,0,0,3,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (3758)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300300,0,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-40 ELSE a.mxx+40 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-40 ELSE a.mxy+40 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (3758)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300300,1,1,37,613,0,0,3,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (3759)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300300,1,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-40 ELSE a.mxx+40 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-40 ELSE a.mxy+40 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (3759)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300300,2,-1,37,613,0,0,1,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (300020)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300300,2,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-20 ELSE a.mxx+20 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-20 ELSE a.mxy+20 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (300020)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;

-- Quest 300301 (Ten Cursed Horns: Felmusk satyrs (hand-spawned))
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300301,0,0,37,613,0,0,3,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (3758,3759,3762)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300301,0,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-40 ELSE a.mxx+40 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-40 ELSE a.mxy+40 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (3758,3759,3762)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300301,1,-1,37,613,0,0,1,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (300020)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300301,1,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-20 ELSE a.mxx+20 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-20 ELSE a.mxy+20 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (300020)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;

-- Quest 300307 (Beads of the Thistlefur: Thistlefur)
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300307,0,0,37,613,0,0,3,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (3921,3922,3924,3925,3926)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300307,0,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-40 ELSE a.mxx+40 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-40 ELSE a.mxy+40 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (3921,3922,3924,3925,3926)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300307,1,-1,37,613,0,0,1,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (300020)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300307,1,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-20 ELSE a.mxx+20 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-20 ELSE a.mxy+20 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (300020)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;

-- Quest 300407 (Rations for the Tide-Guard: Cooking vendors at Thalindra's camp)
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300407,0,0,37,613,0,0,3,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (500058,601558)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300407,0,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-40 ELSE a.mxx+40 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-40 ELSE a.mxy+40 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (500058,601558)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300407,1,-1,37,613,0,0,1,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (300030)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300407,1,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-20 ELSE a.mxx+20 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-20 ELSE a.mxy+20 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (300030)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;

-- Quest 300507 (Feathers of the Thunderhead: Thunderhead Hippogryph / Skystormer)
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300507,0,0,37,613,0,0,3,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (6375,6378)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300507,0,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-40 ELSE a.mxx+40 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-40 ELSE a.mxy+40 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (6375,6378)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300507,1,-1,37,613,0,0,1,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (300040)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300507,1,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-20 ELSE a.mxx+20 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-20 ELSE a.mxy+20 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (300040)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;

-- Quest 300706 (Orders in the Dark: Kil'sorrow Cultist)
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300706,0,0,37,613,0,0,3,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (17147)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300706,0,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-40 ELSE a.mxx+40 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-40 ELSE a.mxy+40 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (17147)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300706,1,-1,37,613,0,0,1,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (300060)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300706,1,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-20 ELSE a.mxx+20 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-20 ELSE a.mxy+20 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (300060)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;

-- Quest 300804 (Relics of the Sanctum: Skeletal Craftsman / Moonrest Highborne)
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300804,0,0,37,613,0,0,3,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (32164,26455)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300804,0,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-40 ELSE a.mxx+40 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-40 ELSE a.mxy+40 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (32164,26455)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300804,1,-1,37,613,0,0,1,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (300070)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300804,1,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-20 ELSE a.mxx+20 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-20 ELSE a.mxy+20 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (300070)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;

-- Quest 300805 (Unbind the Phantoms: Moonrest Highborne)
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300805,0,0,37,613,0,0,3,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (26455)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300805,0,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-40 ELSE a.mxx+40 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-40 ELSE a.mxy+40 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (26455)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
INSERT INTO `quest_poi` (`QuestID`,`id`,`ObjectiveIndex`,`MapID`,`WorldMapAreaId`,`Floor`,`Priority`,`Flags`,`VerifiedBuild`) SELECT 300805,1,-1,37,613,0,0,1,0 FROM (SELECT MIN(position_x) x FROM creature WHERE map=37 AND id IN (300070)) a WHERE a.x IS NOT NULL;
INSERT INTO `quest_poi_points` (`QuestID`,`Idx1`,`Idx2`,`X`,`Y`,`VerifiedBuild`) SELECT 300805,1,c.i, ROUND(CASE WHEN c.cx=0 THEN a.mnx-20 ELSE a.mxx+20 END), ROUND(CASE WHEN c.cy=0 THEN a.mny-20 ELSE a.mxy+20 END),0 FROM (SELECT MIN(position_x) mnx,MAX(position_x) mxx,MIN(position_y) mny,MAX(position_y) mxy FROM creature WHERE map=37 AND id IN (300070)) a CROSS JOIN (SELECT 0 i,0 cx,0 cy UNION ALL SELECT 1,0,1 UNION ALL SELECT 2,1,1 UNION ALL SELECT 3,1,0) c WHERE a.mnx IS NOT NULL;
