-- Cataclysm 4.3.4 spells downported into the 3.3.5 `spell_dbc` overlay.
-- Generated by _cata_spell_downport.py from K:/UntouchedClients/Cata
--   Data/enUS/locale-enUS.MPQ : DBFilesClient/Spell.dbc + SpellEffect.dbc
-- BasePoints carry the -1 / DieSides = 1 shift (Cata dropped DieSides).
-- spell_dbc is SERVER-SIDE ONLY: the server resolves these at once, but the
-- client shows no icon or tooltip until Spell.dbc itself is rebuilt with
-- tools/spell-dbc-append.py and deployed.

DELETE FROM `spell_dbc` WHERE `ID` IN (88198,57718);

INSERT INTO `spell_dbc` (`ActiveIconID`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `CastingTimeIndex`, `Description_Lang_enUS`, `DurationIndex`, `EffectAuraPeriod_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValueB_1`, `EffectMiscValue_1`, `EffectRadiusIndex_1`, `EffectTriggerSpell_1`, `Effect_1`, `EquippedItemClass`, `ID`, `ImplicitTargetA_1`, `ImplicitTargetB_1`, `Name_Lang_enUS`, `PowerType`, `ProcChance`, `RangeIndex`, `SchoolMask`, `Speed`, `SpellIconID`, `SpellVisualID_1`, `SpellVisualID_2`) VALUES (0, 272, 2415919104, 0, 0, 0, 0, 0, 0, 1, 'A putrid cloud of disease surrounds the caster, dealing Nature damage to nearby enemies.', 21, 0, 4, 0, 1, 0, 0, 0, 0, 6, -1, 88198, 1, 0, 'Disease Cloud', 0, 101, 1, 8, 0.0, 263, 19803, 0);
INSERT INTO `spell_dbc` (`ActiveIconID`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `AttributesEx5`, `AttributesEx6`, `AttributesEx7`, `CastingTimeIndex`, `Description_Lang_enUS`, `DurationIndex`, `EffectAuraPeriod_1`, `EffectAura_1`, `EffectBasePoints_1`, `EffectDieSides_1`, `EffectMiscValueB_1`, `EffectMiscValue_1`, `EffectRadiusIndex_1`, `EffectTriggerSpell_1`, `Effect_1`, `EquippedItemClass`, `ID`, `ImplicitTargetA_1`, `ImplicitTargetB_1`, `Name_Lang_enUS`, `PowerType`, `ProcChance`, `RangeIndex`, `SchoolMask`, `Speed`, `SpellIconID`, `SpellVisualID_1`, `SpellVisualID_2`) VALUES (0, 256, 268435456, 0, 0, 0, 0, 0, 0, 1, '', 21, 0, 4, -1, 1, 0, 0, 0, 0, 6, -1, 57718, 1, 0, 'Harpoon Loot Sparkles', 0, 101, 1, 1, 0.0, 1, 12473, 0);
