-- ============================================================
-- DC-QoS: World-Map Zone Labels
-- ============================================================
-- Draws subzone / zone NAME labels on the world map for downported custom maps
-- (Undermine, Pandaria, ...), the way modern WoW's AreaLabelDataProvider does it —
-- pure Lua FontStrings on WorldMapDetailFrame, no engine WorldMapOverlay/Highlight.blp.
--
-- Data: addon.MapZoneLabels (generated by tools/worldmap-zone-labels.js), keyed by the map ART-DIR NAME
-- (lowercase):  labels["undermine"] = { {n="Tailgate Park", x=0.49, y=0.31}, ... }
-- We match it against GetMapInfo() (the displayed map's art-dir name), which is stable on BOTH the continent
-- overview and a zone map — unlike GetCurrentMapAreaID(), which returns 0 on a continent overview.

local addon = DCQOS
if not addon then
    return
end

local ZoneLabels = {
    displayName = "ZoneLabels",
    settingKey = "zoneLabels",
    icon = "Interface\\Icons\\INV_Misc_Map02_01",
    defaults = {
        zoneLabels = {
            enabled = true,
            fontSize = 11,
        },
    },
}

local state = {
    labelsByName = nil,    -- built lazily: [mapArtDirName] = { {n,x,y}, ... }
    pool = {},             -- label Button pool
    overlay = nil,
    hooksInstalled = false,
    refreshQueued = {},
    eventFrame = nil,
    glow = nil,           -- shared zone-shape hover glow
}

local function GetSettings()
    local db = addon.db and addon.db.profile or nil
    return (db and db.zoneLabels) or ZoneLabels.defaults.zoneLabels
end

local function GetOverlayParent()
    return WorldMapButton or WorldMapDetailFrame or nil
end

-- Build the name-keyed lookup once. Data is keyed by the map art-dir name (lowercase), which matches
-- GetMapInfo() on BOTH the continent overview AND a zone map — unlike GetCurrentMapAreaID(), which returns
-- 0 on a continent overview and would hide the continent's labels.
local function BuildLookup()
    if state.labelsByName then
        return state.labelsByName
    end
    local byName = {}
    local src = addon.MapZoneLabels
    if type(src) == "table" then
        for key, list in pairs(src) do
            byName[tostring(key):lower()] = list
        end
    end
    state.labelsByName = byName
    return byName
end

local function CurrentMapKey()
    if type(GetMapInfo) ~= "function" then
        return nil
    end
    local name = GetMapInfo()       -- the WorldMap art-dir name, e.g. "Undermine", "Pandaria", "TheJadeForest"
    if name and name ~= "" then
        return name:lower()
    end
    return nil
end

-- Hardcoded zone navigation for custom continents where GetMapZones/GetCurrentMapContinent return
-- empty/invalid values (3.3.5a native APIs only know continents 1–4).
-- Key: map art-dir name lowercase (matches GetMapInfo()) → array of {n=normalized_name, c=continent, z=zone_idx}
-- continent = WorldMapContinent.ID; z = 1-based index in WorldMapArea DBC row order for that MapID.
local CUSTOM_ZONE_NAV = {
    pandaria = {
        { n = "dreadwastes",            c = 5, z = 6 },
        { n = "isleofgiants",           c = 5, z = 7 },
        { n = "krasarangwilds",         c = 5, z = 5 },
        { n = "kunlaisummit",           c = 5, z = 3 },
        { n = "thejadeforest",          c = 5, z = 1 },
        { n = "timelessisle",           c = 5, z = 8 },
        { n = "townlongsteppes",        c = 5, z = 4 },
        { n = "valleyofthefourwinds",   c = 5, z = 2 },
    },
}

-- Drill into the zone whose label was clicked: match its name against the current continent's zone list
-- and SetMapZoom to that index. No-op if the name isn't a zone (subzone labels on a zone map) or if the
-- continent isn't registered (then nothing to switch to — the WorldMapContinent.dbc must be live).
local function NavigateToZone(name, worldMapAreaId)
    local function norm(s) return (tostring(s or ""):gsub("%W", "")):lower() end
    local target = norm(name)

    -- SetMapByID addresses the WorldMapArea row directly, so it needs neither a
    -- continent index nor a zone index -- the one route that cannot be thrown off
    -- by how the client enumerates custom continents. Tried first for that reason.
    --
    -- It takes the RAW WorldMapArea.ID, unlike GetCurrentMapAreaID() which returns
    -- that id PLUS ONE. Mixing them up is not a subtle failure: passing the UI id
    -- 1217 for Hyjal (WMA 1216) selects row 1217, which is Plaguelands on map 751,
    -- and that is exactly where clicking Hyjal used to land you. Hence the +1 when
    -- confirming the switch took.
    if worldMapAreaId and type(SetMapByID) == "function" then
        local ok = pcall(SetMapByID, worldMapAreaId)
        if ok and type(GetCurrentMapAreaID) == "function"
            and GetCurrentMapAreaID() == worldMapAreaId + 1 then
            return
        end
    end

    if type(SetMapZoom) ~= "function" then return end

    -- Native path, custom continents included. Measured 2026-08-07: the
    -- client enumerates continents from the AreaID-0 WorldMapArea rows, so a
    -- custom one gets a perfectly ordinary index (map 750 = 13) and both
    -- GetMapZones and SetMapZoom accept it -- that is what the stock Zone
    -- dropdown drives itself with, and it works there.
    if type(GetCurrentMapContinent) == "function" and type(GetMapZones) == "function" then
        local continent = GetCurrentMapContinent()
        if continent and continent > 0 then
            local zones = { GetMapZones(continent) }
            for i = 1, #zones do
                if norm(zones[i]) == target then
                    SetMapZoom(continent, i)
                    return
                end
            end
        end
    end

    -- Fallback for anything the live zone list does not answer. Note these
    -- hardcoded continent numbers are WorldMapContinent.ID, which is NOT the
    -- index SetMapZoom wants -- Pandaria is WorldMapContinent 5 but continent
    -- index 8 -- so this path is a last resort, not the primary one. It used to
    -- run first and return early, which stopped the working native lookup above
    -- from ever being tried on a custom continent.
    local mapKey = CurrentMapKey()
    local hints = mapKey and CUSTOM_ZONE_NAV[mapKey] or nil
    if hints then
        for _, h in ipairs(hints) do
            if h.n == target then
                SetMapZoom(h.c, h.z)
                return
            end
        end
    end
end

-- Zone name labels for a CUSTOM CONTINENT overview, positioned on the continent
-- canvas (x = west->east, y = north->south). Keyed by the zone's AreaTable name,
-- which is what GetMapZones() hands back, so the lookup does not care about DBC
-- row order or which continent index the map ended up with.
--
-- Why this layer exists at all: clicking a zone on a custom continent overview
-- does nothing in-game (reported 2026-08-07 for map 750) -- only the Zone
-- dropdown and Zoom Out respond -- even though every input the engine's own
-- hit-testing needs is in place: WorldMapArea zone rects inside the continent
-- rect, 3:2 like Blizzard's, and a <AreaName>Highlight.blp per zone in patch-5
-- byte-for-byte in stock format. So the engine path (UpdateMapHighlight /
-- ProcessMapClick, driven from WorldMapButton_OnUpdate/OnClick) is not something
-- we can rely on here. So the label itself is the target: each name is a Button
-- that calls SetMapByID, never the engine hit test.
--
-- Map 750 ("Mount Hyjal (80-130)") is the case that needs it most: its overview
-- borrows the stock Kalimdor art, whose baked-in zone names belong to the REAL
-- Kalimdor, so the seven playable zones sit on the map completely unlabelled.
-- Names are AreaTable ids 4923/4926-4931; regenerate the coordinates if any of
-- those WorldMapArea rects (1216, 1256-1261) or the continent row 1262 change.
-- x/y = where the zone's NAME goes, normalized on the continent canvas: the
--       centroid of the zone's highlight mask, i.e. where its land actually is.
--       A rect centre would do for inland zones but lands offshore for a coastal
--       one like Darkshore, whose bounding box is half ocean.
-- w   = RAW WorldMapArea.ID of the zone's own map, for SetMapByID (NOT the +1 UI
--       id -- see NavigateToZone).
--
-- Full-zone click areas were tried and removed 2026-08-07: covering each zone with
-- a hit rect plus its Highlight.blp glow reproduces Blizzard's behaviour, but on a
-- map this dense with POI pins the glow drowns the icons and the rects sit between
-- the cursor and them. Clicking the name is the deliberate choice here.
local CONTINENT_ZONES = {
    -- map 750, "Mount Hyjal (80-130)" (continent WorldMapArea 1262).
    --
    -- Positions come from the STOCK map-1 Kalimdor rects and masks, NOT map 750's
    -- own WorldMapArea rows: the overview borrows the stock WotLK Kalimdor art,
    -- while map 750's rects were moved to retail values (correct for its
    -- retail-derived ZONE art) and its *Cata masks trace the post-Cataclysm
    -- coastline. Over a WotLK continent those sit off the land they describe.
    -- w still points at OUR zone maps, so the click goes where it should.
    ["Moonglade (Sanctuary)"]    = { x = 0.5334, y = 0.2078, w = 1258 },
    ["Hyjal Frontier (113-130)"] = { x = 0.5373, y = 0.3243, w = 1216 },
    ["Azshara (80-90)"]          = { x = 0.6104, y = 0.3776, w = 1260 },
    ["Ashenvale (88-98)"]        = { x = 0.5004, y = 0.4129, w = 1261 },
    ["Felwood (96-106)"]         = { x = 0.4908, y = 0.3015, w = 1257 },
    ["Winterspring (104-115)"]   = { x = 0.5782, y = 0.2478, w = 1256 },
    ["Darkshore (80-90)"]        = { x = 0.4710, y = 0.2644, w = 1259 },
    -- Single-zone custom continents. Their overview is nearly redundant, but you
    -- can still land on it via Zoom Out and then be unable to get back in, which
    -- is the same trap. One zone, so the name sits dead centre.
    ["Deepholm"]                 = { x = 0.5000, y = 0.5000, w = 1215 },
    ["Azshara Crater (1-80)"]    = { x = 0.5000, y = 0.5000, w = 1251 },

    -- map 751, "Plaguelands" (continent WorldMapArea 1267).
    --
    -- TEXT-FREE targets -- note the cw/ch. Unlike map 750, which borrows stock
    -- Kalimdor art labelled with the WRONG names, 751's continent tiles were baked
    -- for this map (2026-08-20, bake_worldmap751_continent.py) and already carry the
    -- eight zone names. Drawing them again would double every one, so these entries
    -- only put a click box over the painted name, sized to it, with the hover wash
    -- as the affordance. Players without DC-QOS still see the labels; they just do
    -- not get the navigation.
    --
    -- x/y are the zone WMA rect centroid projected through continent rect 1267
    -- (L 3500, R -6400, T 3866.667, B -2733.333) -- the exact same arithmetic the
    -- bake used to place the painted text, so box and paint cannot drift.
    -- cw/ch are the painted name's measured extent + padding, as canvas fractions.
    -- REGENERATE ALL OF THESE if rect 1267 changes or the art is rebaked.
    ["Eastern Plaguelands (152-158)"] = { x = 0.7882, y = 0.2282, w = 1217, cw = 0.3438, ch = 0.0427, rx = 0.5846, ry = 0.0246, rw = 0.4072, rh = 0.4071, hl = "EasternPlaguelands", },
    ["Western Plaguelands (148-153)"] = { x = 0.5286, y = 0.2929, w = 1268, cw = 0.3533, ch = 0.0427, rx = 0.3114, ry = 0.0757, rw = 0.4343, rh = 0.4344, hl = "WesternPlaguelands", },
    ["Tirisfal Glades (130-136)"]     = { x = 0.2754, y = 0.2326, w = 1269, cw = 0.2510, ch = 0.0427, rx = 0.0472, ry = 0.0043, rw = 0.4564, rh = 0.4565, hl = "Tirisfal", },
    ["Silverpine Forest (134-140)"]   = { x = 0.2172, y = 0.5454, w = 1270, cw = 0.2879, ch = 0.0427, rx = 0.0051, ry = 0.3333, rw = 0.4242, rh = 0.4242, hl = "Silverpine", },
    ["Hillsbrad Foothills (138-144)"] = { x = 0.4074, y = 0.6868, w = 1271, cw = 0.3298, ch = 0.0427, rx = 0.2458, ry = 0.5253, rw = 0.3232, rh = 0.3232, hl = "Hilsbrad", },
    ["The Hinterlands (145-150)"]     = { x = 0.7071, y = 0.5581, w = 1272, cw = 0.2730, ch = 0.0427, rx = 0.5126, ry = 0.3636, rw = 0.3889, rh = 0.3889, hl = "Hinterlands", },
    ["Arathi Highlands (142-147)"]    = { x = 0.6229, y = 0.7878, w = 1273, cw = 0.2904, ch = 0.0427, rx = 0.4411, ry = 0.6060, rw = 0.3636, rh = 0.3636, hl = "Arathi", },
    ["Ruins of Gilneas (130-136)"]    = { x = 0.1649, y = 0.8256, w = 1274, cw = 0.2655, ch = 0.0427, rx = 0.0061, ry = 0.6666, rw = 0.3178, rh = 0.3179, },
}

-- Returns the label list for the current continent overview, or nil when this is
-- not an overview / none of its zones are known. GetCurrentMapZone() == 0 is the
-- overview marker (a zone map reports its 1-based index), and zones the table
-- has never heard of -- stock Kalimdor's, the micro-dungeon WorldMapArea rows --
-- are simply skipped, so nothing is drawn on maps this does not own.
local function BuildContinentZoneList()
    if type(GetCurrentMapZone) ~= "function"
        or type(GetCurrentMapContinent) ~= "function"
        or type(GetMapZones) ~= "function" then
        return nil
    end
    if GetCurrentMapZone() ~= 0 then
        return nil
    end
    local continent = GetCurrentMapContinent()
    if not continent or continent <= 0 then
        return nil
    end

    local zones = { GetMapZones(continent) }
    local list
    for i = 1, #zones do
        local z = CONTINENT_ZONES[zones[i]]
        if z then
            list = list or {}
            -- cw/ch MUST be carried through: they are what marks a text-free target.
            -- Dropping them here silently re-enabled the drawn text on map 751 and
            -- doubled every zone name against the baked art.
            list[#list + 1] = { n = zones[i], x = z.x, y = z.y, w = z.w, cw = z.cw, ch = z.ch,
                                hl = z.hl, rx = z.rx, ry = z.ry, rw = z.rw, rh = z.rh }
        end
    end
    return list
end

-- One shared zone-shape glow, repositioned to whichever label is hovered (only ever
-- one at a time). Stock ships `Interface\WorldMap\<Zone>\<Zone>Highlight.blp` per zone:
-- a 128x128 whose TOP-LEFT 128x85.333 is the lit zone silhouette, hence the 0.6667
-- vertical texcoord. Drawn ADD-blended over the zone's rect on the continent canvas.
--
-- Why hover-only, and why not a full-zone hit rect: covering each zone with its own
-- rect + permanent glow was tried on map 750 and removed -- the glow drowned the POI
-- icons and the rects sat between the cursor and them. Hanging the glow off the LABEL
-- keeps both problems away: nothing new is ever between the cursor and a pin, and the
-- glow appears only while you deliberately point at a zone name. The frame also sits
-- at parent+1, far below QuestMapPins (parent+8), so pins stay on top of it.
local function GetGlow()
    if state.glow then
        return state.glow
    end
    local parent = GetOverlayParent()
    if not parent then
        return nil
    end
    local f = CreateFrame("Frame", "DCQOSZoneGlow", parent)
    f:SetFrameLevel((parent.GetFrameLevel and parent:GetFrameLevel() or 0) + 1)
    local t = f:CreateTexture(nil, "ARTWORK")
    t:SetAllPoints(f)
    t:SetBlendMode("ADD")
    t:SetTexCoord(0, 1, 0, 0.6667)
    t:SetVertexColor(1.0, 0.90, 0.55)
    t:SetAlpha(0.55)
    f.tex = t
    f:Hide()
    state.glow = f
    return f
end


local function ShowGlowFor(btn)
    if not btn.hlArt or not btn.rx then
        return
    end
    local g = GetGlow()
    local overlay = GetOverlayParent()
    if not g or not overlay then
        return
    end
    local w, h = overlay:GetWidth(), overlay:GetHeight()
    if not w or w <= 0 then
        return
    end
    g.tex:SetTexture("Interface\\WorldMap\\" .. btn.hlArt .. "\\" .. btn.hlArt .. "Highlight")
    g:ClearAllPoints()
    g:SetPoint("TOPLEFT", overlay, "TOPLEFT", btn.rx * w, -(btn.ry * h))
    g:SetWidth(btn.rw * w)
    g:SetHeight(btn.rh * h)
    g:Show()
end


local function HideGlow()
    if state.glow then
        state.glow:Hide()
    end
end


local function AcquireLabel(index)
    local fs = state.pool[index]
    if fs then
        return fs
    end
    local parent = GetOverlayParent()
    if not parent then
        return nil
    end
    -- A clickable button carrying the label text. Clicking a ZONE label on a continent map drills into that
    -- zone (SetMapZoom) — a reliable target that doesn't depend on the engine's ProcessMapClick hit-testing.
    -- On a zone map the subzone names aren't in GetMapZones, so the click is a harmless no-op.
    local btn = CreateFrame("Button", "DCQOSZoneLabel" .. index, parent)
    btn:RegisterForClicks("LeftButtonUp")
    -- Well above the map canvas so POI pins never end up on top of the name.
    btn:SetFrameLevel((parent.GetFrameLevel and parent:GetFrameLevel() or 0) + 30)
    -- Hover wash. Only ever shown for TEXT-FREE targets (map 751, whose art already
    -- carries its zone names) -- a name that lights up is its own affordance, but an
    -- invisible hotspot over baked art needs something to say "this is clickable".
    local hl = btn:CreateTexture(nil, "BACKGROUND")
    hl:SetAllPoints(btn)
    hl:SetTexture("Interface\\Buttons\\WHITE8X8")
    hl:SetBlendMode("ADD")
    hl:SetVertexColor(1.0, 0.86, 0.40, 0.16)
    hl:Hide()
    btn.hl = hl
    local txt = btn:CreateFontString(nil, "ARTWORK", "GameFontHighlightSmall")
    txt:SetPoint("CENTER")
    txt:SetJustifyH("CENTER")
    txt:SetJustifyV("MIDDLE")
    txt:SetTextColor(1.0, 0.92, 0.55)           -- soft gold, like Blizzard zone labels
    txt:SetShadowColor(0, 0, 0, 1)
    txt:SetShadowOffset(1, -1)
    btn.text = txt
    btn:SetScript("OnClick", function(self) NavigateToZone(self.zoneName, self.zoneAreaId) end)
    btn:SetScript("OnEnter", function(self)
        self.text:SetTextColor(1, 1, 1)
        if self.silent then self.hl:Show() end
        ShowGlowFor(self)
    end)
    btn:SetScript("OnLeave", function(self)
        self.text:SetTextColor(1.0, 0.92, 0.55)
        self.hl:Hide()
        HideGlow()
    end)
    state.pool[index] = btn
    return btn
end

local function HideFrom(index)
    if index <= 1 and state.glow then
        state.glow:Hide()
    end
    for i = index, #state.pool do
        if state.pool[i] then
            state.pool[i]:Hide()
        end
    end
end

function ZoneLabels:Refresh()
    local settings = GetSettings()
    if not settings.enabled
        or not WorldMapFrame or not WorldMapFrame.IsShown or not WorldMapFrame:IsShown() then
        HideFrom(1)
        return
    end

    local overlay = GetOverlayParent()
    if not overlay then
        HideFrom(1)
        return
    end
    local width, height = overlay:GetWidth(), overlay:GetHeight()
    if not width or width <= 0 or not height or height <= 0 then
        HideFrom(1)
        return
    end

    -- A continent overview of a custom continent gets its zone labels built from
    -- the live zone list; everything else uses the baked per-map subzone data.
    local list = BuildContinentZoneList()
    if not list then
        local mapKey = CurrentMapKey()
        list = mapKey and BuildLookup()[mapKey] or nil
    end
    if not list or #list == 0 then
        HideFrom(1)
        return
    end

    local fontPath = STANDARD_TEXT_FONT or "Fonts\\FRIZQT__.TTF"
    local fontSize = tonumber(settings.fontSize) or 11
    local shown = 0
    for i = 1, #list do
        local entry = list[i]
        local x = tonumber(entry.x)
        local y = tonumber(entry.y)
        if entry.n and x and y then
            local btn = AcquireLabel(shown + 1)
            if btn then
                btn.text:SetFont(fontPath, fontSize, "OUTLINE")
                btn.zoneName = entry.n
                -- Only continent-overview entries carry w; the baked art-dir data
                -- has none, so its subzone labels navigate by name or not at all.
                btn.zoneAreaId = entry.w
                -- cw/ch mark a TEXT-FREE target: the continent art already has the
                -- zone name baked in (map 751), so drawing it again would double it.
                -- The click box is sized to the painted name instead, in canvas
                -- fractions, and only the hover wash marks it.
                -- zone-shape hover glow (continent overviews only; nil elsewhere)
                btn.hlArt = entry.hl
                btn.rx, btn.ry, btn.rw, btn.rh = entry.rx, entry.ry, entry.rw, entry.rh
                btn.silent = (entry.cw and entry.ch) and true or false
                if btn.silent then
                    btn.text:SetText("")
                    btn:SetWidth(entry.cw * width)
                    btn:SetHeight(entry.ch * height)
                else
                    btn.text:SetText(entry.n)
                    btn:SetWidth((btn.text:GetStringWidth() or 40) + 10)
                    btn:SetHeight((btn.text:GetStringHeight() or 12) + 6)
                end
                btn.hl:Hide()
                btn:ClearAllPoints()
                btn:SetPoint("CENTER", overlay, "TOPLEFT", x * width, -(y * height))
                btn:Show()
                shown = shown + 1
            end
        end
    end
    HideFrom(shown + 1)
end

local function QueueRefresh(delay)
    local key = tostring(delay or 0)
    if state.refreshQueued[key] then
        return
    end
    state.refreshQueued[key] = true
    local fire = function()
        state.refreshQueued[key] = nil
        ZoneLabels:Refresh()
    end
    if delay and delay > 0 and type(addon.DelayedCall) == "function" then
        addon:DelayedCall(delay, fire)
    else
        fire()
    end
end

local function InstallHooks()
    if state.hooksInstalled then
        return
    end
    local function RequestRefresh()
        QueueRefresh(0)
        QueueRefresh(0.06)
    end
    if type(addon.RegisterWorldMapRefreshListener) == "function" then
        addon:RegisterWorldMapRefreshListener("ZoneLabelsWorldMap", RequestRefresh)
    end
    if WorldMapFrame and type(WorldMapFrame.HookScript) == "function" then
        WorldMapFrame:HookScript("OnShow", RequestRefresh)
        WorldMapFrame:HookScript("OnHide", function() HideFrom(1) end)
    end

    -- The shared refresh bridge only fires on show/resize, so switching the
    -- displayed map with the frame open would leave the previous map's labels
    -- sitting there -- including after a click on one of them zooms into a zone.
    -- WORLD_MAP_UPDATE is the event the stock frame itself redraws on.
    if type(CreateFrame) == "function" and not state.eventFrame then
        local ev = CreateFrame("Frame")
        ev:RegisterEvent("WORLD_MAP_UPDATE")
        ev:SetScript("OnEvent", RequestRefresh)
        state.eventFrame = ev
    end

    state.hooksInstalled = true
end

-- Core drives modules through OnInitialize / OnEnable / OnDisable, called as
-- PLAIN functions (`module.OnEnable()`, see addon:EnableModule) -- no self is
-- passed, so these must not be colon-defined. This module shipped with
-- Initialize/Enable/Disable, which Core never calls: it had never run once, on
-- any map, which is why its Pandaria/Undermine labels were never seen either.
function ZoneLabels.OnInitialize()
    InstallHooks()
    QueueRefresh(0)
end

function ZoneLabels.OnEnable()
    InstallHooks()
    QueueRefresh(0)
end

function ZoneLabels.OnDisable()
    HideFrom(1)
end

-- Kept as aliases: harmless, and anything that learned the old names still works.
ZoneLabels.Initialize = ZoneLabels.OnInitialize
ZoneLabels.Enable = ZoneLabels.OnEnable
ZoneLabels.Disable = ZoneLabels.OnDisable

addon:RegisterModule("ZoneLabels", ZoneLabels)
