-- ============================================================
-- DC-QoS: World-Map Zone Labels
-- ============================================================
-- Draws subzone / zone NAME labels on the world map for downported custom maps
-- (Undermine, Pandaria, ...), the way modern WoW's AreaLabelDataProvider does it —
-- pure Lua FontStrings on WorldMapDetailFrame, no engine WorldMapOverlay/Highlight.blp.
--
-- Data: addon.MapZoneLabels (generated by tools/worldmap-zone-labels.js), keyed by the map ART-DIR NAME
-- (lowercase):  labels["undermine"] = { {n="Tailgate Park", x=0.49, y=0.31}, ... }
-- We match it against GetMapInfo() (the displayed map's art-dir name), which is stable on BOTH the continent
-- overview and a zone map — unlike GetCurrentMapAreaID(), which returns 0 on a continent overview.

local addon = DCQOS
if not addon then
    return
end

local ZoneLabels = {
    displayName = "ZoneLabels",
    settingKey = "zoneLabels",
    icon = "Interface\\Icons\\INV_Misc_Map02_01",
    defaults = {
        zoneLabels = {
            enabled = true,
            fontSize = 11,
        },
    },
}

local state = {
    labelsByName = nil,    -- built lazily: [mapArtDirName] = { {n,x,y}, ... }
    pool = {},             -- FontString pool
    overlay = nil,
    hooksInstalled = false,
    refreshQueued = {},
}

local function GetSettings()
    local db = addon.db and addon.db.profile or nil
    return (db and db.zoneLabels) or ZoneLabels.defaults.zoneLabels
end

local function GetOverlayParent()
    return WorldMapButton or WorldMapDetailFrame or nil
end

-- Build the name-keyed lookup once. Data is keyed by the map art-dir name (lowercase), which matches
-- GetMapInfo() on BOTH the continent overview AND a zone map — unlike GetCurrentMapAreaID(), which returns
-- 0 on a continent overview and would hide the continent's labels.
local function BuildLookup()
    if state.labelsByName then
        return state.labelsByName
    end
    local byName = {}
    local src = addon.MapZoneLabels
    if type(src) == "table" then
        for key, list in pairs(src) do
            byName[tostring(key):lower()] = list
        end
    end
    state.labelsByName = byName
    return byName
end

local function CurrentMapKey()
    if type(GetMapInfo) ~= "function" then
        return nil
    end
    local name = GetMapInfo()       -- the WorldMap art-dir name, e.g. "Undermine", "Pandaria", "TheJadeForest"
    if name and name ~= "" then
        return name:lower()
    end
    return nil
end

-- Hardcoded zone navigation for custom continents where GetMapZones/GetCurrentMapContinent return
-- empty/invalid values (3.3.5a native APIs only know continents 1–4).
-- Key: map art-dir name lowercase (matches GetMapInfo()) → array of {n=normalized_name, c=continent, z=zone_idx}
-- continent = WorldMapContinent.ID; z = 1-based index in WorldMapArea DBC row order for that MapID.
local CUSTOM_ZONE_NAV = {
    pandaria = {
        { n = "dreadwastes",            c = 5, z = 6 },
        { n = "isleofgiants",           c = 5, z = 7 },
        { n = "krasarangwilds",         c = 5, z = 5 },
        { n = "kunlaisummit",           c = 5, z = 3 },
        { n = "thejadeforest",          c = 5, z = 1 },
        { n = "timelessisle",           c = 5, z = 8 },
        { n = "townlongsteppes",        c = 5, z = 4 },
        { n = "valleyofthefourwinds",   c = 5, z = 2 },
    },
}

-- Drill into the zone whose label was clicked: match its name against the current continent's zone list
-- and SetMapZoom to that index. No-op if the name isn't a zone (subzone labels on a zone map) or if the
-- continent isn't registered (then nothing to switch to — the WorldMapContinent.dbc must be live).
local function NavigateToZone(name)
    if not name or type(SetMapZoom) ~= "function" then return end
    local function norm(s) return (tostring(s or ""):gsub("%W", "")):lower() end
    local target = norm(name)

    -- Custom continent fallback: bypass GetCurrentMapContinent/GetMapZones which 3.3.5a doesn't expose
    -- for continent IDs beyond the 4 stock WotLK continents.
    local mapKey = CurrentMapKey()
    local hints = mapKey and CUSTOM_ZONE_NAV[mapKey] or nil
    if hints then
        for _, h in ipairs(hints) do
            if h.n == target then
                SetMapZoom(h.c, h.z)
                return
            end
        end
        return  -- on a custom continent: subzone label click → harmless no-op
    end

    -- Stock continents: native API path
    if type(GetCurrentMapContinent) ~= "function" or type(GetMapZones) ~= "function" then return end
    local continent = GetCurrentMapContinent()
    if not continent or continent <= 0 then return end
    local zones = { GetMapZones(continent) }
    for i = 1, #zones do
        if norm(zones[i]) == target then
            SetMapZoom(continent, i)
            return
        end
    end
end

local function AcquireLabel(index)
    local fs = state.pool[index]
    if fs then
        return fs
    end
    local parent = GetOverlayParent()
    if not parent then
        return nil
    end
    -- A clickable button carrying the label text. Clicking a ZONE label on a continent map drills into that
    -- zone (SetMapZoom) — a reliable target that doesn't depend on the engine's ProcessMapClick hit-testing.
    -- On a zone map the subzone names aren't in GetMapZones, so the click is a harmless no-op.
    local btn = CreateFrame("Button", "DCQOSZoneLabel" .. index, parent)
    btn:RegisterForClicks("LeftButtonUp")
    btn:SetFrameLevel((parent.GetFrameLevel and parent:GetFrameLevel() or 0) + 5)
    local txt = btn:CreateFontString(nil, "ARTWORK", "GameFontHighlightSmall")
    txt:SetPoint("CENTER")
    txt:SetJustifyH("CENTER")
    txt:SetJustifyV("MIDDLE")
    txt:SetTextColor(1.0, 0.92, 0.55)           -- soft gold, like Blizzard zone labels
    txt:SetShadowColor(0, 0, 0, 1)
    txt:SetShadowOffset(1, -1)
    btn.text = txt
    btn:SetScript("OnClick", function(self) NavigateToZone(self.zoneName) end)
    btn:SetScript("OnEnter", function(self) self.text:SetTextColor(1, 1, 1) end)
    btn:SetScript("OnLeave", function(self) self.text:SetTextColor(1.0, 0.92, 0.55) end)
    state.pool[index] = btn
    return btn
end

local function HideFrom(index)
    for i = index, #state.pool do
        if state.pool[i] then
            state.pool[i]:Hide()
        end
    end
end

function ZoneLabels:Refresh()
    local settings = GetSettings()
    if not settings.enabled
        or not WorldMapFrame or not WorldMapFrame.IsShown or not WorldMapFrame:IsShown() then
        HideFrom(1)
        return
    end

    local overlay = GetOverlayParent()
    if not overlay then
        HideFrom(1)
        return
    end
    local width, height = overlay:GetWidth(), overlay:GetHeight()
    if not width or width <= 0 or not height or height <= 0 then
        HideFrom(1)
        return
    end

    local mapKey = CurrentMapKey()
    local list = mapKey and BuildLookup()[mapKey] or nil
    if not list or #list == 0 then
        HideFrom(1)
        return
    end

    local fontPath = STANDARD_TEXT_FONT or "Fonts\\FRIZQT__.TTF"
    local fontSize = tonumber(settings.fontSize) or 11
    local shown = 0
    for i = 1, #list do
        local entry = list[i]
        local x = tonumber(entry.x)
        local y = tonumber(entry.y)
        if entry.n and x and y then
            local btn = AcquireLabel(shown + 1)
            if btn then
                btn.text:SetFont(fontPath, fontSize, "OUTLINE")
                btn.text:SetText(entry.n)
                btn.zoneName = entry.n
                btn:SetWidth((btn.text:GetStringWidth() or 40) + 10)
                btn:SetHeight((btn.text:GetStringHeight() or 12) + 6)
                btn:ClearAllPoints()
                btn:SetPoint("CENTER", overlay, "TOPLEFT", x * width, -(y * height))
                btn:Show()
                shown = shown + 1
            end
        end
    end
    HideFrom(shown + 1)
end

local function QueueRefresh(delay)
    local key = tostring(delay or 0)
    if state.refreshQueued[key] then
        return
    end
    state.refreshQueued[key] = true
    local fire = function()
        state.refreshQueued[key] = nil
        ZoneLabels:Refresh()
    end
    if delay and delay > 0 and type(addon.DelayedCall) == "function" then
        addon:DelayedCall(delay, fire)
    else
        fire()
    end
end

local function InstallHooks()
    if state.hooksInstalled then
        return
    end
    local function RequestRefresh()
        QueueRefresh(0)
        QueueRefresh(0.06)
    end
    if type(addon.RegisterWorldMapRefreshListener) == "function" then
        addon:RegisterWorldMapRefreshListener("ZoneLabelsWorldMap", RequestRefresh)
    end
    if WorldMapFrame and type(WorldMapFrame.HookScript) == "function" then
        WorldMapFrame:HookScript("OnShow", RequestRefresh)
        WorldMapFrame:HookScript("OnHide", function() HideFrom(1) end)
    end
    state.hooksInstalled = true
end

function ZoneLabels:Initialize()
    InstallHooks()
    QueueRefresh(0)
end

function ZoneLabels:Enable()
    InstallHooks()
    QueueRefresh(0)
end

function ZoneLabels:Disable()
    HideFrom(1)
end

addon:RegisterModule("ZoneLabels", ZoneLabels)
