-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_SharedXMLBase/CallbackRegistrant.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

-- Script CallbackRegistrant.lua (loaded through the TOC)

ns.XML.Load("Blizzard_SharedXMLBase/CallbackRegistrant.xml", {
    { tag = "Frame", attr = { name = "CallbackRegistrantTemplate", mixin = "CallbackRegistrantMixin", virtual = "true" }, children = {
        { tag = "Scripts", children = {
            { tag = "OnShow", attr = { method = "OnShow" } },
            { tag = "OnHide", attr = { method = "OnHide" } },
        } },
    } },
})
