-- Dark Chaos - Cataclysm+ retail mount downport batch 2 (17 models / 17 colors)
-- Auto-generated by retroport_tools/dc_mount_gen_batch.py from the 12.0.7 retail client.
-- One CreatureModelData per model; one creature/display/spell/item/vendor/collection per color.
-- Families incl: bearblizzard(1), chimera(1), dragonchromatic(1), dragonhawk(1), encrypted(1), flyingcar(1), horse(1), kodobeast(1) ...
-- IDs: model 502562-502578 | display 503332-503348 | creature 3463387-3463403
--      item 302561-302577 | spell 302891-302907 | vendor slots 1199-1215

-- 1) creature_model_info
DELETE FROM `creature_model_info` WHERE `DisplayID` BETWEEN 503332 AND 503348;
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`,`VerifiedBuild`)
VALUES
(503332,0.75,2.50,2,0,0),
(503333,0.75,2.50,2,0,0),
(503334,0.75,2.50,2,0,0),
(503335,0.75,2.50,2,0,0),
(503336,0.75,2.50,2,0,0),
(503337,0.75,2.50,2,0,0),
(503338,0.75,2.50,2,0,0),
(503339,0.75,2.50,2,0,0),
(503340,0.75,2.50,2,0,0),
(503341,0.75,2.50,2,0,0),
(503342,0.75,2.50,2,0,0),
(503343,0.75,2.50,2,0,0),
(503344,0.75,2.50,2,0,0),
(503345,0.75,2.50,2,0,0),
(503346,0.75,2.50,2,0,0),
(503347,0.75,2.50,2,0,0),
(503348,0.75,2.50,2,0,0);

-- 2) creature_template
DELETE FROM `creature_template` WHERE `entry` BETWEEN 3463387 AND 3463403;
INSERT INTO `creature_template` (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`faction`,`speed_walk`,`speed_run`,`unit_class`,`type`,`AIName`,`MovementType`,`RegenHealth`,`VerifiedBuild`)
VALUES
(3463387,'Harmonious Salutations Bear','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463388,'Ashenvale Chimaera','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463389,'Corruption of the Aspects','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463390,'Armored Red Dragonhawk','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463391,'Hogrus, Swine of Good Fortune','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463392,'Leywoven Flying Carpet','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463393,'Prestigious Bloodforged Courser','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463394,'Great Sunwalker Kodo','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463395,'Vicious War Raptor','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463396,'Squeakers, the Trickster','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463397,'Great Exarch''s Elekk','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463398,'Golden Ashes of Al''ar','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463399,'Geosynchronous World Spinner','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463400,'Mystic Runesaber','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463401,'Solar Spirehawk','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463402,'Vicious Skyflayer','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463403,'Infernal Direwolf','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0);

-- 3) creature_template_model
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 3463387 AND 3463403;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
VALUES
(3463387,0,503332,1,1,0),
(3463388,0,503333,1,1,0),
(3463389,0,503334,1,1,0),
(3463390,0,503335,1,1,0),
(3463391,0,503336,1,1,0),
(3463392,0,503337,1,1,0),
(3463393,0,503338,1,1,0),
(3463394,0,503339,1,1,0),
(3463395,0,503340,1,1,0),
(3463396,0,503341,1,1,0),
(3463397,0,503342,1,1,0),
(3463398,0,503343,1,1,0),
(3463399,0,503344,1,1,0),
(3463400,0,503345,1,1,0),
(3463401,0,503346,1,1,0),
(3463402,0,503347,1,1,0),
(3463403,0,503348,1,1,0);

-- 4) item_template ('Reins of ...', spellid_2 trigger 6 = learn)
DELETE FROM `item_template` WHERE `entry` BETWEEN 302561 AND 302577;
INSERT INTO `item_template` (`entry`,`class`,`subclass`,`SoundOverrideSubclass`,`name`,`displayid`,`Quality`,`Flags`,`FlagsExtra`,`BuyCount`,`BuyPrice`,`SellPrice`,`InventoryType`,`Material`,`AllowableClass`,`AllowableRace`,`ItemLevel`,`RequiredLevel`,`maxcount`,`stackable`,`ContainerSlots`,`spellid_1`,`spelltrigger_1`,`spellcharges_1`,`spellppmRate_1`,`spellcooldown_1`,`spellcategory_1`,`spellcategorycooldown_1`,`spellid_2`,`spelltrigger_2`,`spellcharges_2`,`spellppmRate_2`,`spellcooldown_2`,`spellcategory_2`,`spellcategorycooldown_2`,`bonding`,`description`,`RequiredDisenchantSkill`,`duration`,`ScriptName`,`DisenchantID`,`FoodType`,`minMoneyLoot`,`maxMoneyLoot`,`flagsCustom`,`VerifiedBuild`)
VALUES
(302561,15,5,-1,'Reins of the Harmonious Salutations Bear',13905031,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302891,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302562,15,5,-1,'Reins of the Ashenvale Chimaera',10406628,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302892,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302563,15,5,-1,'Reins of the Corruption of the Aspects',14698671,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302893,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302564,15,5,-1,'Reins of the Armored Red Dragonhawk',8852827,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302894,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302565,15,5,-1,'Reins of the Hogrus, Swine of Good Fortune',10459601,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302895,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302566,15,5,-1,'Reins of the Leywoven Flying Carpet',9610263,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302896,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302567,15,5,-1,'Reins of the Prestigious Bloodforged Courser',10159777,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302897,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302568,15,5,-1,'Reins of the Great Sunwalker Kodo',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302898,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302569,15,5,-1,'Reins of the Vicious War Raptor',9043774,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302899,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302570,15,5,-1,'Reins of the Squeakers, the Trickster',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302900,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302571,15,5,-1,'Reins of the Great Exarch''s Elekk',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302901,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302572,15,5,-1,'Reins of the Golden Ashes of Al''ar',13905217,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302902,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302573,15,5,-1,'Reins of the Geosynchronous World Spinner',8657937,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302903,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302574,15,5,-1,'Reins of the Mystic Runesaber',9096090,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302904,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302575,15,5,-1,'Reins of the Solar Spirehawk',8840662,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302905,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302576,15,5,-1,'Reins of the Vicious Skyflayer',13715462,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302906,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302577,15,5,-1,'Reins of the Infernal Direwolf',9125819,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302907,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0);

-- 5) npc_vendor (Skeletal Stablemaster)
DELETE FROM `npc_vendor` WHERE `entry`=3461020 AND `item` BETWEEN 302561 AND 302577;
DELETE FROM `npc_vendor` WHERE `entry`=3461020 AND `slot` BETWEEN 1199 AND 1215;
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`)
VALUES
(3461020,1199,302561,0,0,0,0),
(3461020,1200,302562,0,0,0,0),
(3461020,1201,302563,0,0,0,0),
(3461020,1202,302564,0,0,0,0),
(3461020,1203,302565,0,0,0,0),
(3461020,1204,302566,0,0,0,0),
(3461020,1205,302567,0,0,0,0),
(3461020,1206,302568,0,0,0,0),
(3461020,1207,302569,0,0,0,0),
(3461020,1208,302570,0,0,0,0),
(3461020,1209,302571,0,0,0,0),
(3461020,1210,302572,0,0,0,0),
(3461020,1211,302573,0,0,0,0),
(3461020,1212,302574,0,0,0,0),
(3461020,1213,302575,0,0,0,0),
(3461020,1214,302576,0,0,0,0),
(3461020,1215,302577,0,0,0,0);

-- 6) conditions cleanup
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=23 AND `SourceGroup`=3461020 AND `SourceEntry` BETWEEN 302561 AND 302577 AND `ConditionTypeOrReference`=25;

-- 7) dc_mount_definitions (fly=type3/speed310, ground=type0/speed100)
DELETE FROM `dc_mount_definitions` WHERE `spell_id` BETWEEN 302891 AND 302907;
INSERT INTO `dc_mount_definitions` (`spell_id`,`name`,`mount_type`,`source`,`faction`,`rarity`,`speed`,`display_id`)
VALUES
(302891,'Harmonious Salutations Bear',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503332),
(302892,'Ashenvale Chimaera',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503333),
(302893,'Corruption of the Aspects',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503334),
(302894,'Armored Red Dragonhawk',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503335),
(302895,'Hogrus, Swine of Good Fortune',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503336),
(302896,'Leywoven Flying Carpet',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503337),
(302897,'Prestigious Bloodforged Courser',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503338),
(302898,'Great Sunwalker Kodo',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503339),
(302899,'Vicious War Raptor',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503340),
(302900,'Squeakers, the Trickster',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503341),
(302901,'Great Exarch''s Elekk',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503342),
(302902,'Golden Ashes of Al''ar',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503343),
(302903,'Geosynchronous World Spinner',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503344),
(302904,'Mystic Runesaber',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503345),
(302905,'Solar Spirehawk',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503346),
(302906,'Vicious Skyflayer',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503347),
(302907,'Infernal Direwolf',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503348)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`mount_type`=VALUES(`mount_type`),`source`=VALUES(`source`),`faction`=VALUES(`faction`),`rarity`=VALUES(`rarity`),`speed`=VALUES(`speed`),`display_id`=VALUES(`display_id`);

-- 8) dc_collection_definitions (collection_type 1 = MOUNT)
DELETE FROM `dc_collection_definitions` WHERE `collection_type`=1 AND `entry_id` BETWEEN 302891 AND 302907;
INSERT INTO `dc_collection_definitions` (`collection_type`,`entry_id`,`enabled`)
VALUES
(1,302891,1),
(1,302892,1),
(1,302893,1),
(1,302894,1),
(1,302895,1),
(1,302896,1),
(1,302897,1),
(1,302898,1),
(1,302899,1),
(1,302900,1),
(1,302901,1),
(1,302902,1),
(1,302903,1),
(1,302904,1),
(1,302905,1),
(1,302906,1),
(1,302907,1);
