-- Dark Chaos - Cataclysm+ retail mount downport batch 2 (5 models / 5 colors)
-- Auto-generated by retroport_tools/dc_mount_gen_batch.py from the 12.0.7 retail client.
-- One CreatureModelData per model; one creature/display/spell/item/vendor/collection per color.
-- Families incl: mothfluffy(1), rabbitvoid(1), shaowl(1), shawolf(1), springpanda(1) ...
-- IDs: model 502913-502917 | display 503592-503596 | creature 3463504-3463508
--      item 302638-302642 | spell 302963-302967 | vendor slots 1225-1229

-- 1) creature_model_info
DELETE FROM `creature_model_info` WHERE `DisplayID` BETWEEN 503592 AND 503596;
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`,`VerifiedBuild`)
VALUES
(503592,0.75,2.50,2,0,0),
(503593,0.75,2.50,2,0,0),
(503594,0.75,2.50,2,0,0),
(503595,0.75,2.50,2,0,0),
(503596,0.75,2.50,2,0,0);

-- 2) creature_template
DELETE FROM `creature_template` WHERE `entry` BETWEEN 3463504 AND 3463508;
INSERT INTO `creature_template` (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`faction`,`speed_walk`,`speed_run`,`unit_class`,`type`,`AIName`,`MovementType`,`RegenHealth`,`VerifiedBuild`)
VALUES
(3463504,'Sunflare Driftmoth','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463505,'Rabbit''ath','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463506,'Sha-Warped Owl','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463507,'Sha-Warped Riding Wolf','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463508,'Spring Panda','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0);

-- 3) creature_template_model
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 3463504 AND 3463508;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
VALUES
(3463504,0,503592,1,1,0),
(3463505,0,503593,1,1,0),
(3463506,0,503594,1,1,0),
(3463507,0,503595,1,1,0),
(3463508,0,503596,1,1,0);

-- 4) item_template ('Reins of ...', spellid_2 trigger 6 = learn)
DELETE FROM `item_template` WHERE `entry` BETWEEN 302638 AND 302642;
INSERT INTO `item_template` (`entry`,`class`,`subclass`,`SoundOverrideSubclass`,`name`,`displayid`,`Quality`,`Flags`,`FlagsExtra`,`BuyCount`,`BuyPrice`,`SellPrice`,`InventoryType`,`Material`,`AllowableClass`,`AllowableRace`,`ItemLevel`,`RequiredLevel`,`maxcount`,`stackable`,`ContainerSlots`,`spellid_1`,`spelltrigger_1`,`spellcharges_1`,`spellppmRate_1`,`spellcooldown_1`,`spellcategory_1`,`spellcategorycooldown_1`,`spellid_2`,`spelltrigger_2`,`spellcharges_2`,`spellppmRate_2`,`spellcooldown_2`,`spellcategory_2`,`spellcategorycooldown_2`,`bonding`,`description`,`RequiredDisenchantSkill`,`duration`,`ScriptName`,`DisenchantID`,`FoodType`,`minMoneyLoot`,`maxMoneyLoot`,`flagsCustom`,`VerifiedBuild`)
VALUES
(302638,15,5,-1,'Reins of the Sunflare Driftmoth',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302963,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302639,15,5,-1,'Reins of the Rabbit''ath',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302964,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302640,15,5,-1,'Reins of the Sha-Warped Owl',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302965,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302641,15,5,-1,'Reins of the Sha-Warped Riding Wolf',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302966,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302642,15,5,-1,'Reins of the Spring Panda',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302967,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0);

-- 5) npc_vendor (Skeletal Stablemaster)
DELETE FROM `npc_vendor` WHERE `entry`=3461020 AND `item` BETWEEN 302638 AND 302642;
DELETE FROM `npc_vendor` WHERE `entry`=3461020 AND `slot` BETWEEN 1225 AND 1229;
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`)
VALUES
(3461020,1225,302638,0,0,0,0),
(3461020,1226,302639,0,0,0,0),
(3461020,1227,302640,0,0,0,0),
(3461020,1228,302641,0,0,0,0),
(3461020,1229,302642,0,0,0,0);

-- 6) conditions cleanup
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=23 AND `SourceGroup`=3461020 AND `SourceEntry` BETWEEN 302638 AND 302642 AND `ConditionTypeOrReference`=25;

-- 7) dc_mount_definitions (fly=type3/speed310, ground=type0/speed100)
DELETE FROM `dc_mount_definitions` WHERE `spell_id` BETWEEN 302963 AND 302967;
INSERT INTO `dc_mount_definitions` (`spell_id`,`name`,`mount_type`,`source`,`faction`,`rarity`,`speed`,`display_id`)
VALUES
(302963,'Sunflare Driftmoth',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503592),
(302964,'Rabbit''ath',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503593),
(302965,'Sha-Warped Owl',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503594),
(302966,'Sha-Warped Riding Wolf',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503595),
(302967,'Spring Panda',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503596)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`mount_type`=VALUES(`mount_type`),`source`=VALUES(`source`),`faction`=VALUES(`faction`),`rarity`=VALUES(`rarity`),`speed`=VALUES(`speed`),`display_id`=VALUES(`display_id`);

-- 8) dc_collection_definitions (collection_type 1 = MOUNT)
DELETE FROM `dc_collection_definitions` WHERE `collection_type`=1 AND `entry_id` BETWEEN 302963 AND 302967;
INSERT INTO `dc_collection_definitions` (`collection_type`,`entry_id`,`enabled`)
VALUES
(1,302963,1),
(1,302964,1),
(1,302965,1),
(1,302966,1),
(1,302967,1);
