-- Dark Chaos - passenger seats for downported mounts, batch 2 (2026-08-03)
-- Generated by retroport_tools/dc_mount_passenger_seats_batch2.py
--
-- Covers the 4 mounts whose models carry no VehicleSeat1..8 attachment points.
-- Sandstone Drake needs NO new DBC rows (stock Vehicle 200 / seat 2144 match
-- the Cata data exactly). The other three add Vehicle 1704+ / VehicleSeat 10209+.

-- 1) make each mount creature a vehicle
UPDATE `creature_template` SET `VehicleId`=200 WHERE `entry`=3461286; -- Sandstone Drake (1 seat)
--   cata_world 50269 -> VehicleId 200; Vehicle 200 + seat 2144 already in stock 3.3.5
UPDATE `creature_template` SET `VehicleId`=1704 WHERE `entry`=3462494; -- Wondrous Wavewhisker (2 seats)
--   symmetric att 21/22 pair; same anchor Blizzard used for the drake seat
UPDATE `creature_template` SET `VehicleId`=1705 WHERE `entry`=3462151; -- Depleted-Kyparium Rocket (1 seat)
--   ESTIMATED - model has no seat point (att 58-69 are exhaust VFX)
UPDATE `creature_template` SET `VehicleId`=1706 WHERE `entry`=3463399; -- Geosynchronous World Spinner (1 seat)
--   ESTIMATED - model has no seat point (att 58-69 are exhaust VFX)

-- 2) let other players board (keyed by the MOUNT creature entry)
DELETE FROM `npc_spellclick_spells` WHERE `npc_entry` IN (3461286,3462494,3462151,3463399);
INSERT INTO `npc_spellclick_spells` (`npc_entry`,`spell_id`,`cast_flags`,`user_type`) VALUES
(3461286,61424,1,0),
(3462494,61424,1,0),
(3462151,61424,1,0),
(3463399,61424,1,0);
