-- Dark Chaos - retail companion pet downport batch 5 (10 models / 22 colors)
-- Auto-generated by retroport_tools/dc_pet_gen_batch.py from the 12.1.0.69404 retail client.
-- clockworkduck (Aquatic/Classic Clockwork Quacker), axolotlpet (Skipper) and
-- beaverpet (Delta) were blocklisted before generation: their .m2 files are
-- TACT-encrypted on this build.
-- One CreatureModelData per model; one creature/display/spell/item/vendor/collection per color.
-- Families incl: babywindserpent(5), babysnake(4), arcanegolem(2), cat_kirintor(2), cat_naxx(2), cat_uldum(2), hextroll(2), eyeofkilrog_(1) ...
-- IDs: model 503815-503824 | display 503860-503881 | creature 3463580-3463601
--      item 302720-302741 | spell 303040-303061 | vendor slots 1040-1061

-- 1) creature_model_info
DELETE FROM `creature_model_info` WHERE `DisplayID` BETWEEN 503860 AND 503881;
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`,`VerifiedBuild`)
VALUES
(503860,0.75,2.50,2,0,0),
(503861,0.75,2.50,2,0,0),
(503862,0.75,2.50,2,0,0),
(503863,0.75,2.50,2,0,0),
(503864,0.75,2.50,2,0,0),
(503865,0.75,2.50,2,0,0),
(503866,0.75,2.50,2,0,0),
(503867,0.75,2.50,2,0,0),
(503868,0.75,2.50,2,0,0),
(503869,0.75,2.50,2,0,0),
(503870,0.75,2.50,2,0,0),
(503871,0.75,2.50,2,0,0),
(503872,0.75,2.50,2,0,0),
(503873,0.75,2.50,2,0,0),
(503874,0.75,2.50,2,0,0),
(503875,0.75,2.50,2,0,0),
(503876,0.75,2.50,2,0,0),
(503877,0.75,2.50,2,0,0),
(503878,0.75,2.50,2,0,0),
(503879,0.75,2.50,2,0,0),
(503880,0.75,2.50,2,0,0),
(503881,0.75,2.50,2,0,0);

-- 2) creature_template
DELETE FROM `creature_template` WHERE `entry` BETWEEN 3463580 AND 3463601;
INSERT INTO `creature_template` (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`faction`,`speed_walk`,`speed_run`,`unit_class`,`type`,`AIName`,`MovementType`,`RegenHealth`,`VerifiedBuild`)
VALUES
(3463580,'Snek''zali','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463581,'Ula''took','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463582,'Vibrant Venomfang','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463583,'Volatile Venomfang','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463584,'Zesty','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463585,'Caustic Writhling','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463586,'Corrosive Writhling','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463587,'Slitherfang','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463588,'Zan','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463589,'Preyhunter''s Prismguard','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463590,'Preyhunter''s Riftbreaker','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463591,'Archmage''s Familiar','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463592,'Kirin Tor Kitty','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463593,'Cat''Thuzad','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463594,'Catsramas','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463595,'Amewbisath','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463596,'Mewkahen','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463597,'Cauldron Concoction','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463598,'Soulcoil Remnant','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463599,'Arcane Eye','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463600,'J''imothy','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463601,'Unborn Val''kyr','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0);

-- 3) creature_template_model
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 3463580 AND 3463601;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
VALUES
(3463580,0,503860,1,1,0),
(3463581,0,503861,1,1,0),
(3463582,0,503862,1,1,0),
(3463583,0,503863,1,1,0),
(3463584,0,503864,1,1,0),
(3463585,0,503865,1,1,0),
(3463586,0,503866,1,1,0),
(3463587,0,503867,1,1,0),
(3463588,0,503868,1,1,0),
(3463589,0,503869,1,1,0),
(3463590,0,503870,1,1,0),
(3463591,0,503871,1,1,0),
(3463592,0,503872,1,1,0),
(3463593,0,503873,1,1,0),
(3463594,0,503874,1,1,0),
(3463595,0,503875,1,1,0),
(3463596,0,503876,1,1,0),
(3463597,0,503877,1,1,0),
(3463598,0,503878,1,1,0),
(3463599,0,503879,1,1,0),
(3463600,0,503880,1,1,0),
(3463601,0,503881,1,1,0);

-- 4) item_template (class=15 subclass=2, spellid_1=55884 teach placeholder trigger=0, spellid_2=summon trigger=6)
DELETE FROM `item_template` WHERE `entry` BETWEEN 302720 AND 302741;
INSERT INTO `item_template` (`entry`,`class`,`subclass`,`SoundOverrideSubclass`,`name`,`displayid`,`Quality`,`Flags`,`FlagsExtra`,`BuyCount`,`BuyPrice`,`SellPrice`,`InventoryType`,`Material`,`AllowableClass`,`AllowableRace`,`ItemLevel`,`RequiredLevel`,`maxcount`,`stackable`,`ContainerSlots`,`spellid_1`,`spelltrigger_1`,`spellcharges_1`,`spellppmRate_1`,`spellcooldown_1`,`spellcategory_1`,`spellcategorycooldown_1`,`spellid_2`,`spelltrigger_2`,`spellcharges_2`,`spellppmRate_2`,`spellcooldown_2`,`spellcategory_2`,`spellcategorycooldown_2`,`bonding`,`description`,`RequiredDisenchantSkill`,`duration`,`ScriptName`,`DisenchantID`,`FoodType`,`minMoneyLoot`,`maxMoneyLoot`,`flagsCustom`,`VerifiedBuild`)
VALUES
(302720,15,2,-1,'Cage of the Snek''zali',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303040,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302721,15,2,-1,'Cage of the Ula''took',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303041,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302722,15,2,-1,'Cage of the Vibrant Venomfang',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303042,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302723,15,2,-1,'Cage of the Volatile Venomfang',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303043,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302724,15,2,-1,'Cage of the Zesty',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303044,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302725,15,2,-1,'Cage of the Caustic Writhling',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303045,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302726,15,2,-1,'Cage of the Corrosive Writhling',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303046,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302727,15,2,-1,'Cage of the Slitherfang',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303047,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302728,15,2,-1,'Cage of the Zan',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303048,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302729,15,2,-1,'Cage of the Preyhunter''s Prismguard',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303049,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302730,15,2,-1,'Cage of the Preyhunter''s Riftbreaker',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303050,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302731,15,2,-1,'Cage of the Archmage''s Familiar',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303051,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302732,15,2,-1,'Cage of the Kirin Tor Kitty',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303052,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302733,15,2,-1,'Cage of the Cat''Thuzad',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303053,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302734,15,2,-1,'Cage of the Catsramas',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303054,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302735,15,2,-1,'Cage of the Amewbisath',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303055,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302736,15,2,-1,'Cage of the Mewkahen',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303056,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302737,15,2,-1,'Cage of the Cauldron Concoction',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303057,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302738,15,2,-1,'Cage of the Soulcoil Remnant',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303058,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302739,15,2,-1,'Cage of the Arcane Eye',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303059,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302740,15,2,-1,'Cage of the J''imothy',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303060,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302741,15,2,-1,'Cage of the Unborn Val''kyr',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303061,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0);

-- 5) npc_vendor (Skeletal Petkeeper)
DELETE FROM `npc_vendor` WHERE `entry`=3461229 AND `item` BETWEEN 302720 AND 302741;
DELETE FROM `npc_vendor` WHERE `entry`=3461229 AND `slot` BETWEEN 1040 AND 1061;
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`)
VALUES
(3461229,1040,302720,0,0,0,0),
(3461229,1041,302721,0,0,0,0),
(3461229,1042,302722,0,0,0,0),
(3461229,1043,302723,0,0,0,0),
(3461229,1044,302724,0,0,0,0),
(3461229,1045,302725,0,0,0,0),
(3461229,1046,302726,0,0,0,0),
(3461229,1047,302727,0,0,0,0),
(3461229,1048,302728,0,0,0,0),
(3461229,1049,302729,0,0,0,0),
(3461229,1050,302730,0,0,0,0),
(3461229,1051,302731,0,0,0,0),
(3461229,1052,302732,0,0,0,0),
(3461229,1053,302733,0,0,0,0),
(3461229,1054,302734,0,0,0,0),
(3461229,1055,302735,0,0,0,0),
(3461229,1056,302736,0,0,0,0),
(3461229,1057,302737,0,0,0,0),
(3461229,1058,302738,0,0,0,0),
(3461229,1059,302739,0,0,0,0),
(3461229,1060,302740,0,0,0,0),
(3461229,1061,302741,0,0,0,0);

-- 6) conditions cleanup
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=23 AND `SourceGroup`=3461229 AND `SourceEntry` BETWEEN 302720 AND 302741 AND `ConditionTypeOrReference`=25;

-- 7) dc_pet_definitions (pet_entry = item entry)
DELETE FROM `dc_pet_definitions` WHERE `pet_entry` BETWEEN 302720 AND 302741;
INSERT INTO `dc_pet_definitions` (`pet_entry`,`name`,`pet_type`,`pet_spell_id`,`source`,`faction`,`display_id`,`icon`,`rarity`,`expansion`,`flags`,`variant_group`,`variant_color`)
VALUES
(302720,'Snek''zali','companion',303040,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503860,'',1,4,0,'babywindserpent','Snek''zali'),
(302721,'Ula''took','companion',303041,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503861,'',1,4,0,'babywindserpent','Ula''took'),
(302722,'Vibrant Venomfang','companion',303042,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503862,'',1,4,0,'babywindserpent','Vibrant Venomfang'),
(302723,'Volatile Venomfang','companion',303043,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503863,'',1,4,0,'babywindserpent','Volatile Venomfang'),
(302724,'Zesty','companion',303044,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503864,'',1,4,0,'babywindserpent','Zesty'),
(302725,'Caustic Writhling','companion',303045,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503865,'',1,4,0,'babysnake','Caustic Writhling'),
(302726,'Corrosive Writhling','companion',303046,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503866,'',1,4,0,'babysnake','Corrosive Writhling'),
(302727,'Slitherfang','companion',303047,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503867,'',1,4,0,'babysnake','Slitherfang'),
(302728,'Zan','companion',303048,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503868,'',1,4,0,'babysnake','Zan'),
(302729,'Preyhunter''s Prismguard','companion',303049,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503869,'',1,4,0,'arcanegolem','Preyhunter''s Prismguard'),
(302730,'Preyhunter''s Riftbreaker','companion',303050,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503870,'',1,4,0,'arcanegolem','Preyhunter''s Riftbreaker'),
(302731,'Archmage''s Familiar','companion',303051,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503871,'',1,4,0,'cat_kirintor','Archmage''s Familiar'),
(302732,'Kirin Tor Kitty','companion',303052,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503872,'',1,4,0,'cat_kirintor','Kirin Tor Kitty'),
(302733,'Cat''Thuzad','companion',303053,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503873,'',1,4,0,'cat_naxx','Cat''Thuzad'),
(302734,'Catsramas','companion',303054,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503874,'',1,4,0,'cat_naxx','Catsramas'),
(302735,'Amewbisath','companion',303055,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503875,'',1,4,0,'cat_uldum','Amewbisath'),
(302736,'Mewkahen','companion',303056,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503876,'',1,4,0,'cat_uldum','Mewkahen'),
(302737,'Cauldron Concoction','companion',303057,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503877,'',1,4,0,'hextroll','Cauldron Concoction'),
(302738,'Soulcoil Remnant','companion',303058,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503878,'',1,4,0,'hextroll','Soulcoil Remnant'),
(302739,'Arcane Eye','companion',303059,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503879,'',1,4,0,NULL,NULL),
(302740,'J''imothy','companion',303060,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503880,'',1,4,0,NULL,NULL),
(302741,'Unborn Val''kyr','companion',303061,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503881,'',1,4,0,NULL,NULL)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`pet_spell_id`=VALUES(`pet_spell_id`),`source`=VALUES(`source`),`display_id`=VALUES(`display_id`),`variant_group`=VALUES(`variant_group`),`variant_color`=VALUES(`variant_color`);

-- 8) dc_collection_definitions (collection_type 2 = PET, entry_id = item entry)
DELETE FROM `dc_collection_definitions` WHERE `collection_type`=2 AND `entry_id` BETWEEN 302720 AND 302741;
INSERT INTO `dc_collection_definitions` (`collection_type`,`entry_id`,`enabled`)
VALUES
(2,302720,1),
(2,302721,1),
(2,302722,1),
(2,302723,1),
(2,302724,1),
(2,302725,1),
(2,302726,1),
(2,302727,1),
(2,302728,1),
(2,302729,1),
(2,302730,1),
(2,302731,1),
(2,302732,1),
(2,302733,1),
(2,302734,1),
(2,302735,1),
(2,302736,1),
(2,302737,1),
(2,302738,1),
(2,302739,1),
(2,302740,1),
(2,302741,1);
