-- Dark Chaos - Cataclysm+ retail mount downport batch 8 (1 model / 1 color)
-- Auto-generated by retroport_tools/dc_mount_gen_batch.py from retail 12.1.0.69497.
-- One CreatureModelData per model; one creature/display/spell/item/vendor/collection per color.
-- Scope: oxhomemount (Hearthkeeper's Wandering Caravan). It was TACT-encrypted on
-- 12.1.0.69404 and blocklisted on 2026-08-23; the key was published for 12.1.0.69497
-- and the 2026-08-29 re-probe decrypts a real 2.4 MB MD21, so it is downportable now.
-- MountTypeID 230 = ground (mount_type 0, speed 100).
-- IDs: model 503910-503910 | display 503920-503920 | creature 3463610-3463610
--      item 302750-302750 | spell 303062-303062 | vendor slots 1280-1280

-- 1) creature_model_info
DELETE FROM `creature_model_info` WHERE `DisplayID` BETWEEN 503920 AND 503920;
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`,`VerifiedBuild`)
VALUES
(503920,0.75,2.50,2,0,0);

-- 2) creature_template
DELETE FROM `creature_template` WHERE `entry` BETWEEN 3463610 AND 3463610;
INSERT INTO `creature_template` (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`faction`,`speed_walk`,`speed_run`,`unit_class`,`type`,`AIName`,`MovementType`,`RegenHealth`,`VerifiedBuild`)
VALUES
(3463610,'Hearthkeeper''s Wandering Caravan','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0);

-- 3) creature_template_model
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 3463610 AND 3463610;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
VALUES
(3463610,0,503920,1,1,0);

-- 4) item_template ('Reins of ...', spellid_2 trigger 6 = learn)
DELETE FROM `item_template` WHERE `entry` BETWEEN 302750 AND 302750;
INSERT INTO `item_template` (`entry`,`class`,`subclass`,`SoundOverrideSubclass`,`name`,`displayid`,`Quality`,`Flags`,`FlagsExtra`,`BuyCount`,`BuyPrice`,`SellPrice`,`InventoryType`,`Material`,`AllowableClass`,`AllowableRace`,`ItemLevel`,`RequiredLevel`,`maxcount`,`stackable`,`ContainerSlots`,`spellid_1`,`spelltrigger_1`,`spellcharges_1`,`spellppmRate_1`,`spellcooldown_1`,`spellcategory_1`,`spellcategorycooldown_1`,`spellid_2`,`spelltrigger_2`,`spellcharges_2`,`spellppmRate_2`,`spellcooldown_2`,`spellcategory_2`,`spellcategorycooldown_2`,`bonding`,`description`,`RequiredDisenchantSkill`,`duration`,`ScriptName`,`DisenchantID`,`FoodType`,`minMoneyLoot`,`maxMoneyLoot`,`flagsCustom`,`VerifiedBuild`)
VALUES
(302750,15,5,-1,'Reins of the Hearthkeeper''s Wandering Caravan',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303062,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0);

-- 5) npc_vendor (Skeletal Stablemaster)
DELETE FROM `npc_vendor` WHERE `entry`=3461020 AND `item` BETWEEN 302750 AND 302750;
DELETE FROM `npc_vendor` WHERE `entry`=3461020 AND `slot` BETWEEN 1280 AND 1280;
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`)
VALUES
(3461020,1280,302750,0,0,0,0);

-- 6) conditions cleanup
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=23 AND `SourceGroup`=3461020 AND `SourceEntry` BETWEEN 302750 AND 302750 AND `ConditionTypeOrReference`=25;

-- 7) dc_mount_definitions (fly=type3/speed310, ground=type0/speed100)
DELETE FROM `dc_mount_definitions` WHERE `spell_id` BETWEEN 303062 AND 303062;
INSERT INTO `dc_mount_definitions` (`spell_id`,`name`,`mount_type`,`source`,`faction`,`rarity`,`speed`,`display_id`)
VALUES
(303062,'Hearthkeeper''s Wandering Caravan',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503920)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`mount_type`=VALUES(`mount_type`),`source`=VALUES(`source`),`faction`=VALUES(`faction`),`rarity`=VALUES(`rarity`),`speed`=VALUES(`speed`),`display_id`=VALUES(`display_id`);

-- 8) dc_collection_definitions (collection_type 1 = MOUNT)
DELETE FROM `dc_collection_definitions` WHERE `collection_type`=1 AND `entry_id` BETWEEN 303062 AND 303062;
INSERT INTO `dc_collection_definitions` (`collection_type`,`entry_id`,`enabled`)
VALUES
(1,303062,1);
