-- Dark Chaos - Cataclysm+ retail mount downport batch 2 (11 models / 11 colors)
-- Auto-generated by retroport_tools/dc_mount_gen_batch.py from the 12.0.7 retail client.
-- One CreatureModelData per model; one creature/display/spell/item/vendor/collection per color.
-- Families incl: encrypted(1), encrypted(1), encrypted(1), encrypted(1), encrypted(1), mothfluffy(1), rabbitvoid(1), horse(1) ...
-- IDs: model 502778-502788 | display 503525-503535 | creature 3463433-3463443
-- NOTE 2026-07-29: 4 TACT-encrypted models removed post-gen (Sunflare Driftmoth,
--   Rabbit'ath, Spring Panda, Shadow Spirehawk) -> ID holes 502783/502784/502787/502788,
--   displays 503530/503531/503534/503535, spells 302942/302943/302946/302947. 7 mounts ship.
--      item 302612-302622 | spell 302937-302947 | vendor slots 1216-1226

-- 1) creature_model_info
DELETE FROM `creature_model_info` WHERE `DisplayID` BETWEEN 503525 AND 503535;
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`,`VerifiedBuild`)
VALUES
(503525,0.75,2.50,2,0,0),
(503526,0.75,2.50,2,0,0),
(503527,0.75,2.50,2,0,0),
(503528,0.75,2.50,2,0,0),
(503529,0.75,2.50,2,0,0),
(503532,0.75,2.50,2,0,0),
(503533,0.75,2.50,2,0,0);

-- 2) creature_template
DELETE FROM `creature_template` WHERE `entry` BETWEEN 3463433 AND 3463443;
INSERT INTO `creature_template` (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`faction`,`speed_walk`,`speed_run`,`unit_class`,`type`,`AIName`,`MovementType`,`RegenHealth`,`VerifiedBuild`)
VALUES
(3463433,'Sylverian Dreamer','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463434,'Vulpine Familiar','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463435,'Steamscale Incinerator','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463436,'Alabaster Stormtalon','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463437,'Alabaster Thunderwing','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463440,'Spectral Steed','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463441,'Priestess'' Moonsaber','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0);

-- 3) creature_template_model
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 3463433 AND 3463443;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
VALUES
(3463433,0,503525,1,1,0),
(3463434,0,503526,1,1,0),
(3463435,0,503527,1,1,0),
(3463436,0,503528,1,1,0),
(3463437,0,503529,1,1,0),
(3463440,0,503532,1,1,0),
(3463441,0,503533,1,1,0);

-- 4) item_template ('Reins of ...', spellid_2 trigger 6 = learn)
DELETE FROM `item_template` WHERE `entry` BETWEEN 302612 AND 302622;
INSERT INTO `item_template` (`entry`,`class`,`subclass`,`SoundOverrideSubclass`,`name`,`displayid`,`Quality`,`Flags`,`FlagsExtra`,`BuyCount`,`BuyPrice`,`SellPrice`,`InventoryType`,`Material`,`AllowableClass`,`AllowableRace`,`ItemLevel`,`RequiredLevel`,`maxcount`,`stackable`,`ContainerSlots`,`spellid_1`,`spelltrigger_1`,`spellcharges_1`,`spellppmRate_1`,`spellcooldown_1`,`spellcategory_1`,`spellcategorycooldown_1`,`spellid_2`,`spelltrigger_2`,`spellcharges_2`,`spellppmRate_2`,`spellcooldown_2`,`spellcategory_2`,`spellcategorycooldown_2`,`bonding`,`description`,`RequiredDisenchantSkill`,`duration`,`ScriptName`,`DisenchantID`,`FoodType`,`minMoneyLoot`,`maxMoneyLoot`,`flagsCustom`,`VerifiedBuild`)
VALUES
(302612,15,5,-1,'Reins of the Sylverian Dreamer',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302937,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302613,15,5,-1,'Reins of the Vulpine Familiar',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302938,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302614,15,5,-1,'Reins of the Steamscale Incinerator',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302939,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302615,15,5,-1,'Reins of the Alabaster Stormtalon',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302940,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302616,15,5,-1,'Reins of the Alabaster Thunderwing',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302941,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302619,15,5,-1,'Reins of the Spectral Steed',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302944,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302620,15,5,-1,'Reins of the Priestess'' Moonsaber',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302945,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0);

-- 5) npc_vendor (Skeletal Stablemaster)
DELETE FROM `npc_vendor` WHERE `entry`=3461020 AND `item` BETWEEN 302612 AND 302622;
DELETE FROM `npc_vendor` WHERE `entry`=3461020 AND `slot` BETWEEN 1216 AND 1226;
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`)
VALUES
(3461020,1216,302612,0,0,0,0),
(3461020,1217,302613,0,0,0,0),
(3461020,1218,302614,0,0,0,0),
(3461020,1219,302615,0,0,0,0),
(3461020,1220,302616,0,0,0,0),
(3461020,1223,302619,0,0,0,0),
(3461020,1224,302620,0,0,0,0);

-- 6) conditions cleanup
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=23 AND `SourceGroup`=3461020 AND `SourceEntry` BETWEEN 302612 AND 302622 AND `ConditionTypeOrReference`=25;

-- 7) dc_mount_definitions (fly=type3/speed310, ground=type0/speed100)
DELETE FROM `dc_mount_definitions` WHERE `spell_id` BETWEEN 302937 AND 302947;
INSERT INTO `dc_mount_definitions` (`spell_id`,`name`,`mount_type`,`source`,`faction`,`rarity`,`speed`,`display_id`)
VALUES
(302937,'Sylverian Dreamer',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503525),
(302938,'Vulpine Familiar',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503526),
(302939,'Steamscale Incinerator',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503527),
(302940,'Alabaster Stormtalon',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503528),
(302941,'Alabaster Thunderwing',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503529),
(302944,'Spectral Steed',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503532),
(302945,'Priestess'' Moonsaber',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503533)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`mount_type`=VALUES(`mount_type`),`source`=VALUES(`source`),`faction`=VALUES(`faction`),`rarity`=VALUES(`rarity`),`speed`=VALUES(`speed`),`display_id`=VALUES(`display_id`);

-- 8) dc_collection_definitions (collection_type 1 = MOUNT)
DELETE FROM `dc_collection_definitions` WHERE `collection_type`=1 AND `entry_id` BETWEEN 302937 AND 302947;
INSERT INTO `dc_collection_definitions` (`collection_type`,`entry_id`,`enabled`)
VALUES
(1,302937,1),
(1,302938,1),
(1,302939,1),
(1,302940,1),
(1,302941,1),
(1,302944,1),
(1,302945,1);