-- Dark Chaos - retail companion pet downport batch 1 (25 models / 29 colors)
-- Auto-generated by retroport_tools/dc_pet_gen_batch.py from the 12.0.7 retail client.
-- One CreatureModelData per model; one creature/display/spell/item/vendor/collection per color.
-- Families incl: babynaga(2), capybara(2), faeriedragon(2), flyingbook(2), babyfaeriedragon(1), boundairelemental(1), boundearthelemental(1), chromaticdragon(1) ...
-- IDs: model 502579-502603 | display 503349-503377 | creature 3463404-3463432
--      item 302578-302606 | spell 302908-302936 | vendor slots 980-1008

-- 1) creature_model_info
DELETE FROM `creature_model_info` WHERE `DisplayID` BETWEEN 503349 AND 503377;
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`,`VerifiedBuild`)
VALUES
(503349,0.75,2.50,2,0,0),
(503350,0.75,2.50,2,0,0),
(503351,0.75,2.50,2,0,0),
(503352,0.75,2.50,2,0,0),
(503353,0.75,2.50,2,0,0),
(503354,0.75,2.50,2,0,0),
(503355,0.75,2.50,2,0,0),
(503356,0.75,2.50,2,0,0),
(503357,0.75,2.50,2,0,0),
(503358,0.75,2.50,2,0,0),
(503359,0.75,2.50,2,0,0),
(503360,0.75,2.50,2,0,0),
(503361,0.75,2.50,2,0,0),
(503362,0.75,2.50,2,0,0),
(503363,0.75,2.50,2,0,0),
(503364,0.75,2.50,2,0,0),
(503365,0.75,2.50,2,0,0),
(503366,0.75,2.50,2,0,0),
(503367,0.75,2.50,2,0,0),
(503368,0.75,2.50,2,0,0),
(503369,0.75,2.50,2,0,0),
(503370,0.75,2.50,2,0,0),
(503371,0.75,2.50,2,0,0),
(503372,0.75,2.50,2,0,0),
(503373,0.75,2.50,2,0,0),
(503374,0.75,2.50,2,0,0),
(503375,0.75,2.50,2,0,0),
(503376,0.75,2.50,2,0,0),
(503377,0.75,2.50,2,0,0);

-- 2) creature_template
DELETE FROM `creature_template` WHERE `entry` BETWEEN 3463404 AND 3463432;
INSERT INTO `creature_template` (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`faction`,`speed_walk`,`speed_run`,`unit_class`,`type`,`AIName`,`MovementType`,`RegenHealth`,`VerifiedBuild`)
VALUES
(3463404,'Kelpfin','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463405,'Zanj''ir Poker','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463406,'Do, Child of Fi''lo','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463407,'Gortham','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463408,'Kal''andu','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463409,'Moon Darter','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463410,'Animated Tome','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463411,'Court Scribe','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463412,'Star the Lucky Dragon','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463413,'Zephyrian Prince','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463414,'Surger','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463415,'Scourge of the Aspects','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463416,'Dottie','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463417,'Ashleaft Spriteling','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463418,'Viscous Horror','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463419,'Magic Lamp','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463420,'Nightmare Lasher','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463421,'Empowered Manafiend','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463422,'Darkmoon Monkey','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463423,'Deathy','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463424,'Chi-Ji Kite','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463425,'Thundering Serpent Hatchling','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463426,'Lady Feathersworth','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463427,'Ravenous Prideling','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463428,'Firewing','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463429,'Ji-Kun Hatchling','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463430,'Wayward Spirit','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463431,'Salverun','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463432,'Muskpaw Calf','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0);

-- 3) creature_template_model
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 3463404 AND 3463432;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
VALUES
(3463404,0,503349,1,1,0),
(3463405,0,503350,1,1,0),
(3463406,0,503351,1,1,0),
(3463407,0,503352,1,1,0),
(3463408,0,503353,1,1,0),
(3463409,0,503354,1,1,0),
(3463410,0,503355,1,1,0),
(3463411,0,503356,1,1,0),
(3463412,0,503357,1,1,0),
(3463413,0,503358,1,1,0),
(3463414,0,503359,1,1,0),
(3463415,0,503360,1,1,0),
(3463416,0,503361,1,1,0),
(3463417,0,503362,1,1,0),
(3463418,0,503363,1,1,0),
(3463419,0,503364,1,1,0),
(3463420,0,503365,1,1,0),
(3463421,0,503366,1,1,0),
(3463422,0,503367,1,1,0),
(3463423,0,503368,1,1,0),
(3463424,0,503369,1,1,0),
(3463425,0,503370,1,1,0),
(3463426,0,503371,1,1,0),
(3463427,0,503372,1,1,0),
(3463428,0,503373,1,1,0),
(3463429,0,503374,1,1,0),
(3463430,0,503375,1,1,0),
(3463431,0,503376,1,1,0),
(3463432,0,503377,1,1,0);

-- 4) item_template (class=15 subclass=2, spellid_1=55884 teach placeholder trigger=0, spellid_2=summon trigger=6)
DELETE FROM `item_template` WHERE `entry` BETWEEN 302578 AND 302606;
INSERT INTO `item_template` (`entry`,`class`,`subclass`,`SoundOverrideSubclass`,`name`,`displayid`,`Quality`,`Flags`,`FlagsExtra`,`BuyCount`,`BuyPrice`,`SellPrice`,`InventoryType`,`Material`,`AllowableClass`,`AllowableRace`,`ItemLevel`,`RequiredLevel`,`maxcount`,`stackable`,`ContainerSlots`,`spellid_1`,`spelltrigger_1`,`spellcharges_1`,`spellppmRate_1`,`spellcooldown_1`,`spellcategory_1`,`spellcategorycooldown_1`,`spellid_2`,`spelltrigger_2`,`spellcharges_2`,`spellppmRate_2`,`spellcooldown_2`,`spellcategory_2`,`spellcategorycooldown_2`,`bonding`,`description`,`RequiredDisenchantSkill`,`duration`,`ScriptName`,`DisenchantID`,`FoodType`,`minMoneyLoot`,`maxMoneyLoot`,`flagsCustom`,`VerifiedBuild`)
VALUES
(302578,15,2,-1,'Cage of the Kelpfin',10267049,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302908,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302579,15,2,-1,'Cage of the Zanj''ir Poker',10267048,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302909,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302580,15,2,-1,'Cage of the Do, Child of Fi''lo',10205238,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302910,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302581,15,2,-1,'Cage of the Gortham',10205238,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302911,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302582,15,2,-1,'Cage of the Kal''andu',11071791,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302912,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302583,15,2,-1,'Cage of the Moon Darter',13840606,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302913,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302584,15,2,-1,'Cage of the Animated Tome',8134544,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302914,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302585,15,2,-1,'Cage of the Court Scribe',8355498,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302915,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302586,15,2,-1,'Cage of the Star the Lucky Dragon',15442919,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302916,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302587,15,2,-1,'Cage of the Zephyrian Prince',8132845,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302917,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302588,15,2,-1,'Cage of the Surger',8133257,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302918,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302589,15,2,-1,'Cage of the Scourge of the Aspects',14648449,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302919,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302590,15,2,-1,'Cage of the Dottie',10735061,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302920,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302591,15,2,-1,'Cage of the Ashleaft Spriteling',8136021,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302921,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302592,15,2,-1,'Cage of the Viscous Horror',8538039,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302922,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302593,15,2,-1,'Cage of the Magic Lamp',8134971,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302923,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302594,15,2,-1,'Cage of the Nightmare Lasher',8959797,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302924,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302595,15,2,-1,'Cage of the Empowered Manafiend',8237227,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302925,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302596,15,2,-1,'Cage of the Darkmoon Monkey',8132159,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302926,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302597,15,2,-1,'Cage of the Deathy',8134430,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302927,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302598,15,2,-1,'Cage of the Chi-Ji Kite',8604252,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302928,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302599,15,2,-1,'Cage of the Thundering Serpent Hatchling',8646018,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302929,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302600,15,2,-1,'Cage of the Lady Feathersworth',10103802,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302930,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302601,15,2,-1,'Cage of the Ravenous Prideling',8135782,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302931,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302602,15,2,-1,'Cage of the Firewing',8526578,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302932,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302603,15,2,-1,'Cage of the Ji-Kun Hatchling',8838694,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302933,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302604,15,2,-1,'Cage of the Wayward Spirit',8801002,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302934,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302605,15,2,-1,'Cage of the Salverun',13045822,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302935,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302606,15,2,-1,'Cage of the Muskpaw Calf',13751887,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302936,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0);

-- 5) npc_vendor (Skeletal Petkeeper)
DELETE FROM `npc_vendor` WHERE `entry`=3461229 AND `item` BETWEEN 302578 AND 302606;
DELETE FROM `npc_vendor` WHERE `entry`=3461229 AND `slot` BETWEEN 980 AND 1008;
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`)
VALUES
(3461229,980,302578,0,0,0,0),
(3461229,981,302579,0,0,0,0),
(3461229,982,302580,0,0,0,0),
(3461229,983,302581,0,0,0,0),
(3461229,984,302582,0,0,0,0),
(3461229,985,302583,0,0,0,0),
(3461229,986,302584,0,0,0,0),
(3461229,987,302585,0,0,0,0),
(3461229,988,302586,0,0,0,0),
(3461229,989,302587,0,0,0,0),
(3461229,990,302588,0,0,0,0),
(3461229,991,302589,0,0,0,0),
(3461229,992,302590,0,0,0,0),
(3461229,993,302591,0,0,0,0),
(3461229,994,302592,0,0,0,0),
(3461229,995,302593,0,0,0,0),
(3461229,996,302594,0,0,0,0),
(3461229,997,302595,0,0,0,0),
(3461229,998,302596,0,0,0,0),
(3461229,999,302597,0,0,0,0),
(3461229,1000,302598,0,0,0,0),
(3461229,1001,302599,0,0,0,0),
(3461229,1002,302600,0,0,0,0),
(3461229,1003,302601,0,0,0,0),
(3461229,1004,302602,0,0,0,0),
(3461229,1005,302603,0,0,0,0),
(3461229,1006,302604,0,0,0,0),
(3461229,1007,302605,0,0,0,0),
(3461229,1008,302606,0,0,0,0);

-- 6) conditions cleanup
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=23 AND `SourceGroup`=3461229 AND `SourceEntry` BETWEEN 302578 AND 302606 AND `ConditionTypeOrReference`=25;

-- 7) dc_pet_definitions (pet_entry = item entry)
DELETE FROM `dc_pet_definitions` WHERE `pet_entry` BETWEEN 302578 AND 302606;
INSERT INTO `dc_pet_definitions` (`pet_entry`,`name`,`pet_type`,`pet_spell_id`,`source`,`faction`,`display_id`,`icon`,`rarity`,`expansion`,`flags`,`variant_group`,`variant_color`)
VALUES
(302578,'Kelpfin','companion',302908,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503349,'',1,4,0,'babynaga','Kelpfin'),
(302579,'Zanj''ir Poker','companion',302909,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503350,'',1,4,0,'babynaga','Zanj''ir Poker'),
(302580,'Do, Child of Fi''lo','companion',302910,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503351,'',1,4,0,'capybara','Do, Child of Fi''lo'),
(302581,'Gortham','companion',302911,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503352,'',1,4,0,'capybara','Gortham'),
(302582,'Kal''andu','companion',302912,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503353,'',1,4,0,'faeriedragon','Kal''andu'),
(302583,'Moon Darter','companion',302913,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503354,'',1,4,0,'faeriedragon','Moon Darter'),
(302584,'Animated Tome','companion',302914,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503355,'',1,4,0,'flyingbook','Animated Tome'),
(302585,'Court Scribe','companion',302915,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503356,'',1,4,0,'flyingbook','Court Scribe'),
(302586,'Star the Lucky Dragon','companion',302916,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503357,'',1,4,0,NULL,NULL),
(302587,'Zephyrian Prince','companion',302917,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503358,'',1,4,0,NULL,NULL),
(302588,'Surger','companion',302918,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503359,'',1,4,0,NULL,NULL),
(302589,'Scourge of the Aspects','companion',302919,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503360,'',1,4,0,NULL,NULL),
(302590,'Dottie','companion',302920,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503361,'',1,4,0,NULL,NULL),
(302591,'Ashleaft Spriteling','companion',302921,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503362,'',1,4,0,NULL,NULL),
(302592,'Viscous Horror','companion',302922,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503363,'',1,4,0,NULL,NULL),
(302593,'Magic Lamp','companion',302923,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503364,'',1,4,0,NULL,NULL),
(302594,'Nightmare Lasher','companion',302924,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503365,'',1,4,0,NULL,NULL),
(302595,'Empowered Manafiend','companion',302925,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503366,'',1,4,0,NULL,NULL),
(302596,'Darkmoon Monkey','companion',302926,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503367,'',1,4,0,NULL,NULL),
(302597,'Deathy','companion',302927,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503368,'',1,4,0,NULL,NULL),
(302598,'Chi-Ji Kite','companion',302928,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503369,'',1,4,0,NULL,NULL),
(302599,'Thundering Serpent Hatchling','companion',302929,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503370,'',1,4,0,NULL,NULL),
(302600,'Lady Feathersworth','companion',302930,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503371,'',1,4,0,NULL,NULL),
(302601,'Ravenous Prideling','companion',302931,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503372,'',1,4,0,NULL,NULL),
(302602,'Firewing','companion',302932,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503373,'',1,4,0,NULL,NULL),
(302603,'Ji-Kun Hatchling','companion',302933,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503374,'',1,4,0,NULL,NULL),
(302604,'Wayward Spirit','companion',302934,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503375,'',1,4,0,NULL,NULL),
(302605,'Salverun','companion',302935,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503376,'',1,4,0,NULL,NULL),
(302606,'Muskpaw Calf','companion',302936,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503377,'',1,4,0,NULL,NULL)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`pet_spell_id`=VALUES(`pet_spell_id`),`source`=VALUES(`source`),`display_id`=VALUES(`display_id`),`variant_group`=VALUES(`variant_group`),`variant_color`=VALUES(`variant_color`);

-- 8) dc_collection_definitions (collection_type 2 = PET, entry_id = item entry)
DELETE FROM `dc_collection_definitions` WHERE `collection_type`=2 AND `entry_id` BETWEEN 302578 AND 302606;
INSERT INTO `dc_collection_definitions` (`collection_type`,`entry_id`,`enabled`)
VALUES
(2,302578,1),
(2,302579,1),
(2,302580,1),
(2,302581,1),
(2,302582,1),
(2,302583,1),
(2,302584,1),
(2,302585,1),
(2,302586,1),
(2,302587,1),
(2,302588,1),
(2,302589,1),
(2,302590,1),
(2,302591,1),
(2,302592,1),
(2,302593,1),
(2,302594,1),
(2,302595,1),
(2,302596,1),
(2,302597,1),
(2,302598,1),
(2,302599,1),
(2,302600,1),
(2,302601,1),
(2,302602,1),
(2,302603,1),
(2,302604,1),
(2,302605,1),
(2,302606,1);
