-- Dark Chaos - retail companion pet downport batch 1 (4 models / 4 colors)
-- Auto-generated by retroport_tools/dc_pet_gen_batch.py from the 12.0.7 retail client.
-- One CreatureModelData per model; one creature/display/spell/item/vendor/collection per color.
-- Families incl: babymurlocxalatath(1), batrevendreth(1), moth(1), shabeaky(1) ...
-- IDs: model 502920-502923 | display 503600-503603 | creature 3463510-3463513
--      item 302645-302648 | spell 302970-302973 | vendor slots 1024-1027

-- 1) creature_model_info
DELETE FROM `creature_model_info` WHERE `DisplayID` BETWEEN 503600 AND 503603;
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`,`VerifiedBuild`)
VALUES
(503600,0.75,2.50,2,0,0),
(503601,0.75,2.50,2,0,0),
(503602,0.75,2.50,2,0,0),
(503603,0.75,2.50,2,0,0);

-- 2) creature_template
DELETE FROM `creature_template` WHERE `entry` BETWEEN 3463510 AND 3463513;
INSERT INTO `creature_template` (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`faction`,`speed_walk`,`speed_run`,`unit_class`,`type`,`AIName`,`MovementType`,`RegenHealth`,`VerifiedBuild`)
VALUES
(3463510,'Murk''atath','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463511,'The Sire''s Ghastly Screecher','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463512,'Sunflicker Driftmoth','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463513,'Sha-Warped Hippogryph Hatchling','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0);

-- 3) creature_template_model
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 3463510 AND 3463513;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
VALUES
(3463510,0,503600,1,1,0),
(3463511,0,503601,1,1,0),
(3463512,0,503602,1,1,0),
(3463513,0,503603,1,1,0);

-- 4) item_template (class=15 subclass=2, spellid_1=55884 teach placeholder trigger=0, spellid_2=summon trigger=6)
DELETE FROM `item_template` WHERE `entry` BETWEEN 302645 AND 302648;
INSERT INTO `item_template` (`entry`,`class`,`subclass`,`SoundOverrideSubclass`,`name`,`displayid`,`Quality`,`Flags`,`FlagsExtra`,`BuyCount`,`BuyPrice`,`SellPrice`,`InventoryType`,`Material`,`AllowableClass`,`AllowableRace`,`ItemLevel`,`RequiredLevel`,`maxcount`,`stackable`,`ContainerSlots`,`spellid_1`,`spelltrigger_1`,`spellcharges_1`,`spellppmRate_1`,`spellcooldown_1`,`spellcategory_1`,`spellcategorycooldown_1`,`spellid_2`,`spelltrigger_2`,`spellcharges_2`,`spellppmRate_2`,`spellcooldown_2`,`spellcategory_2`,`spellcategorycooldown_2`,`bonding`,`description`,`RequiredDisenchantSkill`,`duration`,`ScriptName`,`DisenchantID`,`FoodType`,`minMoneyLoot`,`maxMoneyLoot`,`flagsCustom`,`VerifiedBuild`)
VALUES
(302645,15,2,-1,'Cage of the Murk''atath',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302970,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302646,15,2,-1,'Cage of the The Sire''s Ghastly Screecher',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302971,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302647,15,2,-1,'Cage of the Sunflicker Driftmoth',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302972,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302648,15,2,-1,'Cage of the Sha-Warped Hippogryph Hatchling',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302973,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0);

-- 5) npc_vendor (Skeletal Petkeeper)
DELETE FROM `npc_vendor` WHERE `entry`=3461229 AND `item` BETWEEN 302645 AND 302648;
DELETE FROM `npc_vendor` WHERE `entry`=3461229 AND `slot` BETWEEN 1024 AND 1027;
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`)
VALUES
(3461229,1024,302645,0,0,0,0),
(3461229,1025,302646,0,0,0,0),
(3461229,1026,302647,0,0,0,0),
(3461229,1027,302648,0,0,0,0);

-- 6) conditions cleanup
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=23 AND `SourceGroup`=3461229 AND `SourceEntry` BETWEEN 302645 AND 302648 AND `ConditionTypeOrReference`=25;

-- 7) dc_pet_definitions (pet_entry = item entry)
DELETE FROM `dc_pet_definitions` WHERE `pet_entry` BETWEEN 302645 AND 302648;
INSERT INTO `dc_pet_definitions` (`pet_entry`,`name`,`pet_type`,`pet_spell_id`,`source`,`faction`,`display_id`,`icon`,`rarity`,`expansion`,`flags`,`variant_group`,`variant_color`)
VALUES
(302645,'Murk''atath','companion',302970,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503600,'',1,4,0,NULL,NULL),
(302646,'The Sire''s Ghastly Screecher','companion',302971,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503601,'',1,4,0,NULL,NULL),
(302647,'Sunflicker Driftmoth','companion',302972,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503602,'',1,4,0,NULL,NULL),
(302648,'Sha-Warped Hippogryph Hatchling','companion',302973,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503603,'',1,4,0,NULL,NULL)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`pet_spell_id`=VALUES(`pet_spell_id`),`source`=VALUES(`source`),`display_id`=VALUES(`display_id`),`variant_group`=VALUES(`variant_group`),`variant_color`=VALUES(`variant_color`);

-- 8) dc_collection_definitions (collection_type 2 = PET, entry_id = item entry)
DELETE FROM `dc_collection_definitions` WHERE `collection_type`=2 AND `entry_id` BETWEEN 302645 AND 302648;
INSERT INTO `dc_collection_definitions` (`collection_type`,`entry_id`,`enabled`)
VALUES
(2,302645,1),
(2,302646,1),
(2,302647,1),
(2,302648,1);
