-- Dark Chaos - retail companion pet downport batch 1 (1 models / 3 colors)
-- Auto-generated by retroport_tools/dc_pet_gen_batch.py from the 12.0.7 retail client.
-- One CreatureModelData per model; one creature/display/spell/item/vendor/collection per color.
-- Families incl: gnomeskeleton(3) ...
-- IDs: model 502935-502935 | display 503620-503622 | creature 3463530-3463532
--      item 302665-302667 | spell 302990-302992 | vendor slots 1030-1032

-- 1) creature_model_info
DELETE FROM `creature_model_info` WHERE `DisplayID` BETWEEN 503620 AND 503622;
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`,`VerifiedBuild`)
VALUES
(503620,0.75,2.50,2,0,0),
(503621,0.75,2.50,2,0,0),
(503622,0.75,2.50,2,0,0);

-- 2) creature_template
DELETE FROM `creature_template` WHERE `entry` BETWEEN 3463530 AND 3463532;
INSERT INTO `creature_template` (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`faction`,`speed_walk`,`speed_run`,`unit_class`,`type`,`AIName`,`MovementType`,`RegenHealth`,`VerifiedBuild`)
VALUES
(3463530,'Detective Ray','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463531,'Micromancer','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463532,'Minimancer','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0);

-- 3) creature_template_model
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 3463530 AND 3463532;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
VALUES
(3463530,0,503620,1,1,0),
(3463531,0,503621,1,1,0),
(3463532,0,503622,1,1,0);

-- 4) item_template (class=15 subclass=2, spellid_1=55884 teach placeholder trigger=0, spellid_2=summon trigger=6)
DELETE FROM `item_template` WHERE `entry` BETWEEN 302665 AND 302667;
INSERT INTO `item_template` (`entry`,`class`,`subclass`,`SoundOverrideSubclass`,`name`,`displayid`,`Quality`,`Flags`,`FlagsExtra`,`BuyCount`,`BuyPrice`,`SellPrice`,`InventoryType`,`Material`,`AllowableClass`,`AllowableRace`,`ItemLevel`,`RequiredLevel`,`maxcount`,`stackable`,`ContainerSlots`,`spellid_1`,`spelltrigger_1`,`spellcharges_1`,`spellppmRate_1`,`spellcooldown_1`,`spellcategory_1`,`spellcategorycooldown_1`,`spellid_2`,`spelltrigger_2`,`spellcharges_2`,`spellppmRate_2`,`spellcooldown_2`,`spellcategory_2`,`spellcategorycooldown_2`,`bonding`,`description`,`RequiredDisenchantSkill`,`duration`,`ScriptName`,`DisenchantID`,`FoodType`,`minMoneyLoot`,`maxMoneyLoot`,`flagsCustom`,`VerifiedBuild`)
VALUES
(302665,15,2,-1,'Cage of the Detective Ray',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302990,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302666,15,2,-1,'Cage of the Micromancer',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302991,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(302667,15,2,-1,'Cage of the Minimancer',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,302992,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0);

-- 5) npc_vendor (Skeletal Petkeeper)
DELETE FROM `npc_vendor` WHERE `entry`=3461229 AND `item` BETWEEN 302665 AND 302667;
DELETE FROM `npc_vendor` WHERE `entry`=3461229 AND `slot` BETWEEN 1030 AND 1032;
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`)
VALUES
(3461229,1030,302665,0,0,0,0),
(3461229,1031,302666,0,0,0,0),
(3461229,1032,302667,0,0,0,0);

-- 6) conditions cleanup
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=23 AND `SourceGroup`=3461229 AND `SourceEntry` BETWEEN 302665 AND 302667 AND `ConditionTypeOrReference`=25;

-- 7) dc_pet_definitions (pet_entry = item entry)
DELETE FROM `dc_pet_definitions` WHERE `pet_entry` BETWEEN 302665 AND 302667;
INSERT INTO `dc_pet_definitions` (`pet_entry`,`name`,`pet_type`,`pet_spell_id`,`source`,`faction`,`display_id`,`icon`,`rarity`,`expansion`,`flags`,`variant_group`,`variant_color`)
VALUES
(302665,'Detective Ray','companion',302990,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503620,'',1,4,0,'gnomeskeleton','Detective Ray'),
(302666,'Micromancer','companion',302991,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503621,'',1,4,0,'gnomeskeleton','Micromancer'),
(302667,'Minimancer','companion',302992,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,503622,'',1,4,0,'gnomeskeleton','Minimancer')
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`pet_spell_id`=VALUES(`pet_spell_id`),`source`=VALUES(`source`),`display_id`=VALUES(`display_id`),`variant_group`=VALUES(`variant_group`),`variant_color`=VALUES(`variant_color`);

-- 8) dc_collection_definitions (collection_type 2 = PET, entry_id = item entry)
DELETE FROM `dc_collection_definitions` WHERE `collection_type`=2 AND `entry_id` BETWEEN 302665 AND 302667;
INSERT INTO `dc_collection_definitions` (`collection_type`,`entry_id`,`enabled`)
VALUES
(2,302665,1),
(2,302666,1),
(2,302667,1);
