-- Dark Chaos - retail companion pet downport batch 1 (6 models / 7 colors)
-- Auto-generated by retroport_tools/dc_pet_gen_batch.py from the 12.0.7 retail client.
-- One CreatureModelData per model; one creature/display/spell/item/vendor/collection per color.
-- Families incl: clockworkduck(2), axolotl(1), babyfaeriedragon_pink(1), beaver(1), encrypted(1), encrypted(1) ...
-- IDs: model 506051-506056 | display 505175-505181 | creature 3463619-3463625
--      item 303071-303077 | spell 303071-303077 | vendor slots 1872-1878

-- 1) creature_model_info
DELETE FROM `creature_model_info` WHERE `DisplayID` BETWEEN 505175 AND 505181;
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`,`VerifiedBuild`)
VALUES
(505175,0.75,2.50,2,0,0),
(505176,0.75,2.50,2,0,0),
(505177,0.75,2.50,2,0,0),
(505178,0.75,2.50,2,0,0),
(505179,0.75,2.50,2,0,0),
(505180,0.75,2.50,2,0,0),
(505181,0.75,2.50,2,0,0);

-- 2) creature_template
DELETE FROM `creature_template` WHERE `entry` BETWEEN 3463619 AND 3463625;
INSERT INTO `creature_template` (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`faction`,`speed_walk`,`speed_run`,`unit_class`,`type`,`AIName`,`MovementType`,`RegenHealth`,`VerifiedBuild`)
VALUES
(3463619,'Aquatic Clockwork Quacker','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463620,'Classic Clockwork Quacker','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463621,'Skipper','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463622,'Pinky','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463623,'Delta','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463624,'Jingles','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0),
(3463625,'Timeless Mechanical Dragonling','Custom Companion Pet',1,1,35,1,1.14286,1,7,'',0,1,0);

-- 3) creature_template_model
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 3463619 AND 3463625;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
VALUES
(3463619,0,505175,1,1,0),
(3463620,0,505176,1,1,0),
(3463621,0,505177,1,1,0),
(3463622,0,505178,1,1,0),
(3463623,0,505179,1,1,0),
(3463624,0,505180,1,1,0),
(3463625,0,505181,1,1,0);

-- 4) item_template (class=15 subclass=2, spellid_1=55884 teach placeholder trigger=0, spellid_2=summon trigger=6)
DELETE FROM `item_template` WHERE `entry` BETWEEN 303071 AND 303077;
INSERT INTO `item_template` (`entry`,`class`,`subclass`,`SoundOverrideSubclass`,`name`,`displayid`,`Quality`,`Flags`,`FlagsExtra`,`BuyCount`,`BuyPrice`,`SellPrice`,`InventoryType`,`Material`,`AllowableClass`,`AllowableRace`,`ItemLevel`,`RequiredLevel`,`maxcount`,`stackable`,`ContainerSlots`,`spellid_1`,`spelltrigger_1`,`spellcharges_1`,`spellppmRate_1`,`spellcooldown_1`,`spellcategory_1`,`spellcategorycooldown_1`,`spellid_2`,`spelltrigger_2`,`spellcharges_2`,`spellppmRate_2`,`spellcooldown_2`,`spellcategory_2`,`spellcategorycooldown_2`,`bonding`,`description`,`RequiredDisenchantSkill`,`duration`,`ScriptName`,`DisenchantID`,`FoodType`,`minMoneyLoot`,`maxMoneyLoot`,`flagsCustom`,`VerifiedBuild`)
VALUES
(303071,15,2,-1,'Cage of the Aquatic Clockwork Quacker',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303071,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(303072,15,2,-1,'Cage of the Classic Clockwork Quacker',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303072,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(303073,15,2,-1,'Cage of the Skipper',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303073,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(303074,15,2,-1,'Cage of the Pinky',68747,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303074,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(303075,15,2,-1,'Cage of the Delta',68747,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303075,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(303076,15,2,-1,'Cage of the Jingles',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303076,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0),
(303077,15,2,-1,'Cage of the Timeless Mechanical Dragonling',68747,3,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303077,6,0,0,-1,0,-1,0,'Teaches you how to summon this companion.',-1,0,'',0,0,0,0,0,0);

-- 5) npc_vendor (Skeletal Petkeeper)
DELETE FROM `npc_vendor` WHERE `entry`=3461229 AND `item` BETWEEN 303071 AND 303077;
DELETE FROM `npc_vendor` WHERE `entry`=3461229 AND `slot` BETWEEN 1872 AND 1878;
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`)
VALUES
(3461229,1872,303071,0,0,0,0),
(3461229,1873,303072,0,0,0,0),
(3461229,1874,303073,0,0,0,0),
(3461229,1875,303074,0,0,0,0),
(3461229,1876,303075,0,0,0,0),
(3461229,1877,303076,0,0,0,0),
(3461229,1878,303077,0,0,0,0);

-- 6) conditions cleanup
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=23 AND `SourceGroup`=3461229 AND `SourceEntry` BETWEEN 303071 AND 303077 AND `ConditionTypeOrReference`=25;

-- 7) dc_pet_definitions (pet_entry = item entry)
DELETE FROM `dc_pet_definitions` WHERE `pet_entry` BETWEEN 303071 AND 303077;
INSERT INTO `dc_pet_definitions` (`pet_entry`,`name`,`pet_type`,`pet_spell_id`,`source`,`faction`,`display_id`,`icon`,`rarity`,`expansion`,`flags`,`variant_group`,`variant_color`)
VALUES
(303071,'Aquatic Clockwork Quacker','companion',303071,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,505175,'inv_clockworkduck',3,4,0,'clockworkduck','Aquatic Clockwork Quacker'),
(303072,'Classic Clockwork Quacker','companion',303072,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,505176,'inv_clockworkduck',3,4,0,'clockworkduck','Classic Clockwork Quacker'),
(303073,'Skipper','companion',303073,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,505177,'inv_axolotlpet',3,4,0,NULL,NULL),
(303074,'Pinky','companion',303074,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,505178,'inv_babyfaeriedragon_pink',4,4,0,NULL,NULL),
(303075,'Delta','companion',303075,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,505179,'inv_beaverpet',4,4,0,NULL,NULL),
(303076,'Jingles','companion',303076,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,505180,'inv_encrypted15',3,4,0,NULL,NULL),
(303077,'Timeless Mechanical Dragonling','companion',303077,'{"type":"vendor","npc":"Skeletal Petkeeper","npcEntry":3461229}',0,505181,'inv_encrypted17',3,4,0,NULL,NULL)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`pet_spell_id`=VALUES(`pet_spell_id`),`source`=VALUES(`source`),`display_id`=VALUES(`display_id`),`variant_group`=VALUES(`variant_group`),`variant_color`=VALUES(`variant_color`);

-- 8) dc_collection_definitions (collection_type 2 = PET, entry_id = item entry)
DELETE FROM `dc_collection_definitions` WHERE `collection_type`=2 AND `entry_id` BETWEEN 303071 AND 303077;
INSERT INTO `dc_collection_definitions` (`collection_type`,`entry_id`,`enabled`)
VALUES
(2,303071,1),
(2,303072,1),
(2,303073,1),
(2,303074,1),
(2,303075,1),
(2,303076,1),
(2,303077,1);
