-- Dark Chaos - Cataclysm+ retail mount downport batch 7 (13 models / 32 colors)
-- Auto-generated by retroport_tools/dc_mount_gen_batch.py from the 12.1.0.69404 retail client.
-- crabtuskarrmount (Tuskarr Hermit Crab) and oxhomemount (Hearthkeeper's Wandering
-- Caravan) were dropped after generation: both .m2 files are TACT-encrypted on this
-- build. Their ids (display 503846/503850, creature 3463566/3463570, item
-- 302706/302710, spell 303026/303030, slots 1266/1270) are left as holes.
-- One CreatureModelData per model; one creature/display/spell/item/vendor/collection per color.
-- Families incl: broomstickspicewitch(7), chameleon(4), venomserpent(4), writhes(4), windserpent(3), viciouslightbloomboar(2), windserpent3_skeletal(2), darkwellphoenix(1) ...
-- IDs: model 503800-503814 | display 503820-503853 | creature 3463540-3463573
--      item 302680-302713 | spell 303000-303033 | vendor slots 1240-1273

-- 1) creature_model_info
DELETE FROM `creature_model_info` WHERE `DisplayID` BETWEEN 503820 AND 503853;
INSERT INTO `creature_model_info` (`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`,`VerifiedBuild`)
VALUES
(503820,0.75,2.50,2,0,0),
(503821,0.75,2.50,2,0,0),
(503822,0.75,2.50,2,0,0),
(503823,0.75,2.50,2,0,0),
(503824,0.75,2.50,2,0,0),
(503825,0.75,2.50,2,0,0),
(503826,0.75,2.50,2,0,0),
(503827,0.75,2.50,2,0,0),
(503828,0.75,2.50,2,0,0),
(503829,0.75,2.50,2,0,0),
(503830,0.75,2.50,2,0,0),
(503831,0.75,2.50,2,0,0),
(503832,0.75,2.50,2,0,0),
(503833,0.75,2.50,2,0,0),
(503834,0.75,2.50,2,0,0),
(503835,0.75,2.50,2,0,0),
(503836,0.75,2.50,2,0,0),
(503837,0.75,2.50,2,0,0),
(503838,0.75,2.50,2,0,0),
(503839,0.75,2.50,2,0,0),
(503840,0.75,2.50,2,0,0),
(503841,0.75,2.50,2,0,0),
(503842,0.75,2.50,2,0,0),
(503843,0.75,2.50,2,0,0),
(503844,0.75,2.50,2,0,0),
(503845,0.75,2.50,2,0,0),
(503847,0.75,2.50,2,0,0),
(503848,0.75,2.50,2,0,0),
(503849,0.75,2.50,2,0,0),
(503851,0.75,2.50,2,0,0),
(503852,0.75,2.50,2,0,0),
(503853,0.75,2.50,2,0,0);

-- 2) creature_template
DELETE FROM `creature_template` WHERE `entry` BETWEEN 3463540 AND 3463573;
INSERT INTO `creature_template` (`entry`,`name`,`subname`,`minlevel`,`maxlevel`,`faction`,`speed_walk`,`speed_run`,`unit_class`,`type`,`AIName`,`MovementType`,`RegenHealth`,`VerifiedBuild`)
VALUES
(3463540,'Autumnal Witchwick''s Rider','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463541,'Blushing Witchwick''s Rider','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463542,'Carmine Witchwick''s Rider','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463543,'Moonlit Witchwick''s Rider','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463544,'Mossy Witchwick''s Rider','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463545,'Scarlet Witchwick''s Rider','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463546,'Wintry Witchwick''s Rider','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463547,'Crested Aqua Leafmimic','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463548,'Crested Ember Leafmimic','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463549,'Crested Verdant Leafmimic','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463550,'Crested Violet Leafmimic','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463551,'Auriferous Venomfang','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463552,'Caustic Venomfang','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463553,'Crimson Venomfang','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463554,'Sea-Dwelling Isle Serpent','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463555,'Indigo Coiled Horror','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463556,'Ruby Writhe','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463557,'The Writhing Brood','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463558,'Venomous Coiler','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463559,'Emerald Skyfang','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463560,'Topaz Skyfang','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463561,'Violet-Backed Skyfang','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463562,'Vicious Lightbloom Boar','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463563,'Vicious Lightbloom Boar','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463564,'Breath of Blight','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463565,'Breath of Ruin','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463567,'Umbral Ashes','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463568,'Primeval Skyfriend','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463569,'Spirit of Tok''jara','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463571,'Whoofle Bramblewing','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463572,'Corroded Soul Crusher','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0),
(3463573,'Apophic Soul Crusher','Custom Mount Model',80,80,35,1,1.14286,1,1,'',0,1,0);

-- 3) creature_template_model
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 3463540 AND 3463573;
INSERT INTO `creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
VALUES
(3463540,0,503820,1,1,0),
(3463541,0,503821,1,1,0),
(3463542,0,503822,1,1,0),
(3463543,0,503823,1,1,0),
(3463544,0,503824,1,1,0),
(3463545,0,503825,1,1,0),
(3463546,0,503826,1,1,0),
(3463547,0,503827,1,1,0),
(3463548,0,503828,1,1,0),
(3463549,0,503829,1,1,0),
(3463550,0,503830,1,1,0),
(3463551,0,503831,1,1,0),
(3463552,0,503832,1,1,0),
(3463553,0,503833,1,1,0),
(3463554,0,503834,1,1,0),
(3463555,0,503835,1,1,0),
(3463556,0,503836,1,1,0),
(3463557,0,503837,1,1,0),
(3463558,0,503838,1,1,0),
(3463559,0,503839,1,1,0),
(3463560,0,503840,1,1,0),
(3463561,0,503841,1,1,0),
(3463562,0,503842,1,1,0),
(3463563,0,503843,1,1,0),
(3463564,0,503844,1,1,0),
(3463565,0,503845,1,1,0),
(3463567,0,503847,1,1,0),
(3463568,0,503848,1,1,0),
(3463569,0,503849,1,1,0),
(3463571,0,503851,1,1,0),
(3463572,0,503852,1,1,0),
(3463573,0,503853,1,1,0);

-- 4) item_template ('Reins of ...', spellid_2 trigger 6 = learn)
DELETE FROM `item_template` WHERE `entry` BETWEEN 302680 AND 302713;
INSERT INTO `item_template` (`entry`,`class`,`subclass`,`SoundOverrideSubclass`,`name`,`displayid`,`Quality`,`Flags`,`FlagsExtra`,`BuyCount`,`BuyPrice`,`SellPrice`,`InventoryType`,`Material`,`AllowableClass`,`AllowableRace`,`ItemLevel`,`RequiredLevel`,`maxcount`,`stackable`,`ContainerSlots`,`spellid_1`,`spelltrigger_1`,`spellcharges_1`,`spellppmRate_1`,`spellcooldown_1`,`spellcategory_1`,`spellcategorycooldown_1`,`spellid_2`,`spelltrigger_2`,`spellcharges_2`,`spellppmRate_2`,`spellcooldown_2`,`spellcategory_2`,`spellcategorycooldown_2`,`bonding`,`description`,`RequiredDisenchantSkill`,`duration`,`ScriptName`,`DisenchantID`,`FoodType`,`minMoneyLoot`,`maxMoneyLoot`,`flagsCustom`,`VerifiedBuild`)
VALUES
(302680,15,5,-1,'Reins of the Autumnal Witchwick''s Rider',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303000,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302681,15,5,-1,'Reins of the Blushing Witchwick''s Rider',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303001,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302682,15,5,-1,'Reins of the Carmine Witchwick''s Rider',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303002,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302683,15,5,-1,'Reins of the Moonlit Witchwick''s Rider',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303003,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302684,15,5,-1,'Reins of the Mossy Witchwick''s Rider',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303004,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302685,15,5,-1,'Reins of the Scarlet Witchwick''s Rider',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303005,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302686,15,5,-1,'Reins of the Wintry Witchwick''s Rider',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303006,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302687,15,5,-1,'Reins of the Crested Aqua Leafmimic',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303007,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302688,15,5,-1,'Reins of the Crested Ember Leafmimic',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303008,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302689,15,5,-1,'Reins of the Crested Verdant Leafmimic',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303009,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302690,15,5,-1,'Reins of the Crested Violet Leafmimic',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303010,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302691,15,5,-1,'Reins of the Auriferous Venomfang',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303011,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302692,15,5,-1,'Reins of the Caustic Venomfang',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303012,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302693,15,5,-1,'Reins of the Crimson Venomfang',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303013,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302694,15,5,-1,'Reins of the Sea-Dwelling Isle Serpent',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303014,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302695,15,5,-1,'Reins of the Indigo Coiled Horror',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303015,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302696,15,5,-1,'Reins of the Ruby Writhe',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303016,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302697,15,5,-1,'Reins of the The Writhing Brood',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303017,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302698,15,5,-1,'Reins of the Venomous Coiler',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303018,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302699,15,5,-1,'Reins of the Emerald Skyfang',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303019,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302700,15,5,-1,'Reins of the Topaz Skyfang',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303020,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302701,15,5,-1,'Reins of the Violet-Backed Skyfang',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303021,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302702,15,5,-1,'Reins of the Vicious Lightbloom Boar',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303022,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302703,15,5,-1,'Reins of the Vicious Lightbloom Boar',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303023,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302704,15,5,-1,'Reins of the Breath of Blight',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303024,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302705,15,5,-1,'Reins of the Breath of Ruin',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303025,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302707,15,5,-1,'Reins of the Umbral Ashes',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303027,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302708,15,5,-1,'Reins of the Primeval Skyfriend',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303028,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302709,15,5,-1,'Reins of the Spirit of Tok''jara',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303029,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302711,15,5,-1,'Reins of the Whoofle Bramblewing',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303031,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302712,15,5,-1,'Reins of the Corroded Soul Crusher',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303032,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0),
(302713,15,5,-1,'Reins of the Apophic Soul Crusher',68743,4,0,0,1,0,0,0,4,-1,-1,40,1,1,1,0,55884,0,-1,0,-1,330,3000,303033,6,0,0,-1,0,-1,0,'Teaches you how to summon this mount.',-1,0,'',0,0,0,0,0,0);

-- 5) npc_vendor (Skeletal Stablemaster)
DELETE FROM `npc_vendor` WHERE `entry`=3461020 AND `item` BETWEEN 302680 AND 302713;
DELETE FROM `npc_vendor` WHERE `entry`=3461020 AND `slot` BETWEEN 1240 AND 1273;
INSERT INTO `npc_vendor` (`entry`,`slot`,`item`,`maxcount`,`incrtime`,`ExtendedCost`,`VerifiedBuild`)
VALUES
(3461020,1240,302680,0,0,0,0),
(3461020,1241,302681,0,0,0,0),
(3461020,1242,302682,0,0,0,0),
(3461020,1243,302683,0,0,0,0),
(3461020,1244,302684,0,0,0,0),
(3461020,1245,302685,0,0,0,0),
(3461020,1246,302686,0,0,0,0),
(3461020,1247,302687,0,0,0,0),
(3461020,1248,302688,0,0,0,0),
(3461020,1249,302689,0,0,0,0),
(3461020,1250,302690,0,0,0,0),
(3461020,1251,302691,0,0,0,0),
(3461020,1252,302692,0,0,0,0),
(3461020,1253,302693,0,0,0,0),
(3461020,1254,302694,0,0,0,0),
(3461020,1255,302695,0,0,0,0),
(3461020,1256,302696,0,0,0,0),
(3461020,1257,302697,0,0,0,0),
(3461020,1258,302698,0,0,0,0),
(3461020,1259,302699,0,0,0,0),
(3461020,1260,302700,0,0,0,0),
(3461020,1261,302701,0,0,0,0),
(3461020,1262,302702,0,0,0,0),
(3461020,1263,302703,0,0,0,0),
(3461020,1264,302704,0,0,0,0),
(3461020,1265,302705,0,0,0,0),
(3461020,1267,302707,0,0,0,0),
(3461020,1268,302708,0,0,0,0),
(3461020,1269,302709,0,0,0,0),
(3461020,1271,302711,0,0,0,0),
(3461020,1272,302712,0,0,0,0),
(3461020,1273,302713,0,0,0,0);

-- 6) conditions cleanup
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=23 AND `SourceGroup`=3461020 AND `SourceEntry` BETWEEN 302680 AND 302713 AND `ConditionTypeOrReference`=25;

-- 7) dc_mount_definitions (fly=type3/speed310, ground=type0/speed100)
DELETE FROM `dc_mount_definitions` WHERE `spell_id` BETWEEN 303000 AND 303033;
INSERT INTO `dc_mount_definitions` (`spell_id`,`name`,`mount_type`,`source`,`faction`,`rarity`,`speed`,`display_id`)
VALUES
(303000,'Autumnal Witchwick''s Rider',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503820),
(303001,'Blushing Witchwick''s Rider',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503821),
(303002,'Carmine Witchwick''s Rider',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503822),
(303003,'Moonlit Witchwick''s Rider',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503823),
(303004,'Mossy Witchwick''s Rider',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503824),
(303005,'Scarlet Witchwick''s Rider',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503825),
(303006,'Wintry Witchwick''s Rider',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503826),
(303007,'Crested Aqua Leafmimic',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503827),
(303008,'Crested Ember Leafmimic',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503828),
(303009,'Crested Verdant Leafmimic',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503829),
(303010,'Crested Violet Leafmimic',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503830),
(303011,'Auriferous Venomfang',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503831),
(303012,'Caustic Venomfang',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503832),
(303013,'Crimson Venomfang',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503833),
(303014,'Sea-Dwelling Isle Serpent',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503834),
(303015,'Indigo Coiled Horror',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503835),
(303016,'Ruby Writhe',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503836),
(303017,'The Writhing Brood',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503837),
(303018,'Venomous Coiler',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503838),
(303019,'Emerald Skyfang',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503839),
(303020,'Topaz Skyfang',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503840),
(303021,'Violet-Backed Skyfang',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503841),
(303022,'Vicious Lightbloom Boar',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503842),
(303023,'Vicious Lightbloom Boar',0,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,100,503843),
(303024,'Breath of Blight',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503844),
(303025,'Breath of Ruin',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503845),
(303027,'Umbral Ashes',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503847),
(303028,'Primeval Skyfriend',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503848),
(303029,'Spirit of Tok''jara',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503849),
(303031,'Whoofle Bramblewing',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503851),
(303032,'Corroded Soul Crusher',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503852),
(303033,'Apophic Soul Crusher',3,'{"type":"vendor","npc":"Skeletal Stablemaster","npcEntry":3461020}',0,4,310,503853)
ON DUPLICATE KEY UPDATE `name`=VALUES(`name`),`mount_type`=VALUES(`mount_type`),`source`=VALUES(`source`),`faction`=VALUES(`faction`),`rarity`=VALUES(`rarity`),`speed`=VALUES(`speed`),`display_id`=VALUES(`display_id`);

-- 8) dc_collection_definitions (collection_type 1 = MOUNT)
DELETE FROM `dc_collection_definitions` WHERE `collection_type`=1 AND `entry_id` BETWEEN 303000 AND 303033;
INSERT INTO `dc_collection_definitions` (`collection_type`,`entry_id`,`enabled`)
VALUES
(1,303000,1),
(1,303001,1),
(1,303002,1),
(1,303003,1),
(1,303004,1),
(1,303005,1),
(1,303006,1),
(1,303007,1),
(1,303008,1),
(1,303009,1),
(1,303010,1),
(1,303011,1),
(1,303012,1),
(1,303013,1),
(1,303014,1),
(1,303015,1),
(1,303016,1),
(1,303017,1),
(1,303018,1),
(1,303019,1),
(1,303020,1),
(1,303021,1),
(1,303022,1),
(1,303023,1),
(1,303024,1),
(1,303025,1),
(1,303027,1),
(1,303028,1),
(1,303029,1),
(1,303031,1),
(1,303032,1),
(1,303033,1);
