-- Creature model retroport — Hyjal (map 750) + Plaguelands (map 751) display-id gap
-- Generated by tools/downport-creature.js (--ids-file, 62 missing display ids from the
-- worldserver "lists non-existing CreatureDisplayID" / "creature_model_info has model for
-- not existed display id" log spam). Source: retail build 12.0.7.68275 CreatureModelData.db2
-- (live decode) + a pre-encryption CreatureDisplayInfo export (CreatureDisplayInfo.db2 is
-- fully encrypted on this build; community TACT key not yet public as of 2026-07-02).
--
-- These are the ORIGINAL Cata/retail display ids already referenced by the existing Hyjal/
-- Plaguelands creature_template_model rows (Twilight Slave/Slavedriver, Orb of Ascension,
-- Molten Behemoth, Windcaller, Pyrelord, Sentinel, Igniter, Turtle Punter, Ragepyre/
-- Blazefury/Flashfire/Hatespark/Heatflayer/Singeslayer, Fire Hawk, etc., plus incidental
-- overlap with a few unrelated raw-import entries like Rom'ogg Bonecrusher that happen to
-- share display ids) -- NO creature_template_model remapping needed; the tool keeps retail
-- display ids as-is, only the underlying model (CreatureModelData) gets a new DC id.
--
-- New DC model ids allocated: 501600-501630 (31 unique models; already appended to
-- Custom/CSV DBC/CreatureModelData.csv + CreatureDisplayInfo.csv).
--
-- Unresolved (2 of 62, not blockers): 29680 (orphaned creature_model_info row, nothing
-- currently references it) and 501315 (belongs to an unrelated custom entry 3500078
-- "Hobart Grapplehammer" on a different "+3,500,000" scheme, out of scope here).
--
-- Extracted model assets (11,292 files, K:/Dark-Chaos/retailextracts/creature_hyjal_plague/)
-- still need: pack the 28 folders in extract_manifest.txt into the client patch MPQ at their
-- listed paths, then recompile+redeploy DBCs (client patch + worldserver data/dbc/).
-- Idempotent (INSERT IGNORE). Run on the world-DB host.

INSERT IGNORE INTO `creature_model_info`
(`DisplayID`,`BoundingRadius`,`CombatReach`,`Gender`,`DisplayID_Other_Gender`,`VerifiedBuild`)
VALUES
(31454,0.6111,2.0313,2,0,0),
(31455,0.6111,2.0313,2,0,0),
(31470,0.6111,2.0313,2,0,0),
(31488,0.6111,2.0313,2,0,0),
(31520,0.6111,2.0313,2,0,0),
(31579,0.6229,1.1455,2,0,0),
(31808,0.6111,2.0313,2,0,0),
(31966,0.6111,2.0313,2,0,0),
(32222,0.6111,2.0313,2,0,0),
(32223,0.6111,2.0313,2,0,0),
(32477,0.6111,2.0313,2,0,0),
(33147,0.6111,2.0313,2,0,0),
(33314,0.6111,2.0313,2,0,0),
(33315,0.6111,2.0313,2,0,0),
(33907,0.6111,2.0313,2,0,0),
(33908,0.6111,2.0313,2,0,0),
(34195,0.6111,2.0313,2,0,0),
(34196,0.6111,2.0313,2,0,0),
(34197,0.6111,2.0313,2,0,0),
(34198,0.6111,2.0313,2,0,0),
(34231,0.6111,2.0313,2,0,0),
(34232,0.6111,2.0313,2,0,0),
(34233,0.6111,2.0313,2,0,0),
(34234,0.6111,2.0313,2,0,0),
(34235,0.6111,2.0313,2,0,0),
(34236,0.6111,2.0313,2,0,0),
(34237,0.6111,2.0313,2,0,0),
(34238,0.6111,2.0313,2,0,0),
(34239,0.6111,2.0313,2,0,0),
(34571,0.6111,2.0313,2,0,0),
(34643,0.6111,2.0313,2,0,0),
(34644,0.6111,1.6066,2,0,0),
(34871,0.6111,2.0313,2,0,0),
(34872,0.6111,2.0313,2,0,0),
(34873,0.6111,2.0313,2,0,0),
(34874,0.6111,2.0313,2,0,0),
(34875,0.6111,2.0313,2,0,0),
(36419,0.6111,2.0313,2,0,0),
(36703,0.6111,2.0313,2,0,0),
(37866,0.6111,2.0313,2,0,0),
(38030,0.6111,2.0313,2,0,0),
(38064,0.6111,2.0313,2,0,0),
(38069,0.5000,2.0000,2,0,0),
(38070,0.5000,2.0000,2,0,0),
(38083,0.6111,2.0313,2,0,0),
(38088,0.6111,2.0313,2,0,0),
(38148,0.6111,2.0313,2,0,0),
(38256,0.6111,2.0313,2,0,0),
(38265,0.6111,2.0313,2,0,0),
(38379,0.6111,2.0313,2,0,0),
(38591,0.6111,2.0313,2,0,0),
(38670,0.6111,2.0313,2,0,0),
(38706,0.6111,2.0313,2,0,0),
(38709,0.6111,2.0313,2,0,0),
(38710,0.6111,2.0313,2,0,0),
(38711,0.6111,2.0313,2,0,0),
(38712,0.6111,2.0313,2,0,0),
(38761,0.6111,2.0313,2,0,0),
(38850,0.6111,2.0313,2,0,0),
(38851,0.6111,2.0313,2,0,0);
