--
-- Legion Dalaran (map 1413) import: translate ruRU creature_text back to English.
--
-- The Legion Dalaran source DB was a Russian-locale one, so 260 of the 458
-- creature_text rows tagged 'Legion Dalaran 1413' shipped as Cyrillic.
-- Contamination is confined to creature_text. Verified clean: npc_text,
-- gossip_menu_option, the sniffed bcast table, quest_template, quest_offer_reward,
-- quest_request_items, page_text, and the creature/gameobject/item _template tables.
--
-- Notes:
--  * Entries 28701 (Timothy Jones) and 29513 (Didi the Wrench) are stock WotLK
--    Dalaran trainers. The import ADDED text groups to them; nothing stock was
--    overwritten, so these are translated rather than restored.
--  * ruRU declension tokens |3-N($c) are replaced with plain $c -- the enUS
--    client has no declension table and renders them literally.
--  * $g<male>:<female>; tokens are kept only where English actually differs;
--    elsewhere the sentence is rewritten so the token is unnecessary.
--  * These are custom entry IDs with no upstream English source, so wording is
--    faithful but not string-identical to Blizzard's originals.
--

UPDATE `creature_text` SET `Text`='Ladies, ladies, calm down. I believe this is the jewelcrafter $n has been working with.' WHERE `CreatureID`=28701 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Of course. They are right there on the table. So far I have no complaints about them!' WHERE `CreatureID`=29513 AND `GroupID`=8 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The explosives are planted! Move to a safe distance and detonate them!' WHERE `CreatureID`=3500029 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Click a nearby grapple point to leap onto the wall. Grapple points within range are highlighted.' WHERE `CreatureID`=3500031 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='$n has caught a huge fearsome crab!' WHERE `CreatureID`=3500033 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='$n has caught a Krasarang forebear!' WHERE `CreatureID`=3500033 AND `GroupID`=0 AND `ID`=1;
UPDATE `creature_text` SET `Text`='$n has caught an ancient crimson-headed crane!' WHERE `CreatureID`=3500033 AND `GroupID`=0 AND `ID`=2;
UPDATE `creature_text` SET `Text`='Ku-Yao\'s bedroll is empty. He is not here.' WHERE `CreatureID`=3500033 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The shield is engraved "Sentinel Ku-Yao". The shield belongs to the boy\'s father.' WHERE `CreatureID`=3500033 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='There you are, $n. Come, Azsuna awaits.' WHERE `CreatureID`=3500043 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Let me know when you are ready to depart, $n.' WHERE `CreatureID`=3500043 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='$n, over here.' WHERE `CreatureID`=3500044 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I have just the thing. Follow me.' WHERE `CreatureID`=3500045 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Give me a second. I am a bit of a pack rat, you know...' WHERE `CreatureID`=3500045 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Let us see now... apexis crystals? No, those will not do at all.' WHERE `CreatureID`=3500045 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I must have stuffed it in there.' WHERE `CreatureID`=3500045 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Enchanting dust... soul shards... no, not that...' WHERE `CreatureID`=3500045 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Aha! There it is! A soul crystal. That will do.' WHERE `CreatureID`=3500045 AND `GroupID`=5 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Take it? These crystals tend to reject beings of a non-demonic nature.' WHERE `CreatureID`=3500045 AND `GroupID`=6 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Do not touch it! Wait for our guest.' WHERE `CreatureID`=3500045 AND `GroupID`=9 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Disturbing that thing will start the process. Er... give it a poke, I suppose.' WHERE `CreatureID`=3500045 AND `GroupID`=10 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Be careful. Suramar has lain desolate for ten thousand years.' WHERE `CreatureID`=3500045 AND `GroupID`=11 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Head to the Broken Shore, Karam is waiting for you there! He is scouting the area around the Tomb right now.' WHERE `CreatureID`=3500048 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Shaman! I have an urgent message.' WHERE `CreatureID`=3500053 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='$n! I have an urgent message.' WHERE `CreatureID`=3500053 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Yes, I have a few spare dummies, but I am not ready to part with them just yet. Unless...' WHERE `CreatureID`=3500057 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Care to run a small errand for me? Do it, and the dummies are yours.' WHERE `CreatureID`=3500057 AND `GroupID`=1 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Well, Shandy did good... she knows how to get blood out of clothes! Here, take your dummies - just as promised.' WHERE `CreatureID`=3500057 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Greetings, $c.' WHERE `CreatureID`=3500061 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I hope the rare ore in our vault will please you more.' WHERE `CreatureID`=3500069 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Greetings.' WHERE `CreatureID`=3500072 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Easy as can be...' WHERE `CreatureID`=3500072 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Done! And tell Tanithria she owes me another silk cushion.' WHERE `CreatureID`=3500072 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I think we should start with Catriona MacRae. She was my last client.' WHERE `CreatureID`=3500072 AND `GroupID`=6 AND `ID`=0;
UPDATE `creature_text` SET `Text`='WHAT IS THAT THING?!' WHERE `CreatureID`=3500072 AND `GroupID`=11 AND `ID`=0;
UPDATE `creature_text` SET `Text`='He was hiding on the shelf. Is he not a darling?' WHERE `CreatureID`=3500076 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Greetings, $c.' WHERE `CreatureID`=3500078 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Greetings! Please, take a look at my wares.' WHERE `CreatureID`=3500078 AND `GroupID`=3 AND `ID`=2;
UPDATE `creature_text` SET `Text`='OH! Now that is a giant!' WHERE `CreatureID`=3500079 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Greetings, $c.' WHERE `CreatureID`=3500080 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Greetings.' WHERE `CreatureID`=3500080 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Uh... I was just... looking at new dyes for cloth. Yes, yes. New dyes. I will return to the shop at once.' WHERE `CreatureID`=3500086 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='You will not regret this. I will kill any demon or servant of the Legion that stands in my way!' WHERE `CreatureID`=3500087 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='An excellent choice. Now let me fill you in on the details of our plan.' WHERE `CreatureID`=3500088 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Looking for something in particular?' WHERE `CreatureID`=3500093 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='That is $p. They say $ghe:she; brought down Deathwing with blades alone!' WHERE `CreatureID`=3500093 AND `GroupID`=3 AND `ID`=2;
UPDATE `creature_text` SET `Text`='We need only a brief word with the eredar... in private. He has the information we need.' WHERE `CreatureID`=3500095 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='That is it, lad! If you see your mother, tell her I am almost out of lockpicks, will you?' WHERE `CreatureID`=3500096 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Ah, good. I will be right down. On my way!' WHERE `CreatureID`=3500097 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Hey! Who was looking for me?' WHERE `CreatureID`=3500097 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I wonder where they all went... Oh well. Maybe they will come back.' WHERE `CreatureID`=3500097 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='My stone? Sure, no problem. It is on the side table.' WHERE `CreatureID`=3500097 AND `GroupID`=5 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Well, if you have no time, then I will not waste mine on you.' WHERE `CreatureID`=3500099 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='You are lucky Khadgar trusts you. Mind you, I do not share his enthusiasm in the slightest.' WHERE `CreatureID`=3500099 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Greetings! Please, take a look at my wares.' WHERE `CreatureID`=3500101 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Greetings.' WHERE `CreatureID`=3500101 AND `GroupID`=0 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Oh, how lovely! A box of new toys!' WHERE `CreatureID`=3500102 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The highlands have fallen. The forces of the clan are scattered.' WHERE `CreatureID`=3500105 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='They have tracked us down!' WHERE `CreatureID`=3500105 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Follow me, $n. The Skyfire is ready to depart.' WHERE `CreatureID`=3500112 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The Aegis of Aggramar, one of the Pillars of Creation, lies in Stormheim.' WHERE `CreatureID`=3500112 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Legend says only one who can pass a certain trial may claim it.' WHERE `CreatureID`=3500112 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Impressive, is it not? The new guns can drop a wyvern at three hundred yards at full speed. Take a look.' WHERE `CreatureID`=3500112 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='We have orders to carry you to Stormheim and aid you through the trial.' WHERE `CreatureID`=3500112 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='We have also been given another task...' WHERE `CreatureID`=3500112 AND `GroupID`=5 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The 7th Legion. The toughest soldiers in the Alliance. They too act on the king\'s personal orders.' WHERE `CreatureID`=3500112 AND `GroupID`=6 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Three days ago a Forsaken fleet left Durotar for the Broken Isles. We believe Sylvanas herself leads it.' WHERE `CreatureID`=3500112 AND `GroupID`=7 AND `ID`=0;
UPDATE `creature_text` SET `Text`='We are to shadow that fleet while avoiding any direct engagement.' WHERE `CreatureID`=3500112 AND `GroupID`=8 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Though if you ask me, that is unavoidable.' WHERE `CreatureID`=3500112 AND `GroupID`=9 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Preparations are nearly complete. Make yourselves comfortable.' WHERE `CreatureID`=3500112 AND `GroupID`=10 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Time to move out. The Dark Lady\'s fleet is nearly ready to set sail.' WHERE `CreatureID`=3500113 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Greetings! Please, take a look at my wares.' WHERE `CreatureID`=3500120 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Greetings, $c.' WHERE `CreatureID`=3500120 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='And here comes $n... would you look at those shades!' WHERE `CreatureID`=3500125 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Careful, $n, watch your step! Any news from the Council?' WHERE `CreatureID`=3500126 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='What is going on in there? The noise keeps getting louder. I hope we learn something soon.' WHERE `CreatureID`=3500126 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='How are things, $n? Visitors come and go, but nobody really knows anything.' WHERE `CreatureID`=3500126 AND `GroupID`=3 AND `ID`=2;
UPDATE `creature_text` SET `Text`='Looking good, $n!' WHERE `CreatureID`=3500144 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Bah, $n! Showing off those fancy shades again?! Wonderful!' WHERE `CreatureID`=3500144 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='And here comes $n... would you look at those shades!' WHERE `CreatureID`=3500144 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Do you know if $n is seeing anyone? Do I have a chance?' WHERE `CreatureID`=3500144 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='My finest hippogryph will be perfect for this task.' WHERE `CreatureID`=3500151 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='And what difference does that make? The vault holds our most precious relics! Losing any one of them is a catastrophe!' WHERE `CreatureID`=3500152 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='We do not even know whether the danger has passed, and you ask about the vault?! Only members of the Council of Six are admitted there!' WHERE `CreatureID`=3500153 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I fear we will not know for some time yet. The inner chambers are still engulfed in fel flame!' WHERE `CreatureID`=3500154 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='And here comes $n... would you look at those shades!' WHERE `CreatureID`=3500169 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Yes, of course, I can wash that dress. But I charge 2 gold for the work.' WHERE `CreatureID`=3500195 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Splendid. I will have every stain out of it in no time!' WHERE `CreatureID`=3500195 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Go on, Aquan. You are up.' WHERE `CreatureID`=3500195 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Here is your dress. Look - not a spot on it; good as new! Thank you for your help.' WHERE `CreatureID`=3500195 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='You think anyone hands things out for free? Sorry, sweetheart, but it is a favor for a favor.' WHERE `CreatureID`=3500207 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I will trade you the scrap for a few new armor dummies. Imindril Spearsong at "Tanks for Everything" should have a couple.' WHERE `CreatureID`=3500207 AND `GroupID`=1 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Bring them to me and the scrap is yours.' WHERE `CreatureID`=3500207 AND `GroupID`=1 AND `ID`=2;
UPDATE `creature_text` SET `Text`='You certainly took your time! Stopped for a drink on the way back, did you? Fine, here is your scrap, just as we agreed.' WHERE `CreatureID`=3500207 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Your order is in the secret room, $gsir:madam;.' WHERE `CreatureID`=3500214 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Yes, of course. They are right there on the table. Why, is something wrong with them?' WHERE `CreatureID`=3500215 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Do you know if $n is seeing anyone? Do I have a chance?' WHERE `CreatureID`=3500217 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='You look great, $n! Just great!' WHERE `CreatureID`=3500220 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Greetings! Please, take a look at my wares.' WHERE `CreatureID`=3500226 AND `GroupID`=0 AND `ID`=2;
UPDATE `creature_text` SET `Text`='Greetings, $c.' WHERE `CreatureID`=3500226 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Come, $ghero:heroine;. I will show you the true strength of Highmountain.' WHERE `CreatureID`=3500236 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Yes, I have what you need. But I am not giving it away for nothing. A trade, now - that is another matter.' WHERE `CreatureID`=3500247 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='There is a pretty red stone up above that caught my eye. Fetch it for me and I will trade you your core for it.' WHERE `CreatureID`=3500247 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Pleasure doing business with you, friend.' WHERE `CreatureID`=3500247 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='And what if I strike it right here...' WHERE `CreatureID`=3500250 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='You will not regret this. I will kill any demon or servant of the Legion that stands in my way!' WHERE `CreatureID`=3500250 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='He spoke well enough, and the skin... looked normal enough. But I found him out all the same.' WHERE `CreatureID`=3500250 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='So the dreadlords have learned to make undead indistinguishable from the living! Even I cannot spot them at a glance!' WHERE `CreatureID`=3500250 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The demons realized they cannot hide from the Illidari in our cities, so this time they sent these... homunculi.' WHERE `CreatureID`=3500250 AND `GroupID`=5 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Our agents have identified these creatures in the Exodar and in Silvermoon.' WHERE `CreatureID`=3500250 AND `GroupID`=6 AND `ID`=0;
UPDATE `creature_text` SET `Text`='A killing in an allied city is too great a risk, but if you cut down a homunculus in the Exodar, no questions will be asked. We will handle the targets in Silvermoon.' WHERE `CreatureID`=3500250 AND `GroupID`=7 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Remember... even though you mean to help, the Alliance will still see it as an attack on one of their own.' WHERE `CreatureID`=3500250 AND `GroupID`=8 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Remember... even though you mean to help, the Horde will still see it as an attack on one of their own.' WHERE `CreatureID`=3500250 AND `GroupID`=9 AND `ID`=0;
UPDATE `creature_text` SET `Text`='A killing in an allied city is too great a risk, but if you cut down a homunculus in Silvermoon, no questions will be asked. We will handle the targets in the Exodar.' WHERE `CreatureID`=3500250 AND `GroupID`=10 AND `ID`=0;
UPDATE `creature_text` SET `Text`='We will meet at the fortress.' WHERE `CreatureID`=3500262 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='$p, Darkness Despair and Ravencrest will escort you to Suramar. A small group has a better chance of slipping into the fortress unseen.' WHERE `CreatureID`=3500262 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Allari led a party in search of the lost warglaives. Perhaps we have finally found them.' WHERE `CreatureID`=3500263 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Eternal suffering. No mercy for Caria.' WHERE `CreatureID`=3500263 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='We will meet at the fortress.' WHERE `CreatureID`=3500263 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Altruis, any ideas.' WHERE `CreatureID`=3500265 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='OH! That is MUCH better.' WHERE `CreatureID`=3500281 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='So this is Dalaran? Jabrul is impressed. The jewelcrafters are this way?' WHERE `CreatureID`=3500281 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='For many long years the draenei hid from the Burning Legion. All that time the naaru aided us greatly; sometimes even at the cost of their own lives. Without their help we would surely have perished.' WHERE `CreatureID`=3500287 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The mages have opened a portal for us. Come. I wish to tell you something of the naaru and the draenei.' WHERE `CreatureID`=3500287 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Then we have a deal. Congratulations, $p. VanCleef is one of our best - as you have already seen for yourself.' WHERE `CreatureID`=3500293 AND `GroupID`=6 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Your father would be very disappointed in you, Vanessa.' WHERE `CreatureID`=3500293 AND `GroupID`=7 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Right, let us start with a lengthwise fillet...' WHERE `CreatureID`=3500295 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Now that is interesting! Deboning after curing wastes less meat...' WHERE `CreatureID`=3500295 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='It would probably be even better with a beer...' WHERE `CreatureID`=3500295 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Excellent! I have a new recipe for you, $p.' WHERE `CreatureID`=3500295 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Your order will be ready in 5 minutes.' WHERE `CreatureID`=3500295 AND `GroupID`=30 AND `ID`=0;
UPDATE `creature_text` SET `Text`='So it is settled. By the way, speak with Velen. He has... a most unusual matter for you.' WHERE `CreatureID`=3500301 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='You have returned with the artifact! Well done, $n!' WHERE `CreatureID`=3500303 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Nothing personal. Just business.' WHERE `CreatureID`=3500304 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I believe I will take you up on your generous offer.' WHERE `CreatureID`=3500304 AND `GroupID`=8 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Alas, Orest has fallen. Word must be sent to Haldaron. Come, Swiftspur.' WHERE `CreatureID`=3500306 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Yes, quite. Thank you very much!' WHERE `CreatureID`=3500308 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='There we are, $n. We have spent weeks on research, and I believe we have uncovered everything there is to know about the history of your weapon.' WHERE `CreatureID`=3500317 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='This research is quite fascinating! I am writing the translated history into the book right now.' WHERE `CreatureID`=3500317 AND `GroupID`=0 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Thank you for such a substantial contribution to our research. I hope our findings have proven useful.' WHERE `CreatureID`=3500317 AND `GroupID`=0 AND `ID`=2;
UPDATE `creature_text` SET `Text`='Your weapon has revealed a most interesting past. It has been added to the book - take a look if you wish.' WHERE `CreatureID`=3500317 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The final chapter of our book is complete. You should definitely read it.' WHERE `CreatureID`=3500317 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Your weapon turns out to have quite a rich past. New translations have been added to the book, you may take a look.' WHERE `CreatureID`=3500317 AND `GroupID`=3 AND `ID`=2;
UPDATE `creature_text` SET `Text`='New facts about the history of your weapon have been added to the book. You should take a look when you have time.' WHERE `CreatureID`=3500317 AND `GroupID`=3 AND `ID`=3;
UPDATE `creature_text` SET `Text`='Time is short. This portal will take us straight to the Violet Citadel.' WHERE `CreatureID`=3500318 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='When you have obtained the artifact, $n, return here. I will try to set things in order in the meantime.' WHERE `CreatureID`=3500318 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Well then, Akazamzarak, you have all the coordinates. Can you set up the portals?' WHERE `CreatureID`=3500318 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Mages of Azeroth! I have gathered you here in the face of a threat to our entire world!' WHERE `CreatureID`=3500318 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The dreadlord Kathra\'natir has fled into the Twisting Nether, taking the secrets of the Council of Tirisfal with him.' WHERE `CreatureID`=3500318 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='We must follow him into the Twisting Nether and find him there. Only then can we be certain he cannot use that knowledge against us.' WHERE `CreatureID`=3500318 AND `GroupID`=5 AND `ID`=0;
UPDATE `creature_text` SET `Text`='To that end I am reforming the order of the Tirisgarde. And I call upon you to join us and take up arms against the Legion! Are you with us?!' WHERE `CreatureID`=3500318 AND `GroupID`=6 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Then it is decided.' WHERE `CreatureID`=3500318 AND `GroupID`=7 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Excellent. In the presence of the greatest mages of Azeroth, I name you $n, Magus of the Tirisgarde.' WHERE `CreatureID`=3500318 AND `GroupID`=8 AND `ID`=0;
UPDATE `creature_text` SET `Text`='This ancient title was once borne by the eldest of Azeroth\'s mages, and it symbolizes the great responsibility placed upon the Tirisgarde. Wear it with pride and honor.' WHERE `CreatureID`=3500318 AND `GroupID`=9 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Now go to the War Room and meet our new goblin ally. You may begin planning your next steps at once.' WHERE `CreatureID`=3500318 AND `GroupID`=10 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I must step away on a personal matter...' WHERE `CreatureID`=3500318 AND `GroupID`=11 AND `ID`=0;
UPDATE `creature_text` SET `Text`='You will like this, $p. Catch up!' WHERE `CreatureID`=3500319 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Are you coming, $p?' WHERE `CreatureID`=3500319 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Ladies and gentlemen, do not deny yourselves the pleasure of witnessing true feats of sleight of hand!' WHERE `CreatureID`=3500320 AND `GroupID`=10 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Thank you, thank you very much. I am most grateful for your donations.' WHERE `CreatureID`=3500320 AND `GroupID`=11 AND `ID`=0;
UPDATE `creature_text` SET `Text`='And... presto!' WHERE `CreatureID`=3500320 AND `GroupID`=12 AND `ID`=0;
UPDATE `creature_text` SET `Text`='And... Whoa, whoa, whoa!' WHERE `CreatureID`=3500320 AND `GroupID`=12 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Now, for my next trick I will need an assistant. Who would like to volunteer?' WHERE `CreatureID`=3500320 AND `GroupID`=13 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Pick a card. Any card.' WHERE `CreatureID`=3500320 AND `GroupID`=14 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Hey! Not that one! Give it back!' WHERE `CreatureID`=3500320 AND `GroupID`=15 AND `ID`=0;
UPDATE `creature_text` SET `Text`='You will be astounded as I pull a rabbit from an ordinary hat before your very eyes!' WHERE `CreatureID`=3500320 AND `GroupID`=16 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Excellent, $n! You are doing splendidly and seem capable of a great deal more... Come see me if you are interested!' WHERE `CreatureID`=3500339 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Please remain calm and wait your turn. A banker will assist you as soon as possible.' WHERE `CreatureID`=3500340 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Easy! Everyone stay calm! That vrykul will not be here for long!' WHERE `CreatureID`=3500340 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='The Council asks that you remain calm while they assess the situation.' WHERE `CreatureID`=3500340 AND `GroupID`=3 AND `ID`=2;
UPDATE `creature_text` SET `Text`='Someone has broken into the vault!' WHERE `CreatureID`=3500340 AND `GroupID`=3 AND `ID`=4;
UPDATE `creature_text` SET `Text`='We ask for your patience - we will share the details with you soon.' WHERE `CreatureID`=3500340 AND `GroupID`=3 AND `ID`=5;
UPDATE `creature_text` SET `Text`='We must remain calm until the Council completes its investigation.' WHERE `CreatureID`=3500340 AND `GroupID`=3 AND `ID`=6;
UPDATE `creature_text` SET `Text`='The Council and I are working actively to resolve the situation.' WHERE `CreatureID`=3500340 AND `GroupID`=3 AND `ID`=7;
UPDATE `creature_text` SET `Text`='The portal is nearly ready!' WHERE `CreatureID`=3500341 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Voila!' WHERE `CreatureID`=3500341 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='We can fly these hippogryphs to Stormheim and await Vuho\'s signal there!' WHERE `CreatureID`=3500345 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Opening the portal!' WHERE `CreatureID`=3500347 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Greg, I pay you to dance, not to mope about! So come on, shake it!' WHERE `CreatureID`=3500348 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='It is a $gpriest:priestess;, praise the Light!' WHERE `CreatureID`=3500357 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='He is inside. Please, do everything you can to save him.' WHERE `CreatureID`=3500357 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Barrem!' WHERE `CreatureID`=3500357 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Meet me at Krasus\' Landing and we will fly to the island on my gryphon.' WHERE `CreatureID`=3500357 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Let us fly, $n. Lightwing is saddled and ready.' WHERE `CreatureID`=3500363 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Let us fly, $n. Lightwing is saddled and ready to depart.' WHERE `CreatureID`=3500363 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Hop on the bird and follow me! To Stormheim!' WHERE `CreatureID`=3500364 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='That went smoothly this time, but it will take longer in the future.' WHERE `CreatureID`=3500376 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Have you got a moment, $n? I have something interesting for you.' WHERE `CreatureID`=3500381 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='An excellent choice. I will see that it is done properly. It is always a pleasure to work with a top-class professional like you, $n.' WHERE `CreatureID`=3500389 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Bah, $n! Showing off those fancy shades again?!' WHERE `CreatureID`=3500395 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='You look great, $n! Just great!' WHERE `CreatureID`=3500402 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Find our surviving brothers and gather them at the Tomb.' WHERE `CreatureID`=3500418 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='So many ages have passed since I last saw the Tidestone whole - and here it is before me.' WHERE `CreatureID`=3500424 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='It is best this stays between us, $c. As they say: loose lips sink ships.' WHERE `CreatureID`=3500426 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='So be it. Turn this great power against the enemies of Tirisfal!' WHERE `CreatureID`=3500429 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Quite a fine home for a mortal. Now let us see what he is hiding here.' WHERE `CreatureID`=3500431 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Until we meet again soon.' WHERE `CreatureID`=3500431 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='When I first saw you, I prayed to the spirits that you could be trusted. And now, thanks to you, our tribes are united once more.' WHERE `CreatureID`=3500437 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='In the name of the tribes of Highmountain, I entrust this hammer to you and your allies. May it crush any foe!' WHERE `CreatureID`=3500437 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='That weapon of yours - it is cursed, $n. Who knows how many sailors it has doomed in my lifetime. Be careful with it.' WHERE `CreatureID`=3500438 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Illidari! That imp has stolen the grimoire! Catch it!' WHERE `CreatureID`=3500439 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Haldaron said that you would come.' WHERE `CreatureID`=3500443 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='It cannot have been easy to obtain such wood and ore.' WHERE `CreatureID`=3500443 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='This material is difficult to work with, but trust me, you will like the result.' WHERE `CreatureID`=3500443 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Your weapon will be sharp and strong. It will pierce any armor and never fail you in battle.' WHERE `CreatureID`=3500443 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I must say, this is my finest creation.' WHERE `CreatureID`=3500443 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='See that it never falls into enemy hands.' WHERE `CreatureID`=3500443 AND `GroupID`=5 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Bah, $n! Showing off those fancy shades again?!' WHERE `CreatureID`=3500445 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I did not sign up for this.' WHERE `CreatureID`=3500453 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Fishing? ...You cannot be serious?!' WHERE `CreatureID`=3500453 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='I see the hunt was a success! Not that I ever doubted it.' WHERE `CreatureID`=3500454 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Your souls are mine!' WHERE `CreatureID`=3500461 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Illidari! The gate is open. All aboard the "Fel Hammer"!' WHERE `CreatureID`=3500461 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Today we celebrate a great victory, paid for with the blood of friends and loved ones.' WHERE `CreatureID`=3500466 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Now we have the Tears of Elune. May they bring us victory over the Burning Legion!' WHERE `CreatureID`=3500466 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Thanks to your courage, the ancient lands of Val\'sharah can heal.' WHERE `CreatureID`=3500466 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='We will meet at the Sanctuary. Safe travels.' WHERE `CreatureID`=3500475 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Now I must attend to my other guests. Good luck, $n!' WHERE `CreatureID`=3500477 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The resources of Dalaran are at your disposal. From this day forward, the chief task of every hero of the Alliance and the Horde is the search for the Pillars of Creation!' WHERE `CreatureID`=3500477 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Eat well if you want to grow big and strong and reach level twenty-five.' WHERE `CreatureID`=3500481 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='You look great, $n! Just great!' WHERE `CreatureID`=3500483 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='We will all follow your example.' WHERE `CreatureID`=3500485 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Perhaps we can still be saved!' WHERE `CreatureID`=3500485 AND `GroupID`=3 AND `ID`=2;
UPDATE `creature_text` SET `Text`='I beg of you, be careful with that staff...' WHERE `CreatureID`=3500485 AND `GroupID`=3 AND `ID`=3;
UPDATE `creature_text` SET `Text`='This portal leads to the Exodar. Good luck to you, $ct.' WHERE `CreatureID`=3500486 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Calm down. She is bound to show up any minute now.' WHERE `CreatureID`=3500487 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The coffee here is so strong!' WHERE `CreatureID`=3500490 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='So when will this Fe\'be deign to show up? She promised to be here an hour ago!' WHERE `CreatureID`=3500490 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='Shh! Keep your voice down...' WHERE `CreatureID`=3500491 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Keep your voice down! Someone is here...' WHERE `CreatureID`=3500491 AND `GroupID`=0 AND `ID`=1;
UPDATE `creature_text` SET `Text`='%s snores deafeningly.' WHERE `CreatureID`=3500495 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='%s snorts.' WHERE `CreatureID`=3500495 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I simply must buy it! The detail work is absolutely exquisite!' WHERE `CreatureID`=3500499 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='It is, without exaggeration, an exquisite creation.' WHERE `CreatureID`=3500499 AND `GroupID`=3 AND `ID`=1;
UPDATE `creature_text` SET `Text`='"I knooow that you work for the Legiooon." That is what you think. That is what your muttering sounds like.' WHERE `CreatureID`=3500509 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Hey! I saw what the demon made off with. Come here, I will tell you everything.' WHERE `CreatureID`=3500512 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='He was so protective of that trinket that he bolted the moment he left the vault' WHERE `CreatureID`=3500512 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='A shame Stormheim is not in sight.' WHERE `CreatureID`=3500521 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Use |TInterface\\Icons\\SPELL_SHADOW_ENSLAVEDEMON.BLP:20|t |cFFFF0000|Hspell:111771|h[Enslave Demon]|h|r to subdue the wrathsteed!' WHERE `CreatureID`=3500528 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='What has she done?! The portal has overloaded and connected to the Void!' WHERE `CreatureID`=3500531 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='All right, I will try to stabilize the portal. I hope you know what you are doing, $c!' WHERE `CreatureID`=3500531 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Wait... something is wrong! I cannot... hold it...' WHERE `CreatureID`=3500531 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Ugh!' WHERE `CreatureID`=3500531 AND `GroupID`=4 AND `ID`=0;
UPDATE `creature_text` SET `Text`='I think the runes worked! The fel energy is fading...' WHERE `CreatureID`=3500531 AND `GroupID`=12 AND `ID`=0;
UPDATE `creature_text` SET `Text`='It is done.' WHERE `CreatureID`=3500531 AND `GroupID`=13 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Fambar has the scent. Follow him into the portal and he will lead you to the missing sorceress.' WHERE `CreatureID`=3500531 AND `GroupID`=14 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The bank? How did they...' WHERE `CreatureID`=3500532 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='The Heart of Kruul... this is bad.' WHERE `CreatureID`=3500532 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Never leave a demon hunter\'s work to mages!' WHERE `CreatureID`=3500532 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Demons may be hiding in the bank. Stay alert.' WHERE `CreatureID`=3500532 AND `GroupID`=3 AND `ID`=0;
UPDATE `creature_text` SET `Text`='It seems fate has seen fit to bring us together again, $c.' WHERE `CreatureID`=3500533 AND `GroupID`=0 AND `ID`=0;
UPDATE `creature_text` SET `Text`='So... Kruul returns.' WHERE `CreatureID`=3500533 AND `GroupID`=1 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Turn your gaze to the Light. I will heal your wounds.' WHERE `CreatureID`=3500533 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Of course, Kathra\'natir\'s prison cannot power the defenses of Dalaran forever. But I am immensely glad that the essence of the demon will remain locked away. It is time to return to the Guardian\'s Sanctum.' WHERE `CreatureID`=3500539 AND `GroupID`=2 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Now, let us see what can be done with this armor.' WHERE `CreatureID`=3500572 AND `GroupID`=5 AND `ID`=0;
UPDATE `creature_text` SET `Text`='First we need to smelt all the ore...' WHERE `CreatureID`=3500572 AND `GroupID`=6 AND `ID`=0;
UPDATE `creature_text` SET `Text`='And now to hammer out the powerstone blank properly... right here... a-a-and here...' WHERE `CreatureID`=3500572 AND `GroupID`=7 AND `ID`=0;
UPDATE `creature_text` SET `Text`='And finally - the centerpiece!' WHERE `CreatureID`=3500572 AND `GroupID`=8 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Done! One of my finest works, if I say so myself! It is all yours.' WHERE `CreatureID`=3500572 AND `GroupID`=9 AND `ID`=0;
UPDATE `creature_text` SET `Text`='Grayson will be pleased with our work. Give him my best regards.' WHERE `CreatureID`=3500572 AND `GroupID`=10 AND `ID`=0;
