-- ---------------------------------------------------------------------------
-- 20  Molten Front -- the 15 timed action lists round 24 never imported
-- ---------------------------------------------------------------------------
-- 16_ brought the CALL_TIMED_ACTIONLIST callers across but not the lists they
-- call. 19 rows have been pointing at action lists that exist in nelt_world and
-- nowhere on our side, so every scene they drive has been silently dead.
--
-- CORRECTION, verified on the live DB 2026-08-06 after 16_ was re-applied: the
-- Leyara finale list 5391200 was NEVER part of this gap. 16_ has always carried
-- it (and documents the 5391200 waypoint dead-end itself, at its own lines 301
-- and 575). It read as missing only because 16_ had not been fully applied when
-- this round's sweep ran. It is excluded here so ownership stays with 16_.
--
-- Note the core logs NOTHING for this class -- a CALL_TIMED_ACTIONLIST pointing
-- at a list that does not exist is not validated at load, it just silently does
-- nothing at runtime. The gap is only visible from the DB:
--
--   SELECT s.entryorguid, s.action_param1 FROM smart_scripts s
--    WHERE s.action_type = 80 AND NOT EXISTS (SELECT 1 FROM smart_scripts a
--      WHERE a.entryorguid = s.action_param1 AND a.source_type = 9);
--
--   3653107 Smothervine          -> 5310700 / 5310701  the spellclick chain
--   3653112 Subterranean Magma Worm -> 5311200 (9)
--   3653234 Anren Shadowseeker   -> 5323400/01/02/03/04 (37 rows, 5 lists)
--   3654025 Elderlimb            -> 5402500 (4)
--   3654070 Tenaron Stormgrip    -> 5407000 (5)
--   3653163 Rope                 -> 5316300 (5)
--   3653354 Escape Winds         -> 5335400 (2)
--   3652705 / 3652990 Captured Hyjal Druid -> 5270500 / 5299000 (9)
--   3649413 Cenarius Event Camera -> 4941300 (1)
--
-- 77 rows in total, all verified present in nelt_world. The list ids are the
-- SOURCE entry x 100, which is this downport's established numbering and is
-- what the already-imported callers name -- so they are inserted unchanged, NOT
-- offset. (3610817 Duggan Wildhammer on map 751 also calls a missing list,
-- 1081700; it is Plaguelands content from a different source and is out of
-- scope here.)
--
-- PARAM SWEEP. The +3,600,000 clone scheme is not applied to action or target
-- params by any generic import, so every one is rewritten explicitly below.
-- This is the same defect family as 116_ (quest objectives), 144_ (TEXT_OVER)
-- and 14_ (KILLED_MONSTER / SUMMON_CREATURE):
--
--   * action 33 KILLED_MONSTER param1 53234 -> 3653234, or Anren's own quest
--     step grants credit for a creature that does not exist.
--   * target_type 19 (closest creature) param1 53366 -> 3653366 Leyara and
--     52669 -> 3652669 Matoclaw. Both clones exist.
--   * action 53 WP_START param2 is a waypoint path id and those stay RAW in
--     this import -- 16_ already imported Malfurion's path 53912 unoffset and
--     it resolves. The four paths these lists need (52990, 53234, 54025 and
--     5323400, 20 points total) were never imported at all; section 4 fixes it.
--   * The eight spells they cast are section 1, which MUST be applied first:
--     SmartAIMgr discards any row whose spell is unknown, so applying the lists
--     without the spells would import them and immediately throw most away.
--     Same ordering constraint 19_ had against 16_.
--
-- KNOWN AND DELIBERATELY NOT "FIXED": list 5391201 row 1 does WP_START on path
-- 5391200, which exists in NEITHER database. Path 5391201 does exist (11
-- points) but it belongs to the 54109/54110 escape run and is correctly
-- referenced by lists 5410900 and 5411001, so repointing Malfurion at it would
-- be wrong, not a fix. Nothing calls list 5391201 in nelt either -- it is dead
-- upstream data whose only effect is one skipped-row line at boot, same class
-- as WaypointPath 16256/17238. Left alone rather than invented.

-- ---- 1. the 8 spells the lists cast (PREREQUISITE -- apply before section 3)
-- 98244/98246/98248/108268/98233/98429/98506 downported from the real Cata
-- 4.3.4 client, 151279 rebuilt from nelt_world.spell_dbc + spelleffect_dbc the
-- way 123_ rebuilt 151099-151276 (it is a Neltharion invention with no client
-- row anywhere). Generated by tools/gen_hyjal_spell_downport_r26.py -- re-run
-- the generator rather than hand-editing.

DELETE FROM `spell_dbc` WHERE `ID` IN (98244,98246,98248,108268,98233,98429,98506,151279);

INSERT INTO `spell_dbc` VALUES
('98244','0','0','0','538968320','136','67108864','0','2048','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','3','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','77','0','0','0','0','0','0','0','0','98243','0','0','0','0','0','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Smothering Grasp','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0'),
('98246','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','9','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','6','0','0','751','0','0','0','0','0','14624','0','0','0','0','0','25','0','0','0','0','0','0','0','0','3','0','0','3000','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Smothering Grasp','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0'),
('98248','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','31','0','0','0','0','0','0','0','0','0','0','0','9','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','1','6','0','0','0','0','0','0','0','0','0','0','0','0','0','96','1','0','0','0','0','0','0','0','0','56','0','0','0','0','0','0','0','0','0','0','0','0','0','0','15214','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Smothering Submerge','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','1','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0'),
('108268','0','0','0','256','268435456','0','262144','128','393224','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','21','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','6','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','4','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Blue Coloring','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0'),
('98233','0','0','0','696254848','1056','273170437','269681152','8388736','393224','4608','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','21','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','6','6','6','0','0','0','0','0','0','0','5','0','0','0','0','1','1','1','0','0','0','0','0','0','56','89','12','0','250','0','0','0','0','0','0','0','0','0','0','3653113','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Head Explode','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','1','1','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0'),
('98429','0','0','0','536871296','268452868','4','268443652','0','134217728','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','28','0','0','0','0','0','181','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','6','6','0','0','0','0','0','0','0','0','0','0','0','0','0','38','1','0','0','0','0','36','0','0','4','4','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','The Furnace: Rope Visual','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','1','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0'),
('98506','0','0','0','696254848','1056','273170437','269681152','8388736','393224','4608','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','7','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','6','0','0','0','0','0','0','0','0','999','0','0','0','0','0','1','0','0','0','0','0','16','0','0','144','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Thermal Jump','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0'),
('151279','0','0','0','696254848','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','-1','0','0','77','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','Neltharion: The Furnace - Rope Script Effect','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','16712190','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','1','0','0','0','0','0','0','0','0');

-- ---- 2. the transform target 98233 "Head Explode" morphs into --------------
-- The aura is TRANSFORM (56) and its EffectMiscValue names creature 53113,
-- which exists on neither side raw or offset -- so without this the worm
-- morphs into nothing, exactly the trap 145_ hit with 97678. r26 remaps the
-- spell to 3653113 and this creates it.
--
-- Two deliberate departures from a verbatim clone:
--   * AIName is forced to '' -- nelt gives 53113 AIName='SmartAI' but has ZERO
--     smart_scripts rows for it, so copying it verbatim would manufacture a
--     fresh "has SmartAI enabled but no SmartAI entries" line.
--   * Display 38153 is substituted with 38152. 38153 is absent from the
--     deployed CreatureDisplayInfo.dbc (28,592 records); 38152 is present and
--     is the same worm, already in use by the caster 3653112.
SET @OFF := 3600000;

DELETE FROM acore_world.`creature_template` WHERE `entry` = 3653113;

INSERT INTO acore_world.`creature_template`
(`entry`,`KillCredit1`,`KillCredit2`,`name`,`subname`,`IconName`,`gossip_menu_id`,`minlevel`,`maxlevel`,`exp`,`faction`,`npcflag`,`speed_walk`,`speed_run`,`speed_swim`,`speed_flight`,`rank`,`dmgschool`,`DamageModifier`,`BaseAttackTime`,`RangeAttackTime`,`BaseVariance`,`RangeVariance`,`unit_class`,`unit_flags`,`unit_flags2`,`dynamicflags`,`family`,`type`,`type_flags`,`lootid`,`pickpocketloot`,`skinloot`,`PetSpellDataId`,`VehicleId`,`mingold`,`maxgold`,`AIName`,`MovementType`,`HoverHeight`,`HealthModifier`,`ManaModifier`,`ArmorModifier`,`RacialLeader`,`movementId`,`RegenHealth`,`flags_extra`,`ScriptName`,`VerifiedBuild`)
SELECT entry+@OFF, IF(KillCredit1>0,KillCredit1+@OFF,0), IF(KillCredit2>0,KillCredit2+@OFF,0), name, subname, IconName, gossip_menu_id, minlevel, maxlevel, LEAST(exp,2), faction_A, npcflag, speed_walk, speed_run, speed_swim, speed_fly, `rank`, dmgschool, dmg_multiplier, baseattacktime, rangeattacktime, 1, 1, unit_class, unit_flags, unit_flags2, dynamicflags, family, type, type_flags, 0, 0, 0, PetSpellDataId, VehicleId, mingold, maxgold,
       '',
       MovementType, HoverHeight, Health_mod, Mana_mod, Armor_mod, RacialLeader, movementId, RegenHealth, flags_extra, '', 0
FROM nelt_world.creature_template
WHERE entry = 53113;

DELETE FROM acore_world.`creature_template_model` WHERE `CreatureID` = 3653113;

INSERT INTO acore_world.`creature_template_model` (`CreatureID`,`Idx`,`CreatureDisplayID`,`DisplayScale`,`Probability`,`VerifiedBuild`)
VALUES (3653113,0,38152,1,1,0);

-- ---- 3. the 15 action lists (77 rows) --------------------------------------
-- source_type 9. Every row in this set carries event_type 0, so the fork's
-- event_param5/6 divergence from upstream (distance lives in 5/6 here, not 1/2)
-- cannot bite -- but that is why the column list is written out rather than
-- SELECT *: nelt_world.smart_scripts has no event_param5/6 at all.
DELETE FROM acore_world.`smart_scripts` WHERE `source_type` = 9 AND `entryorguid` IN (4941300,5270500,5299000,5310700,5310701,5311200,5316300,5323400,5323401,5323402,5323403,5323404,5335400,5402500,5407000);

INSERT INTO acore_world.`smart_scripts`
(`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`event_param5`,`event_param6`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_param4`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`)
SELECT entryorguid, source_type, id, link, event_type, event_phase_mask, event_chance, event_flags,
       event_param1, event_param2, event_param3, event_param4, 0, 0,
       action_type,
       CASE WHEN action_type = 33 AND action_param1 = 53234 THEN 3653234 ELSE action_param1 END,
       action_param2, action_param3, action_param4, action_param5, action_param6,
       target_type,
       CASE WHEN target_type = 19 AND target_param1 = 53366 THEN 3653366
            WHEN target_type = 19 AND target_param1 = 52669 THEN 3652669
            ELSE target_param1 END,
       target_param2, target_param3, target_param4, target_x, target_y, target_z, target_o,
       CONCAT('MF action list restore - src ', entryorguid, '.', id)
FROM nelt_world.smart_scripts
WHERE source_type = 9 AND entryorguid IN (4941300,5270500,5299000,5310700,5310701,5311200,5316300,5323400,5323401,5323402,5323403,5323404,5335400,5402500,5407000);

-- ---- 4. the four waypoint paths those lists start --------------------------
-- 20 points. Ids stay RAW, matching 16_'s already-live path 53912. nelt's
-- waypoints table has no orientation/delay columns, so both default to 0 --
-- which is what every other path in this downport carries.
DELETE FROM acore_world.`waypoints` WHERE `entry` IN (52990,53234,54025,5323400);

INSERT INTO acore_world.`waypoints` (`entry`,`pointid`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`point_comment`)
SELECT entry, pointid, position_x, position_y, position_z, 0, 0, point_comment
FROM nelt_world.waypoints WHERE entry IN (52990,53234,54025,5323400);

-- Verify after apply:
--   * SELECT COUNT(*) FROM smart_scripts WHERE source_type=9
--       AND entryorguid IN (4941300,5270500,5299000,5310700,5310701,5311200,5316300,5323400,5323401,5323402,5323403,5323404,5335400,5402500,5407000)                              -> 77
--   * SELECT COUNT(*) FROM waypoints WHERE entry IN (52990,53234,54025,5323400)     -> 20
--   * SELECT COUNT(*) FROM smart_scripts s WHERE s.action_type=80
--       AND s.entryorguid BETWEEN 3600000 AND 3700000
--       AND NOT EXISTS (SELECT 1 FROM smart_scripts a
--         WHERE a.entryorguid=s.action_param1 AND a.source_type=9)  -> 0
--   * Errors.log keeps exactly ONE waypoint line for this area -- the
--     5391201 / 5391200 upstream gap described in the header.
