-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_SharedTalentUI/Blizzard_TalentButtonArt.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

ns.XML.Load("Blizzard_SharedTalentUI/Blizzard_TalentButtonArt.xml", {
    { tag = "Button", attr = { name = "TalentButtonArtTemplate", mixin = "TalentButtonArtMixin", inherits = "TalentDisplayTemplate", virtual = "true" }, children = {
        { tag = "KeyValues" },
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "BACKGROUND" }, children = {
                { tag = "Texture", attr = { parentKey = "Shadow" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER" } },
                    } },
                } },
            } },
            { tag = "Layer", attr = { level = "BORDER" }, children = {
                { tag = "Texture", attr = { parentKey = "Icon", file = "Interface\\Icons\\INV_Misc_QuestionMark" }, children = {
                    { tag = "Size", attr = { x = "36", y = "36" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER" } },
                    } },
                } },
            } },
            { tag = "Layer", attr = { level = "BORDER", textureSubLevel = "1" }, children = {
                { tag = "Texture", attr = { parentKey = "DisabledOverlay", hidden = "true" }, children = {
                    { tag = "Size", attr = { x = "36", y = "36" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER" } },
                    } },
                    { tag = "Color", attr = { r = "0", g = "0", b = "0", a = "1" } },
                } },
            } },
            { tag = "Layer", attr = { level = "ARTWORK" }, children = {
                { tag = "Texture", attr = { parentKey = "StateBorder", texelSnappingBias = "0.0", snapToPixelGrid = "false" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER" } },
                    } },
                } },
                { tag = "Texture", attr = { parentKey = "StateBorderHover", texelSnappingBias = "0.0", snapToPixelGrid = "false", alphaMode = "ADD", hidden = "true" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER" } },
                    } },
                } },
            } },
            { tag = "Layer", attr = { level = "OVERLAY", textureSubLevel = "2" }, children = {
                { tag = "FontString", attr = { parentKey = "SpendText", inherits = "SystemFont16_Shadow_ThickOutline", justifyH = "CENTER" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "BOTTOM", x = "11", y = "4" } },
                    } },
                } },
                { tag = "Texture", attr = { parentKey = "SelectableIcon", atlas = "talents-icon-learnableplus", useAtlasSize = "true", hidden = "true" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "BOTTOMLEFT", x = "-3", y = "-3" } },
                    } },
                } },
            } },
            { tag = "Layer", attr = { level = "ARTWORK", textureSubLevel = "1" }, children = {
                { tag = "FontString", attr = { parentKey = "SpendTextShadow1", inherits = "SystemFont16_Shadow_ThickOutline", justifyH = "CENTER", parentArray = "spendTextShadows" }, children = {
                    { tag = "Color", attr = { r = "0", g = "0", b = "0" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER", relativeKey = "$parent.SpendText", relativePoint = "CENTER", x = "-1", y = "1" } },
                    } },
                } },
                { tag = "FontString", attr = { parentKey = "SpendTextShadow2", inherits = "SystemFont16_Shadow_ThickOutline", justifyH = "CENTER", parentArray = "spendTextShadows" }, children = {
                    { tag = "Color", attr = { r = "0", g = "0", b = "0" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER", relativeKey = "$parent.SpendText", relativePoint = "CENTER", x = "1", y = "1" } },
                    } },
                } },
                { tag = "FontString", attr = { parentKey = "SpendTextShadow3", inherits = "SystemFont16_Shadow_ThickOutline", justifyH = "CENTER", parentArray = "spendTextShadows" }, children = {
                    { tag = "Color", attr = { r = "0", g = "0", b = "0" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER", relativeKey = "$parent.SpendText", relativePoint = "CENTER", x = "-1", y = "-1" } },
                    } },
                } },
                { tag = "FontString", attr = { parentKey = "SpendTextShadow4", inherits = "SystemFont16_Shadow_ThickOutline", justifyH = "CENTER", parentArray = "spendTextShadows" }, children = {
                    { tag = "Color", attr = { r = "0", g = "0", b = "0" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER", relativeKey = "$parent.SpendText", relativePoint = "CENTER", x = "1", y = "-1" } },
                    } },
                } },
            } },
            { tag = "Layer", attr = { level = "OVERLAY", textureSubLevel = "3" }, children = {
                { tag = "MaskTexture", attr = { parentKey = "IconMask", hWrapMode = "CLAMPTOBLACKADDITIVE", vWrapMode = "CLAMPTOBLACKADDITIVE" }, children = {
                    { tag = "Size", attr = { x = "36", y = "36" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER", relativeKey = "$parent.Icon", relativePoint = "CENTER" } },
                    } },
                    { tag = "MaskedTextures", children = {
                        { tag = "MaskedTexture", attr = { childKey = "Icon" } },
                    } },
                } },
            } },
            { tag = "Layer", attr = { level = "OVERLAY" }, children = {
                { tag = "MaskTexture", attr = { parentKey = "DisabledOverlayMask", atlas = "UI-Frame-IconMask", hWrapMode = "CLAMPTOBLACKADDITIVE", vWrapMode = "CLAMPTOBLACKADDITIVE" }, children = {
                    { tag = "Size", attr = { x = "36", y = "36" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER", relativeKey = "$parent.DisabledOverlay", relativePoint = "CENTER" } },
                    } },
                    { tag = "MaskedTextures", children = {
                        { tag = "MaskedTexture", attr = { childKey = "DisabledOverlay" } },
                    } },
                } },
            } },
            { tag = "Layer", attr = { level = "OVERLAY" }, children = {
                { tag = "Texture", attr = { parentKey = "Glow", hidden = "true", alphaMode = "ADD", atlas = "talents-node-square-greenglow" }, children = {
                    { tag = "Size", attr = { x = "62", y = "62" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER" } },
                    } },
                    { tag = "Animations", children = {
                        { tag = "AnimationGroup", attr = { parentKey = "Anim", looping = "REPEAT", setToFinalAlpha = "true" }, children = {
                            { tag = "Alpha", attr = { fromAlpha = "0", toAlpha = "1", duration = "0.36", order = "1", smoothing = "OUT" } },
                            { tag = "Alpha", attr = { fromAlpha = "1", toAlpha = "0", duration = "0.36", order = "2", smoothing = "IN" } },
                        } },
                    } },
                    { tag = "Scripts", children = {
                        { tag = "OnShow", func = function(self)
                                self.Anim:Play();
                            end },
                        { tag = "OnHide", func = function(self)
                                self.Anim:Stop();
                            end },
                    } },
                } },
            } },
            { tag = "Layer", attr = { level = "OVERLAY" }, children = {
                { tag = "Texture", attr = { parentKey = "Ghost", texelSnappingBias = "0.0", snapToPixelGrid = "false", alpha = "0.8", hidden = "true" }, children = {
                    { tag = "Size", attr = { x = "48", y = "48" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER" } },
                    } },
                } },
            } },
        } },
        { tag = "Frames", children = {
            { tag = "Frame", attr = { parentKey = "SearchIcon", hidden = "true", inherits = "TalentButtonSearchIconTemplate" }, children = {
                { tag = "KeyValues", children = {
                    { tag = "KeyValue", attr = { key = "mouseoverSize", value = "18", type = "number" } },
                } },
                { tag = "Size", attr = { x = "63", y = "63" } },
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "CENTER", relativeKey = "$parent.Icon", relativePoint = "TOPRIGHT" } },
                } },
            } },
        } },
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
        } },
    } },
    { tag = "Button", attr = { name = "TalentButtonCircleTemplate", inherits = "TalentButtonArtTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "GetEdgeDiameterOffset", value = "TalentButtonArtMixin.GetCircleEdgeDiameterOffset", type = "global" } },
            { tag = "KeyValue", attr = { key = "artSet", value = "TalentButtonArtMixin.ArtSet.Circle", type = "global" } },
        } },
        { tag = "Size", attr = { x = "40", y = "40" } },
    } },
    { tag = "Button", attr = { name = "TalentButtonSmallCircleTemplate", inherits = "TalentButtonArtTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "buttonSizeScaleOverride", value = "0.5", type = "number" } },
            { tag = "KeyValue", attr = { key = "artSet", value = "TalentButtonArtMixin.ArtSet.LegionSmallCircle", type = "global" } },
            { tag = "KeyValue", attr = { key = "sizingAdjustment", value = "TalentButtonUtil.SizingAdjustment.Small", type = "global" } },
        } },
        { tag = "Size", attr = { x = "30", y = "30" } },
    } },
    { tag = "Button", attr = { name = "TalentButtonSquareTemplate", inherits = "TalentButtonArtTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "GetEdgeDiameterOffset", value = "TalentButtonArtMixin.GetSquareEdgeDiameterOffset", type = "global" } },
            { tag = "KeyValue", attr = { key = "artSet", value = "TalentButtonArtMixin.ArtSet.Square", type = "global" } },
        } },
        { tag = "Size", attr = { x = "40", y = "40" } },
    } },
    { tag = "Button", attr = { name = "TalentButtonLegionSmallCircleTemplate", inherits = "TalentButtonSmallCircleTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "artSet", value = "TalentButtonArtMixin.ArtSet.LegionSmallCircle", type = "global" } },
        } },
        { tag = "Size", attr = { x = "20", y = "20" } },
    } },
    { tag = "Button", attr = { name = "TalentButtonLegionCircleTemplate", inherits = "TalentButtonCircleTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "artSet", value = "TalentButtonArtMixin.ArtSet.LegionCircle", type = "global" } },
        } },
    } },
    { tag = "Button", attr = { name = "TalentButtonLegionSquareTemplate", inherits = "TalentButtonSquareTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "artSet", value = "TalentButtonArtMixin.ArtSet.LegionSquare", type = "global" } },
        } },
    } },
    { tag = "Button", attr = { name = "TalentButtonLegionInfiniteNode", inherits = "TalentButtonCircleTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "buttonSizeScaleOverride", value = "1.5", type = "number" } },
            { tag = "KeyValue", attr = { key = "artSet", value = "TalentButtonArtMixin.ArtSet.LegionInfiniteCircle", type = "global" } },
            { tag = "KeyValue", attr = { key = "sizingAdjustment", value = "TalentButtonUtil.SizingAdjustment.LegionInfinite", type = "global" } },
        } },
    } },
    { tag = "Button", attr = { name = "TalentButtonLargeSquareTemplate", inherits = "TalentButtonArtTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "artSet", value = "TalentButtonArtMixin.ArtSet.LargeSquare", type = "global" } },
            { tag = "KeyValue", attr = { key = "sizingAdjustment", value = "TalentButtonUtil.SizingAdjustment.Large", type = "global" } },
        } },
        { tag = "Size", attr = { x = "64", y = "64" } },
    } },
    { tag = "Button", attr = { name = "TalentButtonLargeCircleTemplate", inherits = "TalentButtonArtTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "artSet", value = "TalentButtonArtMixin.ArtSet.LargeCircle", type = "global" } },
            { tag = "KeyValue", attr = { key = "sizingAdjustment", value = "TalentButtonUtil.SizingAdjustment.Large", type = "global" } },
        } },
        { tag = "Size", attr = { x = "64", y = "64" } },
    } },
    { tag = "Frame", attr = { name = "TalentButtonCircularGlowTemplate", inherits = "AnimateWhileShownTemplate", virtual = "true" }, children = {
        { tag = "Size", attr = { x = "80", y = "80" } },
        { tag = "Anchors", children = {
            { tag = "Anchor", attr = { point = "CENTER" } },
        } },
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "ARTWORK" }, children = {
                { tag = "Texture", attr = { parentKey = "GlowTexture", atlas = "lemixArtifact-node-circle-glw-FX", setAllPoints = "true" } },
            } },
        } },
        { tag = "Animations", children = {
            { tag = "AnimationGroup", attr = { looping = "REPEAT", setToFinalAlpha = "true" }, children = {
                { tag = "Alpha", attr = { childKey = "GlowTexture", fromAlpha = "0", toAlpha = "1", duration = "1.0", order = "1" } },
                { tag = "Alpha", attr = { childKey = "GlowTexture", fromAlpha = "1", toAlpha = "0", duration = "1.0", order = "2" } },
            } },
        } },
    } },
})
