-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_SharedTalentUI/Blizzard_SharedTalentEdgeTemplates.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

-- Script Blizzard_SharedTalentEdgeTemplates.lua (loaded through the TOC)

ns.XML.Load("Blizzard_SharedTalentUI/Blizzard_SharedTalentEdgeTemplates.xml", {
    { tag = "Frame", attr = { name = "TalentEdgeBaseTemplate", mixin = "TalentEdgeBaseMixin", virtual = "true" } },
    { tag = "Frame", attr = { name = "TalentEdgeStraightTemplate", mixin = "TalentEdgeStraightMixin", inherits = "TalentEdgeBaseTemplate", virtual = "true" }, children = {
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "OVERLAY", textureSubLevel = "-3" }, children = {
                { tag = "Line", attr = { parentKey = "Background", file = "Interface/Artifacts/_Artifacts-DependencyBar-BG", thickness = "12", hWrapMode = "REPEAT" } },
            } },
            { tag = "Layer", attr = { level = "OVERLAY", textureSubLevel = "-2" }, children = {
                { tag = "Line", attr = { parentKey = "Fill", file = "Interface/Artifacts/_Artifacts-DependencyBar-Fill", thickness = "12", hWrapMode = "REPEAT" } },
            } },
            { tag = "Layer", attr = { level = "OVERLAY", textureSubLevel = "-1" }, children = {
                { tag = "Line", attr = { parentKey = "FillScroll1", parentArray = "FillScrolls", file = "Interface/Artifacts/_Artifacts-DependencyBar-FillScroll1", thickness = "12", hWrapMode = "REPEAT", alphaMode = "ADD" } },
                { tag = "Line", attr = { parentKey = "FillScroll2", parentArray = "FillScrolls", file = "Interface/Artifacts/_Artifacts-DependencyBar-FillScroll2", thickness = "12", hWrapMode = "REPEAT", alphaMode = "ADD" } },
            } },
        } },
        { tag = "Animations", children = {
            { tag = "AnimationGroup", attr = { parentKey = "ScrollAnim", setToFinalAlpha = "true", looping = "REPEAT" }, children = {
                { tag = "TextureCoordTranslation", attr = { childKey = "FillScroll1", duration = "8", order = "1", offsetU = "1", offsetV = "0" } },
                { tag = "TextureCoordTranslation", attr = { childKey = "FillScroll2", duration = "8", order = "1", offsetU = "-1", offsetV = "0" } },
            } },
        } },
    } },
    { tag = "Frame", attr = { name = "TalentEdgeArrowTemplate", mixin = "TalentEdgeArrowMixin", inherits = "TalentEdgeBaseTemplate", virtual = "true" }, children = {
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "OVERLAY", textureSubLevel = "-2" }, children = {
                { tag = "Line", attr = { parentKey = "Line", thickness = "6", hWrapMode = "REPEAT" } },
            } },
            { tag = "Layer", attr = { level = "OVERLAY", textureSubLevel = "1" }, children = {
                { tag = "Texture", attr = { parentKey = "ArrowHead", atlas = "talents-arrow-head-gray", useAtlasSize = "true" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER" } },
                    } },
                } },
                { tag = "Texture", attr = { parentKey = "GhostArrowHead", atlas = "talents-arrow-head-ghost", useAtlasSize = "true", alpha = "0.8", hidden = "true" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER" } },
                    } },
                } },
            } },
            { tag = "Layer", attr = { level = "OVERLAY", textureSubLevel = "2" }, children = {
                { tag = "Line", attr = { parentKey = "GhostLine", atlas = "talents-arrow-line-ghost", thickness = "6", hWrapMode = "REPEAT", alphaMode = "ADD", alpha = "0.8", hidden = "true" } },
            } },
        } },
    } },
})
