-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_SharedTalentUI/Blizzard_SharedTalentButtonTemplates.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

ns.XML.Load("Blizzard_SharedTalentUI/Blizzard_SharedTalentButtonTemplates.xml", {
    { tag = "Frame", attr = { name = "TalentButtonSearchIconTemplate", mixin = "TalentButtonSearchIconMixin", inherits = "AnimateWhileShownTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "mouseoverSize", value = "10", type = "number" } },
        } },
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "OVERLAY", textureSubLevel = "3" }, children = {
                { tag = "Texture", attr = { parentKey = "Icon", atlas = "talents-search-match", useAtlasSize = "true" } },
                { tag = "Texture", attr = { parentKey = "OverlayIcon", atlas = "talents-search-match", alphaMode = "ADD" } },
                { tag = "Texture", attr = { parentKey = "Mouseover" }, children = {
                    { tag = "Size", attr = { x = "18", y = "18" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "CENTER" } },
                    } },
                    { tag = "Color", attr = { r = "0", g = "0", b = "0", a = "0" } },
                } },
            } },
        } },
        { tag = "Animations", children = {
            { tag = "AnimationGroup", attr = { parentKey = "GlowAnim", looping = "REPEAT", setToFinalAlpha = "true", inherits = "SyncedAnimGroupTemplate" }, children = {
                { tag = "KeyValues", children = {
                    { tag = "KeyValue", attr = { key = "syncKey", value = "TraitSearchIcon", type = "string" } },
                } },
                { tag = "Alpha", attr = { childKey = "OverlayIcon", fromAlpha = "0", toAlpha = ".5", duration = "1", order = "1", smoothing = "NONE" } },
                { tag = "Alpha", attr = { childKey = "OverlayIcon", fromAlpha = ".5", toAlpha = "0", duration = "1", order = "2", smoothing = "NONE" } },
            } },
        } },
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
        } },
    } },
})
