-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_SharedTalentUI/Blizzard_TalentButtonAnim.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

ns.XML.Load("Blizzard_SharedTalentUI/Blizzard_TalentButtonAnim.xml", {
    { tag = "Frame", attr = { name = "TalentButtonAnimationTemplate", mixin = "TalentDisplayAnimationMixin", virtual = "true" }, children = {
        { tag = "Size", attr = { x = "1", y = "1" } },
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "anchorPoint", value = "CENTER", type = "string" } },
            { tag = "KeyValue", attr = { key = "relativePoint", value = "CENTER", type = "string" } },
            { tag = "KeyValue", attr = { key = "xOffset", value = "0", type = "number" } },
            { tag = "KeyValue", attr = { key = "yOffset", value = "0", type = "number" } },
        } },
    } },
})
