-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_SharedTalentUI/Blizzard_SharedTalentFrameTemplates.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

-- Script Blizzard_SharedTalentFrameTemplates.lua (loaded through the TOC)

ns.XML.Load("Blizzard_SharedTalentUI/Blizzard_SharedTalentFrameTemplates.xml", {
    { tag = "Frame", attr = { name = "TalentFrameCurrencyDisplayTemplate", mixin = "TalentFrameCurrencyDisplayMixin", inherits = "CallbackRegistrantTemplate, ResizeLayoutFrame", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "widthPadding", value = "10", type = "number" } },
            { tag = "KeyValue", attr = { key = "heightPadding", value = "6", type = "number" } },
        } },
        { tag = "Size", attr = { x = "1", y = "1" } },
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "BACKGROUND" }, children = {
                { tag = "Texture", attr = { parentKey = "Background", setAllPoints = "true" }, children = {
                    { tag = "KeyValues", children = {
                        { tag = "KeyValue", attr = { key = "ignoreInLayout", value = "true", type = "boolean" } },
                    } },
                    { tag = "Color", attr = { r = "0.1", g = "0.1", b = "0.1", a = "0.7" } },
                } },
            } },
            { tag = "Layer", attr = { level = "OVERLAY" }, children = {
                { tag = "FontString", attr = { parentKey = "Text", inherits = "GameFontHighlightLarge2", justifyH = "RIGHT" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "RIGHT", x = "-5", y = "0" } },
                    } },
                } },
            } },
        } },
        { tag = "Scripts", children = {
            { tag = "OnShow", attr = { method = "OnShow" } },
        } },
    } },
    { tag = "Frame", attr = { name = "TalentFrameGateTemplate", mixin = "TalentFrameGateMixin", virtual = "true" }, children = {
        { tag = "Size", attr = { x = "124", y = "40" } },
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "ARTWORK" }, children = {
                { tag = "Texture", attr = { parentKey = "LockIcon", atlas = "talents-gate", useAtlasSize = "true" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "RIGHT", x = "20", y = "2" } },
                    } },
                } },
            } },
            { tag = "Layer", attr = { level = "OVERLAY" }, children = {
                { tag = "FontString", attr = { parentKey = "GateText", inherits = "GameFontHighlightHuge2", hidden = "true" }, children = {
                    { tag = "KeyValues", children = {
                        { tag = "KeyValue", attr = { key = "ignoreInLayout", value = "true", type = "boolean" } },
                    } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "RIGHT", relativeKey = "$parent.LockIcon", relativePoint = "LEFT", x = "-10", y = "-1" } },
                    } },
                    { tag = "Color", attr = { r = "1", g = "0.64", b = "0.56" } },
                } },
            } },
        } },
        { tag = "Scripts", children = {
            { tag = "OnEnter", attr = { method = "OnEnter" } },
            { tag = "OnLeave", attr = { method = "OnLeave" } },
        } },
    } },
    { tag = "Frame", attr = { name = "TraitsCommitControlsContainerTemplate", mixin = "TraitsCommitControlsContainerMixin", virtual = "true" }, children = {
        { tag = "Size", attr = { x = "242", y = "27" } },
        { tag = "Frames", children = {
            { tag = "Button", attr = { parentKey = "CommitButton", inherits = "UIPanelButtonNoTooltipTemplate, UIButtonTemplate", text = "TALENT_FRAME_APPLY_BUTTON_TEXT" }, children = {
                { tag = "Size", attr = { x = "164", y = "22" } },
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "CENTER", x = "0", y = "0" } },
                } },
                { tag = "Frames", children = {
                    { tag = "Frame", attr = { parentKey = "YellowGlow", hidden = "true" }, children = {
                        { tag = "Size", attr = { y = "1" } },
                        { tag = "Anchors", children = {
                            { tag = "Anchor", attr = { point = "LEFT", x = "-12", y = "0" } },
                            { tag = "Anchor", attr = { point = "RIGHT", x = "12", y = "0" } },
                        } },
                        { tag = "Layers", children = {
                            { tag = "Layer", attr = { level = "ARTWORK" }, children = {
                                { tag = "Texture", attr = { parentKey = "Left", atlas = "newplayertutorial-yellowGlow-redbutton-left", useAtlasSize = "true", alphaMode = "ADD" }, children = {
                                    { tag = "Anchors", children = {
                                        { tag = "Anchor", attr = { point = "LEFT" } },
                                    } },
                                } },
                                { tag = "Texture", attr = { parentKey = "Right", atlas = "newplayertutorial-yellowGlow-redbutton-right", useAtlasSize = "true", alphaMode = "ADD" }, children = {
                                    { tag = "Anchors", children = {
                                        { tag = "Anchor", attr = { point = "RIGHT" } },
                                    } },
                                } },
                                { tag = "Texture", attr = { parentKey = "Middle", atlas = "newplayertutorial-yellowGlow-redbutton-middle", alphaMode = "ADD" }, children = {
                                    { tag = "Anchors", children = {
                                        { tag = "Anchor", attr = { point = "TOPLEFT", relativeKey = "$parent.Left", relativePoint = "TOPRIGHT" } },
                                        { tag = "Anchor", attr = { point = "BOTTOMRIGHT", relativeKey = "$parent.Right", relativePoint = "BOTTOMLEFT" } },
                                    } },
                                } },
                            } },
                        } },
                    } },
                } },
            } },
            { tag = "Button", attr = { parentKey = "UndoButton", inherits = "IconButtonTemplate", hidden = "true" }, children = {
                { tag = "KeyValues", children = {
                    { tag = "KeyValue", attr = { key = "iconAtlas", value = "talents-button-undo", type = "string" } },
                    { tag = "KeyValue", attr = { key = "useAtlasSize", value = "true", type = "boolean" } },
                    { tag = "KeyValue", attr = { key = "useIconAsHighlight", value = "true", type = "boolean" } },
                    { tag = "KeyValue", attr = { key = "tooltipText", value = "TALENT_FRAME_DISCARD_CHANGES_BUTTON_TOOLTIP", type = "global" } },
                    { tag = "KeyValue", attr = { key = "tooltipTextColor", value = "HIGHLIGHT_FONT_COLOR", type = "global" } },
                } },
                { tag = "Size", attr = { x = "25", y = "25" } },
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "LEFT", relativeKey = "$parent.CommitButton", relativePoint = "RIGHT", x = "14", y = "0" } },
                } },
            } },
            { tag = "Button", attr = { parentKey = "ResetButton", inherits = "IconButtonTemplate", hidden = "true" }, children = {
                { tag = "KeyValues", children = {
                    { tag = "KeyValue", attr = { key = "iconAtlas", value = "talents-button-reset", type = "string" } },
                    { tag = "KeyValue", attr = { key = "useAtlasSize", value = "true", type = "boolean" } },
                    { tag = "KeyValue", attr = { key = "useIconAsHighlight", value = "true", type = "boolean" } },
                    { tag = "KeyValue", attr = { key = "tooltipText", value = "Reset Tree", type = "global" } },
                    { tag = "KeyValue", attr = { key = "tooltipTextColor", value = "HIGHLIGHT_FONT_COLOR", type = "global" } },
                } },
                { tag = "Size", attr = { x = "25", y = "25" } },
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "LEFT", relativeKey = "$parent.CommitButton", relativePoint = "RIGHT", x = "14", y = "0" } },
                } },
            } },
        } },
        { tag = "Scripts", children = {
            { tag = "OnShow", attr = { method = "OnShow" } },
        } },
    } },
    { tag = "Frame", attr = { name = "TalentSubTreeHeaderTemplate", mixin = "TalentSubTreeHeaderMixin", inherits = "VerticalLayoutFrame, CallbackRegistrantTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "fixedWidth", value = "1000", type = "number" } },
        } },
        { tag = "Size", attr = { x = "1", y = "1" } },
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "ARTWORK" }, children = {
                { tag = "Texture", attr = { parentKey = "Line", setAllPoints = "false" }, children = {
                    { tag = "Size", attr = { x = "1", y = "2" } },
                    { tag = "KeyValues", children = {
                        { tag = "KeyValue", attr = { key = "layoutIndex", value = "1", type = "number" } },
                        { tag = "KeyValue", attr = { key = "expand", value = "true", type = "boolean" } },
                        { tag = "KeyValue", attr = { key = "bottomPadding", value = "10", type = "number" } },
                    } },
                    { tag = "Color", attr = { r = "0.4", g = "0.4", b = "0.4" } },
                } },
                { tag = "FontString", attr = { parentKey = "Text", inherits = "Game27Font" }, children = {
                    { tag = "KeyValues", children = {
                        { tag = "KeyValue", attr = { key = "layoutIndex", value = "2", type = "number" } },
                        { tag = "KeyValue", attr = { key = "expand", value = "true", type = "boolean" } },
                        { tag = "KeyValue", attr = { key = "bottomPadding", value = "8", type = "number" } },
                    } },
                    { tag = "Size", attr = { x = "1", y = "24" } },
                    { tag = "Color", attr = { r = "1", g = "1", b = "1" } },
                } },
                { tag = "FontString", attr = { parentKey = "Info", inherits = "Game22Font" }, children = {
                    { tag = "KeyValues", children = {
                        { tag = "KeyValue", attr = { key = "layoutIndex", value = "3", type = "number" } },
                        { tag = "KeyValue", attr = { key = "expand", value = "true", type = "boolean" } },
                    } },
                    { tag = "Size", attr = { x = "1", y = "16" } },
                    { tag = "Color", attr = { r = "1", g = "1", b = "1" } },
                } },
            } },
        } },
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
            { tag = "OnShow", attr = { method = "OnShow" } },
        } },
    } },
    { tag = "Frame", attr = { name = "TalentFrameHeaderTemplate", mixin = "TalentFrameHeaderMixin", inherits = "VerticalLayoutFrame", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "fixedWidth", value = "200", type = "number" } },
        } },
        { tag = "Size", attr = { x = "1", y = "1" } },
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "ARTWORK" }, children = {
                { tag = "FontString", attr = { parentKey = "Text", inherits = "GameFontHighlightLarge2" }, children = {
                    { tag = "KeyValues", children = {
                        { tag = "KeyValue", attr = { key = "layoutIndex", value = "1", type = "number" } },
                        { tag = "KeyValue", attr = { key = "expand", value = "true", type = "boolean" } },
                        { tag = "KeyValue", attr = { key = "bottomPadding", value = "4", type = "number" } },
                    } },
                    { tag = "Size", attr = { x = "1", y = "16" } },
                    { tag = "Color", attr = { r = "1", g = "1", b = "1" } },
                } },
                { tag = "Texture", attr = { parentKey = "Line", setAllPoints = "false" }, children = {
                    { tag = "Size", attr = { x = "1", y = "2" } },
                    { tag = "KeyValues", children = {
                        { tag = "KeyValue", attr = { key = "layoutIndex", value = "2", type = "number" } },
                        { tag = "KeyValue", attr = { key = "expand", value = "true", type = "boolean" } },
                    } },
                    { tag = "Color", attr = { r = "0.7", g = "0.7", b = "0.7" } },
                } },
            } },
        } },
    } },
    { tag = "Button", attr = { name = "TalentTreeSelectableButtonTemplate", mixin = "TalentTreeSelectableButtonMixin", inherits = "SelectableButtonTemplate", virtual = "true" } },
    { tag = "Frame", attr = { name = "TalentFrameTreeSelectorBaseTemplate", mixin = "TalentFrameTreeSelectorMixin", inherits = "CallbackRegistrantTemplate", virtual = "true" }, children = {
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
        } },
    } },
    { tag = "Frame", attr = { name = "TalentFrameTreeSelectorHorizontalTemplate", mixin = "TalentFrameTreeSelectorHorizontalMixin", inherits = "TalentFrameTreeSelectorBaseTemplate, HorizontalLayoutFrame", virtual = "true" }, children = {
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
            { tag = "OnShow", attr = { method = "OnShow" } },
        } },
    } },
    { tag = "Frame", attr = { name = "TalentFrameStarGridTemplate", mixin = "TalentFrameStarGridMixin", inherits = "GridLayoutFrame", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "stride", value = "1", type = "number" } },
            { tag = "KeyValue", attr = { key = "childXPadding", value = "2", type = "number" } },
            { tag = "KeyValue", attr = { key = "layoutFramesGoingRight", value = "true", type = "boolean" } },
            { tag = "KeyValue", attr = { key = "alwaysUpdateLayout", value = "true", type = "boolean" } },
        } },
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
        } },
    } },
})
