-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

-- Script Blizzard_SharedTalentFrame.lua (loaded through the TOC)

ns.XML.Load("Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.xml", {
    { tag = "Frame", attr = { name = "TalentFrameBaseTemplate", mixin = "TalentFrameBaseMixin", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "getTemplateType", value = "TalentButtonUtil.GetTemplateForTalentType", type = "global" } },
            { tag = "KeyValue", attr = { key = "getSpecializedMixin", value = "TalentButtonUtil.GetSpecializedMixin", type = "global" } },
            { tag = "KeyValue", attr = { key = "getEdgeTemplateType", value = "TalentButtonUtil.GetTemplateForEdgeVisualStyle", type = "global" } },
            { tag = "KeyValue", attr = { key = "getSpecializedChoiceMixin", value = "TalentButtonUtil.GetSpecializedChoiceMixin", type = "global" } },
            { tag = "KeyValue", attr = { key = "buttonSize", value = "40", type = "number" } },
            { tag = "KeyValue", attr = { key = "topPadding", value = "0", type = "number" } },
            { tag = "KeyValue", attr = { key = "leftPadding", value = "0", type = "number" } },
            { tag = "KeyValue", attr = { key = "bottomPadding", value = "0", type = "number" } },
            { tag = "KeyValue", attr = { key = "rightPadding", value = "0", type = "number" } },
            { tag = "KeyValue", attr = { key = "basePanOffsetX", value = "0", type = "number" } },
            { tag = "KeyValue", attr = { key = "basePanOffsetY", value = "0", type = "number" } },
            { tag = "KeyValue", attr = { key = "enableZoomAndPan", value = "true", type = "boolean" } },
            { tag = "KeyValue", attr = { key = "excludeStagedChangesForCurrencies", value = "false", type = "boolean" } },
            { tag = "KeyValue", attr = { key = "maximumCommitTime", value = "3", type = "number" } },
            { tag = "KeyValue", attr = { key = "disabledOverlayAlpha", value = "0.4", type = "number" } },
            { tag = "KeyValue", attr = { key = "enableCommitCastBar", value = "false", type = "boolean" } },
            { tag = "KeyValue", attr = { key = "enableCommitSpinner", value = "false", type = "boolean" } },
            { tag = "KeyValue", attr = { key = "enableCommitEndFlash", value = "false", type = "boolean" } },
        } },
        { tag = "Frames", children = {
            { tag = "Frame", attr = { parentKey = "AnimationHolder" }, children = {
                { tag = "Animations", children = {
                    { tag = "AnimationGroup", attr = { parentKey = "BackgroundFlashAnim", setToFinalAlpha = "true" }, children = {
                        { tag = "Alpha", attr = { childKey = "$parent.BackgroundFlash", startDelay = "0", smoothing = "IN", duration = "1.2", fromAlpha = "1", toAlpha = "0" } },
                    } },
                } },
            } },
            { tag = "Frame", attr = { parentKey = "ButtonsParent", mixin = "TalentFrameBaseButtonsParentMixin", clipChildren = "true", frameLevel = "1000" }, children = {
                { tag = "Scripts", children = {
                    { tag = "OnUpdate", attr = { method = "OnUpdate" } },
                    { tag = "OnMouseDown", attr = { method = "OnMouseDown" } },
                    { tag = "OnMouseWheel", attr = { method = "OnMouseWheel" } },
                } },
            } },
            { tag = "Frame", attr = { parentKey = "SelectionChoiceFrame", inherits = "TalentSelectionChoiceFrameTemplate", enableMouse = "true", frameLevel = "2000", fixedFrameLevel = "true" } },
            { tag = "Frame", attr = { parentKey = "DisabledOverlay", enableMouse = "true", frameLevel = "4000", hidden = "true" }, children = {
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "TOPLEFT", relativeKey = "$parent.ButtonsParent", relativePoint = "TOPLEFT" } },
                    { tag = "Anchor", attr = { point = "BOTTOMRIGHT", relativeKey = "$parent.ButtonsParent", relativePoint = "BOTTOMRIGHT" } },
                } },
                { tag = "Layers", children = {
                    { tag = "Layer", attr = { level = "OVERLAY" }, children = {
                        { tag = "Texture", attr = { parentKey = "GrayOverlay" }, children = {
                            { tag = "Color", attr = { r = "0", g = "0", b = "0", a = "1" } },
                        } },
                    } },
                } },
            } },
            { tag = "Frame", attr = { parentKey = "CommitSpinner", inherits = "SpinnerTemplate", frameLevel = "4001", hidden = "true" }, children = {
                { tag = "Size", attr = { x = "110", y = "110" } },
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "CENTER", relativeKey = "$parent.DisabledOverlay" } },
                } },
            } },
        } },
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "BACKGROUND", textureSubLevel = "3" }, children = {
                { tag = "Texture", attr = { parentKey = "BackgroundFlash", atlas = "spec-background", alphaMode = "ADD", alpha = "0" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "TOPLEFT", relativeKey = "$parent.ButtonsParent", relativePoint = "TOPLEFT" } },
                        { tag = "Anchor", attr = { point = "BOTTOMRIGHT", relativeKey = "$parent.ButtonsParent", relativePoint = "BOTTOMRIGHT" } },
                    } },
                } },
            } },
        } },
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
            { tag = "OnShow", attr = { method = "OnShow" } },
            { tag = "OnHide", attr = { method = "OnHide" } },
            { tag = "OnEvent", attr = { method = "OnEvent" } },
        } },
    } },
    { tag = "Frame", attr = { name = "TalentFrameFixedPositionsTemplate", mixin = "TalentFrameFixedPositionsMixin", virtual = "true" } },
    { tag = "Frame", attr = { name = "TalentFrameDisplayOnlyTemplate", mixin = "TalentFrameDisplayOnlyMixin", virtual = "true" } },
})
