#!/usr/bin/env python3
"""Convert retail (11.x) talent-UI art to WoW 3.3.5a BLP2/DXT textures and emit the DC-Talents atlas table.

Inputs
  --src-root   retail interface extract: BLP2 files under lowercase folders (talentframe/, common/, ...).
               colorEncoding 3 (raw BGRA) and 2 (DXT1/3/5) are read; only mip 0 is used as the source image.
  --atlas      retail Helix/AtlasInfo.lua ("Interface/<Folder>/<Sheet>" -> atlas -> w, h, uv, tiling, scale).

Outputs
  <stage-root>/Interface/<Folder>/<Sheet>.blp   BLP2, colorEncoding 2, DXT1 (opaque art) or DXT5 (alpha).
  --lua-out    DC-Talents/Data/AtlasInfo.lua     ns.AtlasSheets, ns.AtlasInfo, ns.AtlasSourceSheet.
  --manifest   manifest.json next to this file   what this tool wrote (sha256, format, PSNR), for reruns.

3.3.5 constraints (see memory blp-hasmips-2-green-textures): the renderer samples DXT only, so header byte 8
(colorEncoding) is always 2 and byte 11 (hasMips) is 0 or 1, never 2. The 256-entry palette block is written
zeroed even for DXT. Every output is decoded back and compared with its source before the run reports success.

Encoding: a vectorised PCA + least-squares BC1 colour fit and a BC4-style alpha fit, run next to Pillow's own
DDS encoder; each 4x4 block keeps whichever candidate has the lower alpha-weighted error. DXT5 colour blocks are
always emitted in unambiguous 4-colour form (c0 > c1, or c0 == c1 with every index 0).

Safety: nothing that already exists in the stage tree is overwritten unless the manifest says this tool wrote
it (same sha256) or the sheet is listed in IN_PLACE (then the original is copied to _backup_enc3/ first).
A name collision stops the run before anything is written.
"""
from __future__ import annotations

import argparse
import concurrent.futures as cf
import fnmatch
import hashlib
import io
import json
import math
import os
import re
import shutil
import struct
import sys
import time

import numpy as np
from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ADDONS_DIR = os.path.normpath(os.path.join(SCRIPT_DIR, '..', '..'))   # Custom/Client addons needed
CUSTOM_DIR = os.path.dirname(ADDONS_DIR)                              # Custom

DEFAULT_SRC_ROOT = r'K:\Dark-Chaos\WoW 11.2.5 PTR interface extract'
DEFAULT_ATLAS = r'K:\Dark-Chaos\WoW 11.2.7 FrameXML\Helix\AtlasInfo.lua'
DEFAULT_STAGE = os.path.join(CUSTOM_DIR, 'Client patches needed')
DEFAULT_LUA = os.path.join(ADDONS_DIR, 'DC-Talents', 'Data', 'AtlasInfo.lua')
DEFAULT_MANIFEST = os.path.join(SCRIPT_DIR, 'manifest.json')

LUA_HEADER = ('-- Generated by _tools/dc-talents/convert_art.py from retail 11.2.7 Helix/AtlasInfo.lua. '
              'Do not edit by hand.')

WOTLK_CLASSES = ('DeathKnight', 'Druid', 'Hunter', 'Mage', 'Paladin', 'Priest', 'Rogue', 'Shaman', 'Warlock',
                 'Warrior')
DEFAULT_SHEETS = (
    ['Interface/TalentFrame/Talents', 'Interface/TalentFrame/TalentsArrowLine']
    + [f'Interface/TalentFrame/TalentsClassBackground{c}{n}' for c in WOTLK_CLASSES for n in (1, 2)]
    + ['Interface/TalentFrame/Specialization', 'Interface/TalentFrame/Specialization2',
       'Interface/TalentFrame/SpecializationClassThumbnails', 'Interface/Common/MinimalCheckbox',
       'Interface/FrameGeneral/UIFrameMetal2x', 'Interface/FrameGeneral/UIFrameMetalHorizontal2x',
       'Interface/FrameGeneral/UIFrameMetalVertical2x']
)
# Sheets whose existing staged file may be replaced (authorised 2026-09-30: they were staged as colorEncoding 3
# and hold an older frame layout that does not match the 11.2.7 atlas). Value = staged file name to keep.
IN_PLACE = {
    'Interface/FrameGeneral/UIFrameMetal2x': 'UIFrameMetal2x.BLP',
    'Interface/FrameGeneral/UIFrameMetalHorizontal2x': 'UIFrameMetalHorizontal2x.BLP',
    'Interface/FrameGeneral/UIFrameMetalVertical2x': 'UIFrameMetalVertical2x.BLP',
}
BACKUP_DIR = '_backup_enc3'   # leading underscore: dc_mpq_deploy.py never ships it
# Never picked up by a --sheets glob: 3.3.5 has no mask textures, the rest is out of scope for DC-Talents.
SKIP_GLOBS = ('*/TalentsAnimations*', '*/TalentsMask*', '*/LemixArtifact*', '*/Garrison/*', '*Transmogrify*',
              '*AuctionHouse*', '*NewPlayerExperienceParts*', '*UILFGPrompts*', '*UIFrameIconMask*')

ALPHA_CUTOFF = 250        # texel counts as translucent below this alpha
ALPHA_FRACTION = 0.001    # DXT5 when more than 0.1 % of the measured texels are translucent
WEIGHT_FLOOR = 1.0 / 16   # colour-fit weight of fully transparent texels (visible texels weigh up to 1)
CHUNK = 16384             # blocks per vectorised encoder step
HEADER_SIZE = 148
PALETTE_SIZE = 1024
DDS_TOL = 2               # max |diff| vs Pillow's DDS BCn decoder (rounding conventions only)
BLP_TOL_RGB = 8           # Pillow's BLP reader expands 565 without bit replication (up to 7 low)
BLP_TOL_A = 2


# ------------------------------------------------------------------------------------------------ atlas parsing

class Atlas:
    __slots__ = ('name', 'width', 'height', 'uv', 'tiles_h', 'tiles_v', 'scale')

    def __init__(self, name, width, height, uv, tiles_h, tiles_v, scale):
        self.name, self.width, self.height, self.uv = name, width, height, uv
        self.tiles_h, self.tiles_v, self.scale = tiles_h, tiles_v, scale

    def uv_floats(self):
        return tuple(float(t) for t in self.uv)


_SHEET_RE = re.compile(r'^\t\["([^"]+)"\]=\{\s*$')
_ENTRY_RE = re.compile(r'^\t\t\["([^"]+)"\]=\{([^{}]*)\},?\s*$')
_NUM_RE = re.compile(r'^-?\d+(\.\d+)?([eE][-+]?\d+)?$')


def parse_atlas_info(path):
    """Return {sheet key: {atlas name: Atlas}}; uv tokens are kept verbatim so the Lua output matches retail."""
    sheets = {}
    current = None
    with open(path, encoding='utf-8') as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.rstrip('\r\n')
            m = _SHEET_RE.match(line)
            if m:
                current = sheets.setdefault(m.group(1), {})
                continue
            if current is None:
                continue
            m = _ENTRY_RE.match(line)
            if m:
                toks = [t.strip() for t in m.group(2).split(',')]
                if (len(toks) != 9 or not all(_NUM_RE.match(t) for t in toks[:6])
                        or toks[6] not in ('true', 'false') or toks[7] not in ('true', 'false')):
                    raise SystemExit(f'{path}:{lineno}: unexpected atlas entry: {line.strip()}')
                # width/height stay verbatim too: retail has fractional logical sizes (e.g. 37.5)
                current[m.group(1)] = Atlas(m.group(1), toks[0], toks[1], tuple(toks[2:6]),
                                            toks[6], toks[7], toks[8].strip('"'))
                continue
            if line.startswith('\t}'):
                current = None
    return sheets


# ------------------------------------------------------------------------------------------------ DXT decoding

def _expand565(q):
    q = q.astype(np.int32)
    r, g, b = (q >> 11) & 31, (q >> 5) & 63, q & 31
    return np.stack([(r << 3) | (r >> 2), (g << 2) | (g >> 4), (b << 3) | (b >> 2)], -1)


def _color_palette(q0, q1, force4):
    """(n,4,3) RGB and (n,4) alpha palettes. force4: DXT3/5 colour blocks are always 4-colour."""
    p0, p1 = _expand565(q0), _expand565(q1)
    four = np.ones(q0.shape, bool) if force4 else (q0 > q1)
    f = four[:, None]
    p2 = np.where(f, (2 * p0 + p1 + 1) // 3, (p0 + p1 + 1) // 2)
    p3 = np.where(f, (p0 + 2 * p1 + 1) // 3, 0)
    rgb = np.stack([p0, p1, p2, p3], 1)
    opaque = np.full(q0.shape, 255)
    alpha = np.stack([opaque, opaque, opaque, np.where(four, 255, 0)], 1)
    return rgb, alpha


def _unpack_color(blk):
    q0 = blk[:, 0].astype(np.int32) | (blk[:, 1].astype(np.int32) << 8)
    q1 = blk[:, 2].astype(np.int32) | (blk[:, 3].astype(np.int32) << 8)
    bits = (blk[:, 4].astype(np.uint32) | (blk[:, 5].astype(np.uint32) << 8)
            | (blk[:, 6].astype(np.uint32) << 16) | (blk[:, 7].astype(np.uint32) << 24))
    idx = ((bits[:, None] >> (2 * np.arange(16, dtype=np.uint32))[None]) & 3).astype(np.int64)
    return q0, q1, idx


def _unpack_alpha(blk):
    bits = np.zeros(len(blk), np.uint64)
    for i in range(6):
        bits |= blk[:, 2 + i].astype(np.uint64) << np.uint64(8 * i)
    idx = ((bits[:, None] >> (np.uint64(3) * np.arange(16, dtype=np.uint64))[None]) & np.uint64(7)).astype(np.int64)
    return blk[:, 0].astype(np.int32), blk[:, 1].astype(np.int32), idx


def _alpha_palette(a0, a1):
    a0 = np.asarray(a0, np.int32)
    a1 = np.asarray(a1, np.int32)
    eight = a0 > a1
    pal = np.zeros((len(a0), 8), np.int32)
    pal[:, 0], pal[:, 1] = a0, a1
    for i in range(1, 7):
        pal[:, 1 + i] = ((7 - i) * a0 + i * a1 + 3) // 7
    for i in range(1, 5):
        pal[:, 1 + i] = np.where(eight, pal[:, 1 + i], ((5 - i) * a0 + i * a1 + 2) // 5)
    pal[:, 6] = np.where(eight, pal[:, 6], 0)
    pal[:, 7] = np.where(eight, pal[:, 7], 255)
    return pal


def _from_blocks(px, w, h):
    bw, bh = (w + 3) // 4, (h + 3) // 4
    c = px.shape[-1]
    img = px.reshape(bh, bw, 4, 4, c).transpose(0, 2, 1, 3, 4).reshape(bh * 4, bw * 4, c)
    return img[:h, :w]


def dxt_size(w, h, fmt):
    return max(1, (w + 3) // 4) * max(1, (h + 3) // 4) * (8 if fmt == 'DXT1' else 16)


def decode_dxt(data, w, h, fmt):
    """Decode one DXT1/DXT3/DXT5 level to (h, w, 4) uint8 RGBA."""
    n = max(1, (w + 3) // 4) * max(1, (h + 3) // 4)
    bs = 8 if fmt == 'DXT1' else 16
    if len(data) < n * bs:
        raise ValueError(f'{fmt} level {w}x{h} needs {n * bs} bytes, got {len(data)}')
    blk = np.frombuffer(data, np.uint8, count=n * bs).reshape(n, bs)
    if fmt == 'DXT1':
        q0, q1, idx = _unpack_color(blk)
        pal, pal_a = _color_palette(q0, q1, force4=False)
        alpha = np.take_along_axis(pal_a, idx, 1)
    else:
        q0, q1, idx = _unpack_color(blk[:, 8:])
        pal, _ = _color_palette(q0, q1, force4=True)
        if fmt == 'DXT5':
            a0, a1, aidx = _unpack_alpha(blk[:, :8])
            alpha = np.take_along_axis(_alpha_palette(a0, a1), aidx, 1)
        else:   # DXT3: explicit 4-bit alpha
            nib = np.stack([blk[:, i // 2] >> (4 * (i % 2)) & 15 for i in range(16)], 1)
            alpha = nib.astype(np.int32) * 17
    rgb = np.take_along_axis(pal, idx[..., None].repeat(3, 2), 1)
    px = np.concatenate([rgb, alpha[..., None]], -1).astype(np.uint8)
    return _from_blocks(px, w, h)


# ------------------------------------------------------------------------------------------------ BLP reading

class BlpInfo:
    def __init__(self, blob):
        if len(blob) < HEADER_SIZE or blob[:4] != b'BLP2':
            raise ValueError('not a BLP2 file')
        self.btype = struct.unpack_from('<I', blob, 4)[0]
        self.enc, self.alpha_depth, self.alpha_type, self.has_mips = blob[8], blob[9], blob[10], blob[11]
        self.width, self.height = struct.unpack_from('<II', blob, 12)
        self.offsets = struct.unpack_from('<16I', blob, 20)
        self.sizes = struct.unpack_from('<16I', blob, 84)
        n = 0
        while n < 16 and self.sizes[n]:
            n += 1
        self.mip_count = n
        if self.btype != 1:
            raise ValueError(f'unsupported BLP2 type {self.btype}')

    @property
    def fmt(self):
        if self.enc == 3:
            return 'RAW'
        if self.enc == 2 and self.alpha_type in (0, 1, 7):
            return {0: 'DXT1', 1: 'DXT3', 7: 'DXT5'}[self.alpha_type]
        raise ValueError(f'unsupported BLP colorEncoding {self.enc} / alphaType {self.alpha_type}')

    def level_bytes(self, blob, level):
        off, size = self.offsets[level], self.sizes[level]
        if off + size > len(blob):
            raise ValueError(f'mip {level} runs past end of file')
        return blob[off:off + size]


def decode_blp_mip0(blob):
    info = BlpInfo(blob)
    w, h = info.width, info.height
    data = info.level_bytes(blob, 0)
    if info.fmt == 'RAW':
        if len(data) < w * h * 4:
            raise ValueError('raw BGRA mip 0 is truncated')
        rgba = np.frombuffer(data, np.uint8, count=w * h * 4).reshape(h, w, 4)[..., [2, 1, 0, 3]].copy()
    else:
        rgba = decode_dxt(data, w, h, info.fmt)
    if info.alpha_depth == 0:
        rgba[..., 3] = 255
    return info, rgba


# ------------------------------------------------------------------------------------------------ DXT encoding

def _quant565(e):
    e = np.clip(e, 0, 255)
    r = np.rint(e[..., 0] * (31 / 255)).astype(np.int32)
    g = np.rint(e[..., 1] * (63 / 255)).astype(np.int32)
    b = np.rint(e[..., 2] * (31 / 255)).astype(np.int32)
    return (r << 11) | (g << 5) | b


def _normalise4(q0, q1, idx):
    """Unambiguous 4-colour block: q0 > q1, or q0 == q1 with every index 0 (every slot equals p0)."""
    swap = q0 < q1
    q0n, q1n = np.where(swap, q1, q0), np.where(swap, q0, q1)
    idx = np.where(swap[:, None], np.array([1, 0, 3, 2])[idx], idx)
    idx = np.where((q0n == q1n)[:, None], 0, idx)
    return q0n, q1n, idx


_T4 = np.array([0.0, 1.0, 1 / 3, 2 / 3], np.float32)          # palette slot -> weight of endpoint 1
_T8 = np.array([0, 1, 1 / 7, 2 / 7, 3 / 7, 4 / 7, 5 / 7, 6 / 7], np.float32)


def _color_error(x, w, q0, q1, idx):
    pal, _ = _color_palette(q0, q1, force4=True)
    got = np.take_along_axis(pal, idx[..., None].repeat(3, 2), 1).astype(np.float32)
    return (((x - got) ** 2).sum(-1) * w).sum(1)


def _encode_color(x, w, valid, iters=3):
    """Weighted PCA range fit + least-squares refinement, 4-colour mode. x (n,16,3) float32, w (n,16)."""
    n = len(x)
    wn = w / w.sum(1, keepdims=True)
    mu = (wn[..., None] * x).sum(1)
    d = x - mu[:, None]
    cov = np.einsum('nk,nki,nkj->nij', wn, d, d)
    diag = np.stack([cov[:, 0, 0], cov[:, 1, 1], cov[:, 2, 2]], 1)
    v = np.take_along_axis(cov, diag.argmax(1)[:, None, None].repeat(3, 1), 2)[..., 0]
    for _ in range(8):
        v = np.einsum('nij,nj->ni', cov, v)
        v /= np.linalg.norm(v, axis=1, keepdims=True) + 1e-12
    t = np.einsum('nki,ni->nk', d, v)
    e0 = mu + v * np.where(valid, t, -1e9).max(1)[:, None]
    e1 = mu + v * np.where(valid, t, 1e9).min(1)[:, None]
    best_err = np.full(n, np.inf)
    best = (np.zeros(n, np.int32), np.zeros(n, np.int32), np.zeros((n, 16), np.int64))
    for it in range(iters + 1):
        q0, q1, _ = _normalise4(_quant565(e0), _quant565(e1), np.zeros((n, 16), np.int64))
        pal, _ = _color_palette(q0, q1, force4=True)
        dist = ((x[:, :, None, :] - pal[:, None, :, :].astype(np.float32)) ** 2).sum(-1)
        dist[q0 == q1, :, 1:] = np.inf                        # equal endpoints: slot 0 only
        idx = dist.argmin(2)
        err = (np.take_along_axis(dist, idx[..., None], 2)[..., 0] * w).sum(1)
        better = err < best_err
        best_err = np.where(better, err, best_err)
        best = (np.where(better, q0, best[0]), np.where(better, q1, best[1]), np.where(better[:, None], idx, best[2]))
        if it == iters:
            break
        tt = _T4[idx]
        a00, a01, a11 = (w * (1 - tt) ** 2).sum(1), (w * (1 - tt) * tt).sum(1), (w * tt ** 2).sum(1)
        b0 = ((w * (1 - tt))[..., None] * x).sum(1)
        b1 = ((w * tt)[..., None] * x).sum(1)
        det = a00 * a11 - a01 ** 2
        ok = np.abs(det) > 1e-6
        sd = np.where(ok, det, 1.0)[:, None]
        e0 = np.where(ok[:, None], (a11[:, None] * b0 - a01[:, None] * b1) / sd, _expand565(q0)).astype(np.float32)
        e1 = np.where(ok[:, None], (a00[:, None] * b1 - a01[:, None] * b0) / sd, _expand565(q1)).astype(np.float32)
    return best[0], best[1], best[2], best_err


def _alpha_fit(a, pal):
    dist = (a[:, :, None] - pal[:, None, :]) ** 2
    idx = dist.argmin(2)
    return idx, np.take_along_axis(dist, idx[..., None], 2)[..., 0].sum(1)


def _encode_alpha(a, iters=2):
    """BC4-style: 8-value mode with least-squares refinement vs 6-value mode with explicit 0/255."""
    n = len(a)
    ai = a.astype(np.int32)
    cands = []
    e0, e1 = ai.max(1).astype(np.float32), ai.min(1).astype(np.float32)
    for it in range(iters + 1):
        r0 = np.clip(np.rint(e0), 0, 255).astype(np.int32)
        r1 = np.clip(np.rint(e1), 0, 255).astype(np.int32)
        hi, lo = np.maximum(r0, r1), np.minimum(r0, r1)
        lo = np.where(hi == lo, np.maximum(hi - 1, 0), lo)     # 8-value mode needs a0 > a1
        hi = np.where(hi == lo, hi + 1, hi)                    # only when hi == lo == 0
        idx, err = _alpha_fit(ai, _alpha_palette(hi, lo))
        cands.append((err, hi, lo, idx))
        if it == iters:
            break
        tt = _T8[idx]
        a00, a01, a11 = ((1 - tt) ** 2).sum(1), ((1 - tt) * tt).sum(1), (tt ** 2).sum(1)
        b0, b1 = ((1 - tt) * ai).sum(1), (tt * ai).sum(1)
        det = a00 * a11 - a01 ** 2
        ok = np.abs(det) > 1e-6
        sd = np.where(ok, det, 1.0)
        e0 = np.where(ok, (a11 * b0 - a01 * b1) / sd, hi)
        e1 = np.where(ok, (a00 * b1 - a01 * b0) / sd, lo)
    inner = (ai > 0) & (ai < 255)
    has = inner.any(1)
    bmin = np.where(has, np.where(inner, ai, 256).min(1), 0)
    bmax = np.where(has, np.where(inner, ai, -1).max(1), 0)
    idx, err = _alpha_fit(ai, _alpha_palette(bmin, bmax))
    cands.append((err, bmin, bmax, idx))
    errs = np.stack([c[0] for c in cands], 1)
    k = errs.argmin(1)
    rows = np.arange(n)
    return (np.stack([c[1] for c in cands], 1)[rows, k], np.stack([c[2] for c in cands], 1)[rows, k],
            np.stack([c[3] for c in cands], 1)[rows, k], errs[rows, k])


def _pack_color(q0, q1, idx):
    out = np.zeros((len(q0), 8), np.uint8)
    out[:, 0], out[:, 1] = q0 & 255, (q0 >> 8) & 255
    out[:, 2], out[:, 3] = q1 & 255, (q1 >> 8) & 255
    bits = (idx.astype(np.uint64) << (2 * np.arange(16, dtype=np.uint64))[None]).sum(1, dtype=np.uint64)
    for i in range(4):
        out[:, 4 + i] = (bits >> np.uint64(8 * i)) & np.uint64(255)
    return out


def _pack_alpha(a0, a1, idx):
    out = np.zeros((len(a0), 8), np.uint8)
    out[:, 0], out[:, 1] = a0, a1
    bits = (idx.astype(np.uint64) << (np.uint64(3) * np.arange(16, dtype=np.uint64))[None]).sum(1, dtype=np.uint64)
    for i in range(6):
        out[:, 2 + i] = (bits >> np.uint64(8 * i)) & np.uint64(255)
    return out


def _pillow_blocks(rgba, fmt):
    """Pillow's own DDS encoder as a second candidate; None when this Pillow cannot write DXT."""
    try:
        im = Image.fromarray(np.ascontiguousarray(rgba if fmt == 'DXT5' else rgba[..., :3]),
                             'RGBA' if fmt == 'DXT5' else 'RGB')
        buf = io.BytesIO()
        im.save(buf, format='DDS', pixel_format=fmt)
        data = buf.getvalue()[128:]
    except Exception:  # noqa: BLE001 - any failure just drops the candidate
        return None
    bs = 8 if fmt == 'DXT1' else 16
    n = (rgba.shape[0] // 4) * (rgba.shape[1] // 4)
    return np.frombuffer(data, np.uint8).reshape(-1, bs) if len(data) == n * bs else None


def encode_dxt(rgba, fmt):
    """Encode one (h, w, 4) uint8 level as DXT1 (opaque, 4-colour) or DXT5."""
    h, w = rgba.shape[:2]
    ph, pw = (h + 3) // 4 * 4, (w + 3) // 4 * 4
    if (ph, pw) != (h, w):
        rgba = np.pad(rgba, ((0, ph - h), (0, pw - w), (0, 0)), mode='edge')
    blocks = rgba.reshape(ph // 4, 4, pw // 4, 4, 4).transpose(0, 2, 1, 3, 4).reshape(-1, 16, 4)
    pil = _pillow_blocks(rgba, fmt)
    out = []
    for s in range(0, len(blocks), CHUNK):
        b = blocks[s:s + CHUNK]
        x = b[..., :3].astype(np.float32)
        a = b[..., 3]
        w8 = np.maximum(a.astype(np.float32) / 255.0, WEIGHT_FLOOR)
        vis = a > 0
        valid = np.where(vis.any(1)[:, None], vis, True)
        q0, q1, idx, err = _encode_color(x, w8, valid)
        if pil is not None:
            pc = pil[s:s + CHUNK] if fmt == 'DXT1' else pil[s:s + CHUNK, 8:]
            pq0, pq1, pidx = _normalise4(*_unpack_color(pc))
            use = _color_error(x, w8, pq0, pq1, pidx) < err
            q0, q1 = np.where(use, pq0, q0), np.where(use, pq1, q1)
            idx = np.where(use[:, None], pidx, idx)
        color = _pack_color(q0, q1, idx)
        if fmt == 'DXT1':
            out.append(color)
            continue
        a0, a1, aidx, aerr = _encode_alpha(a)
        if pil is not None:
            pa0, pa1, paidx = _unpack_alpha(pil[s:s + CHUNK, :8])
            perr = ((np.take_along_axis(_alpha_palette(pa0, pa1), paidx, 1) - a.astype(np.int32)) ** 2).sum(1)
            use = perr < aerr
            a0, a1 = np.where(use, pa0, a0), np.where(use, pa1, a1)
            aidx = np.where(use[:, None], paidx, aidx)
        out.append(np.concatenate([_pack_alpha(a0, a1, aidx), color], 1))
    return np.concatenate(out).tobytes()


def normalise_dxt5_level(data):
    """Rewrite DXT5 colour blocks into unambiguous 4-colour form; lossless under DXT5 decoding rules."""
    blk = np.frombuffer(data, np.uint8).reshape(-1, 16).copy()
    q0, q1, idx = _normalise4(*_unpack_color(blk[:, 8:]))
    blk[:, 8:] = _pack_color(q0, q1, idx)
    return blk.tobytes()


def downsample(rgba):
    """2x2 box filter in premultiplied alpha (a 1-texel axis stays 1)."""
    h, w = rgba.shape[:2]
    nh, nw = max(1, h // 2), max(1, w // 2)
    f = rgba.astype(np.float32).reshape(nh, h // nh, nw, w // nw, 4)
    a = f[..., 3:4] / 255.0
    pm = (f[..., :3] * a).mean((1, 3))
    am = a.mean((1, 3))
    rgb = np.where(am > 1e-6, pm / np.maximum(am, 1e-6), f[..., :3].mean((1, 3)))
    return np.clip(np.rint(np.concatenate([rgb, am * 255.0], -1)), 0, 255).astype(np.uint8)


def build_blp(width, height, fmt, levels):
    alpha_depth, alpha_type = (8, 7) if fmt == 'DXT5' else (0, 0)
    hdr = bytearray(b'BLP2') + struct.pack('<I', 1)
    hdr += bytes([2, alpha_depth, alpha_type, 1 if len(levels) > 1 else 0])
    hdr += struct.pack('<II', width, height)
    offsets, sizes, pos = [], [], HEADER_SIZE + PALETTE_SIZE
    for lv in levels:
        offsets.append(pos)
        sizes.append(len(lv))
        pos += len(lv)
    pad = [0] * (16 - len(levels))
    hdr += struct.pack('<16I', *(offsets + pad)) + struct.pack('<16I', *(sizes + pad))
    return bytes(hdr) + bytes(PALETTE_SIZE) + b''.join(levels)


def chain_length(w, h):
    return int(math.log2(max(w, h))) + 1


# ------------------------------------------------------------------------------------------------ analysis

def analyse(rgba, atlases, alpha_scope):
    """Atlas-coverage layout check + DXT1/DXT5 decision."""
    h, w = rgba.shape[:2]
    a = rgba[..., 3]
    vis = a > 0
    apron = np.zeros((h, w), bool)
    empty = []
    for at in atlases.values():
        left, right, top, bottom = at.uv_floats()
        x0, x1 = (min(w, max(0, int(round(v * w)))) for v in (left, right))
        y0, y1 = (min(h, max(0, int(round(v * h)))) for v in (top, bottom))
        apron[max(0, y0 - 1):y1 + 1, max(0, x0 - 1):x1 + 1] = True   # rect + its 1-texel filter apron
        if not vis[y0:y1, x0:x1].any():
            empty.append(at.name)
    scope = apron if alpha_scope == 'atlas' and apron.any() else np.ones_like(apron)
    translucent = a[scope] < ALPHA_CUTOFF
    frac = float(translucent.mean()) if translucent.size else 0.0
    return {
        'format': 'DXT5' if frac > ALPHA_FRACTION else 'DXT1',
        'alpha_lt250_fraction': round(frac, 6),
        'alpha_lt250_fraction_sheet': round(float((a < ALPHA_CUTOFF).mean()), 6),
        'alpha_lt250_texels_in_scope': int(translucent.sum()),
        'empty_rects': sorted(empty),
        'visible_outside_rects': int(np.count_nonzero(vis & ~apron)),
        'visible_total': int(vis.sum()),
    }


# ------------------------------------------------------------------------------------------------ workers

def _sha256(data):
    return hashlib.sha256(data).hexdigest()


def convert_sheet(job):
    try:
        return _convert_sheet(job)
    except Exception as exc:  # noqa: BLE001 - reported per sheet by main()
        return dict(key=job['key'], error=f'{type(exc).__name__}: {exc}')


def _convert_sheet(job):
    """Worker: load source, decide format, encode (unless dry run). Returns a result dict."""
    t0 = time.time()
    with open(job['src'], 'rb') as f:
        src_blob = f.read()
    info, rgba = decode_blp_mip0(src_blob)
    ana = analyse(rgba, job['atlases'], job['alpha_scope'])
    fmt = ana['format']
    w, h = info.width, info.height
    src_chain = info.has_mips != 0 and info.mip_count > 1
    want_chain = src_chain if job['mips'] == 'auto' else job['mips'] == 'on'
    if want_chain and (w & (w - 1) or h & (h - 1)):
        raise ValueError(f'{w}x{h} is not a power of two; cannot build a mip chain')
    nlev = chain_length(w, h) if want_chain else 1
    passthrough = (info.fmt == fmt and (fmt == 'DXT5' or info.alpha_depth == 0)
                   and info.mip_count >= nlev
                   and all(info.sizes[i] == dxt_size(max(1, w >> i), max(1, h >> i), fmt) for i in range(nlev)))
    res = dict(key=job['key'], format=fmt, width=w, height=h, mips=nlev, analysis=ana,
               src_sha256=_sha256(src_blob), src_enc=info.enc, src_has_mips=info.has_mips,
               src_mip_count=info.mip_count, mode='passthrough' if passthrough else 'encoded')
    sizes = [dxt_size(max(1, w >> i), max(1, h >> i), fmt) for i in range(nlev)]
    res['bytes'] = HEADER_SIZE + PALETTE_SIZE + sum(sizes)
    if job['dry_run']:
        res['seconds'] = round(time.time() - t0, 2)
        return res
    if passthrough:
        levels = [info.level_bytes(src_blob, i) for i in range(nlev)]
        if fmt == 'DXT5':
            levels = [normalise_dxt5_level(lv) for lv in levels]
    else:
        levels, cur = [], rgba
        for i in range(nlev):
            if i:
                cur = downsample(cur)
            levels.append(encode_dxt(cur, fmt))
    blob = build_blp(w, h, fmt, levels)
    assert len(blob) == res['bytes']
    res['blob'] = blob
    res['sha256'] = _sha256(blob)
    res['seconds'] = round(time.time() - t0, 2)
    return res


def _psnr(a, b):
    if a.size == 0:
        return None
    mse = float(np.mean((a.astype(np.float64) - b.astype(np.float64)) ** 2))
    return math.inf if mse == 0 else 10 * math.log10(255.0 * 255.0 / mse)


def _dds_wrap(data, w, h, fmt):
    pf = struct.pack('<II4sIIIII', 32, 0x4, fmt.encode('ascii'), 0, 0, 0, 0, 0)
    body = struct.pack('<IIIIIII', 124, 0x1 | 0x2 | 0x4 | 0x1000 | 0x80000, h, w, len(data), 0, 0)
    body += bytes(44) + pf + struct.pack('<IIIII', 0x1000, 0, 0, 0, 0)
    return b'DDS ' + body + data


def verify_output(job):
    try:
        return _verify_output(job)
    except Exception as exc:  # noqa: BLE001 - reported per sheet by main()
        return dict(key=job['key'], problems=[f'verification crashed: {type(exc).__name__}: {exc}'])


def _verify_output(job):
    """Worker: read the written file back from disk, check the header, decode mip 0, compare with the source."""
    problems = []
    with open(job['out'], 'rb') as f:
        blob = f.read()
    fmt, w, h, nlev = job['format'], job['width'], job['height'], job['mips']
    try:
        info = BlpInfo(blob)
    except ValueError as exc:
        return dict(key=job['key'], problems=[str(exc)])
    want = {
        'type': (info.btype, 1), 'byte8 colorEncoding': (blob[8], 2),
        'byte9 alphaDepth': (blob[9], 8 if fmt == 'DXT5' else 0),
        'byte10 alphaType': (blob[10], 7 if fmt == 'DXT5' else 0),
        'byte11 hasMips': (blob[11], 1 if nlev > 1 else 0), 'width': (info.width, w), 'height': (info.height, h),
        'mip count': (info.mip_count, nlev),
    }
    problems += [f'{k} is {got}, expected {exp}' for k, (got, exp) in want.items() if got != exp]
    if blob[11] not in (0, 1):
        problems.append(f'hasMips byte is {blob[11]} (3.3.5 accepts 0/1 only)')
    pos = HEADER_SIZE + PALETTE_SIZE
    for i in range(16):
        exp_size = dxt_size(max(1, w >> i), max(1, h >> i), fmt) if i < nlev else 0
        exp_off = pos if i < nlev else 0
        if (info.offsets[i], info.sizes[i]) != (exp_off, exp_size):
            problems.append(f'mip {i}: offset/size {info.offsets[i]}/{info.sizes[i]}, expected {exp_off}/{exp_size}')
        pos += exp_size if i < nlev else 0
    if len(blob) != pos:
        problems.append(f'file is {len(blob)} bytes, mip table ends at {pos}')
    if blob[HEADER_SIZE:HEADER_SIZE + PALETTE_SIZE] != bytes(PALETTE_SIZE):
        problems.append('palette block is not zeroed')
    if problems:
        return dict(key=job['key'], problems=problems)
    mip0 = info.level_bytes(blob, 0)
    dec = decode_dxt(mip0, w, h, fmt)
    with open(job['src'], 'rb') as f:
        _, src = decode_blp_mip0(f.read())
    vis = src[..., 3] > 0
    stats = dict(
        byte8=blob[8], byte11=blob[11],
        psnr_rgb_visible=_psnr(dec[..., :3][vis], src[..., :3][vis]),
        psnr_rgb_all=_psnr(dec[..., :3], src[..., :3]),
        psnr_alpha=_psnr(dec[..., 3], src[..., 3]) if fmt == 'DXT5' else None,
    )
    ch = slice(0, 4) if fmt == 'DXT5' else slice(0, 3)
    # independent decoder 1: Pillow's C BCn decoder on the same block data
    try:
        with Image.open(io.BytesIO(_dds_wrap(mip0, w, h, fmt))) as im:
            ref = np.asarray(im.convert('RGBA'))
        stats['dds_maxdiff'] = int(np.abs(ref[..., ch].astype(np.int32) - dec[..., ch]).max())
        if stats['dds_maxdiff'] > DDS_TOL:
            problems.append(f"Pillow DDS decoder differs by {stats['dds_maxdiff']} (> {DDS_TOL})")
    except Exception as exc:  # noqa: BLE001
        problems.append(f'Pillow DDS decode failed: {exc}')
    # independent decoder 2: Pillow's BLP2 reader on the file itself (header + container end to end)
    try:
        with Image.open(io.BytesIO(blob)) as im:
            if im.format != 'BLP' or im.size != (w, h):
                problems.append(f'Pillow BLP reader sees {im.format} {im.size}')
            ref = np.asarray(im.convert('RGBA'))
        drgb = int(np.abs(ref[..., :3].astype(np.int32) - dec[..., :3]).max())
        da = int(np.abs(ref[..., 3].astype(np.int32) - dec[..., 3]).max()) if fmt == 'DXT5' else 0
        stats['blp_maxdiff'] = max(drgb, da)
        if drgb > BLP_TOL_RGB or da > BLP_TOL_A:
            problems.append(f'Pillow BLP reader differs by rgb {drgb} / alpha {da}')
    except Exception as exc:  # noqa: BLE001
        problems.append(f'Pillow BLP read failed: {exc}')
    stats['sha256'] = _sha256(blob)
    return dict(key=job['key'], problems=problems, **stats)


# ------------------------------------------------------------------------------------------------ files & paths

def find_ci(root, parts):
    """Resolve a relative path case-insensitively below root; None when any part is missing."""
    cur = root
    for part in parts:
        try:
            entries = os.listdir(cur)
        except OSError:
            return None
        hit = [e for e in entries if e.lower() == part.lower()]
        if not hit:
            return None
        cur = os.path.join(cur, sorted(hit)[0])
    return cur


def source_path(src_root, key):
    parts = key.split('/')
    if parts[0].lower() == 'interface':
        parts = parts[1:]
    parts[-1] += '.blp'
    return find_ci(src_root, parts) or find_ci(src_root, ['Interface'] + parts)


def write_atomic(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + '.tmp-convert_art'
    with open(tmp, 'wb') as f:
        f.write(data)
    os.replace(tmp, path)


def read_bytes(path):
    with open(path, 'rb') as f:
        return f.read()


def load_manifest(path):
    if not os.path.exists(path):
        return {'outputs': {}}
    with open(path, encoding='utf-8') as f:
        data = json.load(f)
    data.setdefault('outputs', {})
    return data


def _jsonable(v):
    if isinstance(v, float):
        return 'inf' if math.isinf(v) else round(v, 2)
    return v


def lua_path(key):
    return key.replace('/', '\\\\')


def render_lua(shipped, atlas_info):
    """shipped: {sheet key: (width, height)}; atlas_info: parsed AtlasInfo.lua."""
    keys = sorted(shipped, key=lambda k: (k.lower(), k))
    lines = [LUA_HEADER, 'local _, ns = ...', '',
             '-- Pixel size of each shipped sheet (runtime path without extension).',
             'ns.AtlasSheets = {']
    lines += [f'    ["{lua_path(k)}"] = {{ {shipped[k][0]}, {shipped[k][1]} }},' for k in keys]
    lines += ['}', '',
              '-- atlas = { file, width, height, left, right, top, bottom, tilesH, tilesV } (retail values verbatim;',
              '-- width/height are the logical UI size, which can be smaller than the texel rect on hi-res art).',
              'ns.AtlasInfo = {']
    for k in keys:
        names = sorted(atlas_info[k], key=lambda n: (n.lower(), n))
        lines.append(f'    -- {k}: {len(names)} atlases')
        for n in names:
            a = atlas_info[k][n]
            lines.append(f'    ["{n}"] = {{ "{lua_path(k)}", {a.width}, {a.height}, {", ".join(a.uv)}, '
                         f'{a.tiles_h}, {a.tiles_v} }},')
    lines += ['}', '',
              '-- Retail sheet each atlas was taken from (Helix/AtlasInfo.lua key), for coverage audits.',
              'ns.AtlasSourceSheet = {']
    for k in keys:
        for n in sorted(atlas_info[k], key=lambda n: (n.lower(), n)):
            lines.append(f'    ["{n}"] = "{k}",')
    lines += ['}', '']
    return '\n'.join(lines).encode('utf-8')


# ------------------------------------------------------------------------------------------------ main

def resolve_sheets(patterns, atlas_info):
    if not patterns:
        return list(DEFAULT_SHEETS), []
    chosen, unknown = [], []
    lower_keys = {k.lower(): k for k in atlas_info}
    for pat in patterns:
        p = pat.replace('\\', '/')
        is_glob = any(c in p for c in '*?[')
        field = (lambda k: k.lower()) if '/' in p else (lambda k: k.rsplit('/', 1)[-1].lower())
        if not is_glob:
            hits = [k for k in atlas_info if field(k) == p.lower()]
            if not hits and p.lower() in lower_keys:
                hits = [lower_keys[p.lower()]]
        else:
            hits = [k for k in atlas_info if fnmatch.fnmatchcase(field(k), p.lower())
                    and not any(fnmatch.fnmatchcase(k.lower(), g.lower()) for g in SKIP_GLOBS)]
        if not hits:
            unknown.append(pat)
        chosen += [k for k in sorted(hits) if k not in chosen]
    return chosen, unknown


def fmt_psnr(v):
    if v is None:
        return '-'
    if v == 'inf' or (isinstance(v, float) and math.isinf(v)):
        return 'exact'
    return f'{v:.2f}'


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--sheets', nargs='+', metavar='SHEET',
                    help='retail sheet keys (Interface/TalentFrame/Talents) or basenames (Talents); globs allowed. '
                         'Default: the full DC-Talents set.')
    ap.add_argument('--dry-run', action='store_true', help='analyse and report, write nothing')
    ap.add_argument('--verify-only', action='store_true', help='re-verify already written outputs, write nothing')
    ap.add_argument('--src-root', default=DEFAULT_SRC_ROOT)
    ap.add_argument('--atlas', default=DEFAULT_ATLAS)
    ap.add_argument('--stage-root', default=DEFAULT_STAGE)
    ap.add_argument('--lua-out', default=DEFAULT_LUA)
    ap.add_argument('--manifest', default=DEFAULT_MANIFEST)
    ap.add_argument('--alpha-scope', choices=('atlas', 'sheet'), default='atlas',
                    help='measure translucency over the atlas rects (+1 texel apron) or the whole sheet')
    ap.add_argument('--mips', choices=('auto', 'on', 'off'), default='auto',
                    help='auto mirrors the source: full chain to 1x1 when it had one, else mip 0 only')
    ap.add_argument('--jobs', type=int, default=min(8, os.cpu_count() or 1))
    args = ap.parse_args(argv)

    atlas_info = parse_atlas_info(args.atlas)
    keys, unknown = resolve_sheets(args.sheets, atlas_info)
    manifest = load_manifest(args.manifest)
    owned = {rel.lower(): (rel, e) for rel, e in manifest['outputs'].items()}
    stage = os.path.abspath(args.stage_root)

    missing, collisions, jobs = [], [], []
    for key in keys:
        if key not in atlas_info:
            missing.append(f'{key}: not in {os.path.basename(args.atlas)}')
            continue
        src = source_path(args.src_root, key)
        if not src:
            missing.append(f'{key}: no source BLP under {args.src_root}')
            continue
        parts = key.split('/')
        real_dir = find_ci(stage, parts[:-1])
        out_dir = real_dir or os.path.join(stage, *parts[:-1])
        existing = find_ci(out_dir, [IN_PLACE.get(key, parts[-1] + '.blp')]) if real_dir else None
        name = os.path.basename(existing) if existing else IN_PLACE.get(key, parts[-1] + '.blp')
        out = os.path.join(out_dir, name)
        rel = os.path.relpath(out, stage).replace('\\', '/')
        state, backup = 'new', None
        if existing:
            cur_sha = _sha256(read_bytes(existing))
            prev = owned.get(rel.lower())
            if prev and prev[1].get('sha256') == cur_sha:
                state = 'ours'
            elif key in IN_PLACE:
                try:
                    orig = BlpInfo(read_bytes(existing))
                    orig_desc = f'enc {orig.enc}, {orig.width}x{orig.height}'
                except ValueError as exc:
                    orig, orig_desc = None, str(exc)
                backup = os.path.join(stage, BACKUP_DIR, *rel.split('/'))
                if orig is None or orig.enc != 3:
                    state = 'COLLISION'
                    collisions.append(f'{rel}: in-place replacement is only authorised for colorEncoding 3 '
                                      f'originals, found {orig_desc}')
                elif os.path.exists(backup) and _sha256(read_bytes(backup)) != cur_sha:
                    state = 'COLLISION'
                    collisions.append(f'{rel}: backup {os.path.relpath(backup, stage)} exists with different bytes')
                else:
                    state = f'replace ({orig_desc}) -> backup'
            else:
                state = 'COLLISION'
                collisions.append(f'{rel}: already exists as {os.path.relpath(existing, stage)} '
                                  f'and was not written by this tool')
        jobs.append(dict(key=key, src=src, out=out, rel=rel, state=state, backup=backup,
                         atlases=atlas_info[key], alpha_scope=args.alpha_scope, mips=args.mips,
                         dry_run=args.dry_run or args.verify_only))

    lua_existing = os.path.exists(args.lua_out)
    if lua_existing:
        with open(args.lua_out, encoding='utf-8', errors='replace') as f:
            first = f.readline().rstrip('\r\n')
        if first != LUA_HEADER:
            collisions.append(f'{args.lua_out}: exists and is not generated by this tool')

    # duplicate atlas names across everything the Lua table will hold
    lua_keys = {j['key'] for j in jobs} | {e['sheet'] for e in manifest['outputs'].values() if e.get('sheet')}
    seen = {}
    for k in sorted(k for k in lua_keys if k in atlas_info):
        for n in atlas_info[k]:
            if n in seen:
                collisions.append(f'atlas "{n}" exists in both {seen[n]} and {k}')
            seen[n] = k

    print(f'convert_art: {len(jobs)} sheet(s), stage {stage}')
    for j in jobs:
        print(f'  {j["key"]:58s} <- {os.path.relpath(j["src"], args.src_root)}  [{j["state"]}]')
    for m in missing:
        print(f'  MISSING {m}')
    for u in unknown:
        print(f'  UNKNOWN --sheets pattern: {u}')
    if collisions:
        print('\nSTOP - name collisions, nothing was written:')
        for c in collisions:
            print(f'  COLLISION {c}')
        return 3

    if args.verify_only:
        jobs = [j for j in jobs if j['state'] == 'ours']
        if not jobs:
            print('nothing to verify (no outputs of this tool in the stage tree)')
            return 1

    results = {}
    t0 = time.time()
    with cf.ProcessPoolExecutor(max_workers=max(1, args.jobs)) as pool:
        for res in pool.map(convert_sheet, jobs):
            results[res['key']] = res
    print(f'\nanalysed{"" if args.dry_run or args.verify_only else " + encoded"} in {time.time() - t0:.1f}s')
    errors = [(k, r['error']) for k, r in results.items() if 'error' in r]
    if errors:
        print('STOP - conversion failed, nothing was written:')
        for k, e in errors:
            print(f'  ERROR {k}: {e}')
        return 5

    if args.dry_run:
        total = 0
        for j in jobs:
            r = results[j['key']]
            a = r['analysis']
            total += r['bytes']
            print(f'  {j["rel"]:62s} {r["width"]:>4}x{r["height"]:<4} {r["format"]} mips {r["mips"]} '
                  f'{r["bytes"]:>9} B  {r["mode"]:11s} translucent {a["alpha_lt250_fraction"]:.4f} '
                  f'(sheet {a["alpha_lt250_fraction_sheet"]:.4f})  empty rects {len(a["empty_rects"])}')
        print(f'  total {total} bytes ({total / 1048576:.1f} MiB)')
        return 2 if missing or unknown else 0

    written = []
    if not args.verify_only:
        for j in jobs:
            r = results[j['key']]
            if j['backup'] and not os.path.exists(j['backup']):
                os.makedirs(os.path.dirname(j['backup']), exist_ok=True)
                shutil.copy2(j['out'], j['backup'])
                if _sha256(read_bytes(j['backup'])) != _sha256(read_bytes(j['out'])):
                    print(f'STOP - backup copy of {j["rel"]} does not match the original')
                    return 4
            if os.path.exists(j['out']) and _sha256(read_bytes(j['out'])) == r['sha256']:
                j['action'] = 'unchanged'
            else:
                write_atomic(j['out'], r['blob'])
                j['action'] = 'written'
                written.append(j['rel'])
            r.pop('blob', None)

    verify_jobs = [dict(key=j['key'], out=j['out'], src=j['src'], format=results[j['key']]['format'],
                        width=results[j['key']]['width'], height=results[j['key']]['height'],
                        mips=results[j['key']]['mips']) for j in jobs]
    with cf.ProcessPoolExecutor(max_workers=max(1, args.jobs)) as pool:
        checks = {c['key']: c for c in pool.map(verify_output, verify_jobs)}

    failed = []
    for j in jobs:
        r, c = results[j['key']], checks[j['key']]
        if c['problems']:
            failed.append((j['rel'], c['problems']))
        if not args.verify_only and c.get('sha256') != r.get('sha256'):
            failed.append((j['rel'], ['file on disk does not match the encoded bytes']))

    # manifest + Lua (a failed verification keeps the previous manifest entry out of the Lua)
    for j in jobs:
        r, c = results[j['key']], checks[j['key']]
        if c['problems']:
            continue
        prev = owned.get(j['rel'].lower(), (None, {}))[1]
        entry = dict(sheet=j['key'], source=os.path.relpath(j['src'], args.src_root).replace('\\', '/'),
                     source_sha256=r['src_sha256'], sha256=c['sha256'], bytes=os.path.getsize(j['out']),
                     width=r['width'], height=r['height'], format=r['format'], mips=r['mips'], mode=r['mode'],
                     alpha_scope=args.alpha_scope, alpha_lt250_fraction=r['analysis']['alpha_lt250_fraction'],
                     atlases=len(atlas_info[j['key']]),
                     psnr_rgb_visible=_jsonable(c['psnr_rgb_visible']), psnr_rgb_all=_jsonable(c['psnr_rgb_all']),
                     psnr_alpha=_jsonable(c['psnr_alpha']))
        if j['backup']:
            orig = BlpInfo(read_bytes(j['backup']))
            entry['replaced_original'] = dict(backup=os.path.relpath(j['backup'], stage).replace('\\', '/'),
                                              sha256=_sha256(read_bytes(j['backup'])), encoding=orig.enc,
                                              width=orig.width, height=orig.height)
        elif 'replaced_original' in prev:
            entry['replaced_original'] = prev['replaced_original']
        for old_rel in [k for k in manifest['outputs'] if k.lower() == j['rel'].lower()]:
            del manifest['outputs'][old_rel]
        manifest['outputs'][j['rel']] = entry

    gone = [rel for rel in manifest['outputs'] if not os.path.exists(os.path.join(stage, *rel.split('/')))]
    for rel in gone:
        print(f'  note: {rel} is in the manifest but no longer staged - dropped from the Lua table')
        del manifest['outputs'][rel]
    shipped = {e['sheet']: (e['width'], e['height']) for e in manifest['outputs'].values()
               if e['sheet'] in atlas_info}
    lua_bytes = render_lua(shipped, atlas_info)
    lua_action = 'unchanged'
    if not args.verify_only and (not lua_existing or read_bytes(args.lua_out) != lua_bytes):
        write_atomic(args.lua_out, lua_bytes)
        lua_action = 'written'
    try:
        lua_rel = os.path.relpath(args.lua_out, CUSTOM_DIR)
    except ValueError:   # different drive
        lua_rel = os.path.abspath(args.lua_out)
    manifest['lua'] = dict(path=lua_rel.replace('\\', '/'),
                           sha256=_sha256(lua_bytes), sheets=len(shipped),
                           atlases=sum(len(atlas_info[k]) for k in shipped))
    manifest['generator'] = '_tools/dc-talents/convert_art.py'
    if not args.verify_only:
        mbytes = (json.dumps(manifest, indent=2, sort_keys=True) + '\n').encode('utf-8')
        if not os.path.exists(args.manifest) or read_bytes(args.manifest) != mbytes:
            write_atomic(args.manifest, mbytes)

    # report
    print(f'\n{"output (under stage root)":62s} {"size":>9} {"fmt":4} {"mips":>4} {"bytes":>9} '
          f'{"b8":>2} {"b11":>3} {"RGBvis":>6} {"RGBall":>6} {"alpha":>6} {"atl":>3}  mode / action')
    total = 0
    for j in sorted(jobs, key=lambda j: j['rel'].lower()):
        r, c = results[j['key']], checks[j['key']]
        size = os.path.getsize(j['out'])
        total += size
        print(f'{j["rel"]:62s} {r["width"]:>4}x{r["height"]:<4} {r["format"]:4} {r["mips"]:>4} {size:>9} '
              f'{c.get("byte8", "?"):>2} {c.get("byte11", "?"):>3} {fmt_psnr(c.get("psnr_rgb_visible")):>6} '
              f'{fmt_psnr(c.get("psnr_rgb_all")):>6} {fmt_psnr(c.get("psnr_alpha")):>6} '
              f'{len(atlas_info[j["key"]]):>3}  {r["mode"]} / {j.get("action", "verified")}')
    print(f'total {len(jobs)} files, {total} bytes ({total / 1048576:.2f} MiB); Lua {lua_action}: '
          f'{manifest["lua"]["sheets"]} sheets, {manifest["lua"]["atlases"]} atlases -> {args.lua_out}')
    for j in jobs:
        a = results[j['key']]['analysis']
        if a['empty_rects']:
            print(f'  WARN {j["key"]}: {len(a["empty_rects"])} atlas rect(s) hold no visible texel: '
                  f'{", ".join(a["empty_rects"][:5])}')
        if a['visible_outside_rects']:
            print(f'  note {j["key"]}: {a["visible_outside_rects"]} visible texels lie outside every atlas rect '
                  f'({a["visible_outside_rects"] / max(1, a["visible_total"]):.2%} of visible)')
        if results[j['key']]['format'] == 'DXT1' and a['alpha_lt250_texels_in_scope']:
            print(f'  note {j["key"]}: DXT1 drops alpha on {a["alpha_lt250_texels_in_scope"]} translucent texels')
    for rel, probs in failed:
        for p in probs:
            print(f'  FAIL {rel}: {p}')
    for m in missing:
        print(f'  MISSING {m}')
    if failed:
        return 5
    return 2 if missing or unknown else 0


if __name__ == '__main__':
    sys.exit(main())
