-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_SharedXML/AnimationTemplates.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

ns.XML.Load("Blizzard_SharedXML/AnimationTemplates.xml", {
    { tag = "AnimationGroup", attr = { name = "VisibleWhilePlayingAnimGroupTemplate", mixin = "VisibleWhilePlayingAnimGroupMixin", virtual = "true" }, children = {
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "Hide" } },
            { tag = "OnPlay", attr = { method = "Show" } },
            { tag = "OnStop", attr = { method = "Hide" } },
            { tag = "OnFinished", attr = { method = "Hide" } },
        } },
    } },
    { tag = "AnimationGroup", attr = { name = "TargetsVisibleWhilePlayingAnimGroupTemplate", mixin = "TargetsVisibleWhilePlayingAnimGroupMixin", virtual = "true" }, children = {
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "Hide" } },
            { tag = "OnPlay", attr = { method = "Show" } },
            { tag = "OnStop", attr = { method = "Hide" } },
            { tag = "OnFinished", attr = { method = "Hide" } },
        } },
    } },
    { tag = "AnimationGroup", attr = { name = "TargetsHiddenOnFinishedAnimGroupTemplate", mixin = "TargetsVisibleWhilePlayingAnimGroupMixin", virtual = "true" }, children = {
        { tag = "Scripts", children = {
            { tag = "OnPlay", attr = { method = "Show" } },
            { tag = "OnStop", attr = { method = "Hide" } },
            { tag = "OnFinished", attr = { method = "Hide" } },
        } },
    } },
    { tag = "AnimationGroup", attr = { name = "SyncedAnimGroupTemplate", mixin = "SyncedAnimGroupMixin", virtual = "true" } },
    { tag = "Frame", attr = { name = "AnimateWhileShownTemplate", mixin = "AnimateWhileShownMixin", virtual = "true" }, children = {
        { tag = "Scripts", children = {
            { tag = "OnShow", attr = { method = "PlayAnims" } },
            { tag = "OnHide", attr = { method = "StopAnims" } },
        } },
    } },
    { tag = "Frame", attr = { name = "EasyFrameAnimationsTemplate", inherits = "AnimateWhileShownTemplate", enableMouseClicks = "true", virtual = "true" }, children = {
        { tag = "Scripts", children = {
            { tag = "OnMouseDown", attr = { method = "PlayAnims" } },
        } },
    } },
})
