-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_SharedXML/LayoutFrame.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

ns.XML.Load("Blizzard_SharedXML/LayoutFrame.xml", {
    { tag = "Frame", attr = { name = "BaseLayoutFrameTemplate", virtual = "true" }, children = {
        { tag = "Scripts", children = {
            { tag = "OnShow", attr = { method = "OnShow" } },
        } },
    } },
    { tag = "Frame", attr = { name = "VerticalLayoutFrame", virtual = "true", inherits = "BaseLayoutFrameTemplate", mixin = "LayoutMixin, VerticalLayoutMixin" } },
    { tag = "Frame", attr = { name = "HorizontalLayoutFrame", virtual = "true", inherits = "BaseLayoutFrameTemplate", mixin = "LayoutMixin, HorizontalLayoutMixin" } },
    { tag = "Frame", attr = { name = "ResizeLayoutFrame", virtual = "true", inherits = "BaseLayoutFrameTemplate", mixin = "ResizeLayoutMixin" }, children = {
        { tag = "Size", attr = { x = "1", y = "1" } },
    } },
    { tag = "Frame", attr = { name = "GridLayoutFrame", inherits = "ResizeLayoutFrame", virtual = "true", mixin = "GridLayoutFrameMixin" } },
    { tag = "Frame", attr = { name = "StaticGridLayoutFrame", inherits = "BaseLayoutFrameTemplate", virtual = "true", mixin = "StaticGridLayoutFrameMixin" } },
})
