-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_SharedXML/SharedUIPanelTemplates.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

ns.XML.Load("Blizzard_SharedXML/SharedUIPanelTemplates.xml", {
    { tag = "Texture", attr = { name = "_UI-Frame-TopTileStreaks", atlas = "_UI-Frame-TopTileStreaks", virtual = "true", horizTile = "true" }, children = {
        { tag = "Size", attr = { x = "256", y = "43" } },
    } },
    { tag = "Button", attr = { name = "UIPanelCloseButtonDefaultAnchors", inherits = "UIPanelCloseButton", virtual = "true" }, children = {
        { tag = "Anchors", children = {
            { tag = "Anchor", attr = { point = "TOPRIGHT", x = "1", y = "0" } },
        } },
    } },
    { tag = "Frame", attr = { name = "NineSliceCodeTemplate", mixin = "NineSlicePanelMixin", virtual = "true" }, children = {
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
        } },
    } },
    { tag = "Frame", attr = { name = "NineSlicePanelTemplate", inherits = "NineSliceCodeTemplate", frameLevel = "500", setAllPoints = "true", virtual = "true" } },
    { tag = "Frame", attr = { name = "PortraitFrameBaseTemplate", mixin = "PortraitFrameMixin", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "layoutType", value = "PortraitFrameTemplate", type = "string" } },
        } },
        { tag = "Size", attr = { x = "338", y = "424" } },
        { tag = "Frames", children = {
            { tag = "Frame", attr = { parentKey = "NineSlice", inherits = "NineSlicePanelTemplate" } },
            { tag = "Frame", attr = { parentKey = "PortraitContainer", frameLevel = "400" }, children = {
                { tag = "Size", attr = { x = "1", y = "1" } },
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "TOPLEFT" } },
                } },
                { tag = "Layers", children = {
                    { tag = "Layer", attr = { level = "OVERLAY" }, children = {
                        { tag = "Texture", attr = { name = "$parentPortrait", parentKey = "portrait" }, children = {
                            { tag = "Size", attr = { x = "62", y = "62" } },
                            { tag = "Anchors", children = {
                                { tag = "Anchor", attr = { point = "TOPLEFT", x = "-5", y = "7" } },
                            } },
                        } },
                        { tag = "MaskTexture", attr = { parentKey = "CircleMask", file = "Interface\\CharacterFrame\\TempPortraitAlphaMask", hWrapMode = "CLAMPTOBLACKADDITIVE", vWrapMode = "CLAMPTOBLACKADDITIVE" }, children = {
                            { tag = "Anchors", children = {
                                { tag = "Anchor", attr = { point = "TOPLEFT", relativeKey = "$parent.portrait", x = "2", y = "0" } },
                                { tag = "Anchor", attr = { point = "BOTTOMRIGHT", relativeKey = "$parent.portrait", x = "-2", y = "4" } },
                            } },
                            { tag = "MaskedTextures", children = {
                                { tag = "MaskedTexture", attr = { childKey = "portrait" } },
                            } },
                        } },
                    } },
                } },
            } },
            { tag = "Frame", attr = { parentKey = "TitleContainer", frameLevel = "510" }, children = {
                { tag = "Size", attr = { x = "0", y = "20" } },
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "TOPLEFT", x = "58", y = "-1" } },
                    { tag = "Anchor", attr = { point = "TOPRIGHT", x = "-24", y = "-1" } },
                } },
                { tag = "Layers", children = {
                    { tag = "Layer", attr = { level = "OVERLAY" }, children = {
                        { tag = "FontString", attr = { name = "$parentTitleText", inherits = "GameFontNormal", text = "", parentKey = "TitleText", wordwrap = "false" }, children = {
                            { tag = "Anchors", children = {
                                { tag = "Anchor", attr = { point = "TOP", x = "0", y = "-5" } },
                                { tag = "Anchor", attr = { point = "LEFT" } },
                                { tag = "Anchor", attr = { point = "RIGHT" } },
                            } },
                        } },
                    } },
                } },
            } },
        } },
    } },
    { tag = "Frame", attr = { name = "PortraitFrameTexturedBaseTemplate", inherits = "PortraitFrameBaseTemplate", virtual = "true" }, children = {
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "BACKGROUND", textureSubLevel = "-6" }, children = {
                { tag = "Texture", attr = { name = "$parentBg", file = "Interface\\FrameGeneral\\UI-Background-Rock", horizTile = "true", vertTile = "true", parentKey = "Bg" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "TOPLEFT", x = "2", y = "-21" } },
                        { tag = "Anchor", attr = { point = "BOTTOMRIGHT", x = "-2", y = "2" } },
                    } },
                } },
            } },
            { tag = "Layer", attr = { level = "BORDER" }, children = {
                { tag = "Texture", attr = { parentKey = "TopTileStreaks", inherits = "_UI-Frame-TopTileStreaks" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "TOPLEFT", x = "6", y = "-21" } },
                        { tag = "Anchor", attr = { point = "TOPRIGHT", x = "-2", y = "-21" } },
                    } },
                } },
            } },
        } },
    } },
    { tag = "Frame", attr = { name = "PortraitFrameTemplateNoCloseButton", inherits = "PortraitFrameTexturedBaseTemplate", virtual = "true" } },
    { tag = "Frame", attr = { name = "PortraitFrameTemplate", inherits = "PortraitFrameTemplateNoCloseButton", virtual = "true" }, children = {
        { tag = "Frames", children = {
            { tag = "Button", attr = { name = "$parentCloseButton", parentKey = "CloseButton", inherits = "UIPanelCloseButtonDefaultAnchors" } },
        } },
    } },
})
