-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_SharedXML/TabSystem/TabSystemOwner.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

ns.XML.Load("Blizzard_SharedXML/TabSystem/TabSystemOwner.xml", {
    { tag = "Frame", attr = { name = "TabSystemOwnerTemplate", mixin = "TabSystemOwnerMixin", virtual = "true" }, children = {
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
        } },
    } },
})
