-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_PlayerSpells/Blizzard_ClassTalentLoadoutDialogTemplates.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

-- Script Blizzard_ClassTalentLoadoutDialogTemplates.lua (loaded through the TOC)

ns.XML.Load("Blizzard_PlayerSpells/Blizzard_ClassTalentLoadoutDialogTemplates.xml", {
    { tag = "Button", attr = { name = "ClassTalentLoadoutDialogButtonTemplate", inherits = "UIPanelButtonTemplate, UIButtonTemplate", virtual = "true" }, children = {
        { tag = "Size", attr = { x = "120", y = "22" } },
    } },
    { tag = "Frame", attr = { name = "ClassTalentLoadoutDialogNameControlTemplate", mixin = "ClassTalentLoadoutDialogNameControlMixin", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "labelText", value = "", type = "global" } },
        } },
        { tag = "Size", attr = { x = "260", y = "50" } },
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "ARTWORK" }, children = {
                { tag = "FontString", attr = { parentKey = "Label", inherits = "GameFontNormal" }, children = {
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "TOPLEFT" } },
                    } },
                } },
            } },
        } },
        { tag = "Frames", children = {
            { tag = "EditBox", attr = { parentKey = "EditBox", inherits = "InputBoxTemplate", letters = "30" }, children = {
                { tag = "Size", attr = { x = "260", y = "32" } },
                { tag = "FontString", attr = { inherits = "ChatFontNormal" } },
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "TOPLEFT", relativePoint = "BOTTOMLEFT", relativeKey = "$parent.Label", y = "10" } },
                    { tag = "Anchor", attr = { point = "RIGHT" } },
                    { tag = "Anchor", attr = { point = "BOTTOM" } },
                } },
            } },
        } },
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
            { tag = "OnHide", attr = { method = "OnShow" } },
        } },
    } },
    { tag = "Frame", attr = { name = "ClassTalentLoadoutDialogTemplate", mixin = "ClassTalentLoadoutDialogMixin", virtual = "true", frameStrata = "DIALOG", frameLevel = "100" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "titleText", value = "", type = "global" } },
        } },
        { tag = "Size", attr = { x = "460", y = "200" } },
        { tag = "Anchors", children = {
            { tag = "Anchor", attr = { point = "CENTER" } },
        } },
        { tag = "Layers", children = {
            { tag = "Layer", attr = { level = "ARTWORK" }, children = {
                { tag = "FontString", attr = { parentKey = "Title", inherits = "GameFontHighlight" }, children = {
                    { tag = "Size", attr = { x = "250" } },
                    { tag = "Anchors", children = {
                        { tag = "Anchor", attr = { point = "TOP", y = "-20" } },
                    } },
                } },
            } },
        } },
        { tag = "Frames", children = {
            { tag = "Frame", attr = { parentKey = "Border", inherits = "DialogBorderDarkTemplate" } },
            { tag = "Frame", attr = { parentKey = "ContentArea" }, children = {
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "TOPLEFT", x = "40", y = "-40" } },
                    { tag = "Anchor", attr = { point = "BOTTOMRIGHT", x = "-40", y = "25" } },
                } },
            } },
        } },
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
        } },
    } },
})
