-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_PlayerSpells/Blizzard_ClassTalentLoadoutEditDialog.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

-- Script Blizzard_ClassTalentLoadoutEditDialog.lua (loaded through the TOC)

ns.XML.Load("Blizzard_PlayerSpells/Blizzard_ClassTalentLoadoutEditDialog.xml", {
    { tag = "Frame", attr = { name = "ClassTalentLoadoutEditDialog", inherits = "ClassTalentLoadoutDialogTemplate", mixin = "ClassTalentLoadoutEditDialogMixin", parent = "UIParent", hidden = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "titleText", value = "HUD_CLASS_TALENTS_EDIT_LOADOUT_DIALOG_TITLE", type = "global" } },
        } },
        { tag = "Size", attr = { x = "460", y = "200" } },
        { tag = "Frames", children = {
            { tag = "Frame", attr = { parentKey = "NameControl", inherits = "ClassTalentLoadoutDialogNameControlTemplate", mixin = "ClassTalentLoadoutEditDialogNameControlMixin" }, children = {
                { tag = "KeyValues", children = {
                    { tag = "KeyValue", attr = { key = "labelText", value = "HUD_CLASS_TALENTS_EDIT_LOADOUT_DIALOG_EDIT_BOX_LABEL", type = "global" } },
                } },
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "TOPLEFT", relativeKey = "$parent.ContentArea" } },
                    { tag = "Anchor", attr = { point = "RIGHT", relativeKey = "$parent.ContentArea" } },
                } },
            } },
            { tag = "Button", attr = { parentKey = "UsesSharedActionBars", mixin = "UseSharedActionBarsMixin" }, children = {
                { tag = "Size", attr = { y = "30" } },
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "TOP", relativeKey = "$parent.ContentArea", y = "-55" } },
                    { tag = "Anchor", attr = { point = "LEFT", relativeKey = "$parent.ContentArea", x = "20" } },
                    { tag = "Anchor", attr = { point = "RIGHT", relativeKey = "$parent.ContentArea", x = "0" } },
                } },
                { tag = "Frames", children = {
                    { tag = "CheckButton", attr = { parentKey = "CheckButton" }, children = {
                        { tag = "Size", attr = { x = "30", y = "29" } },
                        { tag = "Anchors", children = {
                            { tag = "Anchor", attr = { point = "TOPLEFT" } },
                        } },
                        { tag = "NormalTexture", attr = { atlas = "checkbox-minimal", useAtlasSize = "true" } },
                        { tag = "PushedTexture", attr = { atlas = "checkbox-minimal", useAtlasSize = "true" } },
                        { tag = "CheckedTexture", attr = { atlas = "checkmark-minimal", useAtlasSize = "true" } },
                        { tag = "DisabledCheckedTexture", attr = { atlas = "checkmark-minimal-disabled", useAtlasSize = "true" } },
                    } },
                } },
                { tag = "Layers", children = {
                    { tag = "Layer", attr = { level = "ARTWORK" }, children = {
                        { tag = "FontString", attr = { parentKey = "Label", inherits = "GameFontNormal", text = "HUD_CLASS_TALENTS_EDIT_LOADOUT_SHARED_ACTION_BARS_TEXT" }, children = {
                            { tag = "Anchors", children = {
                                { tag = "Anchor", attr = { point = "LEFT", relativeKey = "$parent.CheckButton", relativePoint = "RIGHT", x = "10", y = "0" } },
                            } },
                        } },
                    } },
                } },
                { tag = "Scripts", children = {
                    { tag = "OnEnter", attr = { method = "OnEnter" } },
                    { tag = "OnLeave", attr = { method = "OnLeave" } },
                    { tag = "OnClick", attr = { method = "OnClick" } },
                } },
            } },
            { tag = "Button", attr = { parentKey = "AcceptButton", inherits = "ClassTalentLoadoutDialogButtonTemplate", text = "ACCEPT" }, children = {
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "BOTTOMLEFT", relativeKey = "$parent.ContentArea" } },
                } },
            } },
            { tag = "Button", attr = { parentKey = "DeleteButton", inherits = "ClassTalentLoadoutDialogButtonTemplate", text = "DELETE" }, children = {
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "BOTTOM", relativeKey = "$parent.ContentArea" } },
                } },
            } },
            { tag = "Button", attr = { parentKey = "CancelButton", inherits = "ClassTalentLoadoutDialogButtonTemplate", text = "CANCEL" }, children = {
                { tag = "Anchors", children = {
                    { tag = "Anchor", attr = { point = "BOTTOMRIGHT", relativeKey = "$parent.ContentArea" } },
                } },
            } },
        } },
        { tag = "Scripts", children = {
            { tag = "OnLoad", attr = { method = "OnLoad" } },
        } },
    } },
})
