-- Generated by _tools/dc-talents/xml2lua.py from retail 11.2.7 (64632) Blizzard_PlayerSpells/Blizzard_ClassTalentEdgeTemplates.xml.
-- Do not edit by hand: change the converter or the runtime (Core/Templates.lua) and regenerate.
local _, ns = ...
setfenv(1, ns.env)

ns.XML.Load("Blizzard_PlayerSpells/Blizzard_ClassTalentEdgeTemplates.xml", {
    { tag = "Frame", attr = { name = "ClassTalentEdgeArrowTemplate", mixin = "ClassTalentEdgeArrowMixin", inherits = "TalentEdgeArrowTemplate", virtual = "true" }, children = {
        { tag = "KeyValues", children = {
            { tag = "KeyValue", attr = { key = "ignoreInLayout", value = "true" } },
        } },
    } },
})
