-- Races 1-11 receive their unlocked-class starting gear TWICE. Optional cleanup.
--
-- Player::Create (Player.cpp ~637) grants CharStartOutfit.dbc AND then playercreateinfo_item,
-- unconditionally, one after the other. This fork unlocked every class for every race by two
-- different mechanisms at two different times:
--
--   * playercreateinfo_item rows for the newly-legal race/class pairs (the older mechanism),
--   * CharStartOutfit.dbc rows 141-242 for the same pairs (the newer one -- every race now
--     has all 20 rows, 10 classes x 2 sexes).
--
-- Both are still live, so 193 of the 201 playercreateinfo_item rows re-grant an item the outfit
-- already handed out. The duplicate cannot be equipped, so it lands in the backpack. Verified
-- in acore_characters: guid 3063, a level-1 Human druid, holds 2x 3661, 2x 6123 and 2x 6124 --
-- exactly the race 1 / class 11 playercreateinfo_item set.
--
-- The custom races (9, 12, 22-27) are NOT affected: they have no playercreateinfo_item rows
-- and are covered by CharStartOutfit alone, which is the correct shape. This file brings
-- races 1-11 to that same shape.
--
-- Generated by diffing playercreateinfo_item against Custom/DBCs/CharStartOutfit.dbc, taking
-- the HIGHEST id per (race, class) because DBCStores.cpp fills sCharStartOutfitMap in id order
-- and the last write wins. The list is explicit rather than a join because races 1-11 live in
-- the DBC file, not in the charstartoutfit_dbc overlay table -- a join would delete nothing.
--
-- 8 rows are genuinely extra rather than duplicated and are deliberately KEPT:
--     race  3  class 11  item  3661
--     race  6  class  2  item 23346
--     race  6  class  4  item 28979
--     race  6  class  9  item  6097
--     race  7  class 11  item  3661
--     race  8  class  9  item  6097
--     race 11  class  4  item 28979
--     race 11  class  9  item  6097
-- If you would rather have those in the outfit too, add them to the matching CharStartOutfit
-- rows instead and delete these as well.
--
-- Reversible: re-run the source data for playercreateinfo_item to restore.

DELETE FROM `playercreateinfo_item` WHERE `race` = 1 AND `class` =  3 AND `itemid` IN (129, 147, 148, 2102, 2508, 2516, 6948, 12282);
DELETE FROM `playercreateinfo_item` WHERE `race` = 1 AND `class` =  7 AND `itemid` IN (36, 153, 154, 2362, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 1 AND `class` = 11 AND `itemid` IN (3661, 6123, 6124, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 2 AND `class` =  2 AND `itemid` IN (43, 44, 45, 2361, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 2 AND `class` =  5 AND `itemid` IN (35, 51, 52, 53, 6144, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 2 AND `class` =  8 AND `itemid` IN (35, 55, 1395, 6096, 6140, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 2 AND `class` = 11 AND `itemid` IN (35, 6124, 6139, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 3 AND `class` =  7 AND `itemid` IN (36, 153, 154, 2362, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 3 AND `class` =  9 AND `itemid` IN (35, 57, 59, 1396, 6097, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 3 AND `class` = 11 AND `itemid` IN (6124, 6139, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 4 AND `class` =  2 AND `itemid` IN (43, 44, 45, 2361, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 4 AND `class` =  7 AND `itemid` IN (36, 153, 154, 2362, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 4 AND `class` =  8 AND `itemid` IN (35, 55, 56, 1395, 6096, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 4 AND `class` =  9 AND `itemid` IN (35, 57, 59, 1396, 6097, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 5 AND `class` =  2 AND `itemid` IN (43, 44, 45, 2361, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 5 AND `class` =  3 AND `itemid` IN (129, 147, 148, 2102, 2508, 2516, 6948, 12282);
DELETE FROM `playercreateinfo_item` WHERE `race` = 5 AND `class` =  7 AND `itemid` IN (36, 153, 154, 2362, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 5 AND `class` = 11 AND `itemid` IN (35, 6124, 6139, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 6 AND `class` =  2 AND `itemid` IN (43, 44, 45, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 6 AND `class` =  4 AND `itemid` IN (120, 121, 2092, 2105, 6948, 50055);
DELETE FROM `playercreateinfo_item` WHERE `race` = 6 AND `class` =  5 AND `itemid` IN (35, 51, 52, 53, 6144, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 6 AND `class` =  8 AND `itemid` IN (35, 55, 1395, 6096, 6140, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 6 AND `class` =  9 AND `itemid` IN (35, 59, 1396, 6129, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 7 AND `class` =  2 AND `itemid` IN (43, 44, 45, 2361, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 7 AND `class` =  3 AND `itemid` IN (129, 147, 148, 2102, 2508, 2516, 6948, 12282);
DELETE FROM `playercreateinfo_item` WHERE `race` = 7 AND `class` =  5 AND `itemid` IN (35, 51, 52, 53, 6098, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 7 AND `class` =  7 AND `itemid` IN (36, 153, 154, 2362, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 7 AND `class` = 11 AND `itemid` IN (6124, 6139, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 8 AND `class` =  2 AND `itemid` IN (43, 44, 45, 2361, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 8 AND `class` =  9 AND `itemid` IN (35, 59, 1396, 6129, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 8 AND `class` = 11 AND `itemid` IN (35, 6124, 6139, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 10 AND `class` =  1 AND `itemid` IN (6948, 20915, 20918, 20919, 23346);
DELETE FROM `playercreateinfo_item` WHERE `race` = 10 AND `class` =  7 AND `itemid` IN (36, 153, 154, 2362, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 10 AND `class` = 11 AND `itemid` IN (3661, 6123, 6124, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 11 AND `class` =  4 AND `itemid` IN (120, 121, 2092, 2105, 6948, 50055);
DELETE FROM `playercreateinfo_item` WHERE `race` = 11 AND `class` =  9 AND `itemid` IN (35, 59, 1396, 6129, 6948);
DELETE FROM `playercreateinfo_item` WHERE `race` = 11 AND `class` = 11 AND `itemid` IN (3661, 6123, 6124, 6948);
